cts/cli/regression.acls.exp
cts/cts-cli.in
lib/common/acl.c

If a node does not have any ACLs set for it explicitly, it's assigned a
deny flag. However, in the case of scoped commands, the input to
`pcmk__apply_acl()` may be a section rather than the whole CIB. The
node at the root of the section that's passed in gets assigned a deny
flag after no ACLs match it.
This causes `pcmk__check_acl()` to fail prematurely when it walks up
the tree of parents. It reaches the node at the root of the section
that was passed to `pcmk__apply_acl()`, finds a deny flag, and returns
FALSE. If that node's parent (e.g., `/cib`) has a read or write ACL,
the parent's ACL is not reached and thus not considered.
The fix is to avoid setting a deny flag for a node if there is no ACL
for that node. `pcmk__check_acl()` already denies access implicitly if
neither read nor …

 Fix: libcrmcommon: Use truly implicit deny for ACLs

---

daemons/pacemakerd/pcmkd_corosync.c
lib/cluster/corosync.c
lib/cluster/cpg.c

I'll be honest here I'm not sure how much this fixes. It's for
bz#1614166 but I can't reproduce that particular issue as
my nodes get (correctly) fenced every time I try it and even with
fencing disabled I dont get that behaviour.
Still, they can't hurt and libqb needs all the help it can
get tidying up after itself

cluster: Close corosync handles when they disconnect

---

include/crm/crm.h

ba38d490 unintentionally reversed the sense of the string comparison

Fix: libcrmcommon: use correct sense of string comparison in crm_action_str()

---

daemons/controld/controld_execd.c
include/crm/common/util.h
include/crm/crm.h
lib/common/agents.c
lib/pengine/utils.c

`pcmk_monitor_timeout` is applied partially to stonith monitor ops but
not to stonith start ops. Start ops use the op timeout
(`CRM_meta_timeout`) even though they perform monitor actions.
For both monitor and start, if an op times out, the "Result of" error
message says the timeout was equal to the meta timeout (default:
20000ms).
This patch overrides the `CRM_meta_timeout` with the
`pcmk_monitor_timeout` for stonith start and monitor actions.
Resolves: RHBZ#1856015
Related to: RHBZ#1677345

Fix: libpe_status: Use pcmk_monitor_timeout for stonith start timeout

---

cts/scheduler/migrate-fail-9.dot
cts/scheduler/migrate-fail-9.exp
cts/scheduler/migrate-fail-9.summary
lib/pengine/unpack.c

See the 2020-08-18 thread to the users@clusterlabs.org list "why is node fenced ?". If a node had a dangling migration, later had a successful stop to recover, and is now shutting down, the scheduler would schedule another stop, which would be unrunnable due to the shutdown, causing unnecessary fencing.
It looks like a similar (known) problem exists with the migrate-fail-4 and migrate-fail-8 regression tests, but the fix would be different.

Fix: scheduler: don't schedule a dangling migration stop if one already occurred

---

daemons/controld/controld_control.c
doc/Pacemaker_Explained/en-US/Ch-Options.txt
doc/sphinx/Pacemaker_Explained/options.rst
lib/pengine/common.c
lib/pengine/unpack.c

The message actually only indicates there's the setting
`have-watchdog=true` and describes the meaning of it. It's rather
confusing to constantly appear if normal SBD with disk is used.
On the other hand, we should improve the documentation about the cluster
options related to watchdog.

Log: libpe_status: downgrade the message about the meaning of `have-watchdog=true` to info

---

lib/common/strings.c

Logging at err level in the event of a parse failure makes scan_ll() too
chatty. Specifically, it causes `crm_node -q/-n` to always log a parse
failure to stderr when run within a bundle, where logging to stderr is
enabled by default via PCMK_stderr.
In the future we may want to drop to crm_debug() in scan_ll(). This will
require looking for particular callers where more visible error checking
is necessary, and logging at higher levels there.
Resolves: RHBZ#1874391

Log: libcrmcommon: Warn instead of err in scan_ll()

---

daemons/fenced/fenced_remote.c

Hi All,
After a fencing failure due to a node failure, the fencing history of crm_mon may not be displayed correctly even if the fencing re-execution is successful.
The following is an example of a problem with a cluster using fence_vmware_rest.
Fencing goes through the vCenter server at 192.168.28.25.
Step1) Build a cluster.
```
[root@rh80-test01 ~]# crm_mon -rfA1m3
* Stack: corosync
* Current DC: rh80-test01 (version 2.0.4-73f6f5c5f2) - partition with quorum
* Last updated: Thu Sep 10 12:48:48 2020
* Last change:  Thu Sep 10 12:47:04 2020 by root via cibadmin on rh80-test01
* 2 nodes configured
* 9 resource instances configured
Node List:
* Online: [ rh80-test01 rh80-test02 ]
Full List of Resources:
* Resource Group: pgsql-group:
* filesystem1 …
```

Mid: fenced: Set the delegate correctly when fencing fails.

---

daemons/attrd/attrd_utils.c
daemons/attrd/pacemaker-attrd.c
daemons/attrd/pacemaker-attrd.h
daemons/controld/controld_based.c
daemons/controld/controld_control.c
daemons/controld/pacemaker-controld.h
daemons/fenced/pacemaker-fenced.c

Hi All,
This PR improves on the following issues:
- https://bugs.clusterlabs.org/show_bug.cgi?id=5434
However, this does not mean that the "Broken Pipe" will not occur completely.
This PR can reduce the frequency of problems.
Best Regards,

Mid: controld,fenced,attrd: Unregister NOTIFY to avoid the occurrence of "Broken pipe" at the time of stop. (Fix CLBZ:#5434)

---

cts/cli/regression.acls.exp
cts/cli/regression.tools.exp
cts/cts-cli.in
tools/crm_resource.c

Also, add the program name to any error prints that happen.  This brings
it in line with what crm_mon is doing.

Fix: tools: Don't display crm_resource error messages twice.

---

lib/services/dbus.c
lib/services/pcmk-dbus.h
lib/services/systemd.c
lib/services/upstart.c

This is what happens when you pull on a thread in Pacemaker.
The latest coverity version reported a potential use-before-initialization error in Pacemaker's DBus code, and it wasn't obvious at first whether it was a true error or a false positive. It turned out to be a false positive, but in order to figure that out ...
"Let me add some comments as I figure out what these functions do ..."
"If I'm going to test this, I need better log messages ..."
"This code with the false positive is really inefficient, I should refactor it ..."
Hopefully now it's cleaner. :) I tested with all the regression tests, CTS, and specific-testing of nonexistent systemd units and some test-only modifications to ask for invalid or undefined properties.

Clean up DBus code

---

.gitignore
configure.ac
lib/common/operations.c
lib/common/tests/Makefile.am
lib/common/tests/operations/Makefile.am
lib/common/tests/operations/parse_op_key.c

This function has problems with most operation names that have an
underscore in them, like "migrate_to" or "migrate_from".  It parses
those as if the "migrate" is part of the resource name, and "to" or
"from" is the operation name.  It does appear to understand _post_notify
and _pre_notify operations, at least.
I've rewritten much of the function to also understand "migrate_to" and
"migrate_from".  I don't believe there are any other operation names
with an underscore in them, but it so it's easy enough to add to the
obvious block.  I can't think of any better way to handle these cases,
given that an underscore is both the separator character and can appear
anywhere in the op key.
I'm hoping the rewritten version is a little easier to follow.  I have
added a lot of comments to make it …

Fix: libcrmcommon: Rewrite much of parse_op_key.

---

daemons/controld/controld_based.c
daemons/controld/controld_election.c
daemons/controld/controld_utils.h

Hi All,
This fix is a continuation of the previous PR.
- https://github.com/ClusterLabs/pacemaker/pull/2173
- https://github.com/ClusterLabs/pacemaker/pull/2177
But...These fixes reduce the frequency of "Broken pipes", but not 100% due to different processes.
(I will continue to consider fixing other "Broken pipe" occurrences.)
Best Regards,

Mid: controld: Avoiding Broken pipe when shutdown.(Fix CLBZ:#5434)

---

lib/common/operations.c

The new parse_op_key is a fair bit slower than the old version, but has the distinct advantage of understanding all the op key formats I know about.  These four patches take various steps to try to speed it up.  On the whole it's faster but still not at the level of the previous version.  Before these changes:
```
$ tools/pcmk_simtimes ~/crm_simulate.2.0.4.out ~/crm_simulate.master.out -s 0.1 -p 5
notify-1                                 2.12s vs 2.26s (+0.14s =  +6.60%)
notify-2                                 2.12s vs 2.25s (+0.13s =  +6.13%)
migrate-stop-start-complex               2.01s vs 2.13s (+0.12s =  +5.97%)
a-demote-then-b-migrate                  3.74s vs 3.93s (+0.19s =  +5.08%)
bug-5059                                 7.85s vs 8.25s (+0.40s =  +5.10%)
novell-239079 …
```

Try to speed up parse_op_key

---

daemons/based/based_callbacks.c

The changes in d71fb9a and f87436c, setting cib_discard_reply on certain controller requests to the CIB, tripped a pre-existing pacemaker-based bug, leading to "Unexpected NULL reply to message" log errors. This fixes that bug.
@clumens , we should merge this into 2.0 before merging the rc1 PR. This won't affect the soname versions or change log. Can you review it?
@HideoYamauchi , have you seen these errors in your logs?
This needs more testing before merging.

Avoid unnecessary CIB error messages

---

GNUmakefile

First, run it with nothing defined.  Then, iterate over a list of
defines that change major portions of compilation.  We want to make sure
the build succeeds with these various things defined or not.
Note that ENABLE_VERSIONED_ATTRS is not included at the moment.  This
seems to be less well supported, so it's not yet worth testing.

Test: cppcheck: Run cppcheck against certain defines.

---

include/crm/pengine/common.h

I had added this on the assumption that we would want to use the basic
resource formatted output messages for also printing out the XML config
of a resource.  However, we're going to go a different direction and
have the XML come from a separate output message.
So, this option can go away.  It was only ever in -rc1 so it's unlikely
anyone is using it.  I'm not simply reverting the patch that introduced
it because that patch also changed how all these pe_print_* options were
defined, and we'd like to keep that formatting.

Fix: scheduler: Remove pe_print_expanded_xml print option.

---

xml/api/crm_mon-2.3.rng

These will always be written out by newer versions of crm_mon, but
because the schema major version hasn't changed, we need to mark them
optional so older output still validates against this schema version.

Fix: xml: Mark new crm_mon attributes as optional.

---

tools/crm_resource.c

... from 1bbd5794, because the variables are not strings.

Fix: tools: revert some changes in crm_resource NULL checks

---

configure.ac
lib/common/cmdline.c
lib/common/tests/Makefile.am
lib/common/tests/cmdline/Makefile.am
lib/common/tests/cmdline/pcmk__cmdline_preproc_test.c

I feel like there's more tests that could be added, but I can't think of them right now.  At the least, this ensures basic functionality and gives us a place to put more tests in the future if bugs are found.

Add tests for pcmk__cmdline_preproc

---

include/portability.h
lib/common/tests/agents/pcmk_stonith_param_test.c
lib/common/tests/cmdline/pcmk__cmdline_preproc_test.c
lib/common/tests/flags/pcmk_all_flags_set_test.c
lib/common/tests/flags/pcmk_any_flags_set_test.c
lib/common/tests/operations/parse_op_key_test.c
lib/common/tests/strings/pcmk__char_in_any_str_test.c
lib/common/tests/strings/pcmk__str_any_of_test.c
lib/common/tests/strings/pcmk__strcmp_test.c
lib/common/tests/utils/pcmk_str_is_infinity_test.c
lib/common/tests/utils/pcmk_str_is_minus_infinity_test.c

These macros were defined in glib 2.38, which we can't use and it seems
like we won't be able to use it any time soon.  Luckily, it's easy
enough to define these in terms of other glib assertion macros in the
case we're on an older system.  That's basically what we were already
doing.  Now we'll only be doing it some of the time instead of all of
the time.

Fix: tests: Use g_assert_true, g_assert_false, and g_assert_null.

---

doc/sphinx/Pacemaker_Explained/rules.rst

They cannot be used in rsc_defaults or within cluster config, for
instance.
See: rhbz#1891929

Doc: Pacemaker Explained: Explain limitations of node attr expressions.

---

.travis.yml
cts/cts-exec.in
cts/cts-fencing.in

Previously for each test case, it would sleep for 1s waiting for the daemon to be initialized and ready for accepting connections. It would accumulate and become expensive given that there are dozens of test cases.
With this commit, rather than sleeping for 1s, it tracks the log and starts each test case whenever the daemon is shown being ready. So that it will save significant time in total for the whole testing with an average system (for my case, reduced from around 2m40s to 1m40s for cts-fencing, from around 7m15s to 6m35s for cts-exec).
On the other hand, for a system with poor performance, this solution also prevents test failures that are due to impatience (1s sleep might not be sufficient).

Test: cts-fencing, cts-exec: optimize fencing and exec regression testing via appropriate synchronization with daemons

---

lib/pacemaker.pc.in

... so other packages can detect where pacemaker is, if installed in a
nonstandard location. This is useful mainly for CI purposes.

Build: libcrmcommon: export prefix and exec_prefix via pkg-config

---

rpm/pacemaker.spec.in

Package builds on SuSE Tumbleweed are failing because the spec file
installs compiled CTS python files into /usr/bin/python2.X, but then
tries to package up files in /usr/bin/python3.X.
The problem here is that python_sitelib is already defined on SuSE, so
our attempts at setting it will never happen.  Thus, we end up with
%{python}=python (which is actually python2), and
%{python_sitelib}=/usr/lib/python3.X.
As a fix, we can set %{python}=python3 if the %{python_version} macro is
set.  Fedora really doesn't want us using this (and will fail if it is
used), but this piece of code should never be run on Fedora anyway.
This is the last ditch effort to set these variables.

Build: rpm: Fix python2 vs. python3 problems on SuSE.

---

daemons/controld/controld_schedulerd.c
lib/common/mainloop.c

Hi All,
This fix resolves the following Bugzilla issues:
- https://bugs.clusterlabs.org/show_bug.cgi?id=5445
This fix resolves a rare case where resources do not stop when the cluster is down.
Best Regards,

High: controld: Retry connection failure when controld is stopped.(Fix:CLBZ#5445)

---

configure.ac

Taken from libqb.
those options are stricly meant for runtime debugging purposes.
do NOT use in production.
check gcc man pages on how to use ASAN and UBSAN.

[build] add --with-sanitizers= option for sanitizer builds

---

tools/crmadmin.c

`crmadmin -D -q` doesn't print the DC quietly. The patch fixes it.

Fix: crmadmin: printing DC quietly if needed

---

xml/alerts-3.5.rng

Commit bd451763 mistakenly used alert-2.9 instead of alerts-2.10 as the
basis for alerts-3.5. This corrects that mistake.

High: xml: Revert to correct schema for alerts-3.5

---

doc/Pacemaker_Explained/en-US/Ch-Rules.txt

39d78f36b23d8910afdafd955df0170e0102b7e7 left the previous default in
the table, meaning we had a row with four columns, which ended up
shifting everything over by a column.  This is now fixed, the the
default column is so narrow that it's a little hard to read.
It doesn't matter too much, because this is all going away in favor of
new documentation soon.

Doc: Pacemaker Explained: Fix the node attributes expression table.

---

include/crm/cib.h
lib/cib/cib_client.c
lib/cib/cib_native.c

Hi All,
This is the fix proposed in Bugzilla below.
- https://bugs.clusterlabs.org/show_bug.cgi?id=5457
Clean up the callback table and notification table at the time of cib_native_signoff().
Best Regards,

Low: libcib: Cleanup at signoff.Fix(CLBZ#5457)

---

configure.ac
include/crm/common/ipc.h
lib/common/crmcommon_private.h
lib/common/ipc_client.c
m4/ax_check_link_flag.m4

When using libqb in SOCKET mode it uses DGRAM connections
that don't support SO_PEERCRED, so we can't use that to authenticate
the daemons. However, libqb does keep this information so we can
use the (newly created) API call to get it.
This requires a new call, that breaks the API of crm_ipc_is_authentic_process
so we wrap the new call in that one to maintain compatibility with
external users.
This does not work if corosync is using SOCKET connections (set
in corosync.conf) as it does not expose the libqb ipcc object
we need to pass into libqb.
Also this uncovered a bug in the linker options we were using
that caused breakage on FreeBSD, so fix that too.

ipc_client: Use libqb to get auth data for ipcc connections

---

crmd/control.c
doc/Pacemaker_Explained/en-US/Ch-Options.txt
lib/pengine/common.c
lib/pengine/unpack.c

Backport of https://github.com/ClusterLabs/pacemaker/pull/2142 for 1.1 branch.
I realize it'd be better to have these clarification/documentation for 1.1 branch as well, especially given that the handling of a negative value of `stonith-watchdog-timeout` is different here. In this case with a negative value, rather than an appropriate timeout automatically being calculated, watchdog-based self-fencing is disabled.

[1.1] Log: libpe_status: downgrade the message about the meaning of `have-watchdog=true` to info

---

cts/CTStests.py
daemons/attrd/attrd_commands.c
daemons/based/based_messages.c
daemons/controld/controld_corosync.c
daemons/controld/controld_election.c
daemons/controld/controld_fencing.c
daemons/controld/controld_join_client.c
daemons/controld/controld_join_dc.c
daemons/controld/controld_membership.c
daemons/controld/controld_messages.c
daemons/controld/controld_remote_ra.c
daemons/controld/controld_schedulerd.c
daemons/controld/controld_te_actions.c
daemons/controld/controld_utils.c
daemons/fenced/fenced_commands.c
daemons/fenced/fenced_history.c
daemons/fenced/fenced_remote.c
daemons/fenced/pacemaker-fenced.c
daemons/pacemakerd/pacemakerd.c
daemons/pacemakerd/pcmkd_corosync.c
include/crm/cluster.h
include/crm/cluster/internal.h
lib/cluster/Makefile.am
lib/cluster/cluster.c
lib/cluster/corosync.c
lib/cluster/cpg.c
lib/cluster/crmcluster_private.h
lib/cluster/election.c
lib/cluster/membership.c

This is part of the extended project to bring the Pacemaker code base into compliance with the current development guidelines, particularly around naming, function return values, and documentation. This covers all internal API in the libcrmcluster library, as well as public API other than what has to be kept for backward compatibility (function names/signatures etc.).

Best practices for libcrmcluster

---

daemons/attrd/attrd_commands.c
daemons/attrd/attrd_utils.c
daemons/attrd/pacemaker-attrd.h

This commit prevents writing out of attributes from being triggered by
cib_replace event on a node that is requesting shutdown, so that it
prevents leftover attributes of the shutdown node in cib.
Race conditions were encountered on shutdown and startup of a node.
Pacemaker is v1.1.18+, but I think the latest revision should be
potentially impacted too.
Node2 was shutting down. When crmd was stopped from node2, node1 erased
all the transient attributes of node2 from cib:
```
Sep 21 08:33:49 [7849] node1       crmd:   notice: peer_update_callback:
Our peer on the DC (node2) is dead
Sep 21 08:33:49 [7844] node1        cib:     info: cib_process_request:
Completed cib_delete operation for section
//node_state[@uname='node2']/transient_attributes: OK (rc=0,
origin=node1/crmd/114, …
```

Fix: attrd: prevent leftover attributes of shutdown node in cib

---

daemons/attrd/attrd_commands.c
lib/lrmd/proxy_common.c

remote_proxy_cb() currently adds the remote node's name as
PCMK__XA_ATTR_NODE_NAME if that attribute is not explicitly set. This is
necessary for attrd update commands. For those, lack of an explicit node
name means to use the local node. Since requests are proxied to full
nodes, the node hosting the remote resource would be incorrectly treated
as the "local node", causing the attribute to be updated for the wrong
node.
However, for other commands, this is not the case. Lack of an explicit
node name can mean "all nodes" (as for CLEAR_FAILURE and QUERY), or a
node name may be ignored (as for REFRESH). In these cases (the
non-update commands), we don't want to add a node name automatically if
it's not explicitly set.
Resolves: RHBZ#1907726

Fix: liblrmd: Limit node name addition to proxied attrd update commands

---

include/crm/common/xml_internal.h
include/crm/pengine/internal.h
lib/common/crmcommon_private.h
lib/common/nvpair.c
lib/common/operations.c
lib/common/patchset.c
lib/common/xml.c
lib/pengine/complex.c
lib/pengine/pe_digest.c
lib/pengine/rules.c

This is a follow-up to PR #2224.
The most interesting part is a new function pcmk__xe_remove_matching_attrs() which is a basically a "foreach remove" function for XML attributes, to reduce code duplication and enhance readability. It does not significantly affect scheduler timings.

Minor scheduler digest fixes and refactoring

---

cts/Makefile.am
cts/cli/crm_resource_digests.xml
cts/cli/regression.tools.exp
cts/cts-cli.in
include/pacemaker-internal.h
include/pacemaker.h
include/pcmki/Makefile.am
include/pcmki/pcmki_resource.h
lib/pacemaker/Makefile.am
lib/pacemaker/pcmk_output.c
lib/pacemaker/pcmk_resource.c
tools/crm_resource.c
tools/crm_resource_runtime.c
xml/Makefile.am
xml/api/digests-2.6.rng

This adds a --digests command-line option to crm_resource, to show what operation digests Pacemaker would use for a given resource and node (optionally with some parameter overrides).
This is not particularly useful for end users, but can help developers with debugging digest-related code and can allow higher-level tools to hide resource parameter changes from Pacemaker, thus avoiding a resource restart (which could cause problems, so anyone doing so takes the risk on themselves and must ensure that the service is in a reasonable state, e.g. making the change effective themselves before changing the parameters and operation digests).
Example use case:
fence_scsi requires a parameter specifying the list of SCSI disks to be reserved. Normally, changing this list forces a restart of the …

New crm_resource --digests option

---

configure.ac
daemons/pacemakerd/pcmkd_corosync.c

corosync shutdown tracking has been broken for ages (since the
trackstart/stop calls were removed in 2012), so pacemaker has not been
able to veto corosync shutdown requests.
The corosync_cfg_startstart/stop calls have now been re-added back to
corosync and with this patch, the pacemaker shutdown veto will
work again (provided shutdown is done as a REQUEST rather then
REGARDLESS or IMMEDIATE of course). There is a new flag (--force
added to corosync-cfgtool -H which uses REGARDLESS.
I'm not 100% sure that I've got the configure.ac correct. Though it does work, it might not be 'correct'.

corosync: Add cfg_trackstart/stop calls

---

.travis.yml

More and more deployment and development is being done on ARM64/AARCH64 architecture.
It would be good if Pacemaker is being tested on ARM64!

Add a job to build and test on ARM64 CPU architecture

---

daemons/execd/remoted_proxy.c
daemons/pacemakerd/pacemakerd.c
include/crm/common/ipc_internal.h
lib/common/ipc_server.c
tools/crm_mon.c

Looks like a clean solution so far.
We had EREMOTEIO already that can be used to notify that there is pacemaker-remoted but the api doesn't support proxying.
Have to check if I can make the proxy-callback NULL but accept.

Fix: crm_mon: detect when run on remote-node

---

daemons/execd/execd_commands.c

Hi All,
This fix avoids fencing resource monitoring errors that can occur when a DC node is fenced.
It corresponds to the following bugzilla fix.
- https://bugs.clusterlabs.org/show_bug.cgi?id=5393
Best Regards,

Mid: execd: Skips merging of canceled fencing monitors.(Fix:#CLBZ5393)

---

include/crm/cib/internal.h
include/crm/common/output_internal.h
lib/cib/cib_remote.c
lib/common/output_html.c
lib/common/output_log.c
lib/common/output_none.c
lib/common/output_text.c
lib/common/output_xml.c
tools/crm_mon.c
tools/crm_mon.h
tools/crm_mon_curses.c

This fixes most things that came up in #2284 except for functionalizing the connection code.  Additionally, this will need to be rebased once #2286 is merged because it touches the same areas.  And finally, I've been unable to actually test the remote CIB functionality.  crm_mon connects to the cluster node, but the following pam errors prevent me from authenticating:
```
Feb 03 09:30:11 cluster01 pacemaker-based     [58028] (cib_remote_listen)       debug: New clear-text connection from 192.168.122.1
Feb 03 09:30:11 cluster01 pacemaker-based     [58028] (cib_remote_listen)       info: Remote CIB client pending authentication | 0x5586db36e120 id: d92f42e9-4b96-4764-9aeb-e6a4fc14120d
Feb 03 09:30:11 cluster01 pacemaker-based     [58028] (cib_remote_auth)         info: Login: …
```

Fix various crm_mon problems

---

tools/crm_resource.c

If no output is produced but an error message is printed (like, when an
inactive resource is provided on the command line), don't print the
error message for the pcmk_rc_no_output error code.  It's weird to see
output and a message about no output at the same time.
Similarly, don't print an "Error: OK" message when usage is printed.

Low: Fix a problem with crm_resource exit code handling.

---

daemons/fenced/fenced_history.c

If a fencer had a pending fencing operation in the history but somehow
was not reachable when the fencing operation returned, the pending
operation would remain outdated and get stuck in the history.
The solution here is to broadcast returned fencing operations and update
outdated pending ones in the history.

Fix: fencer: broadcast returned fencing operations and update outdated pending ones in the history

---

lib/common/iso8601.c

The first one (years) is actually a false positive as coverity is just not looking deep enough into year_days.
In theory it would of course be possible that sbdy specifies a span long enough that seconds would exceed int in days or months.

Fix: iso8601: prevent sec overrun before adding as long long

---

include/crm/crm.h

This is being bumped due to the addition of the --output-as= and
--output-to= arguments to crm_verify for formatted output.  In addition,
there are various minor differences in the crm_resource text output.  It
is hoped that over time, these differences won't matter as much because
consumers can use the XML output instead.

Fix: include: Bump CRM_FEATURE_SET to 3.7.2.

---

tools/crm_resource.c
tools/crm_verify.c

G_OPTION_FLAG_NONE was not defined until glib 2.42, which is later than
the minimum we require.

Low: tools: s/G_OPTION_FLAG_NONE/0/

---

doc/sphinx/Pacemaker_Explained/constraints.rst

The references for rsc-pattern are 1 indexed and not 0 indexed.
See https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_05_01
Signed-off-by: Nathaniel Clark <Nathaniel.Clark@misrule.us>

Doc: rsc-pattern indexing

---

daemons/attrd/pacemaker-attrd.c
daemons/pacemakerd/pcmkd_corosync.c

If the corosync cfg conection goes down, don't just quit, but
keep trying to reconnect.
In theory this could retry forever, but in practice the attrd->cib
connection times out. I've increased the timeout for this to give
corosync a little longer to start, but it's that timeout that
ultimately decides how long pacemaker will survive the loss of
corosync.
(In actual practice, of course, the node should be fenced!)

cluster: try to reconnect with corosync if it goes down

---

fencing/history.c
include/crm/fencing/internal.h

Backports of https://github.com/ClusterLabs/pacemaker/pull/2297 and https://github.com/ClusterLabs/pacemaker/pull/2304 for 1.1 branch.
If a fencer had a pending fencing operation in the history but somehow
was not reachable when the fencing operation returned, the pending
operation would remain outdated and get stuck in the history.
The solution here is to broadcast returned fencing operations and update
outdated pending ones in the history.

[1.1] Fix: fencer: broadcast returned fencing operations and update outdated pending ones in the history

---

INSTALL.md
configure.ac
cts/CTStests.py
cts/cts-scheduler.in
doc/sphinx/Pacemaker_Development/python.rst
include/portability.h
lib/Makefile.am
mk/common.mk
rpm/pacemaker.spec.in
tools/crm_resource.c
tools/crm_verify.c

Previously, we did not have any CI platforms that could test our *oldest* supported dependencies. This meant that occasionally we would accidentally use some feature that wasn't supported in all versions, and would have to revert it once we stumbled across it. This was made worse by Pacemaker's ultra-long support window for old build environments -- typically around a decade, which is a leftover from the days before most distributions packaged Pacemaker and most users built their own.
Now, raise the minimum versions of dependencies to what's available in major Linux distribution releases from about 5 years ago (for example, Debian 8 "jessie", Ubuntu 15 "xenial", and RHEL 7.2). We can actually test these versions in CI, so we can ensure we support what we claim to.

Raise minimum dependency versions (again)

---

cts/cts-scheduler.in

Since commit 4becd5d, if --out-dir is specified, all the required
subdirectories must already exist.
With this commit, we automatically create any missing subdirs, provided
that <out-dir> itself exists.
Since we're creating the subdirectories ourselves now, we also give .out
files and .valgrind files their own subdirs.

Test: cts-scheduler: Create output subdirs if they don't exist

---

xml/Makefile.am
xml/api/crm_mon-2.8.rng
xml/api/nodes-2.8.rng

This allows it to be shared between the crm_mon and future crm_simulate
schemas.  Note that only the most complicated node schema has been
broken out.  There's still the simpler element-node-with-attribute, but
I don't think that will be used anywhere else.
Also note that any schemas including this one will need to define their
own node list that has the reference.  The idea here is that somewhere
might want a schema for just a single node instance in the future.

Feature: xml: Move node-related XML schema into its own file.

---

lib/pengine/utils.c

The function is set up to use rsc->allowed_nodes if rsc is not NULL.
However, we are passing both rsc and rsc->allowed_nodes at almost every
call site.  Simplify those callers to use the function as it is defined.

Refactor: scheduler: Update args to pe__show_node_weights.

---

include/crm/common/internal.h
include/crm/common/ipc_internal.h
include/crm/common/logging.h
include/crm/common/results.h
include/crm/common/util.h
include/crm/common/util_compat.h
include/crm/crm.h
include/crm/crm_compat.h
lib/cib/cib_native.c
lib/common/nvpair.c
lib/common/strings.c
lib/common/utils.c
lib/fencing/st_client.c
lib/pengine/pe_output.c
tools/crm_resource.c
tools/stonith_admin.c

This is mostly renaming some functions to internal equivalents and leaving the old names as deprecated wrappers.
The most interesting thing is dropping the use of __builtin_expect() (__likely()/__unlikely) compiler hinting.

Deprecate more public API

---

lib/pacemaker/pcmk_sched_clone.c

- Refactor: libpacemaker: Functionalize part of sort_clone_instance()
- Refactor: libpacemaker: Avoid unnecessary iterations over GList
- Refactor: libpacemaker: Make sort_clone_instance more uniform
- Refactor: libpacemaker: Reduce nesting in distribute_children()
Branched off #2313

Refactor: libpacemaker: Clone instance sorting and allocation

---

tools/crm_mon.c

actually while resources are evacuated from the node. But atm
there is no clean and easy way to tell when this is done or if
pacemakerd is just shutting down leftover daemons. So try to
connect anyway.
This showed up to be an issue - introduced by checking for
pacemakerd in full up & running state - when resources are
using crm_mon in their stop-operation.
Maybe don't merge this right away.
I've opened this PR with the simplest solution to just handle
the state where pacemakerd is sequentially shutting down
the subdaemons exactly like as if it was fully up and running.
So we can discuss here.
Alternative might be introduction of an additional state so
that when querying the state of pacemakerd the caller can
know that it is actually still trying to get down all resources
on the node …

[WIP] Fix: crm_mon: try to connect CIB while pacemakerd shutting down

---

tools/crm_mon.c

we need to do this in all output modes (xml specifically)

Fix: crm_mon: try to connect CIB while pacemakerd shutting down

---

etc/sysconfig/pacemaker
lib/common/watchdog.c

If a pacemaker sub-process terminates unexpectedly in an environment where fail_fast=yes is set, no message will be left in pacemaker.log indicating the cause.
(We do not use fail_fast=no because there is a problem [1] that the attributes will remain missing if controld or attrd unexpectedly terminates.)
I am aware of the risk [2], but sbd executed via panic_sbd() calls sync() [3] before sysrq_trigger('b').
[1] https://github.com/ClusterLabs/pacemaker/pull/1699
[2] https://github.com/ClusterLabs/pacemaker/pull/874#issuecomment-171069747
[3] https://github.com/ClusterLabs/sbd/blob/v1.4.2/src/sbd-common.c#L958

Call sync() before calling sysrq_trigger(b) in panic_local()

---

tools/crm_resource.c

The output object won't be set up yet, and it can never be set up before
command line processing because we need to look at the parsed arguments
to know what kind of object to set up.  The rest of the code shuffling
is to make args available globally.  If --quiet is passed before the
rest of the arguments, we shouldn't add the error.

Fix: tools: Don't reference the output object in cmdline processing.

---

etc/sysconfig/pacemaker
lib/common/watchdog.c

This is a supplement to https://github.com/ClusterLabs/pacemaker/pull/2344.
I think some users want both log and kernel dump, but what about?

Support "sync-crash" option with PCMK_panic_action

---

tools/crm_mon_curses.c

This was broken by 6233f2ffb429c889747d5d56fa0b679424562c0d, which
switched from the format-specific out->info function to the text-only
pcmk__formatted_printf function.  Remember that curses always needs to
use its own printing functions or the screen will look weird.

Low: Fix maint-mode output on curses mode.

---

lib/pengine/pe_output.c

It looks like this only happens for brief output when there are only
primitive resources in the cluster.  In that case, the summary header
was getting added as a list item under the rest of the resources.

Low: libpe_status: Don't output an extraneous header under crm_mon -b.

---

daemons/controld/controld_execd_state.c
daemons/execd/pacemaker-execd.c
daemons/execd/remoted_tls.c
include/crm/common/mainloop.h
include/crm/lrmd.h
include/crm/lrmd_internal.h
lib/common/mainloop.c
lib/lrmd/lrmd_client.c

This is a spin-off of a project to improve failure messages in status displays. While working on that, I found that liblrmd could return values that would be misinterpreted, leading to nonsensical log messages. This PR cleans up the return codes from all the functions in lrmd_client.c, and improves comments and log messages.
This is a bit questionable for 2.1 since it has a lot of refactoring, but the incorrect codes/messages could be considered bugs, and I'd like to fix them for 2.1.0.

Improve liblrmd return codes and log messages

---

extra/resources/ping

This PR adds a verbose mode that, when enabled, logs the output of ping and fping at the info level.
Sample output:
When ping and the non-verbose debug mode are being used:
```
[root@pcmk-1]# pcs resource update ping use_fping=0
[root@pcmk-1]# pcs resource update ping debug=1
[root@pcmk-1]# crm_resource --force-start -r ping
Operation start for ping (ocf:pacemaker:ping) returned: 'ok' (0)
```
When ping and the new, verbose debug mode are being used:
```
[root@pcmk-1]# pcs resource update ping debug=2
[root@pcmk-1]# crm_resource --force-start -r ping
Operation start for ping (ocf:pacemaker:ping) returned: 'ok' (0)
INFO: my.gateway.com is alive
www.bigcorp.com is alive
```
When fping and the new, verbose debug mode are being used:
```
[root@pcmk-1]# pcs resource update ping use_fping=0 …
```

Log ping and fping output when debug mode is set to verbose

---

daemons/pacemakerd/pacemakerd.c
include/crm/crm.h
xml/Makefile.am
xml/api/pacemakerd-2.10.rng

The main purpose of this is to finish getting pacemakerd moved off the
existing command line handling code (pcmk__cli_help in particular) so
that code can eventually be deprecated or removed.  pacemakerd itself
does fairly little printing.

Feature: daemons: Convert pacemakerd to formatted output.

---

cts/cts-exec.in
cts/cts-fencing.in
cts/lab/watcher.py
daemons/execd/pacemaker-execd.c
daemons/fenced/pacemaker-fenced.c
daemons/pacemakerd/pacemakerd.h
daemons/pacemakerd/pcmkd_corosync.c
include/crm/common/logging.h
include/crm/common/logging_compat.h
include/crm/common/logging_internal.h
lib/common/logging.c
lib/common/utils.c
rpm/pacemaker.spec.in

This addresses issues found when trying to build and run 2.1.0-rc1 on RHEL 9 beta hosts, which have newer versions of software (e.g. Python 3.9), Linux kernel (e.g. having "protected_regular" enabled), etc.

Support newer OS/software versions

---

.travis.yml
configure.ac
cts/lab/CTStests.py
daemons/pacemakerd/pcmkd_corosync.c
lib/common/watchdog.c
rpm/pacemaker.spec.in

This combines two unrelated items, a new build-time option to specify the default for sbd start-up synchronization, and a workaround for a Corosync bug. We should be ready to release 2.1.0-rc2 after this.

Preparation for 2.1.0-rc2 release

---

lib/common/pid.c

In an environment where SBD is enabled, the following **error** message is always output at the time of DC election.
It is not a problem that readlink() of pacemaker-controld (non-root) fails because it targets sbd (root),
but the log level should be lowered to **info** because it will confuse users.
```
:
May 12 18:30:07 rhel83-1 pacemaker-controld  [756142] (crm_timer_popped)        info: Election Trigger just popped | input=I_DC_TIMEOUT time=20000ms
May 12 18:30:07 rhel83-1 pacemaker-controld  [756142] (do_log)  warning: Input I_DC_TIMEOUT received in state S_PENDING from crm_timer_popped
May 12 18:30:07 rhel83-1 pacemaker-controld  [756142] (do_state_transition)     info: State transition S_PENDING -> S_ELECTION | input=I_DC_TIMEOUT cause=C_TIMER_POPPED origin=crm_timer_popped
May 12 …
```

Log: pcmk__pid_active: Lower the log level when readlink() is EACCES

---

tools/crm_resource.c
tools/crm_resource_runtime.c

The point of this is to avoid EINVAL where possible.  That value maps to CRM_EX_SOFTWARE, which means the user will see an "internal software bug" message.  Often times, this is incorrect.  This PR is narrowly focused to just catch a couple cases that are pretty obvious.  There are likely more of them lurking out there.

Fix a couple more error codes in crm_resource

---

tools/crm_verify.c

Broke with ca94575116.
It produces with a command like:
```
Segmentation fault (core dumped)
```

Fix: tools: get `crm_verify --xml-pipe/-p` working again

---

.gitignore
GNUmakefile

lcov solves my two previous big problems with our coverage reports.
First, it didn't know how to deal with include files in brackets.
Second, it didn't know how to deal with the .libs directories.  lcov
appears to handle both of these better, which produces a more accurate
coverage report.

Build: Switch from gcovr to lcov for producing coverage reports.

---

include/crm/common/output_internal.h
lib/common/output.c
tools/crm_resource.c
tools/crm_resource_print.c
tools/crm_resource_runtime.c
xml/api/crm_resource-2.11.rng

The point of this is just to see if I'm on the right track.  It seems like almost all of the work for supporting XML validate-all output is in defining a schema for the resource agents to follow, and then adding support to the resource agents themselves.  There doesn't seem like much required out of crm_resource.
Here's an example of successful output:
```
<pacemaker-result api-version="2.3" request="crm_resource --class ocf --provider pacemaker --agent Dummy --validate --output-as xml">
<validate>
<overrides/>
<result status="0" action="validate-all" name="test" class="ocf" type="Dummy" provider="pacemaker"/>
<command><![CDATA[<dummy><status>0</status></dummy>
]]></command>
</validate>
<status code="0" message="OK"/>
</pacemaker-result>
```
And then here's an example of output when …

Handle XML output from validate-all actions

---

daemons/controld/controld_remote_ra.c

When a remote node is up again after being killed, cleans the attrd's cache for the node. This is necessary to ensure that the CIB and the attrd cache will match. Otherwise, when the node is up the cache will be populated with the values from other nodes (e.g. transient attributes) and the attributes will be clean from the CIB. Causing a discrepancy among these data sources.
How to reproduce the issue:
0. Setup a cluster with 3 nodes. In the third node add two remote nodes. In this example, let's call the remote nodes as `ionian` and `aeolian`.
1.  On the DC node (make sure it is either node1 or node2), check that we don't have any transient node attributes defined for the remote nodes:
`cibadmin --query | python3 -c 'import sys; import xml.etree.ElementTree as ET; …

Purge remote node attribute when the node is up.

---

daemons/attrd/attrd_commands.c
daemons/controld/controld_fencing.c

pacemaker-attrd can write out a remote node's attributes to the CIB only if the node is in its remote peer cache. Unlike the controller, pacemaker-attrd does not manage the remote peer cache via parsing the CIB; instead, it adds nodes to the cache after certain events, the most important being the controller setting the probed attribute when a remote node comes up.
If the cluster restarts on a cluster node, it will get a copy of all current attributes via a sync request to other nodes. However, it will not know that remote nodes are remote, and if the remote nodes are already up, it won't easily learn it. If the node later becomes DC, its scheduler will not see the remote nodes' attributes. If the cluster includes unfencing, this can lead to an unfencing loop.
The main solution is to …

Help attribute manager learn node "remoteness" more quickly

---

daemons/fenced/fenced_commands.c

Hi All,
There is not enough space in the log.
Old log.
```
Jun 23 15:20:36.198 rh83-dev02 pacemaker-fenced    [51976] (handle_request)     notice: Received forwarded fencing request from peerrh83-dev01 to fence (reboot) peer rh83-dev01
```
New log.
```
Jun 23 15:34:24.075 rh83-dev02 pacemaker-fenced    [103570] (handle_request)    notice: Received forwarded fencing request from peer rh83-dev01 to fence (reboot) peer rh83-dev01
```
Best Regards,

Low: fenced: Insufficient space on log.

---

cts/cli/regression.crm_mon.exp
include/crm/common/output_internal.h
lib/pengine/pe_output.c
xml/api/crm_mon-2.13.rng

Adding two additional options (stonith-timeout and priority-fencing-delay) to the crm_mon xml output.
Outputting cluster timing settings in a consistent unit (milliseconds), so they can easily get parsed from monitoring tools not having access to the cluster configuration.

crm_mon xml outputs cluster timing settings in consistent unit.

---

daemons/pacemakerd/pcmkd_corosync.c
lib/cluster/corosync.c
lib/cluster/cpg.c

While the current API calls used by pacemaker are still supported
in corosync, this change makes things more future-proof and easier
to incorporate new features as needed.

cluster: Use most up-to-date corosync API calls

---

cts/scheduler/summary/clone-max-zero.summary
lib/pengine/clone.c

In the corner case where there's no nodes (and therefore no instances of
a clone resource running anywhere), we still want to output the header.
This can occur in PCS testing.
Regression in 2.1.0 caused by f99d9eecb.

Low: scheduler: Output the clone header if there are no instances.

---

cts/cli/regression.tools.exp
lib/pacemaker/pcmk_output.c
lib/pengine/pe_output.c
tools/crm_simulate.c

This typically should only come up if --exclude=nodes is passed to
crm_mon, but it's possible someone might run crm_mon against a CIB with
no nodes.  In this case, do not output an extra blank line between the
cluster status section and the resource list section.

Low: tools: If there are no nodes, don't add an extra blank line.

---

daemons/fenced/pacemaker-fenced.c
lib/pacemaker/pcmk_sched_allocate.c
lib/pacemaker/pcmk_sched_clone.c
lib/pacemaker/pcmk_sched_native.c
lib/pacemaker/pcmk_sched_promotable.c
lib/pengine/bundle.c
lib/pengine/native.c
lib/pengine/unpack.c
tools/crm_resource.c
tools/crm_resource.h
tools/crm_resource_print.c
tools/crm_simulate.c

But, note all the caveats in the first patch.  I could go through and work on some of those to convert more for loops.  An additional idea I had was to add something to call out->message() for each item in a list.  That comes up in a fair number of places.
I have not tested timings for any of this, but I don't think there should be any serious performance hit.  g_list_foreach is a single function call that contains a while loop and a call of the given function for each element.  So, the difference should be the addition of a single function call.

Use g_list_foreach where possible

---

lib/pengine/pe_output.c

The argument to add_dump_node is an xmlNodePtr.  Adding an ampersand at
these two locations means we are passing it an xmlNodePtr *, which
results in segfaults when referencing.

Med: tools: Fix a segfault when calling "crm_simulate -U".

---

daemons/fenced/fenced_commands.c
daemons/fenced/fenced_history.c
daemons/fenced/fenced_remote.c
daemons/fenced/pacemaker-fenced.h
include/crm/fencing/internal.h
include/crm/stonith-ng.h
lib/fencing/st_client.c

Hi All,
This is a revised version of the following revised PR.
- https://github.com/ClusterLabs/pacemaker/pull/2444
Added a nanosec field to the fencing completion time to improve the fencing history display issue that fails and succeeds at exactly the same time.
This feature only works in environments that support CLOCK_MONOTONIC.
As for stonith_api_time (), I haven't modified it because I only need to know the latest time of st_done.
Also, the comparison of nanoseconds (stonith__later_succeeded () and stonith__sort_history ()) is based on the idea that the exact same nanoseconds will not occur.
If there is exactly the same nanosecond data, it may be better to output debug log etc.
(However, in this case, stonith__sort_history() have no control over the sort order.)
Best Regards,
Hideo …

Mid: fenced: Added nanosecond field to operation completion data.

---

include/crm/common/output.h
lib/pacemaker/pcmk_output.c
lib/pengine/pe_output.c
tools/crm_simulate.c

This is the start of a project to improve the display of failed actions in status output (crm_mon/crm_simulate). The changes at this point are minimal. An example of the previous output:
* rsc1_monitor_10000 on dhcp180 'not running' (7): call=16, status='complete', exitreason='none', last-rc-change='2016-03-30 08:46:11 -05:00', queued=0ms, exec=0ms
would now become:
* rsc1_monitor_10000 on dhcp180 'not running' (7): call=16, status=complete, last-rc-change='Wed Mar 30 08:46:11 2016', queued=0ms, exec=0ms
Note that exitreason='none' has been dropped (it will now only be shown if it is available, never 'none'), and the date/time format is now consistent with other date/time displays (such as the Last updated/Last changed fields). Additionally, the queued/exec times will only be shown now …

Minor improvements to failed actions in status display

---

include/pcmki/pcmki_sched_utils.h
lib/pacemaker/Makefile.am
lib/pacemaker/libpacemaker_private.h
lib/pacemaker/pcmk_graph_producer.c
lib/pacemaker/pcmk_sched_allocate.c
lib/pacemaker/pcmk_sched_bundle.c
lib/pacemaker/pcmk_sched_colocation.c
lib/pacemaker/pcmk_sched_constraints.c
lib/pacemaker/pcmk_sched_group.c

As part of a general "best practices" project for libpacemaker, address the size of pcmk_sched_constraints.c by separating functions related to each type of constraint into their own files (starting with colocations in this PR), with pcmk_sched_constraints.c containing only generic functions that apply to any constraint type.
With this PR, pcmk_sched_constraints.c drops from just over 3,000 lines to less than 2,400, while the new pcmk_sched_colocation.c (which also gets a related function from pcmk_sched_graph.c) is just over 800.

Separate colocation-related functions into own source file

---

include/pcmki/pcmki_scheduler.h
lib/pacemaker/libpacemaker_private.h
lib/pacemaker/pcmk_output.c
lib/pacemaker/pcmk_sched_allocate.c
lib/pacemaker/pcmk_sched_colocation.c
lib/pacemaker/pcmk_sched_constraints.c
lib/pacemaker/pcmk_sched_location.c
lib/pacemaker/pcmk_sched_messages.c
lib/pacemaker/pcmk_sched_ordering.c
lib/pacemaker/pcmk_sched_tickets.c
tools/crm_mon.c
tools/crm_resource_runtime.c
tools/crm_ticket.c

After splitting all constraint-type-specific APIs into their own source files, pcmk_sched_constraints.c contains only APIs related to constraints in general. Bring those to current guidelines regarding naming and commenting.

Best practices for generic constraint functions in libpacemaker

---

daemons/controld/controld_execd.c
daemons/controld/controld_execd_state.c
daemons/controld/controld_remote_ra.c
daemons/controld/controld_te_actions.c
daemons/execd/execd_commands.c
daemons/fenced/fenced_remote.c
include/crm/common/results.h
include/crm/common/results_internal.h
include/crm/lrmd_internal.h
include/pcmki/pcmki_transition.h
lib/common/results.c
lib/lrmd/lrmd_client.c
lib/pacemaker/pcmk_graph_consumer.c
lib/pacemaker/pcmk_sched_transition.c
lib/pacemaker/pcmk_sched_utils.c
lib/pengine/pe_output.c

The result of a forked process consists of an execution status (i.e. whether we could successfully execute the action), the process's exit status, and a human-friendly exit reason for status displays.
Formerly, the exit reason would only be set by OCF resource agents. Now, we also set it for some internal errors.

Show some internal errors as exit reason in failed action displays

---

daemons/execd/execd_commands.c
include/crm/common/results.h
include/crm/services.h
lib/common/results.c
lib/fencing/st_client.c
lib/services/services_linux.c
lib/services/systemd.c
lib/services/upstart.c

Pacemaker defines a number of exit codes as extensions to the OCF exit codes, however most of them are more logically execution statuses. Use execution statuses where appropriate and deprecate extended codes no longer used.

Use execution status instead of exit status when appropriate

---

include/crm/services.h
include/crm/services_compat.h
lib/services/services.c
lib/services/services_linux.c
lib/services/services_lsb.c
lib/services/services_private.h
lib/services/systemd.c
lib/services/systemd.h
lib/services/upstart.c
lib/services/upstart.h

This is part of a larger project to ensure that libcrmservice always explicitly sets rc and status in svc_action_t results, rather than relying on the implicit defaults (PCMK_OCF_OK/PCMK_EXEC_DONE) or unconditionally overwriting them with error codes in the callers.

Minor clean-up in libcrmservice

---

lib/services/upstart.c

Upstart support is deprecated, but I want libcrmservice to be able to guarantee that rc and status have been set in all code paths. This has been tested by building (with a suitable patch for using the older dependencies on Ubuntu 14) and running the executor regression tests.

Ensure libcrmservice always explicitly sets rc and status for Upstart actions

---

cts/cts-exec.in
daemons/controld/controld_te_actions.c
daemons/execd/execd_commands.c
include/crm/common/results.h
include/crm/services.h
include/crm/services_internal.h
lib/fencing/st_client.c
lib/lrmd/lrmd_client.c
lib/services/services.c
lib/services/services_linux.c
lib/services/services_private.h
lib/services/systemd.c
tools/crm_resource_runtime.c

This is the last in a series of PRs. Previous ones ensured rc and status were set for systemd and upstart actions; this one covers file-based actions (generic actions, alerts, and ocf, lsb, and nagios resource actions), along with related clean-ups. There is also one systemd-related fix for a longstanding (and unnoticed) issue.

Ensure libcrmservice always explicitly sets rc and status

---

daemons/pacemakerd/pacemakerd.h
daemons/pacemakerd/pcmkd_subdaemons.c

The one thing not done in this patch set yet is dealing with the start_child return value.  If this returns FALSE, we should shut down previously started processes and quit.  However, I've not been able to make much progress on that.  First, a lot of our process shutdown code assumes the presence of a main loop which we will not have when daemons are first being started.
Second, processes may take some time to start and be ready to receive the shutdown signal.  In the time they are doing that, the main pacemakerd process may have already sent the signal.  This will get missed by the subdaemon and pacemakerd will be left spinning endlessly in pcmk_shutdown_worker, logging "Still waiting for %s to terminate".  I'm not sure what to do about this.

Fixes for starting/stopping daemons

---

daemons/execd/execd_alerts.c
daemons/execd/execd_commands.c
include/crm/services_internal.h
lib/fencing/st_client.c
lib/services/services.c
lib/services/services_linux.c
lib/services/services_private.h
lib/services/systemd.c
lib/services/upstart.c

This adds an exit reason to svc_action_t's private data, moves OCF exit reason parsing from the executor to libcrmservice, and sets an exit reason for internal libcrmservice errors. This allows better status messages for failed actions, for easier troubleshooting.

Add exit reasons for internal libcrmservice errors

---

daemons/pacemakerd/pacemakerd.h
daemons/pacemakerd/pcmkd_corosync.c
daemons/pacemakerd/pcmkd_subdaemons.c

This builds on top of #2526 to finish adding support for respawning subdaemons when corosync returns.

Recover from corosync crashes

---

include/crm/common/xml_internal.h
include/crm/services_internal.h
lib/common/xml.c
lib/services/services_linux.c
lib/services/services_private.h
lib/services/systemd.c
tools/crm_resource_print.c
tools/crm_resource_runtime.c
xml/api/crm_resource-2.14.rng

Previously, the crm_resource --force-* options would output the result of the action, but it did not show any exit reason set (whether by the agent itself or internally). Now that the services library manages the exit reason, we can easily show it.

Show exit reasons in crm_resource --force-*

---

daemons/controld/controld_execd_state.c

The event structure contains memory allocated by strdup that needs to be
freed when this function is done.

Low: daemons: Free memory at the end of fail_pending_op.

---

daemons/controld/controld_control.c
daemons/controld/controld_execd_state.c
daemons/controld/controld_schedulerd.c
daemons/controld/controld_utils.h
daemons/fenced/pacemaker-fenced.c
daemons/schedulerd/Makefile.am
daemons/schedulerd/pacemaker-schedulerd.c
daemons/schedulerd/pacemaker-schedulerd.h
daemons/schedulerd/schedulerd_messages.c
include/crm/common/Makefile.am
include/crm/common/ipc_internal.h
include/crm/common/ipc_schedulerd.h
lib/common/Makefile.am
lib/common/crmcommon_private.h
lib/common/ipc_client.c
lib/common/ipc_pacemakerd.c
lib/common/ipc_schedulerd.c
lib/common/ipc_server.c

This patch set does three things:
* Convert pacemaker-schedulerd to use glib for its command line handling.
* Rearrange how pacemaker-schedulerd uses formatted output.
* Convert pacemaker-schedulerd to use the new IPC API mechanism.

Modernize pacemaker-schedulerd

---

cts/cts-fencing.in
daemons/controld/controld_execd.c
daemons/fenced/fenced_commands.c
daemons/fenced/fenced_remote.c
include/crm/fencing/internal.h
lib/fencing/st_client.c
lib/fencing/st_rhcs.c
lib/services/services.c
lib/services/services_linux.c
lib/services/systemd.c
lib/services/upstart.c

The services library provides a full result consisting of exit status, execution status, exit reason, and process output. Previously, the fencer immediately converted this to a legacy Pacemaker return code, which was all that it tracked.
Now, the fencer preserves the full result as long as possible, converting to a legacy code only when needing to return it to clients/peers (for backward compatibility). Internally, it tracks the full result, allowing it to give better log messages, and better mappings to legacy codes.
Now that exit reasons are always logged by services library callers, we can lower the severity of services library log messages, to reduce log duplication seen by the user.
As of this pull request, clients/peers do not receive or use the full result, but that is planned for …

Track and log exit reasons in fencer

---

daemons/based/based_callbacks.c
daemons/based/based_notify.c
daemons/based/pacemaker-based.h
daemons/controld/controld_based.c
include/crm/cib/internal.h

Hi Ken,
Hi All,
This PR is a modified version of the next PR.
- https://github.com/ClusterLabs/pacemaker/pull/2565
After further consideration, I added a section change to the CIB replacement notification.
This avoids unnecessary Elections.
To Ken : I decided to include populate_cib_nodes () in this PR and move it to the if block.
Best Regards,

Mid: based controld: Suppresses unnecessary Election execution.(3)

---

cts/lab/patterns.py
daemons/controld/controld_remote_ra.c

16346686 (2.1.2-rc1) introduced a regression in the handling of
remote connection start timeouts.
It simplified setting failures for handle_remote_ra_start(), but overlooked the
case in retry_start_cmd_cb() where handle_remote_ra_start() is not called
because there is not enough time remaining.
Before that commit, the timeout would get PCMK_OCF_UNKNOWN_ERROR and
PCMK_EXEC_ERROR as the result. Now, fix the regression, and change that to
PCMK_EXEC_TIMEOUT with a suitable exit reason.

Fix: controller: handle remote connection start timeouts correctly

---

rpm/Makefile.am

If building a clean commit the tar-file has the commit and thus the content is defined.
In case of building a modified commit we can't tell what was modified from the filename
thus we have to rebuild the tar-file. Going for the timestamp on top might come to mind
but with git that isn't reliable as you might revert modifications of a file back to the
clean commit.

Fix: build: never reuse existing tar-file if building modified commit

---

extra/resources/controld

When using DLM ra(controld), as both SLE HA and RHEL HA officially recommend no-quorum-policy=freeze(see [1] and [2]), 
considering customers easily forget to set this value, It will be helpful if controld can give a warning when starting
[1] https://documentation.suse.com/sle-ha/15-SP3/single-html/SLE-HA-administration/#sec-ha-config-basics-global-quorum
[2] https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_high_availability_clusters/assembly_configuring-gfs2-in-a-cluster-configuring-and-managing-high-availability-clusters

OCF: controld: Give warning when no-quorum-policy not set as freeze while using DLM

---

daemons/fenced/fenced_commands.c

f52bc8e1ce (2.1.2) introduced a regression by using CLOCK_MONOTONIC to get the
current time. Use CLOCK_REALTIME instead.

Fix: fencer: get current time correctly

---

daemons/fenced/fenced_commands.c
daemons/fenced/fenced_history.c
daemons/fenced/fenced_remote.c
daemons/fenced/pacemaker-fenced.c
daemons/fenced/pacemaker-fenced.h
lib/fencing/st_actions.c

An earlier PR made the fencer track the full result of fence actions, including exit reasons. This extends that to the entire fencer IPC/CPG API.
The fencing client library provides results both as callbacks (to the requester of fencing) and as notifications (to all clients who registered for them). The ultimate goal is to provide the full result in both places, which would require the fencer to track and pass the full result for a bunch of API request types. It made more sense to convert the entire API to use full results, both for consistency and to move away from legacy return codes in general. (Custom legacy return codes can conflict with system errnos, and system errnos are not guaranteed to have the same meaning from node to node.)

Track full result including exit reasons throughout fencer API

---

daemons/attrd/attrd_utils.c
daemons/attrd/pacemaker-attrd.c
include/crm/cib/internal.h
lib/cib/cib_utils.c
lib/pacemaker/pcmk_simulate.c
tools/cibadmin.c
tools/crm_attribute.c
tools/crm_mon.c
tools/crm_node.c
tools/crm_resource.c
tools/crm_ticket.c

We have this same pattern all over the place, so reduce it to a single
common function.  This is kept distinct from cib_delete in case you want
to keep the signoff cib_free_callbacks actions separate.

Refactor: libs, tools: Add a cib__clean_up_connection function.

---

daemons/controld/controld_fencing.c
daemons/execd/execd_commands.c
daemons/execd/pacemaker-execd.h
daemons/fenced/cts-fence-helper.c
doc/sphinx/Pacemaker_Development/components.rst
include/crm/crm.h
include/crm/fencing/internal.h
lib/fencing/st_client.c
lib/pengine/unpack.c

This continues the long project to track exit reasons throughout the fencing code. Previous PRs handled the server side; the client side has three relevant pieces:
* Fencing action callbacks (stonith_callback_data_t)
* Fencing event notifications (stonith_event_t)
* Fencing history (stonith_history_t)
This PR addresses the first of those, which is the result data passed to the client that requested a fencing action. The most visible effect is that the executor can now get the exit reason from the fencing library and pass it to executor clients, which means that exit reasons can now be displayed for internal failures of fence device start, stop, and monitor actions.

Display exit reasons for fence device start/stop/monitor failures

---

include/crm/services.h
lib/fencing/st_actions.c
lib/services/services.c
lib/services/services_linux.c

Currently, we set a stonith action to pending if
`services_action_async_fork_notify()` returns true. However, "true" means
that the `svc_action` should not be freed. This might be because the
`svc_action` forked successfully and is pending, or it might be because
the `svc_action` has already been freed.
In the case of stonith actions, if we fail to fork, the `stonith_action_t`
object stored in `svc_action->cb_data` gets freed by the done callback,
and `services_action_async_fork_notify()` returns true. If we try to set
the action to pending, it causes a segfault.
This commit moves the "set to pending" step to the
`stonith_action_async_forked()` callback. We avoid the segfault and only
set it to pending if it's actually pending.
A slight difference in ordering was required to achieve this. …

Fix: fencing: Don't set stonith action to pending if fork fails

---

include/pacemaker.h
include/pcmki/pcmki_fence.h
lib/pacemaker/pcmk_fence.c
tools/stonith_admin.c

Now that stonith_event_t has an exit reason, add it as well to libpacemaker's high-level fencing API used by stonith_admin, and have stonith_admin display an error message if a fencing action fails.
The high-level fencing API has not been exposed publicly yet, so we don't have to worry about backward compatibility.

Show exit reasons for stonith_admin fencing failures

---

tools/crm_mon.c

The basic problem here is that if you run `crm_mon -d --output-to foo`, it creates a foo file and puts nothing in it because the output format is none.  Tell the user they need to specify an output format.

Improve error handling around crm_mon's daemonize mode

---

tools/crm_mon.c

With PCMK__COMPAT_2_0 enabled, pcmk_show_failed_detail is always
enabled.  Therefore, do not take it into account when showing whether
the "R" (show detail) toggle is in effect in crm_mon's help screen.
Without this, that toggle is always shown as being in effect.

Low: tools: Fix the show detail toggle in crm_mon.

---

include/crm/pengine/internal.h
include/pcmki/pcmki_simulate.h
lib/fencing/st_output.c
lib/pacemaker/pcmk_output.c
lib/pacemaker/pcmk_simulate.c
lib/pengine/bundle.c
lib/pengine/clone.c
lib/pengine/group.c
lib/pengine/native.c
lib/pengine/pe_output.c
tools/crm_mon.c
tools/crm_resource_print.c
tools/crm_simulate.c

Note that pcmk_simulate took an unsigned int and now takes a uint32_t.  This is a public function, but I think on most platforms this ought to be okay.  If not, we can change this one back.

Refactor: Use uint32_t for show_opts and section_opts.

---

configure.ac
daemons/pacemakerd/pacemakerd.c
daemons/pacemakerd/pacemakerd.h
daemons/pacemakerd/pcmkd_messages.c
daemons/pacemakerd/pcmkd_subdaemons.c
lib/common/ipc_client.c

Keep pacemakerd tracking subdaemons for liveness - via qb-ipc-connect and the packets exchanged for authentication as of now.
qb-ipc-connect as of current libqb is blocking for an indefinite time if the subdaemon is unresponsive - -SIGSTOP or busy mainloop.
Thus there is an experimental API extension of libqb https://github.com/ClusterLabs/libqb/pull/450 to be able to deal with that without needing ugly workarounds.
This is as well the reason why CI at this point is expected to fail as upstream master of libqb is missing the API extension.

Subdaemon heartbeat with modified libqb (async API for connect)

---

daemons/fenced/fenced_history.c
daemons/fenced/fenced_remote.c
daemons/fenced/pacemaker-fenced.h
include/crm/common/output_internal.h
include/crm/stonith-ng.h
lib/fencing/Makefile.am
lib/fencing/st_client.c
lib/fencing/st_output.c
tools/crm_mon_curses.c
xml/api/fence-event-2.15.rng

This is the final PR in the long project to show exit reasons in status displays for actions that failed due to internal Pacemaker errors. It adds the full result to the fencer's remote_fencing_op_t so it can be tracked in the fence history, and adds the exit reason to the stonith_history_t type, allowing crm_mon to display it in the failed fencing actions section.

Show exit reasons in failed fence action display

---

daemons/controld/controld_fencing.c
include/crm/stonith-ng.h
lib/fencing/st_client.c
tools/crm_mon.c

If stonith_api_del_notification is given NULL for its second argument,
just remove every notification from the list.

Refactor: libstonithd: Allow removing all registered callbacks at once.

---

lib/common/tests/cmdline/pcmk__cmdline_preproc_test.c
lib/common/tests/strings/Makefile.am
lib/common/tests/strings/pcmk__compress_test.c
lib/common/tests/strings/pcmk__guint_from_hash_test.c
lib/common/tests/strings/pcmk__numeric_strcasecmp_test.c
lib/common/tests/strings/pcmk__parse_ll_range_test.c
lib/common/tests/strings/pcmk__scan_double_test.c
lib/common/tests/strings/pcmk__scan_min_int_test.c
lib/common/tests/strings/pcmk__scan_port_test.c
lib/common/tests/strings/pcmk__str_table_dup_test.c
lib/common/tests/strings/pcmk__strikey_table_test.c
lib/common/tests/strings/pcmk__strkey_table_test.c
lib/common/tests/strings/pcmk__trim_test.c

Note that these tests could do a lot more, but I did not worry about trying to pass NULL in for a lot of parameters and seeing what happens.  It's obvious from looking at most of them that they do not handle NULL arguments in a lot of cases and we're not worried about that at the moment.
After applying these patches, the only parts left without code coverage are:
In scan_ll:
```
58         147 :         } else if (errno != 0) {
59           0 :             rc = errno;
60           0 :             local_result = default_value;
61           0 :             crm_warn("Could not parse integer from '%s' (using %lld instead): "
62             :                      "%s", text, default_value, pcmk_rc_str(rc));
```
I'm not sure we can ever hit this, at least not with glibc.
In pcmk__scan_double: …

Get lib/common/strings.c very close to 100% test coverage

---

daemons/fenced/pacemaker-fenced.c
extra/resources/attribute
extra/resources/o2cb.in
lib/common/options.c

This is the order required by the OCF resource agent schema.
See: rhbz#2049722

Low: resources: Put shortdesc after longdesc in the attribute agent.

---

lib/common/options.c
lib/services/systemd.c

Note that I have not yet been able to test this because I don't have the proper OS version installed, but it looks obviously correct to me.

Escape special XML characters in agent descriptions

---

daemons/fenced/pacemaker-fenced.c
daemons/schedulerd/pacemaker-schedulerd.c
daemons/schedulerd/pacemaker-schedulerd.h
daemons/schedulerd/schedulerd_messages.c
include/crm/pengine/pe_types.h
include/pcmki/pcmki_scheduler.h
lib/pacemaker/pcmk_sched_allocate.c
lib/pacemaker/pcmk_simulate.c
lib/pengine/status.c
tools/crm_resource_runtime.c
tools/crm_verify.c

While working on best practices for libpacemaker, I realized that pe_working_set_t flags were being ignored in some cases. This PR fixes that and includes related best-practices work on the affected functions.

Set working set flags correctly

---

cts/lab/patterns.py
include/pcmki/pcmki_sched_allocate.h
include/pcmki/pcmki_scheduler.h
lib/pacemaker/libpacemaker_private.h
lib/pacemaker/pcmk_sched_allocate.c
lib/pacemaker/pcmk_sched_bundle.c
lib/pacemaker/pcmk_sched_clone.c
lib/pacemaker/pcmk_sched_group.c
lib/pacemaker/pcmk_sched_native.c
lib/pacemaker/pcmk_sched_resource.c
lib/pacemaker/pcmk_sched_utilization.c

This continues the project to bring libpacemaker up to current development guidelines, focusing on functions before "stage 5" in pcmk_sched_allocate.c

Continue best practices for libpacemaker

---

tools/crm_mon.c

Previously, if you did --output-as=html --output-to= and backgrounded
the crm_mon process, it would not print anything to the destination file
until crm_mon exited.  However, if you added --daemonize, it would
output immediately.  This patch just makes the background behavior the
same as the daemonize behavior.
See: clbz#5492

Low: tools: Always output to the HTML dest file.

---

cts/lab/CTStests.py
cts/lab/ClusterManager.py
cts/lab/patterns.py
doc/sphinx/Pacemaker_Development/components.rst
include/pcmki/pcmki_scheduler.h
lib/pacemaker/libpacemaker_private.h
lib/pacemaker/pcmk_sched_allocate.c
lib/pacemaker/pcmk_sched_ordering.c
lib/pengine/utils.c

This continues the project to bring libpacemaker up to current development guidelines, finishing the functions in pcmk_sched_allocate.c. This finally abandons the "stageN" terminology for the scheduler.

Best practices for libpacemaker

---

rpm/pacemaker.spec.in

Pacemaker's spec file calls ./autogen.sh, which calls autoreconf, which
requires the autopoint command from gettext-devel

Build: rpm: depend on gettext-devel instead of gettext

---

configure.ac
include/crm/pengine/internal.h
lib/pengine/native.c
lib/pengine/tests/Makefile.am
lib/pengine/tests/native/Makefile.am
lib/pengine/tests/native/native_find_rsc_test.c
lib/pengine/tests/native/pe_base_name_eq_test.c
lib/pengine/tests/unpack/Makefile.am
lib/pengine/tests/unpack/pe_base_name_end_test.c

I am especially interested in the clone portion of this.
Also, this really skews the coverage numbers because of all the stuff called in the setup function.  That technically gets run during "make check", which means it's now covered by a test case.  Of course, that's not true - we're not actually testing any of that stuff, we're assuming it works in order to test something else.  So I might need to figure out some way to work around that.

Add a unit test for native_find_rsc

---

include/crm/crm.h
include/pcmki/pcmki_acl.h
lib/pacemaker/pcmk_acl.c
tools/Makefile.am
tools/cibadmin.c
xml/base/access-render-2.xsl

This is a forward-port of a commit from #1826.
Add a role and assign it to a user:
```
adduser rouser
usermod -a -G haclient rouser
pcs acl enable
pcs acl role create read-only description="Read access to cluster" read xpath /cib
pcs acl user create rouser read-only
cibadmin --show-access=color -Q -U rouser
```
The xpath referring to /cib is colored blue.
Add another role and assign it to the same user:
```
pcs acl role create write-only description="Write access to configuration" write xpath /cib/configuration
pcs acl role assign write-only rouser
cibadmin --show-access=color -Q -U rouser
```
The xpath referring to /cib/configuration is colored green, and the parts that should be blue are still blue.
Add another role and assign it to the same user:
```
pcs acl role create deny …
```

Feature: cibadmin to be able to "render" access mode for selected user

---

cts/cli/regression.rules.exp
cts/cli/regression.tools.exp
cts/cts-cli.in
include/crm/common/output_internal.h
include/crm/crm.h
tools/crm_rule.c
xml/Makefile.am
xml/api/crm_rule-2.16.rng

The hidden purpose of this PR is that after this, and then doing another one for crm_ticket (which needs to be converted to using glib for args first, ugh) then we can get rid of include/pcmki/pcmki_error.h.  And getting rid of entire source files is very appealing.
Note that the conversion away from CMD_ERR here means that errors will only be printed to the screen.  They will not also get logged with crm_warn.  For crm_rule at least, I am fine with that.  I'm sure I just copied and pasted that from somewhere else.

crm_rule improvements

---

extra/resources/HealthSMART.in

* The HealthSMART agent is now marked as version 1.0.
* Update the unique= attributes on parameters.
* The state directory check will only be run if OCF_CHECK_LEVEL=10.
Fixes T52.

Feature: resources: update HealthSMART agent for OCF 1.1

---

tools/attrd_updater.c

Two things were going wrong here:
(1) The "-v" option needs to be recognized by the command_cb function.
(2) All options must have a long name, so duplicate the "update" name.
Without a long name, the leading NULL is seen as the terminator for the
entire entry array and neither that entry nor any after it will be added
to the program.
Fixes T195.

High: tools: Fix the -v option to attrd_updater.

---

daemons/execd/execd_commands.c
daemons/execd/pacemaker-execd.h
daemons/fenced/fenced_commands.c
daemons/fenced/fenced_remote.c
daemons/fenced/pacemaker-fenced.c
daemons/fenced/pacemaker-fenced.h
include/crm/common/Makefile.am
include/crm/common/internal.h
include/crm/common/ipc_internal.h
include/crm/common/messages_internal.h
lib/common/ipc_server.c
lib/common/messages.c
lib/fencing/st_actions.c
lib/fencing/st_client.c
lib/services/services_linux.c
tools/stonith_admin.c

This is another follow-up addressing issues found during the project adding exit reasons for fencing actions. This improves some fencing logs, and refactors the code to make it simpler and easier to follow. Most significantly, it refactors server API processing as a hash table of function pointers rather than a long series of if-else blocks.

Improve fencing logs and code readability

---

include/crm/common/output_internal.h
include/crm/crm.h
lib/pacemaker/pcmk_output.c
tools/Makefile.am
tools/attrd_updater.c
tools/crm_attribute.c
xml/api/crm_attribute-2.18.rng

This also condenses the number of places where we have an attribute output message a little bit.  attrd_updater and crm_attribute use the same XML message.  crm_attribute uses its own text message because it has a special output format.  The intention is that the attrd_updater text message will become the single version in the future.
Also, perhaps it's worth making a new schema file specifically for the attribute element since it exists identically in two places.  Only the wrappings are different (see attrd_updater schema vs. crm_attribute schema).

Convert attrd_updater to use formatted output

---

tools/crm_attribute.c

If -G is given without -n or -P, print a usage message.  The previous
behavior appears to have been printing out some invalid information and
then printing an error message.  Instead, tell the user what they did
wrong.

Low: tools: Handle an error case in crm_attribute.

---

tools/crm_resource.c

The argument callbacks assume they have the originally initialized
options and update the values accordingly.
While we still accept multiple commands for backward compatibility, the
relevant options should be reset whenever an existing command is
overridden. Otherwise the options would result into havoc and possibly
cause segfaults of problematically composed commands such as
`crm_resource -l -a`.

Fix: tools: prevent possible crm_resource segfaults if multiple commands are specified

---

daemons/fenced/fenced_remote.c

Hi All,
Actually, a longer timeout is used than the timeout output in the next log.
```
Apr 25 12:41:59.270 rh85-dev03 pacemaker-fenced    [55863] (request_peer_fencing)       info: Total timeout set to 60 for peer's fencing targeting rh85-dev01 for pacemaker-controld.55867|id=8930a249
```
The correct timeout should be logged to avoid confusion when tracking the log.
```
Apr 25 12:52:07.542 rh85-dev02 pacemaker-fenced    [131676] (request_peer_fencing)      info: Total timeout set to 72 for peer's fencing targeting rh85-dev01 for pacemaker-controld.131680|id=722d4435
```
Best Regards,

Low: fenced: Correctly log the total fencing timeout.

---

tools/crm_resource.c

Should never matter since the API change (ref. RHBZ 2079498).

Low: Fix print spec for unsigned int count

---

tools/attrd_updater.c

This corrects a bug introduced with
ef0e8a5f63ca0ded566de7edc3ac81f2b56003d5.

Low: tools: Set options.command when "attrd_updater -Y" is used.

---

daemons/execd/pacemaker-execd.c
daemons/execd/pacemaker-execd.h
daemons/execd/remoted_tls.c

[CC: I might have missed something important here, but it was in the "easy" pile of jobs on Phabricator]
When pacemaker-remoted wants to exit, it informs its connection host (if connected),
receives an ack, then waits for an all-clear message before exiting.
If the remote connection drops after sending the shutdown request and
receiving the ack, pacemaker-remoted will continue waiting for the
all-clear even though it can never arrive.
We now exit immediately with an exit status in that case.
fixes: T361

remote: Shutdown if tls goes down while waiting for shutdown all-clear

---

cts/cli/crm_mon-feature_set.xml
cts/cli/regression.crm_mon.exp
cts/cli/regression.feature_set.exp
cts/cli/regression.tools.exp
cts/cts-cli.in
daemons/controld/controld_join_client.c
include/crm/common/output.h
include/crm/common/output_internal.h
include/crm/crm.h
lib/common/output_html.c
lib/pengine/pe_output.c
xml/api/crm_mon-2.21.rng
xml/api/crm_simulate-2.21.rng
xml/api/nodes-2.21.rng

This pull request adds a logic to record CRM feature set as a transient attribute and then report it for all nodes by crm_mon.
Main motivation here is to warn the user if they are running a mixed-version cluster. The same functionality is already present in Hawk but it is incorrectly based on `crm_feature_set` XML attributes which are attached to `lrm_rsc_op` elements. Intention is to also rework the Hawk implementation and utilize the attributes added in this pull request.
Notes:
* The CRM feature set could be potentially recorded as a private attribute. However, this would require crm_mon to make a connection to attrd which I am not sure is desirable.
* Another idea is to record the information directly as an XML attribute in `node_state` elements in CIB. A problem with this approach is …

Report CRM feature set of nodes by crm_mon

---

ChangeLog
cts/lab/CIB.py
daemons/fenced/fenced_commands.c
include/crm/common/messages_internal.h
lib/common/Makefile.am
lib/common/messages.c
lib/common/output_html.c
lib/fencing/Makefile.am
lib/fencing/st_client.c
m4/version.m4
po/zh_CN.po
tools/crm_resource.c

The just-released 2.1.3 had two regressions, one that broke targeting fence devices by node attribute, and one that broke the CTS lab test for that feature, which is why it wasn't detected.
A handful of trivial other fixes from the main branch are also backported to form the basis of a 2.1.4-rc1 release.

Release 2.1.4-rc1

---

daemons/fenced/fenced_history.c
lib/fencing/st_client.c

be0a0b652c added and retrieved fencing results from fencing history entries'
XML. However stonith__xe_get_result() would log an error and set an error
status if no result is set, as is the case with older fencers. So, avoid that
function, and instead parse the results directly. Since a legacy rc was never
added by any version, we don't have to look for one.

Low: fencer: assume unknown status from older fencers' history replies

---

daemons/controld/controld_callbacks.c
daemons/controld/controld_fencing.c
daemons/controld/controld_fencing.h
daemons/controld/controld_join_dc.c
daemons/controld/controld_membership.c
daemons/controld/controld_messages.c
daemons/controld/controld_te_actions.c
daemons/controld/controld_te_callbacks.c
daemons/controld/controld_te_events.c
daemons/controld/controld_te_utils.c
daemons/controld/controld_transition.c
daemons/controld/controld_transition.h
include/pcmki/pcmki_sched_utils.h
include/pcmki/pcmki_scheduler.h
include/pcmki/pcmki_simulate.h
include/pcmki/pcmki_transition.h
lib/pacemaker/libpacemaker_private.h
lib/pacemaker/pcmk_graph_consumer.c
lib/pacemaker/pcmk_graph_logging.c
lib/pacemaker/pcmk_graph_producer.c
lib/pacemaker/pcmk_sched_promotable.c
lib/pacemaker/pcmk_sched_tickets.c
lib/pacemaker/pcmk_sched_utilization.c
lib/pacemaker/pcmk_simulate.c

This continues bringing libpacemaker up to current development guidelines. This one focuses mainly on the transition graph types and is mostly renames.

Best practices for transition graph types

---

daemons/controld/controld_attrd.c
daemons/controld/controld_te_events.c
daemons/controld/controld_utils.h
include/crm/common/ipc_attrd_internal.h
lib/common/ipc_attrd.c

I don't think the first two patches are strictly necessary, but it seems nice to keep a persistent connection and reduce the setup/teardown duplication.

Set fail-count and last-failure atomically

---

lib/fencing/st_output.c
lib/fencing/st_rhcs.c

If the fence agent returns a failure, the XML output does not include the stdout/stderr from the fence agent. The "valid" attribute is also set to the wrong boolean.
Regressions were introduced in https://github.com/ClusterLabs/pacemaker/commit/91a2b2e417d0d3b4ed310b5003879b8d0e2fc831 and https://github.com/ClusterLabs/pacemaker/commit/b441925e2da6b938db0674b98783d1dfb3d2a096.
Example:
```
<pacemaker-result api-version="2.20" request="stonith_admin --output-as=xml --validate --agent fence_apc">
<validate agent="fence_apc" valid="true">
<command code="-103"/>
</validate>
<status code="102" message="Not connected"/>
</pacemaker-result>
102
```
Before regressions (and after fix):
```
<pacemaker-result api-version="2.2" request="stonith_admin --output-as=xml --validate --agent fence_apc"> …
```

Fix regressions in stonith_admin --validate

---

daemons/based/based_messages.c
daemons/controld/controld_execd.c
daemons/controld/controld_messages.c
daemons/controld/controld_te_actions.c
daemons/controld/controld_te_callbacks.c
daemons/controld/controld_transition.c
daemons/controld/controld_transition.h
daemons/fenced/fenced_commands.c
daemons/pacemakerd/pcmkd_messages.c
daemons/schedulerd/schedulerd_messages.c
include/crm/cib/cib_types.h
lib/cib/cib_ops.c
lib/common/ipc_attrd.c
lib/common/ipc_controld.c
lib/common/ipc_pacemakerd.c
lib/common/ipc_schedulerd.c
lib/common/ipc_server.c
lib/pengine/unpack.c
lib/services/systemd.c

The replacement of crm_str() with pcmk__s() opened the door to a more in-depth look at how we validate various bits of input. This aims to improve all of that, especially log messages.

Improve various input validation

---

cts/cli/regression.tools.exp
cts/cts-cli.in
include/crm/common/output_internal.h
tools/crm_resource.c
tools/crm_resource.h
tools/crm_resource_print.c
tools/crm_resource_runtime.c
xml/api/crm_resource-2.22.rng

crm_resource --why gives a list of reasons why a resource may be stopped. The same check is also done at the end of crm_resource --cleanup and --refresh. These checks now include a check for whether the specified node is unhealthy (or all of the resource's allowed nodes are unhealthy, if no node is specified) and the node healthy strategy prevents the resource from running.

Check node health in crm_resource --why

---

daemons/controld/controld_callbacks.c

If it happens to be the old DC that has just shut down, the new DC may
bring up this warning anyway. Although the message is more from the new
DC's point of view purely regarding whether the event matches any
running cluster transition, but it's confusing to end users since the
shutdown was scheduled and should be "expected".
Fixes T454

Log: controller: log an info instead of a warning for a stonith/shutdown that is unknown to the new DC

---

cts/cts-scheduler.in
cts/scheduler/scores/bug-5059.scores
cts/scheduler/scores/remote-connection-shutdown.scores
cts/scheduler/summary/remote-connection-shutdown.summary
lib/pacemaker/libpacemaker_private.h
lib/pacemaker/pcmk_sched_clone.c
lib/pacemaker/pcmk_sched_colocation.c
lib/pacemaker/pcmk_sched_native.c
lib/pacemaker/pcmk_sched_promotable.c

This continues the unending project to bring libpacemaker up to current development guidelines, focusing on some of pcmk_sched_promotable.c. One bug that was discovered in the process is fixed.
This also enables a scheduler regression test that was added more than a year ago but not enabled.

Best practices for some code related to promotable clones

---

doc/sphinx/Pacemaker_Development/helpers.rst
lib/common/strings.c
lib/common/tests/strings/pcmk__strcmp_test.c

Affects documentation and some tests only (revealed on 32-bit
PowerPC).

strings.c: don't expect strcmp() return one-byte values

---

daemons/attrd/attrd_commands.c

Before, we were just calling attrd_client_update again on the whole
top-level node.  The intention here is that we would pass each child to
attrd_client_update in turn.  This has probably not turned up yet
because it requires a cluster with mixed versions of attrd, in addition
to only happening when messages between daemons are sent.  Normal
command line tool usage will not run into this.
This was introduced by 2e9b5ef562.

Low: daemons: Fix a bug processing child XML messages in attrd.

---

tools/attrd_updater.c

This option is deprecated and unused, but should still be recognized.
Regression in 2.1.3 introduced by ef0e8a5f63.
Fixes T526
See rhbz#2110452

High: tools: Add the -q option back to attrd_updater.

---

doc/sphinx/Clusters_from_Scratch/active-active.rst
doc/sphinx/Clusters_from_Scratch/ap-configuration.rst
doc/sphinx/Clusters_from_Scratch/shared-storage.rst

* Remove `syncer` section, which was made obsolete in DRBD 8.4. Move `verify-alg` to `net` section.
* Ref: https://linbit.com/drbd-user-guide/drbd-guide-9_0-en/#s-recent-changes-config-syncer.
* Use new-style configuration instead of legacy 8.4-style. These changes aren't necessary but seem like best practices (although the user guide itself becomes inconsistent later, reverting to what it calls the old style at times).
* Use `device minor 1` instead of device `/dev/drbd1`.
* Move `protocol C` to the `net` section where it belongs.
* Assign explicit an `node-id` to each node.
* Use a `connection` section instead of specifying addresses in `on
<host>` sections.
* Quote strings.
* Ref: https://linbit.com/drbd-user-guide/drbd-guide-9_0-en/#s-drbdconf-example, especially Listings 2 and 4 and …

Doc: Clusters from Scratch: Improve DRBD walkthrough

---

lib/common/ipc_client.c

"crm_attribute -t status -u ..." connects to the attribute daemon using
the sync method.  The call chain for this is send_attrd_update ->
pcmk__attrd_api_update -> connect_and_send_attrd_request ->
pcmk_connect_ipc -> connect_without_main_loop -> crm_ipc_connect.  In
that function, a libqb connection is allocated with qb_ipcc_connect.
In order to avoid leaking memory, that connection needs to be freed with
qb_ipcc_disconnect, which happens in crm_ipc_close.
However, nothing in pcmk__attrd_api_update calls that.  That function
calls destroy_api, which in turn calls pcmk_disconnect_ipc, which seems
like the logical place to free the libqb connection.  Unfortunately, all
it does in the sync case is free the crm_ipc_t that holds the libqb
connection.
So, add a call to crm_ipc_close there to …

Low: libcrmcommon: Fix an IPC-related memory leak.

---

daemons/execd/execd_commands.c

I initially thought there was a possible use-after-free in this code, but after tracing it carefully, the only potential issue was calling cmd_finalize() twice in very limited circumstances.

Don't finalize failed monitor initiation twice

---

include/crm/pengine/internal.h
include/pcmki/pcmki_sched_allocate.h
include/pcmki/pcmki_sched_utils.h
lib/pacemaker/libpacemaker_private.h
lib/pacemaker/pcmk_graph_producer.c
lib/pacemaker/pcmk_sched_actions.c
lib/pacemaker/pcmk_sched_allocate.c
lib/pacemaker/pcmk_sched_bundle.c
lib/pacemaker/pcmk_sched_clone.c
lib/pacemaker/pcmk_sched_colocation.c
lib/pacemaker/pcmk_sched_constraints.c
lib/pacemaker/pcmk_sched_fencing.c
lib/pacemaker/pcmk_sched_group.c
lib/pacemaker/pcmk_sched_native.c
lib/pacemaker/pcmk_sched_nodes.c
lib/pacemaker/pcmk_sched_ordering.c
lib/pacemaker/pcmk_sched_probes.c
lib/pacemaker/pcmk_sched_promotable.c
lib/pacemaker/pcmk_sched_resource.c

This focuses on exposed functions (some static functions still could be changed)

Drop redundant pe_working_set_t arguments from libpacemaker functions

---

cts/cts-scheduler.in

Remove .dot.pe files as part of cleanup after a regression test.
Currently we clean up the .out, .scores.pe, and .summary.pe files.
Closes [T495](https://projects.clusterlabs.org/T495).

Test: cts-regression: Remove .dot.pe files

---

cts/cts-exec.in
cts/cts-fencing.in
rpm/pacemaker.spec.in

If `pacemaker-fenced` is already running when cts-fencing starts, `cts-fencing` will kill the existing fencer. Instead of allowing this to happen, we should bail out and tell the user to stop the cluster.
Likewise for `pacemaker-execd` (or `pacemaker-remoted`, if the `-R` option is used) and `cts-exec`.
Closes: [T496](https://projects.clusterlabs.org/T496)
Closes: [T497](https://projects.clusterlabs.org/T497)

Test: cts-fencing, cts-exec: Bail out if daemon is running

---

daemons/attrd/attrd_cib.c
daemons/based/based_callbacks.c
daemons/based/based_common.c
daemons/based/based_messages.c
daemons/based/based_notify.c
daemons/controld/controld_based.c
daemons/controld/controld_utils.h
include/crm/cib/internal.h
lib/cib/cib_attrs.c
lib/cib/cib_client.c
lib/cib/cib_file.c
lib/cib/cib_native.c
lib/cib/cib_ops.c
tools/cibadmin.c

... for consistency with current guidelines, and to move away from deprecated terminology. Also, compare them case-sensitively.

Rename internal libcib symbols for IPC request types

---

configure.ac
include/crm/common/output_internal.h
lib/common/mock.c
lib/common/mock_private.h
lib/common/output.c
lib/common/output_html.c
lib/common/output_log.c
lib/common/output_text.c
lib/common/output_xml.c
lib/common/tests/Makefile.am
lib/common/tests/output/Makefile.am
lib/common/tests/output/pcmk__call_message_test.c
lib/common/tests/output/pcmk__output_and_clear_error_test.c
lib/common/tests/output/pcmk__output_free_test.c
lib/common/tests/output/pcmk__output_new_test.c
lib/common/tests/output/pcmk__register_format_test.c
lib/common/tests/output/pcmk__register_formats_test.c
lib/common/tests/output/pcmk__register_message_test.c
lib/common/tests/output/pcmk__register_messages_test.c
lib/common/tests/output/pcmk__unregister_formats_test.c
mk/tap.mk
tools/crm_mon_curses.c

NOTE - this PR is so huge because it's based on top of #2798 and #2793.  Once those are merged, I'll rebase this one and it'll shrink a lot.  For now, just start looking at [a507738](https://github.com/ClusterLabs/pacemaker/pull/2800/commits/a507738e2fc73148f9fced5e7d0f22ef9a2c180a) ("Assert in more output-related functions").
This tests everything except the last three functions that are wrappers around specific output formatters.  I want to test the output_*.c files before adding tests for those.
I'm also seeing a lot of duplication in tests/*/Makefile.am - I think AM_CPPFLAGS, LDADD, AM_CFLAGS, and AM_LDFLAGS are identical across files now.  So maybe that's a place to do some code reduction in the next round.

Unit testing for much of lib/common/output.c

---

include/crm/common/unittest_internal.h
lib/common/crmcommon_private.h
lib/common/mock.c
lib/common/tests/io/pcmk__full_path_test.c
lib/common/tests/io/pcmk__get_tmpdir_test.c
lib/common/tests/output/pcmk__output_new_test.c
lib/common/tests/procfs/pcmk__procfs_has_pids_false_test.c
lib/common/tests/procfs/pcmk__procfs_has_pids_true_test.c
lib/common/tests/procfs/pcmk__procfs_pid2path_test.c
lib/common/tests/strings/pcmk__compress_test.c
lib/common/tests/strings/pcmk__str_update_test.c
lib/common/tests/utils/crm_user_lookup_test.c
lib/common/tests/utils/pcmk_daemon_user_test.c
lib/common/tests/utils/pcmk_hostname_test.c
lib/common/utils.c
lib/pengine/tests/status/pe_new_working_set_test.c

Check that mocked functions receive the expected arguments.
Any time we're unsure what the argument will be (for example, when it's an object that's created by the called function and we pass its address to the mocked function), we can use `expect_any(<function>, <parameter_name>)`.
We also clarify that `pcmk__assert_asserts()` accepts a statement in general and isn't limited to an expression. We need that in order to use `expect_*()` macros alongside `pcmk__assert_asserts()`.
More info: https://api.cmocka.org/group__cmocka__param.html

Test: Check for expected arguments in mocked functions

---

daemons/fenced/fenced_commands.c

Hi All,
This fix improves escalation fencing failures in multi-node configurations when there is no topology.
Fencing from DC resource failure is performed by RELAY regardless of the presence or absence of topology.
In addition to this fix, there is code that is no longer needed due to this change, but we will first publicize this fix.
Best Regards,

Mid: fenced: DC node fencing is unconditionally relayed.

---

cts/lab/CTS.py
cts/lab/CTStests.py
cts/lab/environment.py
cts/lab/patterns.py
cts/lab/remote.py

Per T499, phd was a tool for spinning up test clusters, but it hasn't been maintained in years and isn't worth bringing up to date. All the docker stuff in the cts lab was related to phd, so remove it.
Drop the `RemotePrimitives` class since it doesn't do much or really simplify anything. It acts like a two-member struct that gets created once.
Closes T499.

Test: cts-lab: Remove docker, phd, and the RemotePrimitives class

---

lib/pengine/Makefile.am

These got missed when I did libcrmcommon recently.

Update pengine test libs to build as shared

---

include/crm/common/Makefile.am
include/crm/common/acl_internal.h
include/crm/common/internal.h
include/crm/common/io_internal.h

Separate internal IO-related functions into their own header file, for better organization and future reuse.
Remove unused includes from internal.h.
Closes T536

Refactor: libcrmcommon: Add io_internal.h

---

daemons/schedulerd/schedulerd_messages.c
include/crm_internal.h

Define new string constants and use them instead of string literals
Closes T541

Refactor: pacemaker-schedulerd: Constants for graph/config errors/warnings

---

configure.ac
include/crm/pengine/internal.h
lib/common/strings.c
lib/common/tests/strings/pcmk__numeric_strcasecmp_test.c
lib/pacemaker/pcmk_sched_native.c
lib/pengine/Makefile.am
lib/pengine/clone.c
lib/pengine/pe_notif.c
lib/pengine/pe_status_private.h
lib/pengine/tests/Makefile.am
lib/pengine/tests/utils/Makefile.am
lib/pengine/tests/utils/pe__cmp_node_name_test.c
lib/pengine/tests/utils/pe__cmp_rsc_priority_test.c
lib/pengine/unpack.c
lib/pengine/utils.c

* Prepend `pe__` to `sort_node_uname()` and `sort_rsc_priority()` and add doc comment blocks and unit tests.
* Make `pe__sort_rsc_priority()` library-private.
* Update `pe__sort_node_uname()` to handle `NULL` values.
* Add a `NULL` check to `pcmk__numeric_strcasecmp()`.
Closes T534

Refactor: libpe_status: Bring two functions up to current guidelines

---

include/crm/common/results.h
include/crm/pengine/internal.h
lib/common/results.c
lib/pacemaker/pcmk_sched_colocation.c
lib/pacemaker/pcmk_sched_location.c
lib/pacemaker/pcmk_sched_ordering.c
lib/pacemaker/pcmk_sched_tickets.c
lib/pengine/bundle.c
lib/pengine/clone.c
lib/pengine/complex.c
lib/pengine/group.c
lib/pengine/pe_status_private.h
lib/pengine/unpack.c

* Rename to `pe__unpack_resource()` and make library-private
* Use `true`/`false` instead of `TRUE`/`FALSE` with its `bool` variables
* Return a standard Pacemaker return code (currently only `pcmk_rc_ok` or `pcmk_rc_error`, since no others seemed to fit)
* Add a Doxygen comment block
Closes T540

Refactor: libpe_status: Bring common_unpack() up to current guidelines

---

include/crm/common/iso8601.h
include/crm/common/iso8601_internal.h
lib/common/iso8601.c

Little bit of cleanup. No point getting deep into the weeds in iso8601.c, noting https://projects.clusterlabs.org/T432.
Note that the changes from `uint` to `uint32_t` in the very first commit are to be consistent with what we already advertise in the public API header.

Use const arguments in iso8601.c when appropriate

---

lib/cib/cib_utils.c

`cib_object` is not `NULL`-checked until the very end. It should be checked at the beginning to ensure we have a destination to store the CIB. Also as a result, `*cib_object` is never `NULL`-checked. We need to check it at the end to determine our return code.

Fix: libcib: cib__signon_query(): NULL-check correct pointer

---

doc/sphinx/Pacemaker_Development/c.rst
include/crm/common/internal.h
include/crm/common/ipc.h
include/crm/common/ipc_internal.h
include/crm/common/logging.h
include/crm/common/nvpair.h
include/crm/common/xml.h
lib/common/crmcommon_private.h
lib/common/ipc_server.c
lib/common/messages.c
lib/common/nvpair.c
lib/common/patchset.c
lib/common/xml.c
lib/common/xpath.c

Now that we've decided on a convention for doxygen documentation of pointer arguments, update some functions in libcrmcommon. Change doxygen comments from in to in,out where appropriate, and change pointer arguments to const where appropriate. This is not comprehensive but takes care of functions that will be needed to update daemons similarly.

Clarify pointer argument usage in libcrmcommon

---

lib/common/ipc_attrd.c

The commit message for 494cbdd3be616a9dbbdd3151c4f49e169b2be1d6 is
relevant here, too.  This basically extends that commit to wait for ACKs
for the refresh command.  Without this, it doesn't appear that anything
ever happens on the server side.

Med: libcrmcommon: Wait for ACKs from the attrd refresh command.

---

include/crm/pengine/internal.h
lib/pacemaker/libpacemaker_private.h
lib/pacemaker/pcmk_sched_actions.c
lib/pacemaker/pcmk_sched_primitive.c
lib/pengine/pe_actions.c

This continues bringing libpacemaker up to current guidelines, focusing on RecurringOp() and the static functions it calls.

Best practices for RecurringOp()

---

cts/cli/regression.agents.exp
cts/cts-cli.in
include/crm/common/output_internal.h
xml/Makefile.am
xml/api/command-output-2.23.rng
xml/api/crm_resource-2.23.rng
xml/api/stonith_admin-2.23.rng
xml/api/subprocess-output-2.23.rng

In case of an error, the output of `crm_resource --validate` fails to validate (if validate-all does not output XML). This is because if a
`<choice>` contains two elements with the same name in a RelaxNG schema, only the first occurrence is honored and the rest are ignored. (This does not seem to be documented clearly; it's a conclusion based on experimentation.)
A solution is to create just one `<element>` that contains a `<choice>` (instead of a `<choice>` that contains two `<element>`s).
Closes RHBZ#2123727

Fix crm_resource --validate validation

---

configure.ac
daemons/based/based_callbacks.c
lib/cluster/corosync.c
lib/common/remote.c

There are custom constants called U64T, X32T, etc. in configure.ac. They're intended to do the same job as the fixed-width format specifiers (PRIu64, SCNu64, etc.) that are specified in the C standard. The basic idea is that the C99 standard doesn't guarantee the existence of exact-width integer types.
However, Pacemaker already relies on fixed-width types and has for some time. There's no longer any reason to keep these.

Refactor: various: Remove U64T(S), U32T, and X32T print/scanf specs

---

cts/cli/regression.upgrade.exp
cts/cli/regression.validity.exp
doc/sphinx/Pacemaker_Explained/rules.rst
include/crm/msg_xml.h
lib/pengine/rules.c
xml/Makefile.am
xml/README.md
xml/alerts-3.9.rng
xml/constraints-3.9.rng
xml/constraints-next.rng
xml/nodes-3.9.rng
xml/nvset-3.9.rng
xml/options-3.9.rng
xml/resources-3.9.rng
xml/rule-3.9.rng

`rules.c` allows several elements in `duration` and `date_spec` that the rule schema currently does not allow. The main point of this PR is to update the schema to allow everything that the rules parser allows. Summary of changes:
* Refactor the code in very minor ways (mostly name substitutions)
* Automatically rebuild `versions.rng` on a schema bump... or technically, on any schema change, as we do with the `pacemaker-x.y.rng` schemas.
* Create a separate definition for each rule expression type for readability and ease of maintenance.
* Split `duration` and `date_spec` into separate definitions, mark as deprecated the options that are invalid but must be kept for compatibility, and add valid options that are missing.
* Make the choice between `score` and `score-attribute` optional... …

Update rule schema and documentation to match actual behavior

---

daemons/based/based_callbacks.c
daemons/fenced/fenced_commands.c
daemons/fenced/fenced_history.c
daemons/fenced/fenced_remote.c
daemons/fenced/pacemaker-fenced.c
daemons/fenced/pacemaker-fenced.h
daemons/pacemakerd/pcmkd_subdaemons.c

Mark pointer arguments as const where appropriate, and ensure doxygen blocks use [in] or [in,out] as appropriate, in functions for pacemakerd, pacemaker-based, and pacemaker-fenced.
This is not comprehensive but focuses on functions that have doxygen blocks and some functions called by them.

Clarify pointer arguments in some daemons

---

daemons/based/based_callbacks.c
daemons/based/based_notify.c
daemons/based/pacemaker-based.h
daemons/controld/controld_based.c
daemons/controld/controld_te_callbacks.c
include/crm/cib/internal.h

This fixes a regression introduced by 41d0a1af and set up by 45e5e82a. A reordering of the resources in the configuration section of the CIB no longer causes a transition abort.
However, the order of resources in the configuration affects their order of placement, and thus a configuration reordering can require resources to change nodes. In that case, the moves will not be initiated until the next natural transition (up to the value of cluster-recheck-interval).
Closes T549

Fix: daemons: Resource reordering doesn't cause transition abort

---

daemons/fenced/fenced_commands.c
daemons/fenced/fenced_remote.c
include/crm/fencing/internal.h

Hi Ken,
Hi All,
This fix is a revision of the following PR.
- https://github.com/ClusterLabs/pacemaker/pull/2805
* Added device_support_flag to Query response.
* Added constants for on action support and no support
* Added check for on action in find_peer_device() if topology exists.
* Added a check if on action in count_peer_devices() if there is no topology.
* Query search does not check the on action, but checks the on action when searching when there is no topology.
* This is because when there is a topology, it is checked when all the devices in the topology are available as a trigger for fencing.
Best Regards,

Mid: fenced: Skipping devices that don't support the on action.(Fix:CLBZ#5495)

---

doc/sphinx/Pacemaker_Explained/advanced-resources.rst

Doc: Pacemaker Explained: Remove group ordered meta attribute

---

cts/cli/regression.tools.exp
cts/cts-cli.in
include/crm/common/output_internal.h
lib/pengine/native.c
xml/api/crm_mon-2.24.rng
xml/api/crm_resource-2.24.rng
xml/api/crm_simulate-2.24.rng
xml/api/nodes-2.24.rng
xml/api/resources-2.24.rng

And fix a couple more `cts-cli` issues (one of which has been there for a while).
Open to changing attribute name "locked_to"
Closes T433

Add shutdown locks to crm_mon, crm_resource, and crm_simulate XML outputs

---

lib/pengine/pe_output.c
tools/crm_resource_runtime.c

Fix "time_t val = va_arg(args, int);" which bombs out on 32bit
When using -D_TIME_BITS=64 and without this patch, "make check" fails. Particulary, "cts/cts-cli -t crm_mon" will fail.

Fix: libpe_status,tools: work with -D_TIME_BITS=64

---

cts/lab/CTStests.py
cts/lab/patterns.py
daemons/controld/controld_execd.c
daemons/controld/controld_fsa.h
daemons/controld/controld_join_client.c
daemons/controld/controld_join_dc.c
daemons/controld/controld_messages.c
daemons/controld/controld_metadata.c
daemons/controld/controld_metadata.h
daemons/fenced/fenced_commands.c
include/crm/crm.h
include/crm/crm_compat.h
include/crm/fencing/internal.h
include/crm/lrmd_internal.h
include/crm/stonith-ng.h
lib/common/results.c
lib/fencing/st_actions.c
lib/fencing/st_client.c
lib/fencing/st_rhcs.c
lib/lrmd/lrmd_client.c
lib/pacemaker/pcmk_graph_producer.c
lib/pengine/common.c

A longstanding problem has been that the controller executes resource agent metadata actions synchronously. Among the problems with that, it blocks the controller, and if the agent's metadata action attempts to contact the controller, everything hangs until the timeout.
This switches it to asynchronous execution. This is not a comprehensive solution, because there are code paths to getting metadata that could still end up in the synchronous block, but this addresses the most important use case, scheduled resource actions including probe, start, etc. In practice this should mean that metadata is cached before any of the other paths need it.

Execute metadata asynchronously in controller

---

cts/Makefile.am

The recently added crm_mon-T180.xml file was not added to dist_cli_DATA.

Test: cts-cli: Fix cts-cli crm_mon failures in RPM-installed envs

---

include/crm/cib/cib_types.h
include/crm/cib/internal.h
include/crm/common/cmdline_internal.h
include/crm/common/ipc.h
include/crm/common/ipc_attrd_internal.h
include/crm/common/ipc_schedulerd.h
include/crm/common/lists_internal.h
include/crm/common/logging.h
include/crm/common/mainloop.h
include/crm/common/messages_internal.h
include/crm/common/nvpair.h
include/crm/common/output_internal.h
include/crm/common/remote_internal.h
include/crm/common/strings_internal.h
include/crm/common/xml.h
include/crm/common/xml_compat.h
include/crm/common/xml_internal.h
include/crm/fencing/internal.h
include/crm/stonith-ng.h
lib/cib/cib_ops.c
lib/common/cmdline.c
lib/common/lists.c
lib/common/logging.c
lib/common/output.c
lib/common/xml.c
lib/fencing/st_client.c

This is not comprehensive but focuses on libcrmcommon, libcib, and libstonithd APIs with doxygen blocks under include/ and some functions called by them.

Clarify pointer arguments in library APIs

---

daemons/controld/controld_control.c
daemons/fenced/pacemaker-fenced.c
include/crm/common/options_internal.h
lib/cib/cib_utils.c
lib/common/cmdline.c
lib/common/options.c
lib/fencing/st_output.c
lib/pengine/common.c
lib/pengine/native.c

And use shortcut `return g_string_free(str, FALSE)` instead of assigning to a temporary variable and returning that.
In practice `g_free()` (vs. `free()`) shouldn't be required if GLib >= 2.46 is used, but it's a best practice and we only require GLib >= 2.42.

Refactor: various: Use g_free() with gchar *

---

daemons/controld/controld_execd.c
include/crm/common/strings_internal.h
include/crm/pengine/internal.h
lib/cib/cib_attrs.c
lib/common/strings.c
lib/common/tests/strings/pcmk__add_word_test.c
lib/fencing/st_client.c
lib/pacemaker/pcmk_graph_logging.c
lib/pacemaker/pcmk_status.c
lib/pengine/bundle.c
lib/pengine/clone.c
lib/pengine/group.c
lib/pengine/native.c
lib/pengine/pe_actions.c
lib/pengine/pe_notif.c
lib/pengine/pe_output.c
lib/pengine/pe_status_private.h
lib/pengine/unpack.c
lib/pengine/variant.h

Skip the output functions in `bundle.c` for now: `pe__bundle_replica_output_html()`, `pe__bundle_replica_output_text()`, and `print_bundle_replica()`. Since we ultimately pass to `fprintf()`, it might make sense to use `LINE_MAX` as a size limit... not entirely sure. We can come back to those later if we want.
Some performance test results after each successive change, relative to the commits in https://github.com/ClusterLabs/pacemaker/pull/2857:
```
Averages: +0.01s  +0.50%
Averages: +0.08s  +0.52%
Averages: +0.04s  -0.16%
Averages: +0.02s  +0.58%
Averages: +0.15s  +0.63%
<empty>
Averages: +0.02s  +0.65%
Averages: +0.21s  +0.37%
Averages: -0.13s  -4.69%
Averages: +0.01s  +0.58%
Averages: +0.08s  +0.47%
Averages: -0.14s  -5.34%
```

libcib, libpe_status: Replace snprintf() with GString

---

cts/Makefile.am
cts/cli/regression.daemons.exp
cts/cts-cli.in
daemons/controld/controld_control.c
include/crm/common/strings_internal.h
lib/common/acl.c
lib/common/cmdline.c
lib/common/options.c
lib/common/patchset.c
lib/common/strings.c
lib/common/tests/strings/Makefile.am
lib/common/tests/strings/pcmk__g_strcat_test.c
lib/common/xml.c
lib/common/xpath.c

This PR depends on #2879 and includes some overlapping commits. It introduces a new function `pcmk__g_strcat()` that's intended to replace `g_string_append_printf()` when the only interpolated objects are strings (i.e., when there are no integers (`%d`), pointers (`%p`), etc., to be appended to the string). This yields a performance improvement, with `crm_simulate` times decreasing or staying the same for almost every test input in `cts/scheduler/xml`.
Results below are compared to the "Use GString in pcmk__add_separated_word() commit", since it's assumed that that commit will be merged first via #2879.
```
Averages: -0.11s  -2.62%
Averages: -0.40s  -3.48%
Averages: -0.47s  -4.48%
```

Replace g_string_append_printf() with new pcmk__g_strcat() function

---

cts/cli/regression.tools.exp
include/crm/pengine/internal.h
include/pcmki/pcmki_sched_allocate.h
include/pcmki/pcmki_sched_utils.h
lib/pacemaker/libpacemaker_private.h
lib/pacemaker/pcmk_sched_bundle.c
lib/pacemaker/pcmk_sched_clone.c
lib/pacemaker/pcmk_sched_group.c
lib/pacemaker/pcmk_sched_location.c
lib/pacemaker/pcmk_sched_primitive.c
lib/pacemaker/pcmk_sched_resource.c
lib/pengine/pe_actions.c

This continues the project to bring libpacemaker up to current guidelines, focusing on some of the primitive methods.

Best practices for primitive-related functions in libpacemaker

---

daemons/controld/controld_execd.c
daemons/controld/controld_membership.c
daemons/controld/controld_te_callbacks.c
daemons/execd/execd_commands.c
daemons/fenced/fenced_commands.c
daemons/fenced/pacemaker-fenced.c
daemons/fenced/pacemaker-fenced.h
lib/cib/cib_attrs.c
lib/fencing/st_output.c
lib/pacemaker/pcmk_injections.c
lib/pacemaker/pcmk_output.c
lib/pacemaker/pcmk_simulate.c
lib/pengine/bundle.c
lib/pengine/native.c
lib/pengine/pe_actions.c
lib/pengine/pe_output.c
lib/pengine/unpack.c
lib/services/services_lsb.c
tools/crm_resource_ban.c
tools/crm_resource_runtime.c
tools/crm_ticket.c

This hits most of the remaining places where it's reasonable to move from `snprintf()` to GStrings and the like.
The "Reduce duplication in container resource create" commit is definitely the hardest to review even though it doesn't do that much, just because of the way the diff is generated. The idea is that the three existing `create_X_resource()` functions for docker, podman, and rkt are almost identical. Likewise, the new function is almost identical to all of these, with `switch` and `if` statements where needed.

Yet Another GString PR

---

cts/cts-cli.in

Currently it runs only from a source directory since `CRM_DAEMON_DIR` isn't typically in the `PATH`.
Follow-up to fc22d59b.

Test: cts-cli: Allow daemon tests to run from installed packages

---

include/crm/pengine/internal.h
include/pcmki/pcmki_sched_allocate.h
lib/pacemaker/libpacemaker_private.h
lib/pacemaker/pcmk_graph_producer.c
lib/pacemaker/pcmk_sched_actions.c
lib/pacemaker/pcmk_sched_migration.c
lib/pacemaker/pcmk_sched_primitive.c
lib/pacemaker/pcmk_sched_resource.c

This continues the project to bring libpacemaker up to current development guidelines, focusing on the remaining primitive methods.

Best practices for primitive-related methods in libpacemaker

---

include/crm/pengine/internal.h
include/pcmki/pcmki_sched_allocate.h
include/pcmki/pcmki_sched_utils.h
lib/pacemaker/libpacemaker_private.h
lib/pacemaker/pcmk_sched_bundle.c
lib/pacemaker/pcmk_sched_clone.c
lib/pacemaker/pcmk_sched_colocation.c
lib/pacemaker/pcmk_sched_fencing.c
lib/pacemaker/pcmk_sched_group.c
lib/pacemaker/pcmk_sched_primitive.c
lib/pacemaker/pcmk_sched_promotable.c
lib/pacemaker/pcmk_sched_utilization.c
lib/pengine/clone.c
lib/pengine/common.c

This continues the project to bring libpacemaker up to current guidelines, finishing up pcmk_sched_primitive.c.

Best practices for remaining primitive-related functions in libpacemaker

---

include/crm/common/ipc_internal.h
include/crm/common/output_internal.h
include/pacemaker.h
include/pcmki/pcmki_cluster_queries.h
include/pcmki/pcmki_status.h
lib/common/ipc_pacemakerd.c
lib/pacemaker/pcmk_cluster_queries.c
lib/pacemaker/pcmk_output.c
lib/pacemaker/pcmk_status.c
lib/pengine/utils.c
tools/crm_mon.c
tools/crmadmin.c
xml/api/crm_mon-2.25.rng
xml/api/crmadmin-2.25.rng
xml/api/pacemakerd-health-2.25.rng

`crm_mon --one-shot` checks the pacemakerd state before trying to get a CIB connection. If `pacemakerd` is shutting down, it returns `ENOTCONN`. This can cause a resource agent that calls `crm_mon` (for example, `ocf:heartbeat:pgsql`) to fail to stop during shutdown.
This may be a regression introduced by commit 3f342e3. `crm_mon.c:pacemakerd_status()` returns `pcmk_rc_ok` if `pacemakerd` is shutting down, since 49ebe4c and 46d6edd (fixes for CLBZ#5471). 3f342e3 refactored `crm_mon --one-shot` to use library functions, and `pcmk_status.c:pacemakerd_status()` returns `ENOTCONN` if `pacemakerd` is shutting down. As a result, we don't try to connect to the CIB.
Fixes CLBZ#5501

Fix: libpacemaker: crm_mon --one-shot can fail during pacemaker shutdown

---

include/crm/common/ipc_internal.h
include/crm/common/ipc_pacemakerd.h
include/crm/msg_xml.h
include/pacemaker.h
include/pcmki/pcmki_cluster_queries.h
include/pcmki/pcmki_status.h
lib/common/ipc_client.c
lib/common/ipc_controld.c
lib/common/ipc_pacemakerd.c
lib/fencing/st_client.c
lib/pacemaker/pcmk_cluster_queries.c
lib/pacemaker/pcmk_status.c
tools/crm_mon.c
tools/crmadmin.c

My stack of commits related to the `crm_mon` disconnect stuff ([T15](https://projects.clusterlabs.org/T15)) has been growing. I realized that a bunch of them have merit on their own independent of the `crm_mon` disconnect work. I'm opening this PR now to get those reviewed and make eventual review of the rest easier.
I'm not super tied to the "Functionize reply validation" commit. It's a little bit clunky because of the need for different type casts. But it does reduce duplication, and that will be even more pronounced if we ever add more daemons to `pcmk_cluster_queries.c`.

Refactors and minor improvements related to cluster queries

---

daemons/execd/cts-exec-helper.c
include/crm/cib/internal.h
include/crm/common/iso8601_internal.h
include/crm/common/output_internal.h
include/pcmki/pcmki_cluster_queries.h
lib/cib/cib_utils.c
lib/common/iso8601.c
lib/common/nvpair.c
lib/common/output_html.c
lib/common/output_log.c
lib/common/output_none.c
lib/common/output_text.c
lib/common/output_xml.c
lib/common/xml.c
lib/fencing/st_output.c
lib/pacemaker/pcmk_cluster_queries.c
lib/pacemaker/pcmk_fence.c
lib/pacemaker/pcmk_output.c
lib/pacemaker/pcmk_rule.c
lib/pacemaker/pcmk_simulate.c
lib/pacemaker/pcmk_status.c
lib/pengine/pe_output.c
lib/pengine/unpack.c
tools/crm_mon.c
tools/crm_mon_curses.c
tools/crm_simulate.c
tools/crm_verify.c
tools/crmadmin.c

And some other supporting work to facilitate that, including making `cib__signon_query()` more versatile at the expense of a little bit of complexity.
The intent is to soon use the new transient output method in `crm_mon` as well.

Clean up pcmk__status() and display pcmkd state only if we can't get the CIB

---

daemons/attrd/attrd_corosync.c
daemons/attrd/attrd_ipc.c
daemons/attrd/attrd_messages.c
daemons/attrd/attrd_sync.c
daemons/attrd/attrd_utils.c
daemons/attrd/pacemaker-attrd.h
include/crm_internal.h
tools/attrd_updater.c

I have some outstanding questions on this, however:

Add support for cluster-wide sync points

---

xml/best-match.sh

The list_candidates() function is too lax and matches `pacemakerd-health-2.25.rng` when it looks for candidates for `"pacemakerd"`.
This caused an `api-result.rng` compile failure when updating to API version 2.26. Somehow it doesn't seem to cause issues on 2.25.
We shouldn't have to worry about any complicated version strings that contain hyphens or start with a non-digit.

Fix: schemas: False positives in best-match.sh

---

tools/crm_resource.c

Somehow commas were used where semicolons are supposed to be.

Fix: tools: fix syntax on resetting options in crm_resource

---

include/crm/common/output_internal.h
include/pcmki/pcmki_status.h
lib/cib/cib_utils.c
lib/pacemaker/pcmk_output.c
lib/pacemaker/pcmk_simulate.c
lib/pacemaker/pcmk_status.c
lib/pengine/pe_output.c
tools/crm_mon.c
tools/crm_mon.h
tools/crm_mon_curses.c
xml/api/crm_mon-2.26.rng

With `crm_mon --daemonize`, the output will continue to show the last known status after the cluster is stopped on the local node. It should go back to something like `"Cluster is not available"`.
Likewise, messages like `"Reconnecting..."` should not go to the daemonized output. The output file (or external handler) should receive only the cluster status. So we print those messages only if `output_format` is `mon_output_console` (or if we're in one-shot mode, where applicable). Normally those messages don't get printed to the daemonized output anyway because we don't flush the buffer, but theoretically they could get printed if the buffer fills up.
It's questionable whether we want to print `"Cluster is not available"` when we're in interactive mode or only in daemonized mode. For now, …

Fix: tools: crm_mon --daemonize should update when disconnected

---

lib/common/tests/procfs/pcmk__procfs_pid2path_test.c

The expect_value/check_expected_ptr combo from cmocka fails on i686, but only if the pointer in question is a statically declared buffer.  In this case, somewhere in the giant pile of casting that occurs in cmocka, one of the variable or expected value ends up a 32-bit quantity while the other ends up a 64-bit quantity.  The comparison then fails.
Changing these variables into dynamically allocated buffers makes everything work out fine.  This is necessary to get builds working again.

Tests: Fix running pcmk__procfs_pid2path_test on i686.

---

daemons/based/pacemaker-based.c
daemons/controld/pacemaker-controld.c
daemons/fenced/pacemaker-fenced.c
lib/cib/cib_native.c
lib/common/ipc_client.c
lib/common/mainloop.c
lib/fencing/st_client.c
lib/lrmd/proxy_common.c

It turns out there aren't that many places that call crm_ipc_new and weren't handling NULL.  A lot of the callers are already sort of indirectly doing so with constructions like this:
```
native->ipc = crm_ipc_new("stonith-ng", 0);
if (native->ipc && crm_ipc_connect(native->ipc)) {
...
} else if (native->ipc) {
...
}
} else {
...
}
if (native->ipc == NULL) {
rc = -ENOTCONN;
```
It's not especially obvious at first glance, but it looks like it works.  I could modify all these places to be more clear, though.

Handle IPC creation errors

---

include/crm/common/internal.h
include/crm/common/output_internal.h
include/pacemaker.h
include/pcmki/pcmki_cluster_queries.h
lib/common/logging.c
lib/common/results.c
lib/pacemaker/pcmk_cluster_queries.c
lib/pacemaker/pcmk_output.c
lib/pacemaker/pcmk_simulate.c
lib/pacemaker/pcmk_status.c
lib/pengine/pe_output.c
tools/crm_attribute.c
tools/crm_node.c
xml/api/crm_mon-2.27.rng

`crm_mon` shows which node the update came from, when run against a native (live) CIB. The `last_update` origin is not reliably meaningful[1] for CIB files or remote CIB connections and is thus not shown.
For simplicity, the `last_update` origin is also not shown if for some reason we fail to get the node name from the controller when using a native CIB. If desired, we can show "on unknown node" or similar in the output in that situation.
Closes T174
[1] By "not reliably meaningful," I mean that there are a few possibilities. For example:
* The requester node (the node running `crm_mon`) is a member of the source cluster (the cluster that we're getting the CIB from via a file or CIB remote). In this case, the node name is meaningful, but we certainly can't rely on this and can't check it …

Feature: tools: crm_mon now shows last_update origin

---

daemons/attrd/attrd_corosync.c

It's already set on the parent.  It doesn't need to be set there again. This was a thinko introduced with b2937595b2e83a836edb2953104e896be0ac9f5a.

Low: daemons: Set an attribute on the child of a multi-attr message.

---

cts/cli/regression.tools.exp
cts/cts-cli.in

So that it covers the case of correctly displaying pending operations also in text output addressed by fe9150bc4.

Test: cts-cli: add test for text output of crm_resource --list-operations/-O

---

include/crm/common/iso8601.h
include/crm/common/iso8601_internal.h
lib/common/iso8601.c
lib/common/strings.c
lib/fencing/st_output.c
lib/pengine/pe_output.c

When detailed fencing history is enabled or an XML output format is used, each fence history item now contains a high-resolution time of completion. A new value "completed-ns" denotes the quantity of nanoseconds to be added to the "completed" time.
Closes T178

Feature: tools: crm_mon detailed fencing history now shows nanoseconds

---

cts/Makefile.am
cts/cli/crm_mon-rsc-maint.xml
cts/cli/regression.crm_mon.exp
cts/cli/regression.feature_set.exp
cts/cli/regression.tools.exp
cts/cts-cli.in
cts/scheduler/summary/bug-5028-detach.summary
cts/scheduler/summary/node-maintenance-1.summary
cts/scheduler/summary/probe-pending-node.summary
cts/scheduler/summary/rsc-maintenance.summary
cts/scheduler/summary/shutdown-maintenance-node.summary
doc/sphinx/Pacemaker_Explained/resources.rst
include/crm/common/output_internal.h
lib/pengine/bundle.c
lib/pengine/clone.c
lib/pengine/group.c
lib/pengine/native.c
xml/api/crm_mon-2.28.rng
xml/api/crm_resource-2.28.rng
xml/api/crm_simulate-2.28.rng
xml/api/nodes-2.28.rng
xml/api/resources-2.28.rng

Previously, if a resource's "maintenance" meta attribute was set to true (and the cluster's maintenance-mode property was not enabled), the crm_mon output for the resource said "(unmanaged)". Now, it says "(maintenance)" instead.
Note that "maintenance" necessarily implies "unmanaged". So as was already the case with "blocked", if we show "maintenance" then we don't show "unmanaged".
Note also that this improved flag appears whether the resource is in maintenance mode because of cluster-wide maintenance mode, because the "maintenance" resource meta attribute, or both. If the cluster-wide maintenance-mode property is set, it will be indicated elsewhere in the crm_mon output, and there will be no separate indication of the meta attribute until the cluster is taken out of maintenance mode. …

Feature: libpe_status: crm_mon shows "maintenance" for rsc maint meta

---

xml/api/crm_mon-2.28.rng

Somehow the `crm-mon-disconnected` and `stack:pacemakerd-state` changes got removed in the 2.28 schema. As a result, `crm_mon` output using a native CIB connection fails to validate.
This doesn't affect 2.1.5-rc2, which stops at `crm_mon-2.25.rng`.

Fix: schemas: Regression in crm_mon validation

---

daemons/controld/controld_join_client.c
daemons/controld/controld_join_dc.c
include/crm/cluster.h
include/crm/crm.h

The client already listens for a nack in `do_cl_join_finalize_respond()`, but the DC never sends one. Rather, the DC only sends a finalization message if the node is integrated (acked).
The only change needed at the client end is to exit fatally with no respawn. Currently, if the client were to receive a nack, it would respawn and enter a rapid loop (observed after modifying the DC to send a nack).
The DC needs to send a nack, which means it needs to finalize if there are **either** integrated nodes **or** nacked nodes. There may be a better place to put the nack message than the `finalize_join_for()` function -- or perhaps the function should be renamed -- but this seems to work.
I'm open to other approaches if this isn't ideal. I'll have CTSlab running overnight. So far things have gone …

Low: controller: Node exits fatally in response to join nack

---

daemons/controld/controld_te_callbacks.c
daemons/controld/controld_te_events.c
daemons/controld/controld_transition.h

Currently, a simulated failure (for example, from `crm_resource --fail`) often causes the resource's failcount on the given node to be incremented twice: once for each of two incoming events.
A "_last_0" update event often comes in because the previous last event was a recurring monitor. A "_last_failure_0" update comes in because there is now a more recent failure (the newly simulated one).
Events generated by the cluster have corresponding actions in the transition graph. These actions can be marked as "confirmed" once they've been processed the first time. However, this can't be done for simulated events, which are not in the transition graph. They receive a dummy transition ID of -1 and a dummy action number that generally increases over time.
This commit stores a set of outside …

Fix: controller: Don't double-increment failcount for simulated failures

---

daemons/controld/controld_join_dc.c

If a node is fenced while it's joining the cluster, it's possible for the DC to receive its join request after noticing it's down, leading to error logs about the node not being a member and the request being rejected. We shouldn't log an error in this scenario since we know the node went down recently.
This scenario has not been reproducible despite a great deal of trying. Nonetheless, this change only affects log severity, so it's reasonable to implement it in case the situation reappears.
Closes T456

Low: controller: Avoid error if a join request is received after fencing

---

daemons/controld/controld_callbacks.c
daemons/controld/controld_control.c
daemons/controld/controld_join_dc.c
daemons/controld/controld_membership.h

The DC accepts a joining node even if its local CIB manager will later reject the joining node's CIB (for example, due to schema version incompatibility). This can cause an election storm.
`do_dc_join_finalize()` calls `cib_t:cmds:sync_from()` against the joining node, syncing its CIB across the cluster. However, it may fail to apply the diff, and the DC won't notice until we get an error code via the sync callback.
Here, if a joining node has the max generation so far, we verify on the DC side that we recognize its schema name before accepting its join request. That eliminates most of the cases in which we would sync the CIB and then reject the CIB ourselves on the DC.
If the CIB sync does fail in the finalize step, then we add the node to a table of nodes whose CIB syncs have failed, …

Fix: controller: Avoid election storm due to incompatible CIB

---

daemons/based/based_callbacks.c
daemons/based/based_messages.c
daemons/based/pacemaker-based.c
daemons/based/pacemaker-based.h

Moving the contents of the long-unused `cib_cleanup()` function to the done section in b8de0aa exposed a bug. We didn't `strdup(crm_cluster->uname)` before assigning to `cib_our_uname`, but we did `strdup("localhost")` if in stand-alone mode. So when we freed `cib_our_uname` after freeing `crm_cluster`, the same pointer would be freed twice if not in stand-alone mode.
`cib_our_uname` is used only as a const, so now we just replace it with `"localhost"` if stand-alone or `crm_cluster->uname` otherwise. We're avoiding a separate `const char *` global for future-proofing, in case `crm_cluster` or its `uname` member is ever freed and reassigned.

High: based: Fix double free() in pacemaker-based.c

---

daemons/based/based_callbacks.c
tools/cibadmin.c

Currently, `cibadmin --upgrade --force` upgrades the in-memory CIB but doesn't write it to disk. It should write to disk.
The approach used here is to set `config_changed = TRUE` while processing an upgrade request. This isn't technically a config change in the way we've historically used the term (a change to the `<configuration>` section), but it's convenient to use the `config_changed` boolean for this too.
Or we could be more granular and check in `xml_create_patchset()` whether `validate-with` changed. It's noteworthy that the current approach will write to disk even if the schema upgrade fails, which is not necessary. It probably won't matter since upgrades should be uncommon.
Closes T565

Fix: based: CIB schema upgrade should always force a write

---

cts/cli/regression.tools.exp
cts/cts-cli.in

There was an invalid scope warning from `cibadmin` as part of a test setup: the command incorrectly used `-o resource` instead of `-o resources` when deleting a group. Here we fix that and make the group creation and deletion into tests.

Test: cts-cli: Fix invalid scope warning and add two tests

---

daemons/controld/controld_join_dc.c

In the finalization stage, we sync the max_generation CIB across the cluster. It's possible for the sync_from() operation to return a -pcmk_err_old_data error ("Update was older than existing configuration"). That error is fairly normal (hence treating it as a warning already), and it shouldn't cause us to call a new election and nack the max_generation node.
Regression in ae899e8.

Fix: controller: Don't nack joining node due to old CIB

---

cts/scheduler/xml/utilization.xml
daemons/attrd/attrd_attributes.c
daemons/attrd/attrd_cib.c
daemons/attrd/attrd_utils.c
daemons/attrd/pacemaker-attrd.h
doc/sphinx/Pacemaker_Explained/utilization.rst
include/crm/common/attrd_internal.h
include/crm_internal.h
lib/common/ipc_attrd.c
lib/pengine/unpack.c
tools/attrd_updater.c
tools/crm_attribute.c

This seems suspiciously easy.
Basically, you use attrd_updater -z when creating an attribute to specify it's a utilization attribute (just like in crm_attribute).  After that, you don't need to use -z when updating or deleting - it'll just know which block the attribute is in.  The CIB ends up with something like this in it:
```
<transient_attributes id="1">
<instance_attributes id="status-1">
<nvpair id="status-1-.feature-set" name="#feature-set" value="3.16.2"/>
<nvpair id="status-1-master-stateful" name="master-stateful" value="5"/>
<nvpair id="status-1-last-failure-httpd-bundle-podman-0.start_0" name="last-failure-httpd-bundle-podman-0#start_0" value="1668202467"/>
<nvpair id="status-1-fail-count-httpd-bundle-podman-0.start_0" name="fail-count-httpd-bundle-podman-0#start_0" …
```

Support transient utilization attributes

---

include/crm/common/output_internal.h
lib/common/crmcommon_private.h
lib/common/output.c
lib/common/output_xml.c
lib/common/patchset.c
lib/common/xml.c

This is in preparation for formatted output in XML logging, which in turn is the last missing piece for `crm_shadow` formatted output.
There are plans to use `pcmk__output_get_log_level()` and `pcmk__text_output_new()`.

Minor fixes and changes to XML logging functions

---

include/crm/common/logging.h
include/crm/common/logging_compat.h
include/crm/common/xml.h
include/crm/common/xml_internal.h
lib/common/crmcommon_private.h
lib/common/logging.c
lib/common/patchset.c
lib/common/xml.c

When we add formatted output support to XML logging, these changes will make it much easier to reason about.

XML logging best practices and log_data_element() deprecation

---

daemons/fenced/fenced_commands.c
daemons/fenced/pacemaker-fenced.h

seems not to be covered by any of the open PRs.
guess it is new gcc being more picky.

Fix: fenced: use enum fenced_target_by consistently

---

daemons/execd/pacemaker-execd.c
daemons/execd/pacemaker-execd.h
daemons/execd/remoted_tls.c

This reverts the essential part of d61494347, which was based on misdiagnosing a remote node shutdown issue. Initially, it was thought that a "TLS server session ended" log just after a remote node requested shutdown indicated that the proxy connection coincidentally dropped at that moment. It actually is the routine stopping of accepting new proxy connections, and that commit makes the remote node exit immediately without waiting for the all-clear from the cluster.
Fixes T361

High: executor: fix regression in remote node shutdown

---

lib/pacemaker/pcmk_injections.c

It's possible that a node_state entry doesn't have an uname yet.
Previously in that case upon simulate_fencing_action(), crm_simulate
would encounter an assertion failure in pcmk__inject_node() at:
CRM_ASSERT(rc == pcmk_ok);
, since a query by uname wouldn't find the existing node_state entry,
then the unnecessary creation of a new entry would conflict with the
existing one and a new query by uname would still get nothing.
This PR fixes it by finding the existing node_state entry by node id
and adding its uname to the entry rather than creating a new entry.

Fix: libpacemaker: avoid assertion failure if a node_state entry doesn't have an uname yet

---

daemons/based/based_messages.c
include/crm/common/logging_internal.h
lib/common/acl.c
lib/common/patchset.c
lib/common/watchdog.c
lib/common/xml.c
lib/common/xml_display.c
lib/pengine/utils.c

This was on the to-do list anyway, and it simplifies converting the `pcmk__xml_log_changes()` call in `cib_perform_op` to use a `pcmk__output_t` argument (part of a WIP).
Feel free to nitpick the format I used in the callers. It was the least ugly way I found.
Note that in several places I treated an existing `if ((cs != NULL) && (cs->targets != 0))` as equivalent to `crm_is_callsite_active()`. The latter can also refilter but otherwise they seem to be the same. That allows us to use `pcmk__if_tracing()` in more places than we otherwise could.
I also got rid of a full log message that seems useless as well as a piece of another one.
Closes T559

Replace pcmk__log_else() with pcmk__if_tracing()

---

daemons/based/based_callbacks.c
include/crm/common/logging.h
include/crm/common/logging_internal.h
include/crm/common/output_internal.h
include/crm/common/xml_internal.h
lib/cib/cib_utils.c
lib/common/digest.c
lib/common/logging.c
lib/common/output_log.c
lib/common/patchset.c
lib/common/results.c
lib/common/xml.c
lib/common/xml_display.c
tools/crm_diff.c
tools/crm_shadow.c

We're not quite finished, but this is enough for one PR :)
The final big step that I'm aware of is to convert the "xml_log_patchset" family of functions to use message formatters instead. Those will be part of the API and need to support XML output in addition to the other formats.
In contrast, the functions that we refactor here only need to support text and log output formats. So for simplicity, we forego message formatters and instead just use `out->info()`. The downside is that if for some reason they're called with an XML output object, we won't return early like we would with message formatters. (They're internal so that shouldn't happen.) The upside is that we can avoid all the complexity of adding formatters that we don't really need.
At the time of filing this, the first two …

Continue adding pcmk__output_t to XML display functions

---

tools/crm_shadow.c

I misread the RC scheme and converted to a legacy RC in 5e9d943.

Low: tools: Fix use of legacy RC in crm_shadow.c

---

cts/cli/crm_mon.xml
cts/cli/regression.crm_mon.exp
cts/scheduler/summary/bundle-order-partial-stop.summary
cts/scheduler/summary/bundle-order-stop.summary
cts/scheduler/summary/promoted-with-blocked.summary
include/crm/common/output.h
include/crm/common/output_internal.h
include/crm/pengine/internal.h
lib/pengine/bundle.c
lib/pengine/clone.c
lib/pengine/group.c
lib/pengine/native.c
lib/pengine/pe_output.c
tools/crm_mon.c
xml/api/crm_mon-2.29.rng
xml/api/crm_resource-2.29.rng
xml/api/crm_simulate-2.29.rng
xml/api/nodes-2.29.rng
xml/api/resources-2.29.rng

Here is an example:
If you give your resource `ClusterIP` the description `IP address for website`, you can display said description with 
`crm_resource --list`
```
Full List of Resources:
* ClusterIP	(ocf::heartbeat:IPaddr2):	 Stopped (IP address for website)
```
and
`crm_mon --show-detail -r`
```
* Stack: corosync (Pacemaker is running)
* Current DC:	pcmk-1 (1) (version 2.1.5-141.0f5e333a2.git.el8-0f5e333a2) - partition with quorum
* Last updated: Mon Jan 16 16:31:36 2023 on pcmk-1
* Last change:  Mon Jan 16 16:28:22 2023 by root via cibadmin on pcmk-1
* 2 nodes configured
* 2 resource instances configured
Node List:
* Node pcmk-1 (1): online, feature set 3.17.2
* Node pcmk-2 (2): online, feature set 3.17.2
Full List of Resources:
* ClusterIP   (ocf::heartbeat:IPaddr2): …
```

Feature: resources: Improve resource description display

---

daemons/fenced/fenced_remote.c

QE observed a rarely reproducible core dump in the fencer during Pacemaker shutdown, in which we try to `g_source_remove()` an op timer that's already been removed.
`free_stonith_remote_op_list()`
-> `g_hash_table_destroy()`
-> `g_hash_table_remove_all_nodes()`
-> `clear_remote_op_timers()`
-> `g_source_remove()`
-> `crm_glib_handler()`
-> "Source ID 190 was not found when attempting to remove it"
The likely cause is that `request_peer_fencing()` doesn't set `op->op_timer_one` to 0 after calling `g_source_remove()` on it, so if that op is still in the `stonith_remote_op_list` at shutdown with the same timer, `clear_remote_op_timers()` tries to remove the source for `op_timer_one` again.
There are only five locations that call `g_source_remove()` on a `remote_fencing_op_t` timer.
* Three …

Fix: fencer: Prevent double g_source_remove of op_timer_one

---

include/crm/common/logging.h
include/crm/common/output_internal.h
lib/common/output_log.c
lib/common/xml_display.c

libqb expects all log levels to be in the uint8_t range (0 to 255). Several Pacemaker functions and macros currently accept arbitrary integers and don't validate that they're in-range. This fixes that issue.

 Refactor: libcrmcommon: Ensure log levels are in uint8_t range 

---

daemons/fenced/fenced_remote.c

It's RHBZ#2166967 Part 2, Electric Boogaloo.
db10921 was correct to do, but it didn't solve the issue that QE encountered (see #3022).
The original "fix" zeroed out `op->op_timer_one` after calling `g_source_remove()` on that timer. That was still a good idea, but it obviously wasn't the root cause.
I've been able to reproduce this locally under the following conditions:
1. Set up a non-working fence device (missing fence agent script -- this may not be necessary, but I created it in order to match QE's test)
2. Configure sbd:
* `have-watchdog=true`
* `stonith-watchdog-timeout=10`
3. Block `node2`'s outbound communication on port 5405:
```
```
4. Sleep 180 seconds (not exact requirement but sufficient)
5. Stop pacemaker on `node1` (`pcs cluster stop --force`)
Or in one command line, …

Fix: fencer: Avoid double source remove of op_timer_total

---

configure.ac
cts/cts-attrd.in
include/crm/common/attrd_internal.h
include/crm/common/ipc_attrd_internal.h
lib/common/ipc_attrd.c
python/pacemaker/_cts/test.py
tools/attrd_updater.c

According to the header file, if node is NULL, pcmk__attrd_api_query should query the value of the given attribute on all cluster nodes. This is also what the server expects and how attrd_updater is supposed to work.
However, pcmk__attrd_api_query does not correctly handle a NULL here. Instead, it will call pcmk__node_attr_target.  That function takes NULL to mean that it should probe the local cluster node for its name, returning that to pcmk__attrd_api_query.  If it returns non-NULL, that value will then be put into the XML IPC call which means the server will only return the value for that node.
In testing this was usually fine.  However, in pratice, the methods pcmk__node_attr_target uses to figure out the local cluster node name involves checking the OCF_RESKEY_CRM_meta_on_node …

Low: libcrmcommon: Fix handling node=NULL in pcmk__attrd_api_query.

---

daemons/attrd/pacemaker-attrd.c
daemons/based/pacemaker-based.c
daemons/controld/pacemaker-controld.c
daemons/execd/cts-exec-helper.c
daemons/execd/pacemaker-execd.c
daemons/fenced/cts-fence-helper.c
daemons/fenced/pacemaker-fenced.c
daemons/pacemakerd/pacemakerd.c
daemons/schedulerd/pacemaker-schedulerd.c
include/crm/common/output_internal.h
lib/common/output.c
lib/common/tests/output/pcmk__output_and_clear_error_test.c
tools/attrd_updater.c
tools/cibadmin.c
tools/crm_attribute.c
tools/crm_diff.c
tools/crm_error.c
tools/crm_node.c
tools/crm_resource.c
tools/crm_rule.c
tools/crm_shadow.c
tools/crm_simulate.c
tools/crm_ticket.c
tools/crm_verify.c
tools/crmadmin.c
tools/iso8601.c
tools/stonith_admin.c

First, it should take a GError ** so that doing anything in the function modifies the error object that was passed to it.  Second, the test case should assert that the error is NULL, not that some element of it is NULL.

Low: libcrmcommon: Fix problems with pcmk__output_and_clear_error.

---

cts/support/fence_dummy.in
daemons/fenced/fenced_remote.c

When the node to be fenced via watchdog-fencing doesn't advertise self-fencing
calculation of overall fencing time in a topology doesn't take watchdog-timeout
into account.

fix watchdog-fencing with topology

---

cts/cli/regression.tools.exp
cts/cts-cli.in
lib/common/cmdline.c

For the `crm_attribute -p -v -INFINITY` command, when the resource (the `-p` argument) is specified via the `OCF_RESOURCE_INSTANCE` environment variable rather than explicitly on the command line, the string `"-INFINITY"` is
parsed incorrectly.
`pcmk__cmdline_preproc()` treats the leading `'I'` as an argument but skips it because it's not in the `special` string. It then parses the `'N'`, finds it in the `special` string, and treats `"FINITY"` as `N`'s argument. As a result, `crm_attribute` looks for a node (`-N` specifies a node) named `"FINITY"` instead of treating `"-INFINITY"` as the value to update the promotion score.
We should handle `"-INFINITY"` as a string and let GLib handle it instead.
Fixes CLBZ#5509

 Fix: libcrmcommon: Don't parse "-INFINITY" as a list of cmdline options 

---

cts/cli/regression.tools.exp
cts/cts-cli.in
tools/crm_shadow.c

One last step before formatted output. This is tedious but it ought to be done, and now is as good a time as any.
9e8a059 made the `crm_shadow.c` code somewhat easier to follow, but it's still a mess. The `main()` function is monolithic. Code is shared where possible -- often several commands share a particular initialization or validation step. This is typically handled by switch statements. However, it quickly becomes difficult to follow what any particular command is doing from start to finish. This makes it hard to reason about whether changes preserve existing behavior or not.
This PR improves `crm_shadow.c` by functionizing the logic of each command, after global option parsing. There is some duplication among the new functions, but the ease of maintenance justifies it.

Functionize all of crm_shadow.c:main()

---

tools/crm_mon.8.inc

From a request in https://bugzilla.suse.com/show_bug.cgi?id=1208868: 
> The synopsis in the man page for crm_mon is:
> 
> SYNOPSIS
>        crm_mon mode [options]
> 
> I can only see optional options in the man page. There are no mode entries.
> 
> I think the synopsis should read as follows:
> 
> SYNOPSIS
>        crm_mon [options]

Fix: tool: update crm_mon synopsis

---

cts/cli/regression.error_codes.exp
doc/sphinx/Pacemaker_Explained/alerts.rst
include/crm/common/results.h
include/crm/msg_xml.h
lib/common/results.c
lib/pengine/rules_alerts.c

An `<alert>` element or an individual `<recipient>` element can now contain a boolean `enabled` meta attribute. The default value is "true". If `enabled` is set to "false", the alert or recipient will not be used.
If `enabled` is set to "false" at the `<alert>` level, all of the alert's recipients are disabled, regardless of the recipients' `enabled` value.
If `enabled` is set to "true" or is unset at the `<alert>` level, the alert's recipients are enabled or disabled based on their respective values of the `enabled` meta attribute.
Setting `enabled` to "false" can be useful to avoid spamming alert recipients during planned maintenance, for example.

New "enabled" meta-attribute for alerts

---

cts/cli/regression.tools.exp
cts/cts-cli.in
lib/common/attrs.c

, rather than set/get a meaningless promotion score. And in case
OCF_RESOURCE_INSTANCE is also an empty string, return usage error.

Fix: libcrmcommon: allow crm_attribute to try OCF_RESOURCE_INSTANCE environment variable if -p is specified with an empty string

---

extra/resources/SysInfo.in

When the system running time is greater than 1 h, cpu_load (uptime | awk '{print $10}') of the return value is wrong.

Fix: extra/resources/SysInfo.in: This calculation of cpu_load returns an incorrect value in Darwin and Linux

---

daemons/controld/controld_fsa.h
daemons/controld/controld_join_dc.c
daemons/controld/controld_te_actions.c

While a transition is in progress, CIB updates may be generated and received rapidly as resource actions complete. This can cause problems if it happens during a controller join sequence.
The last two major steps of the join sequence are:
1. The client sends XML containing its resource history, obtained from its local executor, to the DC in `do_cl_join_finalize_respond()`.
2. The DC receives this client resource history in `do_dc_join_ack()`, deletes the client's node state in the CIB, and writes the received client resource history to the CIB as the client's new node state.
However, suppose a resource action completes after the client generates its resource history XML. Further suppose that action is recorded in the CIB and is received by the DC's CIB manager before the DC updates the …

Fix: controller: Delay join finalization if a transition is in progress

---

tools/crm_mon.c
tools/crm_mon.h
tools/crm_mon_curses.c

If Pacemaker is built without curses, crm_mon in console mode exits immediately with a segmentation fault. There's no problem in one-shot mode.
Early in main(), we fail to initialize the "curses"-format pcmk__output_t object. In clean_up(), we call out->finish() without NULL-checking the output object.
This commit goes a little bit further than NULL-checking the output object. If we fail to create the curses object, we try to create a text object so that we can display the error.
Before:
```
[reid@laptop pacemaker]$ sudo crm_mon -1
* Stack: corosync (Pacemaker is running)
* Current DC: NONE
* Last updated: Mon Mar 27 18:13:16 2023 on laptop
* Last change:  Fri Mar 24 00:41:47 2023 by hacluster via crmd on laptop
* 1 node configured
* 4 resource instances configured
Node …
```

Low: tools: Fix crm_mon seg fault when curses is missing

---

lib/cib/cib_file.c
lib/cib/cib_native.c
lib/cib/cib_remote.c

All of these commits should be completely trivial unless I did something stupid. I did these a few days ago as cleanup prior to making changes for T185 (flexible CIB replacement or delete/modify). Since I put that on hold to discuss the approach and work on #3068, I might as well submit these now.

Refactor: libcib: Static-ize a bunch of functions

---

cts/cts-fencing.in
cts/lab/CTStests.py
daemons/controld/controld_fencing.c
daemons/fenced/fenced_commands.c
daemons/fenced/fenced_remote.c
lib/pacemaker/pcmk_fence.c
python/pacemaker/_cts/patterns.py

... to prevent any delays from eating up the timeouts and causing constant fencing failures.
This also means, when configuring fencing timeouts, users won't need to take any fencing delays into account by themselves.

Fix: fencer: make sure all fencing delays are applied correctly and taken into account by fencing timeouts

---

daemons/controld/controld_callbacks.c
daemons/controld/controld_join_client.c
daemons/controld/controld_join_dc.c
daemons/controld/controld_messages.c
daemons/controld/controld_messages.h
daemons/controld/controld_remote_ra.c
daemons/execd/execd_commands.c
daemons/execd/pacemaker-execd.c
daemons/execd/pacemaker-execd.h
include/crm/cluster.h
include/crm/common/ipc_internal.h
include/crm/lrmd_internal.h
include/crm_internal.h
lib/cluster/membership.c
lib/lrmd/lrmd_client.c

This is just like the previous PR against main, with the latest comments also taken into account.

Preserve transient attributes across remote connection hiccups

---

daemons/controld/controld_join_client.c
daemons/controld/controld_remote_ra.c
daemons/controld/pacemaker-controld.h
daemons/execd/execd_commands.c
etc/sysconfig/pacemaker.in
include/crm/common/ipc_internal.h
include/crm/lrmd_internal.h
include/crm_internal.h
lib/lrmd/lrmd_client.c

This is against 2.1, but it definitely doesn't need to go there.  It was just easier to write on that branch since it touches a lot of the same code as the persistent transient attrs PR.  Once that's also merged to main, I can redo this PR there too.  But in the mean time, we can at least talk about it.

Support start state on remote nodes

---

daemons/based/based_callbacks.c
daemons/based/based_common.c
daemons/based/based_messages.c
daemons/based/pacemaker-based.h
daemons/controld/controld_transition.c
include/crm/cib/cib_types.h
include/crm/cib/internal.h
lib/cib/cib_client.c
lib/cib/cib_file.c
lib/cib/cib_remote.c
lib/cib/cib_utils.c
lib/common/io.c
lib/common/patchset.c
lib/common/xml.c

This addresses some things that I found while working on T185. Highlights:
* Deprecate unused `cib_api_operations_t` functions (see [T656](https://projects.clusterlabs.org/T656)).
* I'm not tied to all of these, since some of them (particularly `bump_epoch()` and `erase()`) are potentially useful methods. They just don't have internal callers. We could keep them in order to provide a more complete API for external users.
* @kgaillot said in T656: "My long-term goal is to deprecate all of libcib, replaced with equivalent functionality in libcrmcommon (probably a long ways off though)."
* `ping()` could also be deprecated if it turns out that sbd doesn't need it; see comment https://projects.clusterlabs.org/T656#9046, etc.
* Deprecate CIB global callbacks. There are no internal users. It's …

libcib, based, various: Minor fixes and improvements

---

python/pacemaker/_cts/audits.py
python/pacemaker/_cts/remote.py
python/pacemaker/_cts/tests/partialstart.py
python/pacemaker/_cts/tests/restartonebyone.py
python/pacemaker/_cts/tests/standbytest.py
python/pacemaker/_cts/tests/startonebyone.py
python/pacemaker/_cts/tests/stonithdtest.py
python/pacemaker/_cts/tests/stoponebyone.py
python/pacemaker/_cts/watcher.py

This is the same thing, but without the explicit call to repr, which makes the lines a little shorter and gets rid of closing parens in places where there's already a pile of them.

Refactor: python: Use %r instead of calling repr in format strings.

---

lib/services/dbus.c
lib/services/systemd.c

For some reason that I haven't been able to track down, the following warning occurs only when you build with coverage enabled:
dbus.c: In function 'handle_query_result':
dbus.c:598:9: error: 'error' may be used uninitialized [-Werror=maybe-uninitialized]
598 |     if (pcmk_dbus_find_error((void*)&error, reply, &error)) {
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
You don't even have to "make coverage".  Just configuring with coverage enabled and then building normally is enough.

Low: libcrmservice: Fix an error when coverage is enabled.

---

tools/crm_verify.c

This PR doesn't change the fact that the output is not verbose by default:
```
[root@pcmk-1 ~]# crm_verify --xml-file tmp.xml
crm_verify: Errors found during check: config not valid
-V may provide more details
```
So, you still need to specify that you want it to be verbose:
```
[root@pcmk-1 ~]# crm_verify --xml-file tmp.xml --verbose
(unpack_resources) 	error: Resource start-up disabled since no STONITH resources have been defined
(unpack_resources) 	error: Either configure some or disable STONITH with the stonith-enabled option
(unpack_resources) 	error: NOTE: Clusters with shared data need STONITH to ensure data integrity
crm_verify: Errors found during check: config not valid
```
This PR adds the ability to make it quiet:
```
[root@pcmk-1 ~]# crm_verify --xml-file tmp.xml --verbose …
```

Feature: crm_verify: Add --quiet option to crm_verify

---

cts/cli/regression.error_codes.exp
daemons/based/Makefile.am
daemons/based/based_callbacks.c
daemons/based/based_common.c
daemons/based/based_messages.c
daemons/based/based_remote.c
daemons/based/based_transaction.c
daemons/based/based_transaction.h
daemons/based/pacemaker-based.c
daemons/based/pacemaker-based.h
include/crm/cib/cib_types.h
include/crm/cib/internal.h
include/crm/common/results.h
include/crm/msg_xml.h
include/crm/msg_xml_compat.h
lib/cib/cib_client.c
lib/cib/cib_file.c
lib/cib/cib_ops.c
lib/cib/cib_utils.c
lib/common/results.c
lib/common/xml.c

This pull request adds a new feature: atomic CIB transactions. It adds `init_transaction()` and `end_transaction()` methods to `cib_api_operations_t`. Transactions are supported for all three variants of `cib_t` clients: native, file, and remote. Native and remote share an implementation.
The basic idea is that a client can initiate a transaction, append requests to the transaction, and either commit or discard the transaction. Requests that are appended (via the `cib_transaction` value of `enum cib_call_options`) get queued until the transaction is committed. When a transaction is committed, all requests are processed in FIFO order. If any request fails, the transaction is aborted, and the CIB is left in its initial state. The CIB is modified only if all requests in the transaction …

Feature: libcib, based: Support CIB transactions

---

cts/cts-cli.in

Adding this option to cts-cli means that all regression tests now have this option.
cts-cli was writing error messages to a file only. These now get written to the command line when the verbose option is used.
All other regression tests either always write errors to the command line (attrd, exec, fencing) or already have the behavior that cli now has (scheduler).
closes T514

Feature: cts-cli: Add cts-cli option to display failures

---

include/crm/common/Makefile.am
include/crm/common/resources.h
include/crm/common/scheduler.h
include/crm/pengine/common.h
lib/pacemaker/pcmk_sched_primitive.c
lib/pengine/complex.c
lib/pengine/native.c

This is the start of a project to merge the functionality of libpe_rules and libpe_status into libcrmcommon.

Move enum rsc_recovery_type to libcrmcommon

---

daemons/based/Makefile.am
daemons/based/based_callbacks.c
daemons/based/based_common.c
daemons/based/based_io.c
daemons/based/based_messages.c
daemons/based/based_notify.c
daemons/based/based_operation.c
daemons/based/based_remote.c
daemons/based/based_transaction.c
daemons/based/pacemaker-based.c
daemons/based/pacemaker-based.h
include/crm/cib/internal.h
include/crm/common/xml.h
include/crm/common/xml_compat.h
lib/cib/cib_file.c
lib/cib/cib_ops.c
lib/cib/cib_utils.c
lib/common/output_html.c
lib/common/output_xml.c
lib/common/schemas.c
lib/common/xml.c
lib/common/xpath.c
lib/pacemaker/pcmk_sched_constraints.c
lib/pengine/pe_output.c

This allows us to deduplicate the shared data (op name and op attributes). We introduce a new `enum cib__op_type` to use as a key for accessing `cib_op_fn_t` functions. This is a step toward a cleaner CIB transaction implementation, which is coming soon.
We drop `cib_operation_t:prepare` and `cib_operation_t:cleanup` as well.
I was going to go farther with the XML stuff but dropped that for now. I included in this PR what I had already done. Getting rid of `getDocPtr()` doesn't actually allow all that many switches to const (I only checked `xml.c` so I'm sure I missed a bunch that we can update later). Most of the barriers to const come from libxml2 itself.

Use a single cib__operation_t table for pacemaker-based and libcib

---

daemons/controld/controld_fencing.c

Previously controld would unconditionally keep invoking stonith__watchdog_fencing_enabled_for_node_api() even if `stonith-watchdog-timeout` was not configured, which would also keep worrying users with the log:
pacemaker-controld[...]:  notice: Cluster does not have watchdog fencing device

Fix: controller: do not check whether watchdog fencing is enabled for the node if `stonith-watchdog-timeout` is not even configured

---

rpm/pacemaker.spec.in

That directory doesn't exist anymore following moving the last file into _cts instead.

Low: build: No longer try to package the cts python directory.

---

tools/attrd_updater.c

Hi All,
Attrd_updater ignores dampen when setting values.
This fix is important because it is also used in resource agents etc.
Best Regards,

High: tools: The dampen parameter is disabled when setting values with attrd_updater.

---

lib/common/ipc_controld.c

ipc_controld.c:reply_expected() wrongly omitted PCMK__CONTROLD_CMD_NODES (which hasn't been a problem because crm_node uses a mainloop instead of sync dispatch for that) and CRM_OP_RM_NODE_CACHE (which can be sent via ipc_client.c:pcmk_ipc_purge_node()).
Because CRM_OP_RM_NODE_CACHE gets only an ack and no further replies, we now have to be careful not to return true from the controller's dispatch() function, otherwise crm_node -R would wait forever for more data. That means we have to check for whether any replies are expected, which means we have to increment expected replies *before* sending a request (in case it's sync).
Regression introduced in 2.0.5 by ae14fa4a
Fixes T681

Fix: libcrmcommon: wait for reply from appropriate controller commands

---

include/crm/common/actions.h
include/crm/common/scheduler.h
include/crm/pengine/common.h
lib/pacemaker/pcmk_sched_actions.c
lib/pacemaker/pcmk_sched_bundle.c
lib/pacemaker/pcmk_sched_group.c
lib/pacemaker/pcmk_sched_instances.c
lib/pacemaker/pcmk_sched_remote.c
lib/pengine/common.c
lib/pengine/pe_actions.c
lib/pengine/pe_notif.c

This is part of a project to merge the functionality of libpe_rules/libpe_status into libcrmcommon, bringing it up to current guidelines as we go

Move enum action_tasks to libcrmcommon

---

cts/cli/regression.tools.exp
include/crm/crm.h
lib/pacemaker/pcmk_output.c
tools/Makefile.am
tools/crm_node.c
xml/Makefile.am
xml/api/crm_node-2.32.rng

Some parts of this are a little weird.  Hopefully, the commit messages and comments explain why.  The extremely brief idea was that I wanted to use existing formatted output messages as much as possible, within the constraint that text output can't change right now.  So that resulted in some strange stuff around the output messages.
I've also not added an XML schema yet because I want to get everything else figured out first.  Here's what the XML output looks like at the moment:
```
[root@rhel9-cluster-1 ~]# ./test.sh 
+ crm_node -i --output-as=xml
<pacemaker-result api-version="2.30" request="crm_node -i --output-as=xml">
<node-info nodeid="1" have-quorum="true" remote_node="false"/>
<status code="0" message="OK"/>
</pacemaker-result>
+ crm_node -l --output-as=xml
<pacemaker-result …
```

Convert crm_node to formatted output

---

configure.ac

When running `configure` from within the RPM build directory, the relative paths that set `API_VERSION` and `CIB_VERSION` don't match anything in the git index. However, the `git ls-files` command returns success even if its output is empty. So we never fall back to the `ls` command if the `git ls-files` output is empty. As a result, the `API_VERSION` and `CIB_VERSION` variables get set to empty strings in an RPM build.
This causes `cts-lab` to fail in an RPM installation. The `validate-with` attribute in the empty CIB is set based on the value of `CIB_VERSION`. If `CIB_VERSION` is empty, `validate-with` gets set to `"pacemaker-"`, which is invalid.
---
If there's a better way to do this, I'm all ears. Ideally we'd find a way to make `git ls-files` match the files we want. That way we …

Fix: build: Fix API and CIB versions in RPM build

---

daemons/attrd/attrd_corosync.c
daemons/attrd/attrd_ipc.c
daemons/based/based_callbacks.c
daemons/based/based_messages.c
daemons/based/based_operation.c
daemons/based/based_remote.c
daemons/based/based_transaction.c
daemons/based/based_transaction.h
daemons/based/pacemaker-based.c
daemons/based/pacemaker-based.h
daemons/controld/controld_cib.c
daemons/controld/controld_cib.h
daemons/controld/controld_election.c
daemons/controld/controld_join_dc.c
daemons/controld/controld_membership.c
daemons/controld/controld_remote_ra.c
include/crm/cib/cib_types.h
include/crm/cib/internal.h
include/crm/common/nvpair.h
include/crm/common/util_compat.h
lib/cib/cib_client.c
lib/cib/cib_file.c
lib/cib/cib_native.c
lib/cib/cib_ops.c
lib/cib/cib_remote.c
lib/cib/cib_utils.c
lib/common/nvpair.c
lib/common/xml.c
lib/pengine/complex.c

This fixes a regression in the controller join sequence introduced by https://github.com/ClusterLabs/pacemaker/commit/5e3b3d142cc41376e8a1a88faa12d6062e726035. As of that commit, there are multiple asynchronous calls when building each transaction in do_dc_join_ack(). If multiple nodes were joining in parallel, the DC may try to initiate a transaction for one node while a transaction was already open for another node. However, the DC's CIB client can have only one active transaction at a time.
Now, the transaction is created, sent to the CIB manager, and freed synchronously. There is no opportunity for another node's join ack to try to initiate a transaction in the meantime.
Fixes [T690](https://projects.clusterlabs.org/T690)

Move CIB transaction management to client and fix controller regression

---

daemons/fenced/pacemaker-fenced.c
include/crm/common/resources.h
include/crm/compatibility.h
include/crm/pengine/pe_types.h
include/crm/pengine/status.h
lib/pacemaker/pcmk_graph_producer.c
lib/pacemaker/pcmk_resource.c
lib/pacemaker/pcmk_sched_actions.c
lib/pacemaker/pcmk_sched_bundle.c
lib/pacemaker/pcmk_sched_clone.c
lib/pacemaker/pcmk_sched_colocation.c
lib/pacemaker/pcmk_sched_fencing.c
lib/pacemaker/pcmk_sched_group.c
lib/pacemaker/pcmk_sched_instances.c
lib/pacemaker/pcmk_sched_primitive.c
lib/pacemaker/pcmk_sched_probes.c
lib/pengine/bundle.c
lib/pengine/clone.c
lib/pengine/complex.c
lib/pengine/group.c
lib/pengine/native.c
lib/pengine/pe_actions.c
lib/pengine/pe_output.c
lib/pengine/unpack.c
lib/pengine/utils.c
tools/crm_resource_runtime.c

This is part of a project to merge the functionality of libpe_status and libpe_rules into libcrmcommon, bringing it up to current guidelines in the process

Move enum pe_obj_types to libcrmcommon

---

python/Makefile.am

The tests and the Makefiles might be in different locations.  For instance, built Makefiles could end up in a build directory while the test files themselves (which do not require building) stay in the source directory.
Note that if we ever write python tests that require building (whose filenames end with .in, for instance) then we will need to augment the paths searched.
Fixes T693

Test: python: Specify a path to python tests.

---

daemons/controld/controld_election.c
daemons/controld/controld_fsa.c
daemons/controld/controld_join_client.c
daemons/controld/controld_messages.c
lib/common/mainloop.c
lib/common/schemas.c

Anything that's been commented out since early last decade (or before) is clearly not important enough to get around to figuring out, so it's cut.  Other uses remain, including a bunch that are commented out because we're waiting on a compatibility break.

Refactor: Remove code commented out with "#if 0".

---

agents/ocf/HealthCPU.in

The attrd_delay parameter is added to allow the user to specify the delay time freely. And，According to attrd_upater -h, -B can change the value of an attribute and the value of the -d parameter, while -U can only change the value of an attribute.

Add the parameter of dampening and fix attrd_updater command

---

include/pacemaker-internal.h
include/pacemaker.h
include/pcmki/pcmki_agents.h
lib/pacemaker/Makefile.am
lib/pacemaker/pcmk_agents.c
tools/crm_resource.c

This is the same functionality as "crm_resource --list-agents", but in a pair of public and private functions.  crm_resource has then been modified to just call the private function instead of doing this on its own.
Ref T44

API: libpacemaker: Add function for listing resource agents.

---

include/crm/pengine/internal.h
lib/pacemaker/pcmk_sched_migration.c
lib/pacemaker/pcmk_sched_primitive.c
lib/pengine/pe_actions.c
lib/pengine/unpack.c

`pcmk__create_migration_actions()` could benefit from further reorganization IMO. However, the changes I wanted to make involved creating the `migrate_from` action before the `migrate_to` action. That changed test outputs (the action numbers and the order in which actions appeared in the summary).
The function is clear enough as-is, so it's not worth sorting through all that to figure out whether the changes are meaningful.

Minor cleanup of some action code

---

daemons/based/based_callbacks.c
daemons/based/based_messages.c
daemons/based/pacemaker-based.c
daemons/based/pacemaker-based.h

Drop unused `logger_out`
I missed this in #3222

Refactor: based: Use new XML logger functions

---

Makefile.am
python/Makefile.am

See the substantial comments in the Makefile.am for the reason.
With this done, we can get rid of the additional path added to PYTHONPATH as well as get rid of trying to run tests out of separate directories.  Passing both on the command line was always a bug anyway, and that bug was disguising the underlying problem, resulting in no python tests actually being run.

Build: python: Fix python tests when there's a separate build directory

---

cts/cli/regression.daemons.exp
cts/scheduler/summary/migrate-fencing.summary
daemons/controld/controld_join_dc.c
daemons/controld/controld_membership.c
daemons/controld/controld_messages.c
daemons/controld/controld_te_utils.c
doc/sphinx/Pacemaker_Explained/options.rst
include/crm/cluster.h
include/crm/cluster/compat.h
include/crm/common/nodes.h
include/crm/crm.h
include/crm/msg_xml.h
include/crm/msg_xml_compat.h
include/crm_internal.h
lib/cluster/cluster.c
lib/cluster/membership.c
lib/common/ipc_controld.c
lib/pacemaker/pcmk_injections.c
lib/pacemaker/pcmk_output.c
lib/pengine/common.c
lib/pengine/pe_output.c
lib/pengine/unpack.c

Allow node-pending-timeout to be set to 0 to disable the timeout, raise the default to 2 hours, and avoid fencing nodes due to node-pending-timeout when they are leaving the cluster rather than joining.

Improve handling of node-pending-timeout

---

daemons/controld/controld_cib.c
include/crm/cib/cib_types.h
lib/cib/cib_client.c
lib/cib/cib_file.c
lib/cib/cib_native.c
lib/cib/cib_remote.c

We avoid dropping `cib_internal_op()` from `attrd` until after #3229 is merged. We cannot drop it from `cibadmin.c` (the only other non-library caller) because we need the granularity for other reasons than setting the user.

New cib_api_operations_t:set_user() method

---

lib/common/patchset.c
lib/common/schemas.c

Node types other than document, element, attribute, and comment shouldn't occur in a CIB, and they don't get a `_private` member created by `xml.c:new_private_data()`. Pacemaker strips out text nodes from a CIB and should ignore or throw errors on other unexpected node types.
This allows us to remove some hack code from `schemas.c:apply_transformation()`. It's unclear why that "emergency" code was needed in the first place; no reproducer notes were given.
Even immediately before it was added, regression tests ran fine (including `xml/regression.sh`). We've been unable to reproduce a crash with current code with either the `cts-cli` upgrade test (which includes a transformation using `upgrade-2.10.xsl`) or the `xml/regression.sh` test. As far as we can tell, Pacemaker always strips out …

Low: libcrmcommon: Ignore text nodes when creating XML patchset

---

daemons/controld/controld_callbacks.c
daemons/controld/controld_te_utils.c
lib/pengine/unpack.c

The node-pending-timeout is intended to apply only when the node is joining the cluster, not when it is leaving. Avoid enforcing it for leaving nodes by setting their in_ccm to 1 (rather than a timestamp) when they leave CPG. This will cause the scheduler to ignore node-pending-timeout (since it appears the same as a legacy node_state entry).
This does mean that if someone stops Pacemaker (but not the cluster layer) on a node, then starts it again (without restarting the cluster layer), that node-pending-timeout will not apply in that case, either. But since that would likely be a system administrator doing manual troubleshooting, that's acceptable.
Fixes T695

Fix: controller: don't fence leaving nodes for node-pending-timeout

---

include/crm/pengine/internal.h
lib/pacemaker/pcmk_sched_actions.c
lib/pacemaker/pcmk_sched_group.c
lib/pacemaker/pcmk_sched_migration.c
lib/pacemaker/pcmk_sched_ordering.c
lib/pacemaker/pcmk_sched_probes.c
lib/pacemaker/pcmk_sched_recurring.c
lib/pacemaker/pcmk_sched_resource.c
lib/pengine/failcounts.c
lib/pengine/pe_actions.c
lib/pengine/pe_digest.c
lib/pengine/pe_notif.c
lib/pengine/unpack.c
tools/crm_resource_runtime.c

Previously, custom_action() took an argument for whether the action should be added to the transition graph or not. Callers that passed FALSE just needed to unpack the action configuration XML and didn't really need the entire action. Refactor and expose the action unpacking functions so that those callers can get just what they need, and custom_action() can always add the action to the graph.
This will help make T381 (per-action failure timeouts) easier.

Make unpacking action configuration more efficient

---

cts/cli/regression.daemons.exp
daemons/controld/controld_control.c
doc/sphinx/Pacemaker_Explained/options.rst
lib/pengine/common.c

Hi All,
This PR follows the next PR and changes the default value of node-pending-timeout to 0.
- https://github.com/ClusterLabs/pacemaker/pull/3254
Best Regards,

Mid: controld/schedulerd: Change the default value of node-pending-timeout to 0.

---

INSTALL.md
configure.ac
lib/common/schemas.c
lib/common/xml.c

xmlLoadExtDtdDefaultValue should be replaced by the XML_PARSE_DTDLOAD parser option. However, we don't call any function that accepts parser options where we currently use xmlLoadExtDtdDefaultValue. We also don't use an xmlParserCtxt, so we can't call xmlCtxtUseOptions(). (There's no analog for xmlRelaxNGParserCtxt.)
xmlSubstituteEntitiesDefault() should be replaced by XML_PARSE_NOENT. Similarly, we don't call any function that accepts parser options where we currently use xmlSubstituteEntitiesDefault().
xmlLineNumbersDefault() is always enabled by the modern parser API.
xmlParseFile() should be replaced by xmlReadFile(). Here we use a NULL encoding and no options.
Note that the "new" or "modern" libxml2 parser API was released over 20 years ago, and we already use it in other places. So …

Fix: libcrmcommon: Drop deprecated libxml2 symbols

---

configure.ac
lib/common/crmcommon_private.h
lib/common/schemas.c
lib/common/tests/Makefile.am
lib/common/tests/schemas/Makefile.am
lib/common/tests/schemas/pcmk__xml_find_x_0_schema_index_test.c

* Lots of comments to explain how it works.
* Walk the list backwards, stopping on the first one in the major version series.  This means the first one no longer has to be X.0.
* Require that known_schemas be non-NULL.
* Don't use the returned index to also mean we've found something since that means if the index we actually want to return is 0, the function will have to run every time.

Refactor: libcrmcommon: Improve xml_find_x_0_schema_index.

---

cts/cli/regression.acls.exp
cts/cli/regression.tools.exp
tools/cibadmin.c
tools/crm_diff.c
tools/crm_ticket.c

c63a898 introduced a patch that uses pcmk__xml2fd to output XML objects. This function uses libxml's buffered output, meaning that we are now mixing libxml and stdlib output functions which have different opinions on buffering.
As a result, tools that output XML in addition to regular output may now see the order of output changed, potentially in confusing ways.
For tools that are using formatted output, it's okay to continue to call pcmk__xml2fd.  The XML formatted output object will use this for all its output (see xml_finish) so we're not mixing library calls.  The other formatted output objects only use stdlib output functions, so we're not mixing library calls there either.
This patch therefore only reverts the portion in the tools/ directory, as well as changes the affected test …

Med: tools: Fix a regression in tool XML output.

---

doc/sphinx/Clusters_from_Scratch/cluster-setup.rst
doc/sphinx/Pacemaker_Administration/alerts.rst
doc/sphinx/Pacemaker_Administration/configuring.rst
doc/sphinx/Pacemaker_Explained/acls.rst
doc/sphinx/Pacemaker_Remote/baremetal-tutorial.rst
doc/sphinx/Pacemaker_Remote/kvm-tutorial.rst
doc/sphinx/conf.py.in

And use substitutions where possible for hacluster and haclient.

Doc: Pacemaker Explained: Fix CIB_user default

---

daemons/attrd/attrd_cib.c

73b8c033 modified attrd to use a CIB transaction in attrd_write_attribute(). However, attribute-delete requests had no effect because "/cib" was missing from the CIB delete request's XPath.
Fixes T732

Fix: attrd: Regression in transient attr deletions

---

cts/cli/regression.tools.exp
cts/cts-cli.in

Multi-line commands -- for example, those containing a multi-line string argument -- aren't parsed correctly. All lines after the first appear in the output (as $app), with everything after the first space (if any) removed by sed. This caused a ton of whitespace in the output of a couple of recently added crm_verify commands and caused the summary "Passed" lines to print incorrectly.

Test: cts-cli: Use only the first line of cmd in output

---

agents/ocf/SysInfo.in
lib/common/attrs.c

We can use either the first commit ("Check correct env vars") or the second two commits ("Drop pcmk__node_attr_target" and "Use ocf_attribute_target"). We'll drop whichever one(s) we don't use.
The last commit ("Use attrd_updater dampen delay in SysInfo") is something found incidentally.
I haven't combed through commits 2 and 3 as closely as I should to check for errors. We can do that after further discussion of which direction we want to go.
Fixes [T733](https://projects.clusterlabs.org/T733).

Fix: libcrmcommon: pcmk__node_attr_target() checks wrong env variables

---

daemons/based/based_callbacks.c

939a408c, 8e9e6642, and 618e77d7 caused the CIB version attribute values to get fetched too early in `cib_process_request()`. `cib_process_command()` can change them.
This resulted in corruption (probably affecting only logging) after some commands, with garbage values being logged. For example:
```
info: Completed cib_modify operation for section nodes: OK (rc=0, origin=laptop/crmd/4, version=<81>rcT.!^K9^H<9d>U.1^K9^H<9d>U)
```
We need to fetch the values after `cib_process_command()`. Here we do it immediately before use.

Log: based: Fix CIB version values

---

daemons/attrd/attrd_attributes.c
daemons/controld/controld_execd.c
daemons/controld/controld_fencing.c
daemons/fenced/fenced_cib.c
daemons/fenced/fenced_remote.c
daemons/fenced/pacemaker-fenced.c
daemons/fenced/pacemaker-fenced.h
daemons/pacemakerd/pcmkd_subdaemons.c
lib/common/strings.c
lib/common/tests/strings/crm_get_msec_test.c
lib/pengine/pe_actions.c
lib/pengine/rules_alerts.c
tools/crm_resource.c
tools/stonith_admin.c

This has two main parts:
* Bounds-check the return value in callers, ensuring we don't overflow the data type where we want to store it.
* Make the body more maintainable.
In service of maintainability, I added a dynamically allocated buffer. It's not technically necessary, but it's MUCH easier to reason about what's happening this way.
We could use a fixed-size buffer based on the length of a long long if we assume it's always 64 bits -- which is not guaranteed by the standard. I don't want to have to think about edge cases involving truncation of the number or the units in an overly long input string.
I got rid of the pointer to where the number starts and how long the number is, as well as the check of the particular kind of whitespace character at the end of the string. I replaced all …

Some crm_get_msec() best practices

---

tools/crm_mon.c

This is easiest to observe when Pacemaker is stopping.
When crm_mon is running in interactive mode (the default) and the cluster is stopped, `crm_mon` crashes with a segmentation fault. This is a regression that was introduced in Pacemaker 2.1.0 by commit bc91cc5. However, for some reason the crash doesn't happen on all platforms. In particular, I can reproduce the crash on Fedora 38 and 39, but not on RHEL 9.3 or Fedora 37. This is independent of the Pacemaker version.
The cause is a use-after-free. In detail, it is as follows:
1. `crm_mon` registers a notification via its stonith API client for disconnect events. This notification will call either `mon_st_callback_event()` or `mon_st_callback_display()`, depending on the CLI options. Both of these callbacks call …

Fix: tools: crm_mon segfaults when fencer connection is lost

---

cts/cli/regression.daemons.exp
doc/sphinx/Pacemaker_Explained/cluster-options.rst
lib/common/options.c

* "changeset" -> "revision"
* "messaging stack" ->  "messaging layer"
* "failure timeouts" -> "failure-timeout settings"
* Clarify descriptions of `fence-reaction` and `stonith-watchdog-timeout`
* Synchronize descriptions of `stonith-watchdog-timeout` between metadata and Pacemaker Explained.

Doc: libcrmcommon, Pacemaker Explained: improve descriptions of cluster options

---

tools/crm_attribute.c

This happens because pcmk__node_attr_target() returns its argument if its argument is NULL, "auto", or "localhost" and no relevant environment variables are found. Then crm_attribute frees the return value, makes a copy of it, and assigns it back to options.dest_uname.
The fix is to check whether the return value is equal to the argument.
Fixes RHEL-23065

Fix: tools: crm_attribute emits garbage for --node localhost or auto

---

GNUmakefile
rpm/Makefile.am
rpm/rpmlintrc

First, we were using the wrong command line option.  It should be "-r rpmlintrc".  Second, everything we have in the rpmlintrc file at the moment is not even necessary, causing rpmlint to throw errors about unused filters.
We can later bring the file back if it's necessary, but just removing it causes rpmlint to pass.
Fixes T760

Build: Remove the rpmlintrc file.

---

cts/cli/regression.acls.exp
cts/cli/regression.daemons.exp
cts/cli/regression.rules.exp
cts/cli/regression.tools.exp
daemons/based/pacemaker-based.c
daemons/controld/pacemaker-controld.c
daemons/fenced/pacemaker-fenced.c
daemons/schedulerd/pacemaker-schedulerd.c
include/crm/common/options_internal.h
include/crm/common/xml.h
include/crm/common/xml_compat.h
include/crm/common/xml_internal.h
lib/cib/cib_utils.c
lib/common/options.c
lib/common/output_log.c
lib/common/output_xml.c
lib/common/tests/xml/Makefile.am
lib/common/tests/xml/pcmk__xml_escape_test.c
lib/common/tests/xml/pcmk__xml_needs_escape_test.c
lib/common/xml.c
lib/common/xml_attr.c
lib/common/xml_display.c
lib/fencing/st_lha.c
lib/pengine/pe_output.c
lib/services/services_lsb.c
lib/services/systemd.c
po/zh_CN.po
tools/crm_rule.c

This part can stand on its own before we continue moving toward proper `pcmk__output_t` formatted output.

Formatted output for cluster options (part 1)

---

cts/cts-cli.in

Basically, always use test_assert_validate with --output-as=xml.

Test: cts-cli: Validate output when using --output-as=xml.

---

lib/services/systemd.c
lib/services/upstart.c

078e007c changed a few double quotes to single quotes in the fake metadata for systemd and upstart agents. This causes a pattern match to fail in cts-lab.
A better fix is to create and dump real XML instead of substituting into a string. This gets the job done for now.

Fix: libcrmservice: Revert single quotes to double quotes in metadata

---

lib/pengine/Makefile.am

Now that the code being tested has moved into libcrmcommon, these variables are no longer needed and cause autotools to raise warnings.
This should have been done in 3af5699c7de52880e373815c0322875a2068ba75.

Build: libpe_rules: Remove unneeded build stuff for libpe_rules_test.

---

daemons/pacemakerd/pacemakerd.c
lib/lrmd/lrmd_output.c
lib/pacemaker/pcmk_output.c
tools/crm_resource_print.c

Any custom output message that calls pcmk__output_create_parent should later call pcmk__output_xml_pop_parent.  Without doing this, any other XML nodes created after the custom message will be created with an unexpected parent.
Big caveat:  The "node" custom message works this way on purpose, however.  It counts on the fact that it creates the parent and exits, then other things happen, and then the parent is popped.  I can't convince myself that the parent is correctly being popped in every instance but that looks like the intent.

Refactor: libraries: Call pcmk__output_xml_pop_parent.

---

tools/crm_attribute.c

Previously (perhaps as far back as when crm_attribute was introduced) we haven't done any validation on whether an attribute name was given along with the -v option specifying the new attribute value.  Instead we just asserted.
Instead, check that a name or pattern was given and if not, display an error message.  The other two asserts can go, as well.  options.type will always be set by the call to set_type(), and options.attr_value will be set if -v was given on the command line.
Fixes T765

Low: tools: Fix argument validation for crm_attribute update.

---

lib/common/crmcommon_private.h

So that they are correctly handled on 32-bit systems.
Previously unit test would fail on 32-bit systems:
```
> lib/common/tests/xml/crm_xml_init_test
TAP version 13
1..8
ok 1 - buffer_scheme_test
not ok 2 - create_document_node
```

Fix: libcrmcommon: use uint32_t for 32-bit magic numbers

---

lib/common/tests/xml/pcmk__xml_escape_test.c
lib/common/xml.c

Fixes regression introduced in c6d9cea9.
That commit introduced `pcmk__xml_escape()`, which (among other things) escapes non-printing characters as their hexadecimal character references. However, a prefix of `"#x"` (instead of only `"#"`) is required to indicate that the number is in hex rather than decimal.

Fix: libcrmcommon: Escape XML non-printing characters correctly as hex

---

cts/cli/regression.tools.exp
cts/cts-cli.in
include/crm/common/xml_names.h
include/crm/crm.h
lib/pacemaker/pcmk_output.c
lib/pengine/pe_output.c
tools/crm_ticket.c
xml/Makefile.am
xml/api/crm_mon-2.35.rng
xml/api/crm_ticket-2.35.rng
xml/api/ticket-2.35.rng

This also includes the patch from #3356, but I assume I'll have to rebase this a couple times so I'm not worried about that.
One significant thing to note is that I don't think the new ticket schema is complete.  There's a block in the ticket_xml function that adds arbitrary key/value pairs as attributes to the ticket's XML node.  I'm not sure what all could be in those pairs, so at the moment I've just left it out of the schema.  I'll have to add something, though, and if they can be potentially anything, the schema is a little less useful.

Convert crm_ticket to use formatted output

---

tools/cibsecret.in

When python program calling cibsecret with a small terminal width, the command `ps -ef | grep '[p]acemaker-controld'` will return 1, see
```
>>> cmd = "ps -ef | grep '[p]acemaker-controld' >/dev/null"
>>> # When terminal width is small
>>> subprocess.call(cmd, shell=True)
1
>>> # When terminal is big enough
>>> subprocess.call(cmd, shell=True)
0
```
Use 'ps axww' can avoid this issue, also for BSD environment

Fix: cibsecret: Use 'ps axww' to avoid truncating issue

---

cts/cli/regression.daemons.exp
daemons/fenced/pacemaker-fenced.c
include/crm/common/output_internal.h
lib/common/options.c
lib/common/options_display.c
lib/common/output_xml.c

We've recently deprecated daemon metadata commands in favor of `crm_attribute --list-options=cluster`, using the `"option-list"` message formatter function. Along the way, we've made a number of changes to clean up and standardize the output.
Unfortunately, some external tools (for example, `pcs` and `crmsh`) depend on very specific strings in the old output format. For example, `pcs` ignores the `<content>` element containing the list of possible values; instead it relies on the `"  Allowed values:"` string in the `<longdesc>`. It also validates the output against its own custom version of the OCF resource agent schema (many agents don't conform to the official one), which does not allow the `"advanced"` and `"generated"` attributes.
`crmsh` has some similar dependencies, though I'm not …

Fix: libcrmcommon: Revert daemon metadata output to pre-3e84f934

---

INSTALL.md
python/pacemaker/_cts/watcher.py

At least as of systemd v254, journalctl has the following bug: if `--after-cursor`, `--until`, and `--lines` options are all three used, the `--until` option is ignored.
This results in an infinite loop in `LogWatcher.look()`. When we reach the timeout, we call `set_end()` on the `JournalObj` to set a limit timestamp, so that we can get all remaining logs that were created until the timeout expired. Then we run the following repeatedly until we reach the limit (as determined by the output containing only a cursor):
```
journalctl --after-cursor=X --until=self.limit --lines=200
```
Due to the bug, the command above will continue to yield log messages indefinitely. As long as we keep finding log messages and adding them to our line cache, we'll keep looping.
Here we work around the issue by …

Fix: cts-lab: Parse log watch timestamps on exerciser side

---

doc/sphinx/Pacemaker_Explained/nodes.rst
include/crm/common/xml_internal.h
lib/common/crmcommon_private.h
lib/common/tests/xml/pcmk__xml_escape_test.c
lib/common/tests/xml/pcmk__xml_needs_escape_test.c
lib/common/xml.c
lib/common/xml_attr.c
lib/common/xml_display.c
lib/common/xml_io.c
lib/fencing/st_lha.c
lib/pacemaker/pcmk_output.c
lib/pengine/pe_output.c
lib/services/services_lsb.c
lib/services/systemd.c
tools/crm_attribute.c

Regression introduced by c6d9cea9, sort of.
Before that commit, newlines and tabs were escaped as `"\n"` and `"\t"`, respectively. These are not valid XML escape sequences.
We made the decision not to escape newlines and tabs when we added the `pcmk__xml_escape()` function, with the caveat that the "right" answer was unclear:
> If not, the XML will be more visually understandable, but conformant XML parsers will treat the newline as a space (for example, if something extracts the text and displays it to the user). If we do, the parser case may be closer to our original intent, but the XML is harder to read, and it may not be appropriate (for example, the parsing tool might prefer to do line wrapping of a textual paragraph on its own)." …

Fix: libcrmcommon: Escape newlines and tabs in XML attribute values

---

cts/cli/regression.access_render.exp
cts/cts-cli.in

I find it strange that tony is able to see the ACLs in the output, since he's denied any permissions on `<acls>`. I changed "tony" to "reid" (my username), and the output is identical except for the name change... so it's not about which user is running the test.
I see that the test was disabled in the first place via 326eb9f6 due to unspecified output mismatches that appear only in CI... so we'll see if they happen again, and document them if so.

Enable access-render test in cts-cli

---

daemons/fenced/fenced_remote.c

Conventionally it's signed long under the GNU C library, which is 32 bits on 32-bit architectures, but Glibc provides the __TIME_BITS==64 option, which makes it signed long long instead (64 bits) and makes no difference on 64-bit architectures [1].  This enables using the %lld conversion specifier uniformly across all supported architectures. This got exposed by Debian recently transitioning to 64-bit time_t [2].
[1] https://sourceware.org/glibc/wiki/Y2038ProofnessDesign
[2] https://wiki.debian.org/ReleaseGoals/64bit-time

Log: fencer: always format time_t values as long long

---

cts/cli/regression.tools.exp
cts/cli/regression.upgrade.exp
cts/cli/regression.validity.exp
cts/cts-cli.in
daemons/fenced/fenced_scheduler.c
doc/sphinx/Pacemaker_Explained/alerts.rst
doc/sphinx/Pacemaker_Explained/constraints.rst
doc/sphinx/Pacemaker_Explained/fencing.rst
doc/sphinx/Pacemaker_Explained/local-options.rst
doc/sphinx/Pacemaker_Explained/reusing-configuration.rst
doc/sphinx/Pacemaker_Explained/rules.rst
doc/sphinx/Pacemaker_Explained/utilization.rst
include/crm/common/scheduler_internal.h
include/crm/pengine/internal.h
lib/common/rules.c
lib/pacemaker/pcmk_sched_constraints.c
lib/pacemaker/pcmk_sched_location.c
lib/pengine/complex.c
lib/pengine/pe_actions.c
lib/pengine/status.c
tools/crm_resource.c
tools/crm_resource.h
tools/crm_resource_runtime.c
xml/alerts-3.10.rng
xml/constraints-3.10.rng
xml/nodes-3.10.rng
xml/nvset-3.10.rng
xml/options-3.10.rng
xml/resources-3.10.rng
xml/rule-3.10.rng

This includes a number of fixes in rule processing, deprecates some more rule syntax, prepares the schemas for dropping deprecated syntax, and overhauls the rules documentation.

Bring rule schemas, documentation, and code in alignment

---

lib/pengine/complex.c

Previously a resource ID would be always logged as "(null)" since it was not assigned a value yet.

Log: scheduler: correctly log resource IDs of the deprecated classes

---

lib/pengine/complex.c

Being built to be compatible with 2.0 series doesn't change the fact that the resource classes Nagios and Upstart are deprecated and will be removed in a future release. Users probably better get notified anyways.

Log: scheduler: deprecate Nagios and Upstart resources even if built with --enable-compat-2.0

---

lib/common/xml.c

`mark_xml_changes()` with `check_top=true` may free `new_child` via `pcmk__apply_creation_acl()`. Calling `pcmk__xml_next(new_child)` after that is a use-after-free error. This caused a seg fault on FreeBSD.
There are other opportunities to refactor `mark_xml_created()` and change-tracking in general, and I bet we can avoid `check_top` and make things easier to reason about. This should fix the immediate issue.

Fix: libcrmcommon: Avoid use-after-free in mark_xml_changes()

---

include/crm/common/logging_internal.h
lib/common/roles.c
lib/pengine/bundle.c
lib/pengine/clone.c
lib/pengine/complex.c

I think there's another PR out there at the moment that also touches the `pcmk__wo_` constants, so whichever goes second will have to make some changes there.  Also note that this does not address deprecating `crm_map_element_name`, which is also going to be in a separate PR.

Warn on deprecated CIB syntax

---

lib/common/tests/schemas/Makefile.am

_SOURCES means something to autoconf and results in the following error messages:
lib/common/tests/schemas/Makefile.am:54: warning: variable 'LINK_SOURCES' is defined but no program or
lib/common/tests/schemas/Makefile.am:54: library has 'LINK' as canonical name (possible typo)

Low: Build: Rename LINK_SOURCES to LINK_FILES.

---

include/Makefile.am

We've been shipping a publically available API in the library for a litle while now, but there's been no header that allows access to that API.

Build: libpacemaker: Start shipping the pacemaker.h file.

---

include/crm/pengine/internal.h
lib/pengine/bundle.c
lib/pengine/clone.c
lib/pengine/group.c
lib/pengine/native.c
lib/pengine/pe_output.c

This function doesn't need to take a count of pairs.  In fact, once it takes a NULL terminator, it's just a wrapper around pcmk__xe_set_propv.

Refactor: scheduler: Simplify pe__name_and_nvpairs_xml.

---

cts/cli/regression.tools.exp
lib/pacemaker/pcmk_output.c
tools/attrd_updater.c
tools/crm_attribute.c

This gets rid of the special output message in crm_attribute by making the one in the library support the same output format.  There's still the node-attribute message elsewhere, but I'm not sure it makes sense to combine these.  They take vastly different arguments, and the node-attribute message has a bunch of stuff about connectivity status.
I wonder if we might want to split the connectivity stuff out into its own message, and then rename both attribute and node-attribute to something that sounds less confusing.

Combine attribute formatted output messages

---

python/Makefile.am
python/pacemaker/_cts/watcher.py

* Disable older warnings that way occur depending on which version of pyflake you have installed.
* Single-line docstrings should be on a single line.

Refactor: python: Fix a couple minor pyflake issues

---

fuzzers/README.md
fuzzers/cib_file_fuzzer.c
fuzzers/iso8601_fuzzer.c
fuzzers/strings_fuzzer.c
fuzzers/utils_fuzzer.c

Adds OSS-Fuzz integration to enable continuous fuzzing of Pacemaker.
The corresponding PR on OSS-Fuzz is here: https://github.com/google/oss-fuzz/pull/11978

OSS-Fuzz integration

---

lib/fencing/st_lha.c

Regression introduced by acfbd5e01 (not yet released).
A st_info_fn() may free any existing output buffer every time when it's called like:
https://github.com/ClusterLabs/cluster-glue/blob/5cc622b4/lib/plugins/stonith/external.c#L612
So we should copy the output every time.

Fix: libstonithd: avoid use-after-free when retrieving metadata of Linux-HA fence agents

---

tools/cibadmin.c

Should use --score.
Also change formatting of --score option documentation. It appeared correctly in help output, but the man page generation yielded ugly indentation.
The new formatting looks worse (but passable) for --help output and looks better (previously unpassable) for man page.

Doc: tools: cibadmin incorrect example for score update

---

lib/fencing/st_lha.c

Fix: libstonithd: free escaped metadata descriptions with g_free()

---

include/crm/msg_xml_compat.h

We have to keep one single constant (`XML_TAG_CIB`) because it's used by sbd. Since we're at a compatibility break anyway, perhaps we could move it to `xml_compat.h` and get rid of `msg_xml_compat.h`.
There are a LOT of commits, but they're all as simple as can be. I'm putting them all in one PR in case you want to power through and avoid an extra build clogging up CI. However, we can break it up if you'd like.

Drop almost all of msg_xml_compat.h

---

lib/fencing/st_lha.c

Backport https://github.com/ClusterLabs/pacemaker/pull/3476 and https://github.com/ClusterLabs/pacemaker/pull/3492 to 2.1
Regression introduced by acfbd5e01 (not yet released).
A st_info_fn() may free any existing output buffer every time when it's called like:
https://github.com/ClusterLabs/cluster-glue/blob/5cc622b4/lib/plugins/stonith/external.c#L612
So we should copy the output every time.

[2.1] Fix: libstonithd: avoid use-after-free when retrieving metadata of Linux-HA fence agents

---

lib/pacemaker/pcmk_output.c

Introduced by 8d12f32efa06878778c86045fb01ee2d0bbe05ab, but never in a final release.

Low: libpacemaker: Add spaces back to attrd_updater query output.

---

lib/pacemaker/pcmk_injections.c

The attribute name of an nvpair for this should be "value".
Regression introduced by ce3a9863df (not yet released).

Fix: libpacemaker: correctly retrieve any existing fail-count for increment

---

lib/pacemaker/pcmk_injections.c

Backport https://github.com/ClusterLabs/pacemaker/pull/3510 to 2.1
The attribute name of an nvpair for this should be "value".
Regression introduced by ce3a9863df (not yet released).

[2.1] Fix: libpacemaker: correctly retrieve any existing fail-count for increment

---

cts/cli/regression.tools.exp
tools/crm_simulate.c

Somewhere along the line, we changed the interactive behavior of crm_simulate to not enable fancy text formatting.  This is necessary for non-interactive use (like when running cts-scheduler), but for interactive use, it is hard to read.
Change the conditional on when fancy text is enabled to be always, as long as we are not showing scores in quiet mode.  This seems to be the combination that differentiates interactive use from regression test use.
Fixes T833

Low: tools: Don't skip formatting if running crm_simulate interactively.

---

lib/common/digest.c

MD5 is not a supported algorithm when FIPS is enabled.  Luckily, we are not using it for any security purposes - only for calculating hashes of XML blobs.  In order to use the MD5 algorithm, we have to temporarily disable and then re-enable the FIPS check in gnutls which provides macros for this purpose.
We were previously not seeing this problem because we were using gnulib, which is not FIPS aware.  The switch to gnutls causes the problem.
Tested by running "make check" on a system that was installed with the fips=1 kernel command line parameter, which resulted in a segfault.  The addition of this patch causes the check to succeed.

Med: libcrmcommon: Disable FIPS mode when running md5sum check.

---

INSTALL.md
configure.ac
include/portability.h

The macros needed to enable/disable FIPS mode were not introduced until 3.6.2.  Pacemaker supports building on systems as late as Ubuntu 18, which has 3.5.18.
So, make 3.5.18 the required version and add a note that we really do prefer 3.6.2.  Then, add a configure test and compability macros to handle the gap between the minimum required version and the preferred version.
This means that anyone with gnutls >= 3.5.18 and < 3.6.2 cannot run Pacemaker in FIPS mode.  In practice, this should not be a problem because it only affects the following people:
* Ubuntu 18 users - The commits that switched us to using gnutls were only on the main (Pacemaker 3) branch, and we do not expect that Ubuntu will backport Pacemaker 3 to that release.
* People building from source - No one that cares about …

Med: Build: Update gnutls build requirements.

---

cts/cli/regression.tools.exp
tools/crm_verify.c

The output of crm_verify no longer distinguished configuration warnings from errors as brought up from:
https://github.com/ClusterLabs/pacemaker/pull/3266#discussion_r1636411072
Regression introduced in 2.1.7 by 0c5a32624a
This commit fixes it by splitting output_config_issue() into separate error and warning handlers, and add the "warning:" or "error:" prefix to the message.
Fixes T834

Fix: tools: crm_verify distinguishes configuration warnings and errors

---

cts/cli/regression.tools.exp
tools/crm_verify.c

Backport https://github.com/ClusterLabs/pacemaker/pull/3538 to 2.1
The output of crm_verify no longer distinguished configuration warnings from errors as brought up from:
https://github.com/ClusterLabs/pacemaker/pull/3266#discussion_r1636411072
Regression introduced in 2.1.7 by 0c5a32624a
This commit fixes it by splitting output_config_issue() into separate error and warning handlers, and add the "warning:" or "error:" prefix to the message.
Fixes T834

[2.1] Fix: tools: crm_verify distinguishes configuration warnings and errors

---

include/pcmki/pcmki_verify.h
lib/pacemaker/pcmk_verify.c
tools/crm_verify.c

Currently, if an updated schema is acceptable, the old CIB XML is freed by pcmk_update_configured_schema() and then again by crm_verify.c:main(). Here we fix this by passing a pointer-to-pointer into pcmk__verify(), so that crm_verify gets a pointer to the new XML object instead of to the freed one.
This fixes a regression introduced by a744f1a8.

Fix: tools: Don't double-free XML in crm_verify after schema update

---

include/pcmki/pcmki_verify.h
lib/pacemaker/pcmk_verify.c
tools/crm_verify.c

Currently, if an updated schema is acceptable, the old CIB XML is freed by pcmk_update_configured_schema() and then again by crm_verify.c:main(). Here we fix this by passing a pointer-to-pointer into pcmk__verify(), so that crm_verify gets a pointer to the new XML object instead of to the freed one.
This fixes a regression introduced by a744f1a8.

[2.1] Fix: tools: Don't double-free XML in crm_verify after schema update

---

lib/cluster/cluster.c

Regression introduced by c63acbadd6 (not yet released).
It also removes an unexpected "break" if not SUPPORT_COROSYNC.

Fix: libcrmcluster: use local hostname for node name if not configured in corosync

---

lib/cluster/cluster.c

Backport https://github.com/ClusterLabs/pacemaker/pull/3547 to 2.1
Regression introduced by c63acbadd6 (not yet released).
It also removes an unexpected "break" if not SUPPORT_COROSYNC.

[2.1] Fix: libcrmcluster: use local hostname for node name if not configured in corosync

---

lib/cluster/cluster.c

sbd doesn't call the constructor (pcmk_cluster_new()) to create the pcmk_cluster_t object, as it should. Instead, it uses a static object. As a result, the priv member has not been allocated when sbd calls crm_cluster_connect().
Fixes regression (for sbd) introduced in f0df6261. Callers that use the pcmk_cluster_new() constructor were unaffected. This regression did not make it into any release.
Reported by @gao-yan

Fix: libcrmcluster: Ensure priv member exists in crm_cluster_connect()

---

ChangeLog
etc/sysconfig/pacemaker.in
include/crm/common/cmdline_internal.h
lib/common/remote.c

The ChangeLog update for rc2 was accidentally applied to the 2.1 branch first, so forward-port it here. Also address a couple of compatibility issues ahead of the 3.0.0 release.

Prepare for 2.1.8-rc3 release

---

include/crm/cib/internal.h
lib/cib/cib_utils.c
tools/cibadmin.c
tools/crm_attribute.c
tools/crm_node.c
tools/crm_resource.c
tools/crm_shadow.c
tools/crm_ticket.c

... up to 5 times.
Previously CIB clients wouldn't retry signon upon an EAGAIN and directly return a connection error, which made them not resilient enough.
A new function cib__signon_attempts() is added for the purpose. It's similar to how it's done in pcmk__connect_ipc().
Apparently there's a plan on converting CIB manager to use pcmk_ipc_api_t as client interface
https://projects.clusterlabs.org/T143
But I think it still makes sense to make the current code base deal with such a situation.
Let's take a look if it makes sense. I'll ask the user to try it out as well.

Fix: tools: CIB clients retry signon upon an EAGAIN error

---

include/pcmki/pcmki_status.h
lib/pacemaker/pcmk_status.c
tools/crm_mon.c
tools/crm_mon.h

I stumbled across this task while dropping support for Nagios resources (the `--simple-status` machinery is for Nagios, but unrelated to resources).
Closes T707

Drop deprecated crm_mon options

---

tests/test-headers.sh

When building under mock, CXX is always set even though the program is not present in the build root because we do not BuildRequires it.  So, we additionally need to check that the program exists.

Test: test-headers.sh: Modify the C++ check again.

---

include/crm/cib/internal.h
lib/cib/cib_utils.c
tools/cibadmin.c
tools/crm_attribute.c
tools/crm_node.c
tools/crm_resource.c
tools/crm_shadow.c
tools/crm_ticket.c

... up to 5 times.
Backport https://github.com/ClusterLabs/pacemaker/pull/3546 to 2.1
Previously CIB clients wouldn't retry signon upon an EAGAIN and directly return a connection error, which made them not resilient enough.
A new function cib__signon_attempts() is added for the purpose. It's similar to how it's done in pcmk__connect_ipc().

[2.1]  Fix: tools: CIB clients retry signon upon an EAGAIN error

---

cts/cts-scheduler.in

A couple date-related scheduler regression tests accept arguments. When running all the tests in one go, the regression test grabs the arguments out of the SchedulerTest object automatically.
If you run these tests individually (using --run), it is expected that you will provide the command line arguments yourself.  If you don't, the tests will fail.  Instead, it should default to grabbing the arguments out of the SchedulerTest object if you don't provide any on the command line.
Fixes T835

Low: CTS: Fix argument handling for certain scheduler tests.

---

lib/pengine/pe_output.c
tools/crm_mon_curses.c

scheduler->flags changed type in 5fe19612148, so change both the type we're passing to va_arg as well as the annotation.

Refactor: Change the type on the maint-mode message.

---

include/crm/lrmd.h
lib/lrmd/lrmd_client.c

We previously deprecated this behavior for pacemaker-2, this removes it from master.

Remove undocumented Pacemaker Remote key handling behavior

---

cts/cts-attrd.in

The bug introduced by 8d12f32efa06878778c86045fb01ee2d0bbe05ab was not caught by cts-attrd because it only occurred in text output mode, and cts-attrd only uses XML output mode.  This tests duplicates various existing queries in text mode.  While it's unlikely we will have that exact problem again in the future, it seems like a good idea to test the text output code as well.

Tests: cts: Add non-XML tests to cts-attrd.

---

include/crm/common/logging_internal.h
lib/common/rules.c
lib/common/tests/rules/pcmk__evaluate_attr_expression_test.c
lib/common/tests/rules/pcmk__evaluate_date_expression_test.c
lib/common/tests/rules/pcmk__evaluate_date_spec_test.c
lib/common/tests/rules/pcmk__evaluate_op_expression_test.c
lib/common/tests/rules/pcmk__evaluate_rsc_expression_test.c
lib/common/tests/rules/pcmk__unpack_duration_test.c
lib/common/tests/rules/pcmk_evaluate_rule_test.c
lib/pacemaker/pcmk_rule.c
lib/pacemaker/pcmk_sched_colocation.c
lib/pacemaker/pcmk_sched_tickets.c
lib/pacemaker/pcmk_sched_utilization.c
tools/crm_resource_ban.c

This breaks behavioral backward compatibility and so will not be backported to the 2.1 branch

Treat misconfigured rules as not passing

---

daemons/controld/controld_remote_ra.c

lrmd_event_new_client gets handled at the top of remote_lrm_op_callback and then the function returns, so there's no way for this block to be reached.

Refactor: daemons: Remove an unreachable block from controld.

---

include/crm/common/util.h

... so the one marked "deprecated" in util_compat.h is used

Doc: libcrmcommon: remove stray declaration

---

xml/api/crmadmin-2.25.rng
xml/api/crmadmin-2.4.rng

I think these always should have been present as options in the schema. Without them, crmadmin output does not validate.

Low: schemas: Add additional node types to the crmadmin schema.

---

include/crm/common/remote_internal.h
lib/common/remote.c
lib/lrmd/lrmd_client.c

I can't convince myself that this is completely correct.  My testing still shows the two remote connection resources starting serially, but I am wondering if it's because handle_remote_ra_exec is getting called several seconds apart for the two resources.  I'm not seeing anywhere in my patches where I'm still doing something in a blocking manner, however.

Perform gnutls handshake asynchronously

---

daemons/attrd/attrd_cib.c
include/crm/common/xml_internal.h
lib/common/patchset.c
lib/common/tests/patchset/pcmk__cib_element_in_patchset_test.c

This fixes a regression introduced by https://github.com/ClusterLabs/pacemaker/commit/20ad1a974d5dff9f9e1a84c01fd329596c6691f9.
If the CIB does not already contain an alerts element, creating a new alert requires creating the alerts element. This is included in the patchset as a create operation. (Adding a new alert to an existing alerts element is a modify operation.)
Prior to this commit, we were checking whether `cib_op="create"`. We should be checking whether `operation="create"`.
As a result, if a new alert was created in a CIB that did not previously contain an alerts element, the controller would not detect the change and would not process the new alert.
Fixes T865
Fixes RHEL-55458

Fix: libcrmcommon: Detect newly created alerts section

---

lib/cib/cib_utils.c

I'd prefer not to backport the unit tests or the move to libcrmcommon from #3624.
This fixes a regression introduced by 20ad1a9.
If the CIB does not already contain an alerts element, creating a new alert requires creating the alerts element. This is included in the patchset as a create operation. (Adding a new alert to an existing alerts element is a modify operation.)
Prior to this commit, we were checking whether cib_op="create". We should be checking whether operation="create".
As a result, if a new alert was created in a CIB that did not previously contain an alerts element, the controller would not detect the change and would not process the new alert.
Fixes T865
Fixes RHEL-55458

[2.1] Fix: libcrmcommon: Detect newly created alerts section

---

lib/pengine/rules.c

Previously, if the name attribute was set in an nvpair with id-ref, that name would override the name in the referenced nvpair. Now we ignore it instead.
A name in this position is already disallowed by the schema.

Feature: libpe_rules: Drop support for name with id-ref attribute

---

include/crm/common/logging_internal.h
lib/pacemaker/pcmk_sched_location.c

Instead, create multiple constraints or use a nested rule with boolean-op="or" in the top-level rule.
The schema already disallows multiple top-level location constraint rules.
Now, we ignore any top-level rules after the first one.

Feature: libpe_rules: Drop support for multiple top-level location rules

---

include/crm/common/nvpair.h

High: libcrmcommon: Include nvpair_compat.h in nvpair.h

---

python/pacemaker/_cts/clustermanager.py
python/pacemaker/_cts/tests/reattach.py

This has been broken since being introduced in 4b03268ade7.  Something in XML handling must have changed to cause it to start being a problem, but I don't see what.

Low: python: Fix sloppy XML in ctslab

---

cts/cli/regression.validity.exp
cts/cts-cli.in

Tests are currently breaking on debian-experimental (which uses a newer version of libxml2) because this prefix does not appear in the output.
This change should ensure the validity errors appear the same on all platforms (as long as the message itself doesn't change).

Test: cts-cli: Drop Relax-NG validity error prefixes

---

include/crm/common/logging_internal.h
include/crm/common/nodes_internal.h
include/crm/common/options_internal.h
lib/pengine/pe_output.c
lib/pengine/unpack.c

Ping nodes have been deprecated since 2.1.3. See commit 1478ee54 for more details.
This is already disallowed by the schema.
Closes T302

Feature: libpe_status: Drop support for ping nodes

---

cts/cli/regression.validity.exp
cts/cts-cli.in

Tests are currently breaking on debian-experimental (which uses a newer version of libxml2) because this prefix does not appear in the output.
This change should ensure the validity errors appear the same on all platforms (as long as the message itself doesn't change).
This is a backport of 1f696fc2b9fbba4d169a0b1003c16041006d5efd

[2.1] Test: cts-cli: Drop Relax-NG validity error prefixes

---

lib/common/output_text.c

Only text output mode is affected by this - other output formats write to a buffer, so an error there is likely a memory problem and should be asserted on.  Additionally, there are other places in text output where we assert on writing to out->dest - these are not affected either because we only allow dest to be a filename (or "-", but see below).
Strangely, text_info does not appear to be affected despite doing basically the same thing but on stdout.  This is the same reason why --output-to=- is not a problem.
Fixes T891

High: libcrmcommon: Don't assert on failure to write errors.

---

daemons/based/based_remote.c
include/crm/common/remote_internal.h
lib/cib/cib_remote.c
lib/common/remote.c

This breaks a bunch of patches out of #3633 since the remote CIB stuff seems to be a lot less sensitive.  I've tested this by running things as normal, and additionally by inserting a line into cib_remote_msg where pcmk__read_available_remote_data always returns EAGAIN.  The result of the latter test is that pacemaker-based logs other things happening in between the client starting authentication and that authentication eventually timing out.

Perform remote CIB operations asynchronously

---

tools/crm_resource_runtime.c

This fixes a regression introduced by 05e8f1b9 in 2.1.8.

[2.1] Fix: tools: crm_resource returns error on failed schema upgrade

---

daemons/pacemakerd/pcmkd_subdaemons.c
doc/sphinx/Pacemaker_Explained/local-options.rst
lib/cib/Makefile.am
lib/cluster/Makefile.am
lib/common/Makefile.am
lib/common/iso8601.c
lib/common/tests/iso8601/Makefile.am
lib/common/tests/iso8601/crm_time_add_seconds_test.c
lib/fencing/Makefile.am
lib/lrmd/Makefile.am
lib/pacemaker/Makefile.am
lib/pengine/Makefile.am
lib/services/Makefile.am
m4/version.m4

The first two (release info) commits are forward-ports from 2.1.9-rc1, to make it clear that 3.0.0 will contain everything in 2.1.9. (Once 3.0.0 is released, 2.1 release info will no longer be forward-ported.)
The rest are trivial issues found recently. They will be backported to 2.1 for 2.1.9-rc2.

Minor fixes

---

lib/common/ipc_attrd.c
tools/attrd_updater.c

Before, `attrd_updater -Q` would query all nodes when called by a user and the local node when called by a resource agent.  Now, the same command line will query only the local node when called by a user.  This can be modified by using -N to specify a node, or --all to specify all nodes.
Fixes T630

Feature: tools: Define behavior of attrd_updater -Q without -N

---

lib/pengine/pe_status_private.h
lib/pengine/status.c
lib/pengine/unpack.c

Rename to pcmk__validate_fencing_topology() and drop the scheduler argument, since we're not truly unpacking anything. Throw an error instead of a warning upon configuration error. Improve error messages. Check separately for unparsable integer.

Refactor: libpe_status: Best practices for pcmk__unpack_fencing_topology

---

python/pacemaker/_cts/patterns.py

This is a result of c0f9478af9867f130acadf10fcbf335d5da70c2c switching from using services_ocf_exitcode_str (which had a lower case "ok") to crm_exit_str (which has an upper case "OK").

Low: python: Fix expected patterns from pacemaker-controld.

---

daemons/controld/controld_messages.c

Right after starting the cluster the DC is offline for short time, and if you call `crmadmin --dc_lookup` during this time, it would hang. This change leaves the xml-src attribute that the crmadmin receives from the pacemaker-controld empty, so that crmadmin knows the DC was not selected.
ref: https://projects.clusterlabs.org/T735

Fix: controld: leave xml-src attribute empty when no DC selected #2902 #3606

---

cts/cli/regression.cibadmin.exp
cts/cts-cli.in

We are seeing a problem during test builds where the digest can differ. This problem has not been seen when doing builds locally with mock, nor on the clusterlabs CI infrastructure.  It additionally does not seem to be a symptom of any other problem, since we've had no reports with weird CIB differing problems.
Note that the digest was not included in the expected output from the moment it was first committed in 2008 until I converted cts-cli.in to python  Presumedly, this was originally done because the input CIB would be changing and they didn't also want to have to remember to change the expected output.  Unfortunately, this makes it difficult to know if we would have been seeing these digest differences all along.

Low: cts: Don't include the digest in expected output.

---

doc/Doxyfile.in

Doc: doxygen: Do not output PCMK__OUTPUT_ARGS macros to the docs.

---

python/pacemaker/_cts/watcher.py

We support OSes with older versions of dateutil
This will be backported to 2.1

Build: python: do not require isoparse function to exist

---

daemons/execd/pacemaker-execd.c

Upon shutdown of executor, lrmd_drain_alerts() calls pcmk_drain_main_loop() which calls g_main_context_iteration(). If there's a pending SIGCHLD signal, it will be processed by crm_signal_dispatch() -> child_death_dispatch() -> child_waitpid() -> services__finalize_async_op() -> action_complete(), which accesses the hash table "rsc_list".
Previously "rsc_list" was destroyed before lrmd_drain_alerts(), which would cause use-after-free.

Fix: executor: avoid use-after-free upon shutdown

---

daemons/execd/pacemaker-execd.c

Backport https://github.com/ClusterLabs/pacemaker/pull/3718 to 2.1
Upon shutdown of executor, lrmd_drain_alerts() calls pcmk_drain_main_loop() which calls g_main_context_iteration(). If there's a pending SIGCHLD signal, it will be processed by crm_signal_dispatch() -> child_death_dispatch() -> child_waitpid() -> services__finalize_async_op() -> action_complete(), which accesses the hash table "rsc_list".
Previously "rsc_list" was destroyed before lrmd_drain_alerts(), which would cause use-after-free.

[2.1] Fix: executor: avoid use-after-free upon shutdown

---

lib/lrmd/lrmd_client.c

Previous patches only dealt with the TLS handshake.  This one - I *think* - makes the API handshake async as well.  I initially also had a patch to use standard Pacemaker return codes in lrmd_send_command, but something about that wasn't working.  I could give it another try if necessary.

Make the lrmd API handshake async

---

include/crm/common/nvpair_internal.h
lib/common/nvpair.c
lib/common/tests/nvpair/Makefile.am
lib/common/tests/nvpair/pcmk__cmp_nvpair_blocks_test.c
lib/pengine/rules.c

This is part of a larger project to move the functionality of libpe_rules into libcrmcommon and bring the code up to current guidelines.

Move sort_pairs() to libcrmcommon

---

daemons/controld/controld_execd.c

Support for `__attribute__((fallthrough))` varies between compilers and releases, so we've got macros to detect and deal with it.  However, there's only one spot we are making use of the implicit fallthrough and it only saves duplication of one line.  Plus, that's really kind of a misfeature of C (hence the compiler warning).
So, just get rid of it and remember to not use implicit fallthroughs in the future.
Fixes T558

Refactor: daemons: Get rid of an implicit fallthrough.

---

.copr/Makefile
mk/release.mk
rpm/Makefile.am

This gets it working again locally, at least.  See:  https://copr.fedorainfracloud.org/coprs/clumens/pacemaker.  I haven't tried setting up the webhook but it doesn't look difficult.  If that's something we want to do, I'm happy to do it (as well as run the pacemaker copr repo under my own account).

Build improvements around copr

---

rpm/rpmlintrc

For some reason, this Mandriva-specific check is enabled on centos 10. There's no information about it being used elsewhere, and no clear reason why we are starting to see it now and only on pacemaker.  Disable it in our config file.

Build: rpm: Ignore the lib-package-without-%mklibname rpmlint error

---

daemons/execd/execd_commands.c

Hi @kgaillot 
Hi All,
This fix PR is an improvement on the next PR.
* https://github.com/ClusterLabs/pacemaker/pull/3720
-----
1. It speeds up error detection when the systemd resource monitor continues to return pending.
1. In addition, if the systemd resource probe returns pending, a follow up monitor will be performed until the timeout occurs, waiting for RUNNING/NOT RUNNING to be detected.
Best Regards,

Mid: systemd: Improved Pending status in monitor/probe for systemd resources. 

---

cts/cts-scheduler.in

Master/Slave terminology and "ocf::" have been completely removed in the main branch, so there's no need to continue doing these substitutions.

Test: cts-scheduler: Remove sed needed for backwards compat.

---

cts/schemas/test-3/ref.err/acl-drop.ref.err-1
cts/schemas/test-3/ref.err/acl-drop.ref.err-4
cts/schemas/test-3/ref/acl-drop.ref-0
cts/schemas/test-3/ref/acl-drop.ref-1
cts/schemas/test-3/ref/acl-drop.ref-2
cts/schemas/test-3/ref/acl-drop.ref-3
cts/schemas/test-3/ref/acl-drop.ref-4
cts/schemas/test-3/ref/acl-drop.ref-99
cts/schemas/test-3/xml/acl-drop.xml
xml/upgrade-3.10-2.xsl
xml/upgrade-3.10-99.xsl

This is a partial fix of [T898](https://projects.clusterlabs.org/T898). This prevents a schema validation error from occurring due to invalid IDREF in an ACL permission's `reference` attribute. However, the task of preserving behavior when an element is *replaced by one or more new elements* (whether the ACL permission uses `reference` or `xpath`) remains.

Fix: xml: Ensure ACL permissions are valid after XSL transformations

---

daemons/based/based_remote.c
daemons/execd/remoted_tls.c
doc/sphinx/Pacemaker_Explained/local-options.rst
etc/sysconfig/pacemaker.in
include/crm/common/tls_internal.h
lib/cib/cib_remote.c
lib/common/tls.c
lib/lrmd/lrmd_client.c

Tested:
- Still works without certs
- If certs are enabled on the server but not the client, falling back to PSK keys is not allowed
- Moving a Pacemaker Remote resource from a node with a cert to one without does not work (the cluster does not like this happening, but removing the constraint will cause the resource to move back to the node with the cert)
- Moving a Pacemaker Remote resource from a nod with a cert to one with its own cert does work
I did not explicitly test expirations or CRLs, but it's the exact same code as on the remote CIB connections and both worked there so I have no reason to think they wouldn't work here.

Add TLS support for Pacemaker Remote connections

---

agents/ocf/controld.in

I found that when my DLM RA's id starts with `gfs` and `GFS`, the log shows:
```
pacemaker-controld[2039]:  notice: GFs2-dlm_start_0@alp-2 output [ /usr/lib/ocf/resource.d/pacemaker/controld: line 184: gfs_controld: command not found
```
Consider this log
```
commit 75934649b85259d1559eabca40be820095643239
Author: Andrew Price <anprice@redhat.com>
Date:   Tue Feb 12 09:58:11 2019 +0000
gfs2.5: General updates and layout improvements
- Update the manpage to mention lvmlockd and don't mention gfs2_quota
or gfs_controld (both obsolete).
```
Should we drop gfs_controld from RA?

OCF: controld.in: Remove gfs_controld command as it's already obsoleted

---

agents/ocf/controld.in

[3.0] OCF: controld.in: Remove gfs_controld command as it's already obsoleted

---

include/crm/common/xml_names_internal.h
lib/pacemaker/libpacemaker_private.h
lib/pacemaker/pcmk_graph_consumer.c
lib/pacemaker/pcmk_graph_producer.c
lib/pacemaker/pcmk_injections.c
lib/pacemaker/pcmk_simulate.c

... to be consistent with what controller does with update_failcount()

Fix: libpacemaker: set fail-count to INFINITY for fatal failures

---

include/crm/common/xml_names_internal.h
lib/pacemaker/libpacemaker_private.h
lib/pacemaker/pcmk_graph_consumer.c
lib/pacemaker/pcmk_graph_producer.c
lib/pacemaker/pcmk_injections.c
lib/pacemaker/pcmk_simulate.c

... to be consistent with what controller does with update_failcount()
Backport https://github.com/ClusterLabs/pacemaker/pull/3769 to 3.0

[3.0] Fix: libpacemaker: set fail-count to INFINITY for fatal failures

---

agents/ocf/ping.in

Hi all!
I found the following warning appeared  when trying to create a ping resource on RHEL 10.0 beta.
```
[root@rh10-b01 tmp]# pcs -f ping.xml resource create ping ocf:pacemaker:ping \
name="ping-status" host_list="192.168.122.1" attempts="2" timeout="2" debug="true" \
op start timeout=60s on-fail=restart \
monitor timeout=60s interval=10s on-fail=restart \
stop timeout=60s on-fail=fence
Warning: Validating resource options using the resource agent itself is enabled by default and produces warnings. In a future version, this might be changed to errors. Specify --agent-validation to switch to the future behavior.
Warning: Validation result from agent:
egrep: warning: egrep is obsolescent; using grep -E
```
The environment where this issue occurred is as follows: 
```
[root@rh10-b01 …
```

Replace the egrep command with the EGREP definition in ping RA

---

lib/cib/cib_remote.c

Fix: libcib: Don't send CRM_OP_REGISTER from cib_remote client

---

daemons/controld/controld_te_events.c

When using -O3 to build pacemaker, gcc (14) will throw format-overflow warnings for some possibly null '%s' directive arguments. This the current instances of such warnings by introducing checks for null pointers.
alerts.c:153:19: error: '%s' directive argument is null [-Werror=format-overflow=]
153 |         crm_trace("Inserting alert key %s = '%s'", *key, value);
|                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
alerts.c:153:46: note: format string is defined here
153 |         crm_trace("Inserting alert key %s = '%s'", *key, value);
|

Low: controller: address format-overflow warnings

---

daemons/controld/controld_te_events.c
lib/common/alerts.c

Backporting https://github.com/ClusterLabs/pacemaker/pull/3794
When using -O3 to build pacemaker, gcc (14) will throw format-overflow warnings for some possibly null '%s' directive arguments. This the current instances of such warnings by introducing checks for null pointers.
alerts.c:153:19: error: '%s' directive argument is null [-Werror=format-overflow=]
153 |         crm_trace("Inserting alert key %s = '%s'", *key, value);
|                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
alerts.c:153:46: note: format string is defined here
153 |         crm_trace("Inserting alert key %s = '%s'", *key, value);
|

[2.1] Low: various: address format-overflow warnings

---

include/crm/cib.h
include/crm/stonith-ng.h

This fixes a longstanding regression, introduced in dad2411 for libstonithd and in e014c52 for libcib.
The libstonithd version mismatch currently causes issues with dlm_controld, impacting gfs2 filesystems.
It's not clear whether anything uses the CIB_LIBRARY constant. It looks as if it could be deprecated. Nothing internal uses it. However, dlm includes stonith-ng.h, which uses STONITH_LIBRARY in inline functions.

Fix: libraries: Update version numbers in so names

---

include/crm/cib.h
include/crm/stonith-ng.h

This fixes a longstanding regression, introduced in dad2411 for libstonithd and in e014c52 for libcib.
The libstonithd version mismatch currently causes issues with dlm_controld, impacting gfs2 filesystems.
It's not clear whether anything uses the CIB_LIBRARY constant. It looks as if it could be deprecated. Nothing internal uses it. However, dlm includes stonith-ng.h, which uses STONITH_LIBRARY in inline functions.

[3.0] Fix: libraries: Update version numbers in so names

---

lib/common/output_text.c
tools/crm_mon_curses.c

We were freeing the string members of text_list_data_t, but not the text_list_data_t object itself. Similarly for curses_list_data_t.
Ref T704

 Low: libcrmcommon: Fix memory leak in text_end_list()/curses_end_list()

---

cts/cli/regression.error_codes.exp
include/crm/common/results.h
lib/common/results.c
lib/pacemaker/pcmk_cluster_queries.c

If the DC is not yet elected, the crmadmin will return an error. (This change complements #3606).

Fix: crmadmin: return error if DC is not elected #2902 #3606

---

doc/sphinx/Pacemaker_Development/components.rst

Which has been dropped in commit ed688c8cf3

Doc: Pacemaker_Development: Use enum controld_join_phase instead of crm_join_phase

---

daemons/execd/execd_commands.c
lib/services/dbus.c
lib/services/systemd.c

This splits out a bunch of the prep stuff from #3805 into its own PR so we can get it in faster.  I think this is all fairly uncontroversial stuff.

Prepare for the systemd+dbus PR

---

lib/cluster/cpg.c

When sbd is connecting to cluster by calling crm_cluster_connect() -> pcmk_cluster_connect() -> pcmk__corosync_connect() -> pcmk__cpg_connect() -> pcmk__server_message_type()
, it triggers assertion:
error: log_assertion_as: pcmk__server_message_type: Triggered fatal assertion at servers.c:165 : (server > 0) && (server < PCMK__NELEM(server_info))
This fixes it by avoiding calling pcmk__server_message_type() in pcmk__cpg_connect().

 Fix: libcrmcluster: prevent external callers from triggering assertion when connecting to cluster

---

.clang-format
devel/Makefile.am

The indent tool has fallen out of favor with a lot of developers, while clang-format seems to be growing in popularity.  We're not enforcing the usage of any style tool because they never get everything 100% right, and I'm not really sure anyone ever actually uses this target - I know I never have.
However, this at least updates it to be something more modern should anyone want to use it.  To generate this config, I dumped the default GNU coding style (clang-format -style=gnu -dump-config), removed anything that wasn't related to regular old C, and then went through every config option and checked to make sure it was close to our existing style.  I'm sure something incorrect has snuck through.

Build: devel: Replace indent with clang-format.

---

configure.ac

Fedora >=42 tries to unify `/usr/sbin` with `/usr/bin`, which causes problems for our bundles' container resources in the default case. See the comment in `configure.ac` for much more detail.

[2.1] Fix: build: Fix default pacemaker-remoted path on Fedora >= 42

---

configure.ac

Fedora >=42 tries to unify `/usr/sbin` with `/usr/bin`, which causes problems for our bundles' container resources in the default case. See the comment in `configure.ac` for much more detail.

[3.0] Fix: build: Fix default pacemaker-remoted path on Fedora >= 42

---

configure.ac
lib/common/watchdog.c

Fedora >=42 tries to unify `/usr/sbin` with `/usr/bin`, which causes problems for our bundles' container resources in the default case. See the comment in `configure.ac` for much more detail.

Fix: build: Fix default pacemaker-remoted path on Fedora >= 42

---

devel/Makefile.am

* COVERAGE_DIR should be an absolute path so it doesn't get accidentally created outside of the source/build tree.
* Use long command line arguments to everything to make it a little more clear what these commands do.  We so rarely use any of these tools that no one remembers the short versions.
* Ignore unused excludes.  At some point, an unused exclude became an error which stops the build process.  Ignore those errors instead of trying to figure out what is and isn't used.
* Restrict code coverage to the lib/ directory in the main target. Previously, we were scanning everything and then going through and removing certain directories.  Instead, let's just scan the one thing we do care about.  This loses coverage checking of include/, but I'm okay with that.
* Add && before the genhtml …

Build: Fix coverage targets.

---

daemons/pacemakerd/pcmkd_subdaemons.c
devel/Makefile.am
include/crm/common/io_internal.h
lib/cluster/cpg.c
lib/common/cmdline.c
lib/common/io.c
lib/common/output.c
lib/common/remote.c
lib/common/strings.c
lib/common/xml_io.c
lib/pacemaker/pcmk_ticket.c

@waltdisgrace Here's another simple one.  My only concern here is that different versions of cppcheck may still require the older suppression messages.  However, I don't think we mention anywhere what version of static analysis tools the pacemaker code is expected to pass with.  Maybe we should specify that somewhere.

Update cppcheck config to pass cleanly

---

cts/cli/regression.crm_simulate.exp
cts/cts-cli.in
lib/common/results.c
rpm/pacemaker.spec.in

These were dropped during the conversion from shell to python.

Med: cts: Add missing crm_simulate regression tests back to cts-cli.

---

lib/common/strings.c
lib/services/systemd.c
lib/services/systemd.h
tools/crm_resource.c
tools/crm_resource.h
tools/crm_resource_print.c
tools/crm_resource_runtime.c

These have been getting in the way of trying to set timeouts via override files in #3818.

Fix systemd unit overrides

---

cts/cli/regression.crm_resource.exp
cts/cts-cli.in
lib/services/services.c
tools/crm_resource.c
tools/crm_resource.h
tools/crm_resource_print.c
tools/crm_resource_runtime.c

Coverity is throwing some new false positives in https://github.com/ClusterLabs/pacemaker/pull/3832. Two of them are in code that I actually modified, but a lot more are in totally unrelated code in `crm_resource`. It's flagging NULL dereferences along code paths that are verifiably impossible to reach.
We could add Coverity suppressions. But false positives are often a sign that the code is too hard to follow in the first place. And I think that's the case here.
The changes that I've started on also happen to be first steps toward moving more functionality into libpacemaker.
The first few commits focus on avoiding passing around `options.host_uname` as much as possible. Coverity was complaining; it gets confusing to verify that it's non-NULL when it's supposed to be; and we're …

Overhaul crm_resource

---

cts/scheduler/summary/stop-failure-no-fencing.summary
cts/scheduler/summary/stop-failure-no-quorum.summary
cts/scheduler/summary/unmanaged-promoted.summary
lib/pengine/native.c

... even if the node is offline.
Previously, parents of an unmanaged resource were not added to the node
if the node was offline. So that for instance a resource group in
`maintenance` mode as a whole would not be displayed by
crm_mon/crm_simulate at all.

Fix: libpe_status: consider parents of an unmanaged resource active on the node

---

lib/common/schemas.c

Currently this fails the `pcmk__schema_files_later_than_test.c:valid_name()` unit test on FreeBSD. Since we don't get access to CI builders anymore, I'm not sure where to begin other than setting up a FreeBSD VM and learning how to compile C code on it. I guess I'll thoroughly inspect the POSIX and FreeBSD docs for each regexes and `sscanf()` and try to figure out what differs.

scandir() fixes for schema transformations

---

daemons/execd/execd_commands.c
include/crm/services_internal.h
lib/fencing/st_actions.c
lib/lrmd/lrmd_client.c
lib/services/services.c
lib/services/services_private.h
lib/services/systemd.c

This builds on top of #3841.  I haven't tested it yet but again, I wanted to get it out there.
One interesting note here is that action_complete is much simpler on the 2.1 branch and we could actually get rid of the followup monitor block, and then everything that touches `real_action`.  I've opted to not do that to keep the changes to a minimum and to make any future backporting easier.  But as of right now, it's all dead code.

Use dbus to detect completion of systemd resources start/stop actions

---

cts/cli/regression.error_codes.exp
lib/common/results.c

This adds an info entry for `pcmk_rc_no_dc` return code so that pcmk_rc_str() provides an informative description for it rather than just an "Error".
This should have been done with a1d94f7ab5.
In particular for the output of `crmadmin --dc_lookup/-D`, dc() function outputs somewhat redundant information when DC is not yet elected. But I'm not sure whether/how we should change the output format there.

Fix: libcrmcommon: provide a description for pcmk_rc_no_dc return code

---

python/pacemaker/_cts/validate.py

If running from a source checkout and you don't have PCMK_schema_directory set, then rng_directory would fail because it returns an incorrect path.  This hasn't failed for me in the past because even though I run cts tests from a source checkout, I always have PCMK_schema_directory set locally in /etc/sysconfig/pacemaker.
Fixes T982

Low: python: Fix setting schema directory in source checkout.

---

daemons/attrd/attrd_corosync.c
daemons/attrd/attrd_messages.c
daemons/attrd/pacemaker-attrd.c
daemons/attrd/pacemaker-attrd.h
lib/cluster/cluster.c

If nodes are not configured with names in corosync, when a node joins
the cluster, it takes a while for it to learn the names of all the other
online peers. Previously, if any of the peers happened to leave when its
`name` was unknown to us yet, pacemaker-attrd would trigger assertion in
`attrd_peer_remove()` and segfault in
`attrd_remove_peer_protocol_ver()`.

Fix: pacemaker-attrd: prevent segfault if a peer leaves when its name is unknown yet

---

include/crm/common/scheduler.h

Commit f342b77561 broke backward compatibility by inserting the new member `fence_remote_without_quorum` into the middle of the `pe_working_set_s` struct.

Refactor: libcrmcommon: move the new struct member to the end for backward compatibility

---

cts/cts-fencing.in
cts/support/fence_dummy.in
daemons/fenced/fenced_cib.c
daemons/fenced/fenced_commands.c
daemons/fenced/fenced_scheduler.c
daemons/fenced/pacemaker-fenced.c
daemons/fenced/pacemaker-fenced.h
doc/sphinx/Pacemaker_Explained/fencing.rst
include/crm/fencing/internal.h
lib/fencing/st_actions.c
lib/fencing/st_client.c
lib/fencing/st_rhcs.c

A few things that came up while trying to figure out #3855.

Some fencer device registration refactors

---

daemons/controld/controld_fencing.c
daemons/execd/execd_commands.c
daemons/execd/pacemaker-execd.c
daemons/fenced/cts-fence-helper.c
daemons/fenced/fenced_cib.c
daemons/fenced/fenced_commands.c
daemons/fenced/fenced_history.c
daemons/fenced/fenced_remote.c
daemons/fenced/fenced_scheduler.c
daemons/fenced/pacemaker-fenced.c
daemons/fenced/pacemaker-fenced.h
include/crm/fencing/internal.h
include/crm/stonith-ng.h
include/pacemaker.h
include/pcmki/pcmki_fence.h
lib/fencing/st_client.c
lib/fencing/st_lha.c
lib/fencing/st_output.c
lib/fencing/st_rhcs.c
lib/lrmd/lrmd_client.c
lib/pacemaker/pcmk_fence.c
lib/pacemaker/pcmk_setup.c
lib/pacemaker/pcmk_status.c
tools/crm_mon.c
tools/crm_resource.c
tools/stonith_admin.c

More fencer refactors (mostly related to flags)

---

daemons/based/based_notify.c
doc/sphinx/Pacemaker_Explained/local-options.rst
etc/sysconfig/pacemaker.in
include/crm/common/ipc.h
include/crm/common/ipc_internal.h
include/crm/common/mainloop.h
include/crm/common/options_internal.h
lib/cib/cib_native.c
lib/common/crmcommon_private.h
lib/common/ipc_client.c
lib/common/ipc_common.c
lib/common/ipc_server.c
lib/common/mainloop.c

This is also in preparation for the IPC split message split up code.  These commits are surprisingly standalone, which will make testing the actual split up easier.  Note that merging this PR will get rid of IPC compression entirely, which will break anyone with a large cluster.
My proposal is that we get this into an approved state and leave it unmerged so I can finish debugging the split up code.  I don't want to merge this quite yet just in case something happens on the split up patches and we are unable to get it done before release time.  Once that's also ready to go, we merge both PRs.
I expect to have the split up PR done fairly soon.  It mostly works, but I have some double free related segfaults to sort out still.

Remove compression in the IPC code

---

lib/pengine/unpack.c

Most other things in unpack_config are logged at debug or trace level. Having the fencing message at the warn level makes it come up quite often.

Refactor: scheduler: Lower fencing log message to debug level.

---

cts/cli/regression.error_codes.exp
daemons/based/based_notify.c
include/crm/common/ipc.h
include/crm/common/ipc_internal.h
include/crm/common/results.h
lib/common/crmcommon_private.h
lib/common/ipc_client.c
lib/common/ipc_common.c
lib/common/ipc_server.c
lib/common/mainloop.c
lib/common/results.c
lib/fencing/st_client.c
lib/lrmd/lrmd_client.c

There's two kinds of IPC messages - regular ones (these don't really have a name), and server events.  These use different libqb channels, different libqb send/recv functions, and for the most part different pacemaker functions.  Server events are much easier to deal with from a split up perspective: they are added to a send queue that is periodically flushed, which means there's no need to worry with EAGAIN.  They also, for the most part, seem to be smaller so they don't get split up as much which means less traffic bogging down the network.
This PR takes a lot of code from #3868 and rearranges some of the patches to be in a more logical order, but changes the patches to handle the sending and receiving.  I think this should make it easier to review as well since there's a whole lot less …

Support splitting up IPC server events

---

python/pacemaker/_cts/patterns.py

This doesn't seem to point at any specific problem that prevents ctslab from running and passing, but perhaps logging it is important to someone.  So, just ignore it in ctslab.

Test: cts: Ignore the "Local CIB ... differs from ..." message.

---

daemons/attrd/attrd_ipc.c
daemons/based/based_callbacks.c
daemons/controld/controld_control.c
daemons/execd/pacemaker-execd.c
daemons/execd/remoted_proxy.c
daemons/fenced/pacemaker-fenced.c
daemons/pacemakerd/pcmkd_messages.c
daemons/schedulerd/schedulerd_messages.c
include/crm/common/ipc_internal.h
lib/common/ipc_client.c
lib/common/ipc_server.c

This is it - the last PR necessary for splitting up IPC messages.  There are definitely still problems around scaling the IPC code, but at this point they shouldn't be due to the size of messages, and those problems were pre-existing.

Support splitting up IPC messages

---

cts/cli/regression.crm_attribute.exp
cts/cli/regression.daemons.exp
include/crm/common/options.h
include/crm/common/scheduler_internal.h
include/crm/crm.h
lib/common/options.c
lib/pengine/unpack.c
lib/pengine/utils.c

This is a patch against the main branch to change remote fencing behavior.  It is substantially different from #3856 and followup PRs, though it addresses the same issue.  Here, we use a scheduler flag and the `set_config_flag` function to grab it.  This gets rid of the need for the followup PRs.  We also default to the new behavior now, and adding the CIB setting changes back to the older behavior.
This is untested (it's a real chore to test), but I suppose I should try to do that again before this actually gets merged.  In the meantime, it's worth making sure I got all these double negatives right.  I also wonder if there's some way we should draw further attention to this change.

Change remote fencing behavior

---

tests/tap-driver.sh

We've been having CI problems that seem to originate from gawk being called by tap-driver.sh trying to allocate way too much memory, but only on certain platforms.  As a first step, let's update this script (which, we were using a version from 2011) and see if that helps anything.  If not, it's at least nice to update this ancient code.

Test: tap-driver.sh:  Update from the latest in automake source.

---

ChangeLog.md

ctslab is still running, but I don't expect it to find anything given that all we've changed since rc1 is docs and static analysis results reporting.

Doc: ChangeLog: update for 3.0.1-rc2 release

---

lib/pacemaker/pcmk_cluster_queries.c

This is a regression introduced by e438946787.  In that patch, what we're trying to do is retry IPC connections between daemons.  If a daemon gets ECONNREFUSED when it initiates an IPC connection, the most likely reason is that another daemon has been killed and is restarting but is not yet ready to accept connections.  Waiting and retrying repeatedly is an acceptable way to deal with this.
However, if a command line tool gets ECONNREFUSED, it's more likely that the problem is the cluster isn't running at all.  In this case, waiting and retrying just introduces a delay for a situation that will never be resolved.  Reverting just the part in pcmk_cluster_queries.c should fix this problem without affecting any of the daemons - they don't call this code.
Fixes RHEL-106594

Med: libpacemaker: Do not retry on ECONNREFUSED in tools.

---

include/crm/common/tls_internal.h
lib/common/tls.c
lib/common/utils.c

This is #3790 with an extra patch on top to improve error reporting.  I think we could probably go farther with improving gnutls-related error reporting, but I'm not willing to work on that right now.  I'm a little pessimistic on this kind of error reporting in the first place since it all just goes out the logging firehose, and someone has to know to go digging around in there when their cluster doesn't work.
There are no code changes in the first three patches.
I tested the following:
* Expired certificates (that's how I discovered we needed to add the error reporting code back)
* Certificates are valid
* Certificate required by server, but not supplied by client
* Certificate not required by server, but supplied by client anyway
* The previous three for remote CIB operations as well

Drop workarounds for GnuTLS <3.4.6

---

daemons/controld/controld_callbacks.c
daemons/controld/controld_control.c
daemons/controld/controld_fsa.c
daemons/controld/controld_globals.h
daemons/controld/controld_messages.c
daemons/controld/controld_messages.h

This makes more semantic sense, and it avoids expensive linked list traversals to append to the message queue. `g_queue_push_tail()` jumps straight to the end.

Refactor: controller: Use GQueue for FSA message queue

---

cts/cli/regression.crm_attribute.exp
cts/cli/regression.daemons.exp
include/crm/common/xml_names.h
lib/common/options_display.c
tools/crm_node.c

This fixes a regression introduced by commits 37b87dca and c0d90ba1. The options "stop-orphan-resources" and "stop-orphan-actions" no longer appeared in the output of crm_attribute --list-options=cluster. This broke workflows that use pcs to set those properties.
The issue is not specific to those two options, but rather affects any option with the alt_name field set. Those are currently the only ones, however.
For the "default" display, we build up the aliases list separately from the deprecated list. Creating a temporary pcmk__cluster_option_t object on the stack and allocating/freeing only one desc string at a time turns out to be simpler than building a list of heap-allocated temporary pcmk__cluster_option_t objects.
Fixes T998
Fixes RHEL-112591

Fix: libcrmcommon: Show deprecated option aliases in outputs

---

python/pacemaker/_cts/environment.py

From the python documentation:
Changed in version 3.12: Passing None for s argument now raises an exception, rather than reading sys.stdin.

Low: cts: Don't try to shlex.split(None) for fencing params.

---

cts/cli/regression.crm_attribute.exp
cts/cli/regression.daemons.exp
doc/sphinx/Pacemaker_Explained/cluster-options.rst
lib/common/ipc_server.c
lib/common/options.c

This almost seems too easy.  The next step is getting some stress testing done on it, but before I start asking around about that, we should do patch review and perhaps consider whether to allow other clients to bypass the queue limit check as well.
I'm also undecided on whether this actually takes care of T38 or not.  It definitely makes the scalability of the queue much less of an issue, perhaps enough to where we can consider it closed.  I'm not sure that there's anything else we could do in this area before considering it closed.

Fix IPC backlog problems

---

tools/crm_resource.c
tools/crm_resource.h
tools/crm_resource_ban.c
tools/crm_resource_print.c
tools/crm_resource_runtime.c

Previously, if the --timeout value parsed to a value greater than (UINT_MAX - 999), the wait timeout would overflow. The effective timeout would be either 0 seconds or 1 second. This is because 999 was added to the guint value before passing it to pcmk__timeout_ms2s().
Now, we simply pass the timeout in milliseconds to pcmk__timeout_ms2s(), without adding 999.
This implies a slight behavior change. Previously, timeouts were always rounded up to the next greatest second. Now, they're rounded to the nearest second. For example, previously:
* timeout values between 1ms and 500ms => wait timeout of 1 second
* timeout values between 501ms and 1500ms => wait timeout of 2 seconds
* timeout values between 1501ms and 2500ms => wait timeout of 3 seconds
* and so on
Now:
* timeout values between 1ms …

Fix: tools: Handle large timeouts correctly in crm_resource --wait
