- mcp/pacemaker.c
Whenever a node to constitute a cluster repeats start and a stop,
Pacemakerd of the node not to stop leaks out memory.
> Memory leak of pacemakerd.

- configure.ac
Configure should detect ncurses' link flags and respect them to avoid compilation failure.
I used pkg-config to do so, maybe there may be a less ugly way but it works.
More info : https://bugs.gentoo.org/show_bug.cgi?id=526770
> Fix: Build: respect ncurses lib flags

- pengine/constraints.c
At one point, the ordered set's require-all feature required
a nested loop. This nesting of the two loops is no longer
necessary now that a pseudo action is in use.
> Low: pengine: remove unnecessary nested loop

- configure.ac
ncurses < 5.8 doesn't provide pkg-config files
> Build: Fix building if ncurses doesn't provide pkg-config files

- lib/common/xml.c
In lib/cib/cib_utils.c: cib_perform_op(), we validate the created local_diff: 
test_rc = xml_apply_patchset(c, local_diff, manage_counters);
But if the diff was created with digest, we should not prune leaves from it. Otherwise, the validation in cib_perform_op() would fail.
> Fix: xml: Do not prune leaves from v1 cib diffs that are being created with digests

- cts/CTSlab.py
- cts/README
- cts/environment.py
- cts/patterns.py
I split the revision in the previous pull request ("fix regressions in CTS", now closed) into four smaller revisions with more detailed commit messages. Additionally, I removed the obsolete external/ssh stonith section from README.
These revisions to cts update the README, fix regressions in the cman use case and the --trunc option, fix a bug in the usage() method, and add a --help option.
> Clean up CTS

- cts/LSBDummy.in
Option '-e' of 'echo' command may be unsupported in some
POSIX-complete shells.
> Fix bashisms in LSBDummy script

- tools/crm_standby
First revision changes whitespace only.
Second revision uses -eq/-ne instead of =/!= where appropriate.
Third revision is the meat. At some point, crm_attribute's command-line options were updated, e.g. --attr-value became --update. crm_standby's man page and help text were updated accordingly, but not the actual options accepted. This takes care of that and does some minor cleanup (additional comments, separating help text into a variable, etc.).
> Update crm_standby options to match its documentation

- cib/io.c
- include/crm/common/Makefile.am
- include/crm/common/io.h
- include/crm_internal.h
- lib/common/Makefile.am
- lib/common/digest.c
- lib/common/io.c
- lib/common/utils.c
- lib/common/xml.c
These commits lay the groundwork for enabling CIB_file to operate on the real CIB. They are not entirely necessary for that goal but helped me get familiar with the affected pieces. The I/O-related functions in lib/common/utils.c were separated into a new file io.c, and some reusable I/O bits of the CIB daemon were moved there. Similarly, the digest-related functions in lib/common/xml.c were separated into digest.c, and a bit of daemon code moved there.
> Move some reusable CIB daemon code into libraries

- cib/cibio.h
- cib/io.c
- include/crm/cib/internal.h
- include/crm/error.h
- include/crm_internal.h
- lib/cib/cib_file.c
- lib/common/logging.c
- lib/common/xml.c
These refactoring commits are the final prep work for enabling CIB_file to operate on the real CIB. The effect is to segregate daemon-specific CIB code (mainloop stuff, global variables) from generic CIB code and move the latter to the CIB library. I tried as far as possible to avoid any behavioral changes; the only such changes should be improved error handling.
CTS with 25 random tests against a 3-node RHEL7 cluster completed without errors.
For "remove dead code", I grepped the entire code base to make sure the variables weren't used.
For all revisions, I checked cts/patterns.py to make sure no changed messages were used by CTS.
> Move reusable CIB daemon code to the CIB library

- include/crm/common/io.h
- include/crm_internal.h
- lib/cib/cib_file.c
- lib/common/Makefile.am
- lib/common/compat.c
- lib/common/io.c
These commits allow the CIB library to detect when CIB_file points to the live CIB, and if so, it creates a signature file when writing. It will also back up the existing CIB in the backup series, and update the ownerships of all written files appropriately.
If you saw my earlier commits that did not get a pull request, the first three commits here are identical, but the tip is different. The earlier version dropped privileges to daemon before writing out the file; it turns out that is insufficient, as the file may already exist under a different ownership. This version changes the ownership after writing the file.
CTS with 25 random tests against a 3-node RHEL7 cluster completed with no errors. The actual functionality of running various tools with CIB_file pointing to the live CIB will …
> Automatically update .sig files in file backends when clients update live CIB

- fencing/commands.c
- fencing/main.c
- fencing/remote.c
- include/crm/fencing/internal.h
This prevents double fencing when using slow fencing devices such as sbd.
A "pcmk_delay_max" parameter can be configured for a fencing resource to
enable random delay for stonith actions and specify the maximum of
random delay.
> Feature: fencing: cl#5134 - Support random fencing delay to avoid double fencing

- configure.ac
These two patches fix errors that happen only when Pacemaker is cross-compiled.
I experienced these errors when trying to cross-compile Pacemaker with Buildroot. In particular, passing -I/usr/include to a cross-compiler leads to mix host headers with target headers and causes compilation errors.
> Cross compilation fixes

- .gitignore
- attrd/commands.c
- attrd/internal.h
- attrd/main.c
- include/crm/attrd.h
- include/crm_internal.h
- lib/common/utils.c
- tools/attrd_updater.c
These commits enable support for private attributes (i.e. ones which will never be written to the CIB) in attrd, libcrmcommon's attrd_update_delegate() function, and the attrd_updater tool.  This request has been amended and rebased to (1) revert whitespace-only changes per beekhof; and (2) get some recently merged commits that were needed for further work. Of particular interest:
* The first three commits were already reviewed by beekhof.
* dcfa267 flags a potential bug in attrd with a comment for later investigation.
* 2a3b375 is unrelated to this project: It adds HBDummy to .gitignore (commit 190e756 introduced cts/HBDummy.in but neglected to do this).
* 77bb239 fixes an attrd bug introduced in 7714443
I ran CTS with 25 random tests against a 3-node RHEL cluster to ensure I didn't …
> Enable support for private (non-CIB) attributes

- doc/Makefile.am
- doc/Pacemaker_Explained/en-US/Ap-LSB.txt
- doc/Pacemaker_Explained/en-US/Ap-OCF.txt
- doc/Pacemaker_Explained/en-US/Ap-Upgrade-Config.txt
- doc/Pacemaker_Explained/en-US/Ap-Upgrade.txt
- doc/Pacemaker_Explained/en-US/Book_Info.xml
- doc/Pacemaker_Explained/en-US/Ch-Advanced-Options.txt
- doc/Pacemaker_Explained/en-US/Ch-Advanced-Resources.txt
- doc/Pacemaker_Explained/en-US/Ch-Basics.txt
- doc/Pacemaker_Explained/en-US/Ch-Constraints.txt
- doc/Pacemaker_Explained/en-US/Ch-Multi-site-Clusters.txt
- doc/Pacemaker_Explained/en-US/Ch-Nodes.txt
- doc/Pacemaker_Explained/en-US/Ch-Notifications.txt
- doc/Pacemaker_Explained/en-US/Ch-Options.txt
- doc/Pacemaker_Explained/en-US/Ch-Resource-Templates.txt
- doc/Pacemaker_Explained/en-US/Ch-Resources.txt
- doc/Pacemaker_Explained/en-US/Ch-Rules.txt
- doc/Pacemaker_Explained/en-US/Ch-Status.txt
- doc/Pacemaker_Explained/en-US/Ch-Stonith.txt
- doc/Pacemaker_Explained/en-US/Ch-Utilization.txt
- doc/Pacemaker_Explained/en-US/NOTES
- doc/Pacemaker_Explained/en-US/Pacemaker_Explained.ent
- doc/Pacemaker_Explained/en-US/Revision_History.xml
Apologies for the egregious size of this update; I had my copy editor hat on when I went though Pacemaker Explained and went to town. No more like this, promise. :-)
* The "stylistic consistency", "minor clarifications" and "minor reorganization" revisions isolate the least significant bits so they can be quickly skimmed. They do not affect the content significantly, just the presentation.
* The Makefile revision adds an RSYNC_DEST variable for where docs are uploaded to, so it is easy to override on the command line.
* Using the above, I generated a full set of branded docs available for comparison at http://people.redhat.com/kgaillot/doc/en-US/ -- for example http://people.redhat.com/kgaillot/doc/en-US/Pacemaker/1.1-pcs/html/Pacemaker_Explained/
I made these changes as I read the …
> Update Pacemaker Explained for clarity, consistency and current syntax

- include/crm/pengine/status.h
- pengine/allocate.c
- pengine/native.c
Resolved memory leaks. Well, and refactored --  I think it's more precise to reschedule specific monitors ;-)
> Refactor: pengine: Reschedule specific monitors when resource definitions have changed

- .gitignore
- Doxyfile.in
- include/crm/lrmd.h
- include/crm/services.h
- include/doxygen.h
These revisions fix warnings when doing "make doxygen". Doxyfile is updated to doxygen 1.8.5 (RHEL/CentOS 7 version), the doxygen-generated documentation is ignored by git, and errors in doxygen comment blocks are corrected. The massive Doxyfile.in revision is simply the result of running "doxygen -u" to upgrade the file format and has no functional changes; the command updated all the comments (I preserved the automake macros used in Doxyfile.in).
I made this revision while investigating why doxygen does not use comment blocks in source files, only headers. That issue is not corrected by this; it can probably be fixed with some minor tweaks to Doxyfile, but that will be left for another day.
> Doxygen cleanup

- include/crm/services.h
- lib/services/services_linux.c
- lrmd/lrmd.c
LSB status exit code 4 is now treated as "status unknown" (increase fail count) rather than "not installed" (fail over immediately). Also, custom LSB status exit codes are used internally when the LSB agent could not be executed.
> Fix CL BZ#5234: interpret LSB status codes properly

- crmd/callbacks.c
CRMd transitioner could not recover from "Too many failures to fence".
Steps to produce:
1. Two-node cluster with stonith, for example using IPMI.
2. Node-1 has a complete power outage for a couple of minutes. The
IPMI device is also without power, which causes the fencing to fail
3. Node-2 tries to fence node-1 for several times but fails.
4. Node-2 reports "Too many failures to fence node-1 (11), giving up".
5. The power returns and node-1 boots up normally.
6. Node-1 rejoins the cluster, but resources are not started on it.
Expected result:
The stonith failcount for node-1 should be reset and resources should
be started on node-1.
Actual result:
Node-2 still logs "Too many failures to fence" and resources are not
started on node-1.
> Fix: crmd: Reset stonith failcount to recover transitioner when the node rejoins

- fencing/commands.c
Lack of support for semi-colon delimiter in pcmk_host_list can lead to confusion, seeing as pcmk_host_map does allow it. Out of habit users may use it for both, leading to a host not being seen as eligible to be fenced by a given device.
> fencing: Allow semi-colon delimiter for pcmk_host_list

- tools/crm_resource.c
For example, given an anonymous clone resource set:
```
Clone Set: clone1 [rsc1]
Started: [ node1 node2 ]
```
`crm_resource --locate --resource rsc1` will output:
```
resource rsc1 is running on: node1
resource rsc1 is running on: node2
```
, instead of only:
```
resource rsc1 is running on: node1
```
This commit also fixes the counting of running resources.
> Fix: crm_resource: Display the locations of all anonymous clone children when supplying the children's common ID

- mcp/pacemaker.combined.upstart.in
We added setting of the automatic start in
upstart.(pacemaker.combined.conf)
It is necessary for the user to exclude comment.
We confirmed movement only in RHEL6.6.
#Possibly a change may be necessary for the different distribution.
Best Regards,
> Low: mcp: Add 'start on started local and runlevel' to Upstart job.

- lrmd/lrmd.c
I ran a test case using the DummySD systemd agent from the standard CTS configuration. I kill -9'd the python command before it could finish starting up. Before this patch, crm_mon reported exec=2ms under failed actions, and with this patch, it reported >10000ms (which was about the actual time when I killed it).
CTS with 75 random tests ran fine against this.
> Fix reported times after systemd operation

- cib/io.c
- lib/cib/cib_file.c
This restores the log messages to exactly what they were before 9f83b41. I'd recommend reducing them even further; if you agree, I'll amend this:
* Remove the second crm_info() added here in cib/io.c. That's if the main CIB file is bad, and we need to read from one of the backups; in such a case there will already be a warning just beforehand and a warning (if unsuccessful) or notice (if successful) with the backup filename just afterward.
* Maybe get rid of the crm_trace() added here in lib/cib/cib_file.c. That's when we're verifying the existing CIB before writing a new one. There won't be any logs beforehand, but we'll log an error immediately if it fails, and log a debug message "Writing CIB to disk" a couple steps later, so I think that's adequate to investigate any issues.
* Get rid …
> restore CIB read-and-verify logging to 1.1.12 verbosity

- tools/crm_mon.c
Aside from a little bit of lipstick, the headline here is HTML/XML output support for node attributes, operations, failcounts and tickets.
I am not submitting this for 1.1.13 because this is a rather large change for the rc phase and because this uses the new "guest node" terminology that is not in use anywhere else yet.
I've done quite a bit of testing with various option combinations (fixing some trivial corner-case bugs here and there). You can see before-and-after output at http://people.redhat.com/kgaillot/crm_mon/
> crm_mon enhancements

- configure.ac
- mcp/pacemaker.service.in
- pacemaker.spec.in
- tools/Makefile.am
- tools/crm_mon.service.in
It supported systemd in crm_mon.
We wish this correction is included in Pacemaker1.1.13.
Best Regards,
> Low: tools: Support of the start from systemd of crm_mon.

- lib/fencing/st_client.c
Some heartbeat stonith plugins support "port" themselves. We should not
use it for passing the victim to fence_legacy
> Fix: fencing: Correctly make args for fencing agents

- xml/upgrade-1.3.xsl
Any old ACLs rule configured with both "ref" and "attribute" could not be transformed into a new rule that validates against acls-2.0.rng.
And although the new "attribute" actually has the  different semantic, I think it's safer to preserve it when transforming "tag" to "object-type".
> Fix: xml: Fix upgrade-1.3.xsl to correctly transform ACL rules with "attribute"

- crmd/fsa_defines.h
- crmd/lrm.c
- crmd/te_callbacks.c
- crmd/te_events.c
- lib/pengine/utils.c
The cluster now handles on-fail=ignore properly. Previously, the fail count would still get updated, potentially leading to a migration. The most obvious situation was a start failure with start-failure-is-fatal=true (the default), which would cause the fail count to be set to INFINITY resulting in an immediate migration.
> Fix rhbz#1200849

- crmd/callbacks.c
- include/crm/crm.h
This issue is related to https://github.com/ClusterLabs/pacemaker/commit/5cb541fb0d34b1d224debb222ade51178a9eb5ba and https://github.com/ClusterLabs/pacemaker/commit/23b5f07fc15fd8436ff70883770349390771f8eb
In a mixed cluster, if the node that is shutting down is an old version
of DC, it won't send the CRM_OP_SHUTDOWN_REQ to the other newly upgraded
nodes. So the other nodes won't get a chance to update this node's
"expected" field to "down" from their membership caches, while they'll
still erase this node's transient attributes. Any node that is later
elected to be the new DC will decide to fence this node that has just
shut down.
The idea of this fix is not to erase this node's transient attributes
in this case to prevent the fencing. Although when this node first
rejoins, there could …
> Fix: crmd: Prevent the old version of DC from being fenced when it shuts down for rolling-upgrade

- crmd/te_events.c
- include/crm/msg_xml.h
- include/crm/pengine/status.h
- lib/pengine/utils.c
- pengine/graph.c
This reimplementation avoids the need to change any pengine regression tests,
and deprecates the XML_ATTR_TE_ALLOWFAIL operation attribute and the
corresponding pe_action_failure_is_fatal value of pe_action_flags
(retaining them for backward API compatibility).
> Refactor: crmd/pengine: implement on-fail=ignore without allow-fail

- pengine/allocate.c
- The "node" that's used in crm_trace() could have been freed
- Make the trace message more reasonable
> Fix: pengine: Prevent use-after-free in sort_rsc_process_order()

- cib/callbacks.c
- cib/callbacks.h
- cib/messages.c
- include/crm/cib.h
- lib/cib/cib_utils.c
- lib/common/xml.c
Well, if all the nodes are running the latest code in legacy mode, CIB doesn't get updated/synchronized correctly.  AFAICS, the legacy mode still requires https://github.com/ClusterLabs/pacemaker/commit/d153b86382516dd2716ff07145ef6a8c499e8d7f to work, right?
I'm still testing the code. I'm pushing them to show the idea. Please help take a look if they make sense.
-  Force plugin-based cluster to be in legacy mode through modifying cib/callbacks.c:cib_legacy_mode().  So multi-master is disabled.
- Keep  lib/common/xml.c: patch_legacy_mode() as it is,  so that it can also benefit from v2 diff format unless  "export legacy=cib" is explicitly set in /etc/sysconfig/pacemaker.
- Recover broadcast by reverting https://github.com/ClusterLabs/pacemaker/commit/d153b86382516dd2716ff07145ef6a8c499e8d …
> Fix cib legacy mode

- cib/callbacks.c
- include/crm/cib.h
- lib/cib/cib_utils.c
This basically reverts https://github.com/ClusterLabs/pacemaker/commit/8211f32ca0a50d5627792044a2164c9cb53a36c1, and add a condition for the assert in send_peer_reply().
> Fix: cib: No need to enforce cib digests for v2 diffs in legacy mode

- include/crm/common/xml.h
- lib/cib/cib_utils.c
- lib/common/xml.c
- tools/cib_shadow.c
- tools/xml_diff.c
Although https://github.com/ClusterLabs/pacemaker/commit/caac728b227bb14b541d32274ea80083e16d21ab fixes the issue of calculating digest with an on-tracking xml. But we'd better not do that with an on-tracking xml at all. This would be very important in case some day we want to switch back to libxml2 xmlNodeDump() function to dump xml string. 
With this refactoring, it  calculates and adds digest for a patchset after doing xml_accept_changes() to the target xml.
> Refactor: cib: Calculate and add digest for a patchset after accepting changes for the target xml

- lib/cib/cib_utils.c
Schema "pacemaker-1.1" has a larger index number than the regular
schemas now.
> Fix: cib: Correctly add "update-origin", "update-client" and "update-user" attributes for cib

- fencing/remote.c
- fencing/standalone_config.c
A couple of one-line fixes for stonith issues
e841639 fixes a bug introduced in 5fcdb10 resulting in an incorrect fencing topology level being chosen for some nodes.
> Stonith fixes

- lib/services/systemd.c
Given that it'll be dealt with in the following logic:
if (unit == NULL) {
crm_debug("Could not obtain unit named '%s'", op->agent);
op->rc = PCMK_OCF_NOT_INSTALLED;
...
> Fix: systemd: No need to trigger assert if cannot obtain an unit

- lib/services/dbus.c
- lib/services/pcmk-dbus.h
- lib/services/systemd.c
- lib/services/upstart.c
The reply timeout of dbus defaults to 25 seconds. That's not sufficient
in case the system is under high load. This commit uses operation timeout
for dbus reply timeout instead.
Does it make sense?
> Fix: dbus: Use operation timeout for dbus reply timeout

- crmd/remote_lrmd_ra.c
without this patch, madness occurs if a resource matches a pacemaker node id.
> Fix: crmd: handle resources named the same as cluster nodes

- extra/resources/Dummy
- lib/services/services.c
- lib/services/services_linux.c
- lib/services/services_private.h
- lrmd/regression.py.in
Resource execution is already serialized in the lrmd, but we've seen that once recurring operations are handed off to the service library that monitor and notify actions can collide.
This patch enforces serialized execution of actions within the service library. If actions are being executed for a resource that already has a pending in-flight action in progress, those actions are put into the 'blocking_ops' list. That list is checked every time an operation is finalized allowing blocked ops to be executed immediately once the in flight operation has completed.
I've included a lrmd regression test that exercises this behavior.
> serialize rsc execution within service library

- attrd/commands.c
- attrd/legacy.c
- attrd/main.c
- cib/main.c
- crmd/callbacks.c
- crmd/control.c
- crmd/membership.h
- fencing/commands.c
- fencing/main.c
- include/crm/cluster.h
- include/crm/cluster/internal.h
- lib/cluster/corosync.c
- lib/cluster/cpg.c
- lib/cluster/heartbeat.c
- lib/cluster/membership.c
- mcp/pacemaker.c
- tools/crm_node.c
These revisions fix RHBZ#1193499 (the "member weirdness" issue) by overhauling peer cache management. Rather than being managed by each daemon's callback, the caches are managed by libcluster automatically, ensuring that exiting nodes are removed from the cache. This incidentally fixes a number of other minor issues, including potential use-after-free bugs, a potential iterator invalidation bug, and incorrect log messages.
> Peer cache overhaul

- crmd/utils.c
- cts/CM_lha.py
- cts/CTStests.py
- cts/patterns.py
- cts/watcher.py
- include/crm/common/logging.h
- lib/cib/cib_native.c
- lib/common/ipc.c
- lib/common/logging.c
- lib/common/mainloop.c
- lib/common/utils.c
- lib/fencing/st_client.c
- lib/lrmd/lrmd_client.c
- lrmd/pacemaker_remote.service.in
- mcp/pacemaker.service.in
- tools/attrd_updater.c
- tools/crm_node.c
In addition to some CTS fixes, this request adds support for split logging, drops the function name from syslog messages, and rephrases some log messages to be more user-friendly. No split logging is actually done yet.
> Make logging more admin-friendly

- lrmd/lrmd.c
This avoids things like nodes getting killed due to hanging stop operations if a start operation caused stonithd to crash.
I saw and debugged this issue on pacemaker 1.1.10+git20130802-1ubuntu2.3 (Ubuntu Trusty). Although the issue manifests itself there due to another bug that is already fixed, it's a bug in its own right, hence this PR. I don't know of any way to trigger this behavior on the current version of pacemaker short of manually killing stonithd in the middle of an op, but it could theoretically happen if stonithd dies for whatever reason.
This is the sequence of events that triggers the bug, conditional on the (long fixed) bug mentioned in PR #334:
1. lrmd gets a start action, and it becomes rsc->active
2. stonithd times out on the action (e.g. stonith device is …
> Fix: lrmd: cancel currently pending STONITH op if stonithd connection is lost

- include/crm/common/xml.h
- lib/cib/cib_ops.c
- lib/common/xml.c
An xpath like "//*[contains(@id,'rsc1')]" or a bad xpath can match xml
nodes that have parent-child relationships among them. That would cause
use-after-free when invoking "cibadmin --delete-all --xpath" with it.
This commit deduplicates xml nodes from xpathObj->nodesetval->nodeTab
as long as any of their parents are also in there.
> Fix: cib: Prevent use-after-free issues when deleting xml nodes with xpath

- cts/CTStests.py
- fencing/README.md
- fencing/commands.c
- fencing/internal.h
- fencing/remote.c
While this includes a couple of minor fixes and some additional developer documentation, the main goal is to lay the groundwork for being able to remap reboot to off+on.
> Minor stonith fixes and refactoring

- extra/resources/Dummy
Prevent the error message on stopping "Dummy" resource:
stderr [ rm: cannot remove '/var/run/Dummy.*.state.serialized': No such file or directory ]
> Fix: RA: Prevent an error message on stopping "Dummy" resource

- fencing/regression.py.in
- fencing/remote.c
This significant refactoring finishes getting the existing code in shape to be usable for remapping sequential topology reboots to all-off-then-all-on.
A remapped operation will need to track each device's timeout, maximum random delay, execution status, required status and node eligibility separately for the operation's "off" and "on" phases, so most of the refactoring is isolating that handling so it can be reused.
> Refactor stonith code to prepare for remapped reboots

- lib/pengine/unpack.c
- pengine/allocate.c
Failures need to be cleared correctly, not just ignored.
Also clearing failures needs to happen before we allow the connection to be re-established.
This fixes issues discovered while running the docker pcmk remote regression tests 'phd_docker_autogen -c 3 -b 6 -I 300'
> High: pengine: clear failures after reconnect_interval expires

- attrd/commands.c
- cib/main.c
- crmd/throttle.c
- cts/CIB.py
- fencing/remote.c
- lib/cib/cib_ops.c
- lib/cluster/membership.c
- lib/fencing/st_client.c
- lrmd/lrmd.c
- tools/fake_transition.c
This request fixes a number of unrelated bugs. The most important commit works around an issue introduced with a8de240 where the CIB can core-dump on exit due to the peer status callback destroying the peer cache. The others fix a minor issue in CTS and several minor issues reported by valgrind.
> Misc. bug fixes

- crmd/lrm.c
The behavior was mistakenly changed by 5824e7a. Any parameters with
unique="1" should be added into the "op-force-restart" list, instead of
the ones with unique="0".
> Fix: crmd: Do not enforce restart for changes of non-unique parameters

- fencing/main.c
The behavior was mistakenly changed by commit df1825e. Given the
condition (type == crm_status_uname), we would never know peers'
unames unless we initiated a fencing, started a STONITH_OP_QUERY and
received uname broadcasts from peers. However, according to the logic
related to uname in fencing_peer_active(), we didn't actually calculate
the correct number of expected replies before we started the
STONITH_OP_QUERY. Hence, we would ignore the later but valuable replies,
and could mistakenly think no one could fence the target node, which would
introduce fencing failure.
This commit reverts the condition of sending uname broadcasts back to
(type != crm_status_processes). So nodes will broadcast unames as early
as possible, once a peer's state has changed.
> Fix: fencing: Broadcast uname as soon as a peer's state has changed

- attrd/commands.c
- attrd/legacy.c
- crmd/crmd_utils.h
- crmd/join_client.c
- crmd/join_dc.c
- crmd/membership.c
- crmd/pengine.c
- crmd/te_callbacks.c
- crmd/utils.c
- include/crm/cib.h
- include/crm/cib/internal.h
- lib/cib/cib_client.c
- lib/cib/cib_utils.c
Previously, freeing of CIB callback user data was left to the calling application (in the pacemaker code base, it was done in the callbacks themselves). That resulted in leaks when libcib removed callbacks without calling them first (e.g. when a callback for an existing call ID was replaced, or when the entire table was dropped). Now, callers can register a free function with the callback, and libcib will manage the memory.
This involves public API additions but no changes or removals. However there are two changes in behavior: (1) if num_cib_op_callbacks() is called from a callback, its return value will now include the currently executing callback (i.e. it will be 1 more than before); and (2) applications that use CIB callbacks must not free the callback user data (which would cause a …
> Fix memory leaks in CIB callbacks

- lib/cluster/legacy.c
- tools/crm_node.c
- valgrind-pcmk.suppressions
These trivial revisions fix some minor issues found when running CTS in a CMAN cluster under valgrind.
> Minor CMAN cleanup

- cib/callbacks.c
- cib/callbacks.h
- cib/main.c
- cib/messages.c
- cts/CTStests.py
- fencing/commands.c
- lib/services/upstart.c
Previously, a workaround was added to the peer cache handling because the CIB peer status callback could destroy the peer cache tables. This is an actual fix, so that the CIB no longer does that.
Two unrelated minor commits fix a CTS pattern issue and a potential memory issue.
> Peer cache fix

- lrmd/pacemaker_remote.service.in
- mcp/pacemaker.service.in
Since systemd-218[1], systemd will emit following lines in the journal
upon (re)loading its configuration:
Support for option SysVStartPriority= has been removed and it is ignored
As it allegedly had no importance for some time even before, simply
drop it.
[1] http://cgit.freedesktop.org/systemd/systemd/commit/?id=9e37c95
Signed-off-by: Jan Pokorný <jpokorny@redhat.com>
> Low: drop legacy SysVStartPriority from service units

- crmd/lrm_state.c
Fix: Set the attribute from remote node.
* The characteristic by attrd_updater carried out in the node that is remote by way of proxy is not surely set.
```
[root@sl7-01 ~]# crm_mon -1 -Af
Last updated: Thu Jul 30 10:41:10 2015          Last change: Thu Jul 30 10:41:07 2015 by root via cibadmin on sl7-01
Stack: corosync
Current DC: sl7-01 (version 1.1.13-b2b4950) - partition WITHOUT quorum
3 nodes and 4 resources configured
Online: [ sl7-01 ]
RemoteOnline: [ snmp1 snmp2 ]
(snip)
Node Attributes:
* Node sl7-01:
* Node snmp1:
* Node snmp2:
Migration Summary:
* Node sl7-01:
* Node snmp1:
* Node snmp2:
[root@snmp1 ~]# attrd_updater -n test -v 100
[root@sl7-01 ~]# crm_mon -1 -Af
Last updated: Thu Jul 30 10:41:32 2015          Last change: Thu Jul 30 10:41:07 2015 by root via cibadmin on sl7-01 …
```
> Fix: Set the attribute from remote node.

- include/crm/common/ipc.h
- include/crm/common/ipcs.h
- lib/common/ipc.c
Previously, pick_ipc_buffer() compared two integers, which made the following true:
0 > 0x80000000
That would trigger assert in crm_ipc_prepare():
CRM_ASSERT(result != NULL);
Besides, crm_ipc_prepare() and pick_ipc_buffer() could suggest negative
values for PCMK_ipc_buffer.
This commit fixes these by using "unsigned int".
> Fix: ipc: Correctly compare values for the size of ipc buffer and prevent suggesting a negative value when it's insufficient

- fencing/remote.c
- tools/crm_simulate.c
on an s390x system:
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ha_set_tm_time (source=0x0, target=0xb188f960) at iso8601.c:1004
1004        if (source->tm_year > 0) {
(gdb) bt
#0  ha_set_tm_time (source=0x0, target=0xb188f960) at iso8601.c:1004
#1  crm_time_set_timet (target=0xb188f960, source=source@entry=0x3ffffa670a0) at iso8601.c:1037
#2  0x0000000080004f26 in get_date (data_set=0x3ffffa67218, data_set=0x3ffffa67218) at crm_simulate.c:72
#3  0x0000000080003d20 in main (argc=<optimized out>, argv=0x3ffffa67538) at crm_simulate.c:789
This commit fixes the cast in get_date() which would result in incorrect
values for arches with 64bit time_t
> Fix: crm_simulate: Prevent segfault on arches with 64bit time_t

- fencing/commands.c
- fencing/internal.h
- fencing/main.c
- fencing/remote.c
This brings handling of automatic unfencing in line with the currently intended behavior, i.e. "automatic" and (legacy) "required" fence agent action parameters apply only to "on" actions.
> Simplify automatic unfencing

- crmd/lrm_state.c
Resolve memory leak introduced by 446a100. I don't see the necessity of using crm_element_value_copy() in here. It appears to have introduced memory leak.
> Fix: crmd: Resolve memory leak in remote_proxy_cb()

- crmd/lrm_state.c
- lrmd/ipc_proxy.c
Every time a user carries out crm_mon and cibadmin in remote node via
proxy, log outputs it.
In addition, log outputs it every time a resource executes a command
with monitors in remote node.
```
Jun 24 16:11:26 bl460g8n1 crmd[58595]: info: new remote proxy client established to cib_ro, session id 25f2ce7e-44bd-450a-8311-b9969a70fbc6
Jun 24 16:11:26 bl460g8n1 crmd[58595]: info: new remote proxy client established to cib_rw, session id 04b53915-1912-4dcd-b878-1eee549485fc
Jun 24 16:11:26 bl460g8n1 crmd[58595]: info: new remote proxy client established to cib_ro, session id 8984746d-ecdd-4bdd-8ee4-c5c0b5952d33
Jun 24 16:11:26 bl460g8n1 crmd[58595]: info: new remote proxy client established to cib_rw, session id fa36c226-92c8-403e-ba2d-a56cfe441162
Jun 24 16:11:27 bl460g8n1 crmd[58595]: …
```
> Low: Change the log of the noise to the trace log.

- lib/common/ipc.c
Previously, the suggested size for PCMK_ipc_buffer could be constantly
doubled every time the error was encountered, which leaded to confusion.
This commit also changes the logging format to indicate the size of the
original message.
> Fix: ipc: Do not constantly increase suggested size for PCMK_ipc_buffer every time we find it's insufficient

- lib/pengine/unpack.c
It is like the problem that entered when you summarized an old judgment
in function (record_failed_op) by the next correction.
*https://github.com/ClusterLabs/pacemaker/commit/9cd666ac15a2998f4543e1dac33edea36bbcf930#diff-7dae505817fa61e544018e581ee45933
> Fix: pengine: The failed action of the resource that occurred in shutdown is not displayed.

- lib/services/services.c
They occurred for every monitor operation of systemd resources.
> Log: services: Reduce severity of noisy log messages

- lib/common/xml.c
Otherwise if nothing else changed in the new xml, even the versions
weren't bumped, crm_diff would output an empty xml diff.
>  Fix: xml: Mark xml nodes as dirty if any children move

- cib/callbacks.c
- lib/cib/cib_ops.c
The cib_config_change() function only applies to v1 diffs. Previously,
if cib was running in legacy mode while using v2 diff format, it would
get incorrect result from the function and refuse to write back on-disk
cib on the slave node.
> Fix: cib: Check if the configuration changes with cib_config_changed() only for v1 diffs

- fencing/commands.c
- fencing/main.c
- include/crm/fencing/internal.h
- lib/fencing/st_client.c
12ca8bb broke the stonith regression tests, and a4f67f5 fixed the regression tests but broke normal stonith operation. This reconciles the two.
> Use fencing level tag consistently in internal XML

- lib/common/xml.c
When CDATA is included in metada of the resource, an error occurs.
Oct  9 09:35:57 rh66-tomcat1 crmd[11182]:    error: crm_abort: pcmkRegisterNode: Triggered assert at xml.c:595 : node->type == XML_ELEMENT_NODE
The present conditions are only resources of tomcat, but, in
consideration of the future, should ignore CDATA.
/usr/lib/ocf/resource.d/heartbeat/tomcat
(snip)
<parameter name="tomcat_name" unique="1" >
<longdesc lang="en"><![CDATA[
The name of the resource, added as a Java parameter in JAVA_OPTS:
-Dname=<tomcat_name> to Tomcat process on start. Used to ensure
process is still running and must be unique.
]]></longdesc>
<shortdesc>The name of the resource</shortdesc>
<content type="string" default="" />
</parameter>
(snip)
Best Regards,
> Low: libcommon: Ignore CDATA of metadata of the resource.

- cib/callbacks.c
Sbd repeatedly sends noop requests to cib. This makes it less noisy.
> Log: cib: Downgrade the log message on forwarding CRM_OP_NOOP requests  from INFO to DEBUG

- lrmd/lrmd.c
When cleaning up or reprobing a resource, the resource will be
unregistered from lrmd. In free_rsc(), when it loops over
rsc->pending_ops and rsc->recurring_ops GLists, cmd_finalize() is
invoked either directly or via a callback, which removes elements from
the GLists. Previously, with the for loops, this could break the
iterating of the lists and miss the following elements in the lists.
If a resource was configured with multiple monitor operations, cleanup
command would not cancel all existing monitor operations. This could
cause unexpected monitor failures to occur after the resource was
stopped on the node.
The while loops are more appropriate for handling them.
> Fix: lrmd: Finalize all pending and recurring operations when cleaning up a resource

- lib/services/systemd.c
An user's system encounters high load, which leads to monitor timeout of systemd resources. Then the connection to system dbus is found to be closed.
I think in that case we should try to reconnect. Please check if I've missed anything.
> Fix: systemd: Reconnect to System DBus if the connection is closed

- lib/services/dbus.c
- lib/services/services.c
- lib/services/services_linux.c
- lib/services/services_private.h
- lib/services/systemd.c
- lib/services/systemd.h
- lib/services/upstart.c
- lib/services/upstart.h
Fix: services: Correctly determine if operations are in-flight
Previously, we kind of abused the return codes of upstart_job_exec(),
systemd_unit_exec() and services_os_action_execute(). For an
asynchronous operation, the return code is supposed to tell whether the
'op' should be freed by the caller. It doesn't exactly indicate whether
the 'op' is in-flight.
For instance, in services_os_action_execute(), if stat() or fork() fail,
operation_finalize() will be called for an asynchronous operation, which
will free the operation and return TRUE if the operation is
non-recurring. But in action_async_helper(), the freed operation
would be considered in-flight and added into inflight_ops list.
> Fixes for the execution functions of services

- lib/services/dbus.c
- lib/services/systemd.c
Previously, as long as we could not get the path of the unit via
LoadUnit, it would return PCMK_OCF_NOT_INSTALLED, which is a hard error.
It should not return PCMK_OCF_NOT_INSTALLED unless it's sure about that.
For uncertain errors such as "org.freedesktop.DBus.Error.NoReply", it
should return PCMK_OCF_UNKNOWN_ERROR instead.
> Fix: systemd: Return PCMK_OCF_UNKNOWN_ERROR instead of PCMK_OCF_NOT_INSTALLED for uncertain errors on LoadUnit

- tools/crm_resource_runtime.c
Previously, it only cleaned up the first primitive in an anonymous
cloned group.
> Fix: crm_resource: Correctly clean up all children for anonymous cloned groups

- lib/services/services.c
2091b55f set dbus-specific structure member to NULL without wrapping in
SUPPORT_DBUS. Fixed by removing the relevant lines b/c they were unnecessary
due to structure being calloc'ed.
> Fix: libservices: restore build without dbus

- include/crm/common/logging.h
- include/crm/common/xml.h
- lib/common/xml.c
- lib/fencing/st_client.c
crm_resource --show-metadata drops documentation strings for fencing agents
crm_resource --show-metadata works fine for normal OCF agents and STONITH plugins, but when run on fencing agents, e.g.:
crm_resource --show-metadata=stonith:fence_drac
then all the parameters have empty <shortdesc> elements.  This prevents "crm ra info" from showing anything particularly useful for fencing agents.
>  crm_resource --show-metadata drops documentation strings for fencing agents

- attrd/commands.c
- crmd/cib.c
- crmd/crmd_fsa.h
- crmd/lrm.c
- crmd/te_actions.c
- crmd/te_callbacks.c
- crmd/te_events.c
- crmd/te_utils.c
- include/crm/cluster.h
- include/crm/cluster/internal.h
- include/crm/common/xml.h
- lib/cluster/membership.c
The most significant commit in this request modifies match_down_event() to match only fence and shutdown events (previously it would sometimes mistakenly match clear-failcount).
The other commits are some simple refactors that will come in handy when we start tracking pacemaker_remote node member/lost state.
> Fix minor bug when matching down events

- crmd/notify.c
- crmd/notify.h
- fencing/admin.c
- fencing/commands.c
- fencing/internal.h
- fencing/main.c
- fencing/regression.py.in
- fencing/standalone_config.c
- include/crm/fencing/internal.h
- include/crm/stonith-ng.h
- lib/fencing/st_client.c
This adds support for target-by-attribute to the libfencing API, stonith_admin and regression tests.
It also includes two unrelated commits for fixing some issues with timeout handling.
> Finalize support for targeting fencing by node attribute

- crmd/lrm_state.c
there is a duplicate line in function fail_pending_op(crmd/lrm_state.c)
> remove a dup line from function fail_pending_op

- lib/common/utils.c
crm_make_daemon() cannot make Pid file.
Please reflect it to master.
> High : Mistake of the parameter order.

- configure.ac
Header checks use the preprocessor so don't look at CFLAGS.
> Fix detection of heartbeat headers on FreeBSD

- tools/crm_resource.c
When the first character of the argument is a colon, the original code
printed uninitialized memory, because sscanf returned 0.  For example:
$ /usr/sbin/crm_resource --list-agents=:
No agents found for standard=øDÀ, provider=
This patch avoids using arbitrarily sized buffers, and separates
standard and provider by changing argv through the optarg pointer.
> crm_resource --list-agents: don't print uninitialized memory

- lib/common/remote.c
(I wanted to report it as an issue, however, it seems to be disabled on Github, so proposing a little fixup.)
When parsing a compressed message, message header is reloaded from the
uncompressed buffer. However, because remote->buffer_offset is zeroed
prior that, it'll consider the buffer already processed and return NULL.
Zeoring remote->buffer_offset after header retrieval should remedy this.
AFAICS, the decompression branch is not used so this perhaps is not an
issue in the real world.
> Fix: header == NULL when parsing compressed message

- lib/services/systemd.c
- lrmd/lrmd.c
have lrmd wait till systemd actually starts bringing down systemd resources
instead of being confused if service is still active on first status
send a reload to systemd whenever a unitfile is changed instead of doing
this just with every 10th change
> Fix RHBZ#1165423: Do an ordered shutdown of systemd resources

- configure.ac
I have no idea what this whole "sanitizing" business is supposed to do in `configure.ac`, but it complicates the packaging of Pacemaker in Debian, so I decided to start a discussion here. The current best packaging practice recommends adhering to the [multiarch specification](https://wiki.ubuntu.com/MultiarchSpec), and this is backed by very good tool support. Straightforward packaging thus results in `configure` calls like
```
./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --libexecdir=\${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --disable-static …
```
> Don't override any libdir containing $prefix

- lib/common/ipc.c
- lib/common/utils.c
- lib/services/services_linux.c
With the following patches I'm now able to run a simple 3 node cluster on Debian 8.2, FreeBSD 9.3, and FreeBSD 10.1 with an ocf:pacemaker:ping RA which I can migrate between them.
> improved freebsd support

- tools/cib_shadow.c
Previously, shells that don't support --noprofile option failed to be
invoked. So far as I've seen, only bash supports --noprofile option.
> Fix: crm_shadow: Do not invoke shells with --noprofile option other than bash

- fencing/commands.c
- fencing/internal.h
When executing a stonith action, stonith_action_async_done() can
re-invoke internal_stonith_action_execute(). In that case, it will
introduce a new pid for the action, which can not be tracked by the
invoker of stonith_action_execute_async().
This commit fixes it by tracking the (async_command_t *)op.
> Fix: fencing: Correctly track active stonith actions

- crmd/lrm_state.c
- lib/lrmd/proxy_common.c
Previously, the relevant remote proxies would still exist even if a
remote node was already disconnected. So whenever there was an event, it
would still trigger remote_proxy_dispatch_internal(). Especially if the
remote node was unexpectedly disconnected, lrmd_tls_send() would fail to
relay the event and call lrmd_tls_disconnect() again. It actually always
occurred when reconnecting to the remote node, which basically made
reconnecting impossible.
> Fix: crmd: Disconnect the relevant remote proxies as well when disconnecting a remote node

- pacemaker.spec.in
Since pacemaker-remote needs these directories as well.
> Build: spec: Move the common directories under /var/lib/pacemaker into pacemaker-cli package

- crmd/callbacks.c
- crmd/crmd_lrm.h
- crmd/crmd_messages.h
- crmd/lrm.c
- crmd/membership.c
- crmd/messages.c
- crmd/remote_lrmd_ra.c
- crmd/te_events.c
- crmd/te_utils.c
- include/crm/cluster.h
- include/crm/crm.h
- lib/cluster/cluster.c
- lib/cluster/membership.c
Track whether Pacemaker Remote nodes are up or down, in the remote peer cache (on the connection host and the DC) and in the CIB. This narrows the difference between cluster nodes and Pacemaker Remote nodes, and allows quicker recovery and resource placement after failures.
> Track status of Pacemaker Remote nodes

- lib/common/ipc.c
e5964d5 changed the logic in pick_ipc_buffer(). It doesn't look right
to let the parameter "max" affect "global_max". And any following
invocations would basically ignore "max" and directly return "global_max".
> Fix: ipc: Respect the parameter of pick_ipc_buffer() but don't let it affect the global value

- tools/cib_shadow.c
The command line flag for crm_shadow --display is 'p', but the command
section looks for 'P', so the crm_shadow --display command never
actually does anything.
This commit fixes the typo.
> Fix: crm_shadow: fix broken --display command

- doc/Pacemaker_Explained/en-US/Ch-Resources.txt
- extra/resources/Dummy
- extra/resources/HealthCPU
- extra/resources/Stateful
This fixes a simple typo, which spread out. Beyond that, the `HA_VARRUN` variable is undocumented. Its usage seems to stem from [[Linux-ha-dev] Pseudo RAs do not work properly on Corosync stack](http://lists.linux-ha.org/pipermail/linux-ha-dev/2010-March/017258.html) (commit baef7d98), but I wonder if the original reason still applies and warrants polluting the `/var/run` directory with state files. Isn't `HA_RSCTMP_OLD=/var/run/heartbeat/rsctmp` the directory Heartbeat removes on start? `HA_RSCTMP=/var/run/resource-agents` was invented in the above thread, if I read it correctly.
> Fix state file metadata in Dummy, Stateful and HealthCPU resource agents

- mcp/pacemaker.sysconfig
> The default IPC buffer size is 128k since 1.1.10 (8196f23a)

- lib/services/services_linux.c
Explicit commented assert will ease the code comprehension.
> Low: action_launch_child is effectively noreturn

- pacemaker.spec.in
This is because of the license of the initscripts.
> Build: spec: declare also BSD license as suitable

- lrmd/tls_backend.c
This fixes http://bugs.clusterlabs.org/show_bug.cgi?id=5269
> Fix: remote: cl#5269 - Notify other clients of a new connection only if the handshake has completed (bsc#967388)

- extra/cluster-init
- xml/Makefile.am
This change effectively reverts [8ebeb52] and re-does the intended
compatibility enhancement in a less intrusive (and hopefully more
compatible) way + the same is applied at another instance of
'BRE-imposed, ERE-unsupported backslashing of meta-plus'.
Note that there is a counter-proposal by Ken:
<https://github.com/ClusterLabs/pacemaker/pull/938>
It is expected that -E switch will eventually become fully adpoted by
main "sed" implementations, but at this point it seems unwise to drop
backward compatibility (with up to at least ~2008 POSIX)  altogether:
<http://austingroupbugs.net/view.php?id=528>
<https://github.com/ClusterLabs/pacemaker/pull/861#commitcomment-16356114>
[8ebeb52] https://github.com/ClusterLabs/pacemaker/pull/861
> Low: rethink sed command complexity vs. compatibility trade-off

- lib/cib/cib_attrs.c
Previously, if a remote node already existed under
/cib/configuration/nodes/, query_node_uuid() would return
*is_remote_node = FALSE for it though.
> Fix: libcib: Correctly determine the node type

- crmd/utils.c
- tools/crm_attribute.c
- tools/crm_resource_runtime.c
Legacy attrd cannot handle attributes for remote nodes. Fix it by
conditionally reverting part of 488d82f.
> Fix: crmd,tools: Set attributes for remote nodes directly into cib if it's legacy attrd

- attrd/commands.c
This patch becomes the contents which came out in a discussion of next pullrequest.
* https://github.com/ClusterLabs/pacemaker/pull/946
> Low: attrd: If a value of dampen is a negative number, attrd outputs warn log.

- pengine/clone.c
In clone_update_actions_interleave(), if first_task is "demote", but
first is not actually being demoted, the demote action doesn't exist
(first_action == NULL). Do not trigger assert for this case.
> Fix: pengine: Suppress assert if a stateful clone is not being demoted

- attrd/commands.c
- attrd/main.c
- include/crm_internal.h
- lib/common/utils.c
- tools/attrd_updater.c
Hi All,
I added the support of the change of dampen by attrd and attrd_updater.
I added a function to change the value only for dampen and a function to change the combination of dampen and value.
The command-line of attrd_updater is as follows.
1)Change the combination of dampen and value.
attrd_updater -B value -n name -d dampen
2)Change the value only for dampen.
attrd_updater -Y -n name -d dampen
It is necessary to discuss the next matter.
* https://github.com/ClusterLabs/pacemaker/pull/906
* https://github.com/ClusterLabs/pacemaker/pull/946
Best Regards,
Hideo Yamacuhi.
> Mid: attrd: Support of the dampen change by attrd.

- configure.ac
This fixes detecting libqb when it is outside the default library search path, in /opt/lib for example.
I found out the hard way that we assume -lqb is in $LIBS in too many places. Ideally we should explicitly link with $libqb_LIBS, but that can come later.
> Take pkg-config result into account when checking for libqb

- crmd/te_actions.c
8b98a9b2 introduced a regression such that if a node that has never been seen
is fenced and remains unseen after the fence, it will incorrectly remain
unclean, because the cluster state will never be updated in the CIB.
> Fix: crmd: update cluster state in CIB after fencing an unseen node

- GNUmakefile
- pacemaker.spec.in
Make natively generated spec and archive versioning cope better with post-releases (snapshots) and avoid full hashes in the source tarballs.
> Build: spec: better revision and version schema

- extra/resources/ping
When generating man pages for the agents:
pacemaker/extra/resources/ping: line 357: ocf_is_true: command not found
Note that neither set of "true" indicators (those in ocf_is_true
function of ocf-shellfuncs[*] file vs. those recognized as values
of "debug" OCF parameter in the very script) is a subset of the other,
but acknowledge that latter is a master on its own domain
(at least for now, also to avoid regression when "True" is used).
[*] as an aside, there's also an almost anecdotical "ja" Germanism
> Low: ping resource: avoid undefined func w/ OCF_FUNCTIONS=/dev/null

- .gitignore
- configure.ac
- doc/Makefile.am
- doc/publican-clusterlabs/xsl/html-single.xsl
- doc/publican-clusterlabs/xsl/html.xsl
- doc/publican-clusterlabs/xsl/pdf.xsl
- pacemaker.spec.in
There are cases one wants to avoid Publican being involved in the build
process at all (for instance, if a local copy is too old to behave
gracefully with what build process requires).
We avoid introducing a new configure option by (sort of) overloading
--with-brand one.
See also rhbz#1326350 (instructing configure using --with-brand=
would then help).
> Build: explicitly allow skipping Publican building docs and sanitize docs building as such

- lib/pengine/unpack.c
- pengine/regression.sh
- pengine/test10/multiple-monitor-one-failed.dot
- pengine/test10/multiple-monitor-one-failed.exp
- pengine/test10/multiple-monitor-one-failed.scores
- pengine/test10/multiple-monitor-one-failed.summary
- pengine/test10/multiple-monitor-one-failed.xml
Previously with d87de1b, if not all the configured monitor operations
failed, the resource could be considered running well.
This commit fixes it by conditionally "clear_past_failure".
> Fix: pengine: Consider resource failed if any of the configured monitor operations failed

- extra/resources/ping
ping RA doesn't work correctly with IPv6 addresses, it should use `fping6`instead of `fping`. I've implemented very simple address parsing that is not as precise as that in [resource agents](https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/findif.sh), however, it makes do only with shell builtins.
Cc: @gao-yan
> Fix: ping resource: Use fping6 for IPv6 hosts

- cib/main.c
- fencing/commands.c
- fencing/internal.h
- fencing/main.c
- fencing/remote.c
Fix: cib/fencing: Set status callback before connecting to cluster
Otherwise, we'd at least miss the initial call to crm_status_callback():
init_cs_connection_once() -> crm_get_peer() -> crm_update_peer_uname()
-> crm_status_callback()
Previously for stonithd, it would not be able to broadcast its uname at
the earliest time, which could potentially introduce other issues.
> Fix issues of fencing by nodeid

- extra/resources/SysInfo
This also improves the description about the parameter "min_disk_free"
and the node attribute "#health_disk" in the metadata.
> Fix: RA: SysInfo - Reset the node attribute "#health_disk" to "green" when there's sufficient free disk

- attrd/commands.c
The logic in attrd_peer_update() from 361e125:
if(a == NULL) {
if (safe_str_eq(op, ATTRD_OP_UPDATE) || safe_str_eq(op, ATTRD_OP_UPDATE_BOTH)) {
a = create_attribute(xml);
} else {
crm_warn("Update error (attribute %s not found)", attr);
return;
}
}
ignored the xml children of ATTRD_OP_SYNC_RESPONSE and broke the
synchronization of attributes.
> High: attrd: Fix the synchronization of attributes

- crmd/cib.c
- crmd/control.c
- crmd/notify.c
- crmd/notify.h
- extra/alerts/pcmk_alert_sample.sh
- extra/alerts/pcmk_snmp_helper.sh
- include/crm/msg_xml.h
some more renaming notify -> alert in the publicly exposed headers and sample-scripts
add attribute sanity checking
spare additional cib query for alerts
rename tstamp_format to more consistent timestamp-format
left out updated "Pacemaker Explained" so far in favour of not committing anything inconsistent
> Alert cleanup

- lib/cluster/legacy.c
This is so as to fix
http://clusterlabs.org/pipermail/users/2016-May/002902.html
> Low: hide the unused function when compiling w/o CMAN support

- mcp/pacemaker.in
[Updated PR #993 to use "local" and rebase against 1.1 branch]
In the original variant, function status() overwrite $rtrn 'in global
scope' which leads to a pretended failing stop() function and
respectively failing initscript when called with action stop.
References: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=686548
Signed-off-by: Christian Schneider <christian.schneider@aoe.com>
Signed-off-by: Christoph Berg <myon@debian.org>
> Fix init script return status

- GNUmakefile
This is just a parallel to commit 5401f3b that covered just spec proper
(without GNUmakefile-predestined preprocessing, it actually works just
fine for pre-releases... it might be a good idea to eliminate the
accumulated redundancy there, eventually, perhaps as a partial revert
of c071e92 that wasn't necessarily correct as one should be still able
to pass "--define '_with_FOO 1'" to rpmbuild as an alternative).
> Build: let "make [s]rpm" use pre-/post-release logic from spec proper

- tools/crm_mon.c
On x32, time_t is long long, but long is only 32bits, so sprintf("%ld", time_t)
will error out. Fix by always casting to long long which is long enough on any
platform.
(This is #1010 rebased onto 1.1.)
> Fix time formatting on x32

- lib/fencing/st_client.c
Neither WIFSTOPPED nor WIFCONTINUED could evaluate to true here, because
the waitpid() calls above lack the WUNTRACED and WCONTINUED flags.  Since
we don't use ptrace() this is an "impossible" branch, but it's best to
have the raw status value around to enable post-mortem manual decoding.
This patch also enhances portability, because WIFCONTINUED is not defined
on Hurd (at least).
> st_client: print the full unexpected status value from waitpid()

- lrmd/pacemaker_remote.in
- mcp/pacemaker.in
Because pacemaker and pacemaker-remote both need /usr.
> Add $remote_fs dependencies to the init scripts

- crmd/lrm.c
- crmd/lrm_state.c
Previously, putting a remote connection resource into maintenance mode
would cause crmd hanging on waiting for the cancellation of the monitor
operation to return until it timed out.
The cancellation operation for a remote connection resource is
synchronous. We should acknowledge it directly.
> Fix: crmd: Acknowledge cancellation operations for remote connection resources

- lib/services/services_linux.c
Modern compilers will fail with "ignoring return value of ‘write’,
declared with attribute warn_unused_result" otherwise.
(In my tests with gcc 5.3 on GNU Hurd, it wasn't enough to simply cast
the return value to (void) which is often suggested as a way to suppress
this kind of error.)
> Suppress unused result warning in signal handler

- .travis.yml
This prevented Travis CI to catching on the commits for/at this branch
completely.
Reference:
https://en.wikipedia.org/wiki/YAML#Casting_data_types
> Build: travis: avoid implicit cast of 1.1 branch to float

- lib/pengine/clone.c
- lib/pengine/native.c
- tools/crm_resource_runtime.c
* consistently use 'Slave', not sometimes 'Slave', sometimes 'Started'
* only report target role, if it is the limitation (target-role:Slave)
Both target-role Master and target-role Started
do not limit us in any way.
> crm_mon: consistently print ms resource state

- lib/pengine/unpack.c
Hi All,
I made the next modifications before.
* https://github.com/ClusterLabs/pacemaker/pull/782
This correction was to revise that the trouble information at the time of the stop disappeared.
For example, trouble occurred in Dummy resource at the time of a node stop, and the trouble information was not displayed when stonith failed.
However, my correction of the past had a problem.
After a resource broke down in a node having stonith, the trouble information is displayed in crm_mon even if I stop the node.
```
Online: [ pm02 ]
OFFLINE: [ vm01 ]
Full list of resources:
prmDummy1      (ocf::heartbeat:Dummy): Started pm02
Resource Group: grpStonith1
prmStonith1-1      (stonith:external/xxxxx1):      Stopped
prmStonith1-2      (stonith:external/xxxxx2):        Stopped
Resource Group: …
```
> Mid : pengine : Correction of the record judgment of the failed information.

- lib/services/systemd.c
I've been trying to manage a `name.socket` unit, but the existing code translates this to `name.socket.service`. This change fixes that.
> Allow unit names ending in .socket.

- crmd/notify.c
Hi All,
I referred to fencing/remote.c.
* https://github.com/HideoYamauchi/pacemaker/blob/change_alert_desc/fencing/remote.c#L509
I included action and delegate in content of desc of fencing in the same way.
The present trap.
```
May 30 14:26:23 snmp-manager snmptrapd[32068]: 2016-05-30 14:26:23 
pgsr02 [UDP: [192.168.100.177]:57155->[192.168.100.189]:162]:
(snip)
PACEMAKER-MIB::pacemakerNotificationOperation = STRING: "st_notify_fence"       
PACEMAKER-MIB::pacemakerNotificationDescription = STRING: "Operation st_notify_fence requested by pgsr02 for peer pgsr01: OK (ref=3fa43de3-6be4-4789-bf53-da82dd5f6526)"        
PACEMAKER-MIB::pacemakerNotificationReturnCode = INTEGER: 0
```
Trap after the change.
```
Jun 16 14:37:26 snmp-manager snmptrapd[30062]: 2016-06-16 14:37:26 
pgsr02 [UDP: …
```
> Low: crmd: Change desc of alert of the fencing.

- extra/alerts/alert_file.sh.sample
- extra/alerts/alert_smtp.sh.sample
I think it's better to install the sample alert scripts as executable to make them easier to try out.
The rest is argued for in the commit messages.
Please consider incorporating these changes.
Thanks.
> Alert fixes

- include/crm/pengine/rules.h
- lib/pengine/rules.c
- pengine/constraints.c
- xml/constraints-2.6.rng
It was already possible to use regexp in a resource name location applies to.
Now it is also possible to use sed-like %0 - %9 references in both
score-attribute and rule expression to construct attribute names.
(% is used instead of \ to make crmsh almost happy).
Also, fix rsc_pattern is missing from constraints rng ecept constraints-next.
> Feature: Allow regexp substitutions in location constraints

- lrmd/pacemaker_remote.in
Originally it was set to the daemon name (pacemaker_remoted), but that's
out of line with the script name, the systemd service name and the general
trend, which the main Pacemaker daemon follows as well.
Differing names also break the automatic synchronization of SysV init and
systemd service statuses (as done in Debian at least).
> pacemaker_remote: set LSB Provides header to the service name

- attrd/legacy.c
Signed-off-by: Masatake YAMATO <yamato@redhat.com>
> Refactor: use defined macro instead of string literal in attrd

- extra/alerts/alert_snmp.sh.sample
small but annoying if you want to copy out cib-xml to configure
> fix: extra: correct quoting of timestamp-format in alert-snmp-example

- fencing/fence_legacy
Cluster-glue stonith agents have their own parameters for the host
list. We need to query the devices and get the so-called dynamic-list
via "stonith -l", which invokes "gethosts" action of the cluster-glue
stonith agents.
> Fix: fencing: fence_legacy - Search capable devices by querying them through "list" action for cluster-glue stonith agents

- lib/pengine/utils.c
This feature resulted from discussions at OpenStack Summit - Austin 2016 and later discussions on the users@clusterlabs.org mailing list. It allows resource agents to know whether a demote or stop action will be followed by a start in the same transition, so they can optimize appropriately.
> Improve trace logging when finding actions

- lib/common/watchdog.c
- mcp/pacemaker.sysconfig
Hi All,
We want to allow us to change action when we reboot in fail_fast and sbd so that panic rises.
Because I want to acquire information at the time of these actions using kdump.
I want you to merge it because we want to use this feature from Pacemaker-1.1.14.
> wd: Correction to do to change action of the system reboot by fail_fast

- include/crm_internal.h
It's not in use as of 18e78014a3973eebdc323ba92d7ffd22f33e04c1.
Sidenote: at least with corosync v2, this symbol is normally defined
in libcorosync_common.so.
> Refactor: drop qb_to_cs_error emulation when !defined(CS_USES_LIBQB)

- extra/resources/ping
In fping_check, two temporary files are created in /tmp.
If /tmp is full, the creation fails silently and subsequently
the ping registers no connection to the targets.
With this change, the problem is caught and reported.
> Low: ping: Log sensible error when /tmp is full (bsc#987348)

- .gitattributes
- git management files themselves
- Travis CI related files
> Maint: mark files not appropriate for automatic archive files

- crmd/messages.c
Hi All,
When the load of the cluster is high, the action is limited by throttle function.
However, the cluster cannot carry out the action of the graph until an action carrying out is completed when load becomes mild.
When the load of the cluster changed, this correction carries out a feasible action and carries out a feasible action with parallelism.
Best Regards,
Hideo Yamacuhi.
> Mid: crmd: When node load was reduced, crmd carries out a feasible action.

- tools/crm_mon.c
3844f09 considered the changes in cib status that should be ignored.
But actually it still reported errors for any changes of cib
configuration.
Given that we only care about the xml objects that may contain
lrm_rsc_op anyway, downgrade the message to trace for all the other
cases.
> Log: crm_mon: Avoid logging errors for any CIB changes that we don't care about

- mcp/pacemaker.in
If "stop --skip-cman" is specified, the pacemaker init script will never
stop CMAN. This allows higher-level tools to preserve quorum for DLM-based
resources while stopping pacemaker on all nodes, then stop CMAN on all nodes.
> Feature: mcp: allow stopping Pacemaker without stopping CMAN

- crmd/election.c
- crmd/lrm.c
- crmd/te_callbacks.c
- lib/common/xml.c
- lib/pengine/unpack.c
A thread on the users@clusterlabs.org mailing list, "DC of the election will be an infinite loop.", uncovered a problem with XML comment processing in v2 patchset diffs.
An infinite DC election loop would occur when there is more than one comment at the same level within a CIB XML element, the partition has only one node, and the partition does not yet have a DC. The behavior was introduced in 1.1.14 with commit 1073786e, which did not have any bugs itself, but exercised the code differently, triggering bugs existing since the introduction of v2 patchsets (specifically commit 212ef6fe).
This request fixes multiple issues:
* An info-level message had an extraneous %d format specifier, which did not appear to cause any serious problems.
* The XML logging functions would log a spurious "/>" …
> Fix XML comment processing

- include/crm/msg_xml.h
- pengine/constraints.c
- pengine/test10/use-after-free-merge.xml
- xml/constraints-1.0.rng
- xml/constraints-1.2.rng
- xml/constraints-2.1.rng
- xml/constraints-2.2.rng
- xml/constraints-2.3.rng
- xml/constraints-2.6.rng
- xml/constraints-next.rng
Unlike the first (and second) commit, the third may be controversial and I'll happily drop it if you think there's no need to blindly follow ancient predestined path, which pacemaker users could live without for so many years.
> xml: score-attribute{,-mangled} in RNG schemas

- crmd/join_dc.c
Hi All,
I revised next pullrequest.
- https://github.com/ClusterLabs/pacemaker/pull/1102
This patch prevents that a state of LRMD of the DC node disappears by the participation of the node during an action.
It is the correspondence patch of the next bug.
- http://bugs.clusterlabs.org/show_bug.cgi?id=5286
Many thanks,
> Mid: crmd: Keep a state of LRMD in the DC node latest.

- crmd/lrm.c
- include/crm/lrmd.h
- include/crm/msg_xml.h
- include/crm/pengine/complex.h
- include/crm/pengine/rules.h
- include/crm/pengine/status.h
- include/crm_internal.h
- lib/common/digest.c
- lib/common/utils.c
- lib/lrmd/lrmd_client.c
- lib/pengine/complex.c
- lib/pengine/rules.c
- lib/pengine/utils.c
- lrmd/Makefile.am
- lrmd/lrmd.c
- lrmd/lrmd_private.h
- lrmd/main.c
- pengine/graph.c
Here is the implementation of the feature we have discussed in [#1001](https://github.com/ClusterLabs/pacemaker/pull/1001).
Similar to lib/pengine/rules.c:unpack_instance_attributes() I've created unpack_versioned_attributes() which evaluates non-versioned expressions in rules and does not touch versioned ones. It ends up with XML which is included in the message to LRMd.
So, following your example
```
<primitive id="A" class="ocf" type="myRA" provider="me">
<instance_attributes id="ia01" score="3">
<rule id="ia01-r01" score="INFINITY" >
<expression id="ia01-r01-e01" type=version attribute="#ra-version"
operation="gt" value="1.0"/>
</rule>
<nvpair id="ia01-nv02" name="super-new-param" value="10"/>
</instance_attributes>
<instance_attributes id="ia02" score="2">
<rule id="ia02-r01" …
```
> Feature: add versioned parameters support

- lib/pengine/complex.c
- pengine/regression.sh
- pengine/test10/migrate-versioned.dot
- pengine/test10/migrate-versioned.exp
- pengine/test10/migrate-versioned.scores
- pengine/test10/migrate-versioned.summary
- pengine/test10/migrate-versioned.xml
This is a resolution of the issue discussed in [#1063](https://github.com/ClusterLabs/pacemaker/pull/1063).
> Fix: pengine: disable migration for versioned resources

- crmd/callbacks.c
- crmd/crmd_utils.h
- crmd/election.c
- crmd/heartbeat.c
- crmd/lrm.c
- crmd/membership.c
- crmd/remote_lrmd_ra.c
- crmd/te_actions.c
- crmd/te_callbacks.c
- cts/CTStests.py
- fencing/fence_dummy
- include/crm/pengine/status.h
- lib/cib/cib_utils.c
- lib/cluster/election.c
- lib/pengine/status.c
- tools/crm_resource_runtime.c
1.1.15 introduced a regression where a remote node's LRM history would be cleared when its connection resource is stopped, rather than only at start. This could interfere with the cluster detecting which stop actions are implied by fencing.
> Important regression in 1.1.15 Pacemaker Remote handling

- extra/resources/ping
Unfortunately the previous attempt to avoid this issue (commit
7eb958ce4) didn't work since the problem happens only when the
output buffer is flushed but the write fails. Since there is no
mechanism in the shell to check if a pipe write is successful,
this silently fails.
In ping_check, there are no temporary files created. It's
possible to avoid the temporaries for fping too, but I had to
resort to using python.
> Low: ping: Avoid temp files in fping_check  (bsc#987348)

- lib/common/xml.c
Test case:
Change constraints-1.0.rng so as to deny score-attribute
in rsc_colocation; then:
$ make  # so as to generate the schemas
$ PCMK_schema_directory=$(pwd)/xml tools/crm_simulate -x $(pwd)/pengine/test10/use-after-free-merge.xml -S
BEFORE:
Entity: line 56: element rsc_colocation: Relax-NG validity error : Invalid attribute score-attribute for element rsc_colocation
Entity: line 49: element rsc_location: Relax-NG validity error : Element constraints has extra content: rsc_location
[...infloop...]
AFTER:
Entity: line 56: element rsc_colocation: Relax-NG validity error : Invalid attribute score-attribute for element rsc_colocation
Entity: line 49: element rsc_location: Relax-NG validity error : Element constraints has extra content: rsc_location
[several times]
4 of 5 resources …
> High: fix infloop when "validate-with" schema does not validate

- extra/resources/ping
In a7373f9, bash heredocs still create a temporary file in the
background. This commit avoids temporary files in a simple compromise
way when parsing the output of fping.
> Fix: ping: Avoid temporary files for fping check

- .gitattributes
- Makefile.am
Hence drop it from autotools-produced distribution files and git
archives, and make the Makefile deal with that file missing.
Alternative would be to make configure.ac figure out if that file
missing, but it sounds like too much complexity for no gain.
> Maint: scratch.c is only useful when developing

- tools/regression.sh
- tools/regression.validity.exp
This particular change increases robustness against this particular
change (in error.c) applicable for v2.9.0+:
https://git.gnome.org/browse/libxml2/commit/?id=97fa5b3c8f3fe6ff79123ab43ed6b846fd1dd6dd
> Test: tools: validity tests should not depend on libxml2 version

- tools/crm_mon.c
setenv can cause a segfault if the value passed to it is NULL. Only set CRM_notify_recipient if
external_recipient is not NULL.
This could be  a change glibc between 2.21 and 2.23.1, because the issue did not seem to occur in prior versions. This can be tested by invoking crm_mon with --external-agent but not --external-recipient on fedora24.
> Fix: crm_mon: Do not call setenv with null value

- cts/__init__.py
- cts/logging.py
- doc/Pacemaker_Development/en-US/Ch-Python.txt
- doc/Pacemaker_Development/en-US/Revision_History.xml
- fencing/fence_dummy
- fencing/regression.py.in
- lib/fencing/st_client.c
- lrmd/pacemaker_remote.in
- lrmd/regression.py.in
pylint turned up that we weren't using new-style classes in our python code. As all classes are new-style in Python 3, we should be using them, for our goal of 2.6+/3.2+ compatibility. So, this edits the fencing and lrmd regression tests to use new-style classes, and adds that to our python coding guidelines.
Additionally, this reformats and restructures the code to run more cleanly under pylint, and recommends that in the style guidelines.
This also updates a small bit of CTS code to be 2.6+/3.2+ compatible, and fixes some minor issues found in the course of all this.
> Use new-style classes in python regression tests

- lib/common/remote.c
- lib/lrmd/lrmd_client.c
Previously due to the incorrectly calculated timeouts, incomplete messages could
be received and handled  when it was not supposed to time out.
Related: http://clusterlabs.org/pipermail/users/2016-June/003198.html
> Fix: remote: Correctly calculate the remaining timeouts when receiving messages

- mcp/pacemaker.service.in
...when stonithd is the proper daemon in charge of node executions.
> Low: pacemaker.service: do not mistakenly suggest killing fenced

- cts/CTS.py
- cts/CTSaudits.py
- cts/CTSscenarios.py
- cts/CTStests.py
The , format is not supported for exception-handling in Python3.0+.
https://docs.python.org/release/3.0.1/whatsnew/2.6.html#pep-3110
Signed-off-by: Nishanth Aravamudan <nish.aravamudan@canonical.com>
> cts: fix syntax error with python3+

- configure.ac
Understandably, chroot-based buildsystems do not reliably expose system
message bus, so additional fallback to handle this corner case is added.
The DBus method is kept primary, also to have possible DBus API changes
checked, should the version of the Upstart interface at the target system
differ from what pacemaker uses.
> Build: configure: run initctl as an upstart detection fallback

- pacemaker.spec.in
When pacemaker_remote is setup with sbd and
pacemaker-watcher an upgrade of the package
triggers a watchdog reboot with most of the
time corruption of pacemaker-config-file
Resolves: rhbz1372009
> High: scriptlets: Fix pacemaker-remote upgrade

- crmd/lrm.c
- crmd/te_actions.c
Although we had the assurance of CPG, there was the race condition that
the peer received the lrm_invoke request from the DC, got the operation
performed, returned and updated into the CIB very fast, even before
the pending operation was injected into the CIB. The late pending
operation would override the real result of the operation and get
stalled in the CIB, which would basically tell the wrong state of the
resource.
The idea of this fix is to record the pending operation from the node
where the operation will be performed rather than from the DC, and right
before it's performed, to avoid the race condition.
> Fix: crmd: cl#5185 - Record pending operations in the CIB before they are performed

- extra/resources/ClusterMon
If the process is unmanaged and you reboot the server ClusterMon might match another process with the same PID.
This patch makes sure it's matching the expected process.
> ClusterMon: fix to avoid matching other process with the same PID

- tools/attrd_updater.c
HAVE_ATOMIC_ATTRD is either 0 or 1 thus use #if instead of #ifdef
[ "$__OCF_ACTION" = "start" ] seems to be in RAs to detect the legacy attrd and thus
use the old interface of attrd_updater.
As this anyway doesn't work made attrd_updater accept -B even in case of the legacy
attrd being in use. So the distinctions should be needed anymore.
> fix usage of HAVE_ATOMIC_ATTRD in attrd_updater

- attrd/commands.c
- crmd/join_dc.c
- fencing/commands.c
- lib/cluster/cpg.c
- lib/pengine/utils.c
- lib/services/services.c
- pengine/main.c
- pengine/native.c
- memory leak in crmd/join_dc.c:do_dc_join_ack()
- dead code in lib/services/services.c:resources_list_standards()
- hidden variables in attrd/commands.c:attrd_peer_update(),
fencing/commands.c:handle_request(), pengine/main.c:pe_ipc_dispatch(),
lib/cluster/cpg.c:pcmk_message_common_cs(),
and lib/pengine/utils.c:resource_location()
- unused value in pengine/native.c:RecurringOp()
> Fix: various: issues discovered via valgrind and coverity

- extra/clustermon.sh
This is a fix for the clustermon.sh script when using snmptraps.
When using ClusterMon resource or crm_mon with this script as an external agent, snmptraps are never sent. 
Some variables were not defined. After replacing them with the original ones, the script is sending snmptraps correctly.
> fix clustermon.sh sendsnmp function with working variables

- configure.ac
Introduced with b38f7c5; spotted by and many thanks to wferi:
https://github.com/ClusterLabs/pacemaker/commit/b38f7c54d81a73cabd13f77ed518c45f58a3c25f#commitcomment-19727928
> Build: configure: fix fouled parameter expansion

- xml/constraints-1.0.rng
- xml/constraints-1.2.rng
- xml/constraints-2.1.rng
- xml/constraints-2.2.rng
- xml/constraints-2.3.rng
- xml/constraints-2.6.rng
This commit partially reverts commit
30383cc5d70d542a95860a043f4d044f9fa5af5e to prevent either rolling
upgrade or offline upgrade from being possibly broken.
So that the removal of the attributes score-attribute and
score-attribute-mangle only remains for constraints-next.rng as a
reminder. We'll remove the attributes in the next bumped RNG version and
create a XSL file for doing transformation.
> xml: rng: Keep score-attribute{,-mangle} in the existing RelaxNG schema files for graceful upgrades

- lib/common/watchdog.c
Fixed the problem which caused SEGV by comparing NULL when the PCMK_panic_action environment variable is not set.
> wd: Fix to not compare NULL when environment variable is not set

- xml/resources-2.7.rng
Surely, the class attribute for templates should list the same
set of classes as the one for primitives?
> Low: rng: Add missing resource classes to template

- crmd/te_callbacks.c
Increase to same level as failed fencing operations so that reaching the
limit is notified to same log "readers".
Cc: @gao-yan
> Low: cmrd: increase severity when fencing limit is hit

- .gitattributes
- .tito.spec.tmpl
- .tito/custom.py
- .tito/tito.props
- GNUmakefile
New tito-related files makes the repository compatible with tito method
of building in COPR (https://fedorahosted.org/copr/wiki/UserDocs#Tito).
> build: allow for git -> automatic COPR builds integration

- fencing/commands.c
device_has_duplicate would return a dup if all params in device where in dup with the same value but
if dup had a param that device did not dup would still be considered a duplicate. This updates
the duplicate check to make sure that all keys and values overlap in both device and dup params.
> stonith: Check for missing params in new device and dup

- lib/services/systemd.c
Previously if pacemaker performed a monitor operation while a service was reloading, pacemaker treated it as if the service were stopped/failed.
Fixes http://bugs.clusterlabs.org/show_bug.cgi?id=5307
*(edit: linked wrong bug)*
> treat systemd service reloading as OK instead of FAILED

- fencing/admin.c
Hi All,
Next pullrequest causes it.
* https://github.com/ClusterLabs/pacemaker/pull/1194
I add list-targets option to stonith_admin command.
```
[root@rh73-01 fencing]# stonith_admin --help
stonith_admin - Provides access to the stonith-ng API.
Allows the administrator to add/remove/list devices, check device and host status and fence hosts
Usage: stonith_admin mode [options]
(snip)
Commands:
-l, --list=value       List devices that can terminate the specified host
-L, --list-registered  List all registered devices
-I, --list-installed   List all installed devices
-s, --list-targets=value       List the device's target
(snip)
[root@rh73-01 fencing]# stonith_admin -L
prmStonith2-1
1 devices found
[root@rh73-01 fencing]# stonith_admin -s prmStonith2-1
rh66-hb3
rh66-hb2
(snip)
rh73-01
``` …
> Low: stonith_admin: Addition of the list-targets option.

- GNUmakefile
- pacemaker.spec.in
- spec file should silently ignore "--with pre_release" condition
when commit variable carries the tag alias instead of the hash;
note that if the tag itself implies pre-release with -rcX suffix,
pre-release logic is selected regardless
- similarly, GNUMakefile should not push the version to be substituted
in the spec file up when the current checkout happens to be tagged
Disclaimer: this is to solve rough edges in COPR integration, because
currently a build from 1.1 branch (i.e. enforcing "--with pre_release"),
HEAD resolving to Pacemaker-1.1.16 tag, the generated version would be
"1.1.17-0.1.1.1.16.git" instead of expected "1.1.16-1".
To some extent, the whole arrangement relies on established release
procedures, e.g., in terms of restoring work on release ("decimal dot
decimal") branch …
> build: spec: rationalize pre-release vs. tags logic

- configure.ac
- mcp/pacemaker.c
Hi All,
After a user installed Pacemaker, access permission of the access is as follows.
```
[root@rh73-01-test ~]# ls -lt /var/lib | grep pacemaker ; ls -lt /var/lib/pacemaker
drwxr-x---  6 hacluster      haclient         61 Dec  8 12:40 pacemaker
total 0
drwxr-x--- 2 hacluster haclient  71 Dec  8 12:41 pengine
drwxr-x--- 2 hacluster haclient 132 Dec  8 12:41 cib
drwxr-x--- 2 hacluster haclient   6 Sep  9 10:49 blackbox
drwxr-x--- 2 hacluster haclient   6 Sep  9 10:49 cores
-----pacemaker.spec.in-----
(snip)
%dir %attr (750, %{uname}, %{gname}) %{_var}/lib/pacemaker/cib
%dir %attr (750, %{uname}, %{gname}) %{_var}/lib/pacemaker/pengine
(snip)
%dir %attr (750, %{uname}, %{gname}) %{_var}/lib/pacemaker
%dir %attr (750, %{uname}, %{gname}) %{_var}/lib/pacemaker/blackbox
%dir %attr (750, …
```
> Low: mcp: Correction of the difference in access permission setting.

- mcp/pacemaker.combined.upstart.in
Since the latest corosync initializes watchdog_timeout at startup, setting soft_margin here is no longer necessary.
I will delete this setting.
The systemd startup script on corosync side has been fixed below.
https://github.com/corosync/corosync/pull/168
> upstart: Delete unnecessary soft_margin

- lib/services/dbus.c
With "service" class of resources, by chance, lrmd hangs on futex()
syscall:
root@node2:~ # cat /proc/2503/stack
[<ffffffff810fa0c0>] futex_wait_queue_me+0xc0/0x130
[<ffffffff810faf23>] futex_wait+0x163/0x250
[<ffffffff810fc870>] do_futex+0xe0/0x540
[<ffffffff810fcd3e>] SyS_futex+0x6e/0x140
[<ffffffff815e142e>] entry_SYSCALL_64_fastpath+0x12/0x6d
[<ffffffffffffffff>] 0xffffffffffffffff
Cluster no longer behaves and cannot recover from the situation.
According to the backtrace, it seems due to the reentrancy of
dbus_connection_dispatch():
(gdb) bt
#0  0x00007f07f7d2e0af in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f07f6c29925 in _dbus_connection_acquire_dispatch (connection=0x13411f0) at dbus-connection.c:4142
#2  0x00007f07f6c2b3bc in …
> Fix: dbus: Prevent lrmd from hanging on dbus calls

- tools/report.common.in
Grepping large binary files can exhaust memory. This avoids that and speeds up
crm_report's log scan by: skipping things that aren't files, aren't readable,
or are empty; skipping files with more than 256 nonprintable bytes in the first
1024; and using LC_ALL="C" to speed up grep.
> Fix: tools: avoid grep crashes in crm_report when scanning system logs

- extra/alerts/alert_snmp.sh.sample
Hi All,
I add the designation of the SNMP_PERSISTENT_DIR directory for snmptrap tool.
With this patch, I restrain the next log output with snmptrap tool.
```
crmd[3569]:  notice: notify_9:4265:stderr [ Cannot rename /var/lib/net-snmp/snmpapp.conf to /var/lib/net-snmp/snmpapp.0.conf ]
crmd[3569]:  notice: notify_9:4265:stderr [ Cannot unlink /var/lib/net-snmp/snmpapp.conf ]
crmd[6507]:  notice: notify_9:6626:stderr [ Created directory: /xxxx/.snmp_presist/cert_indexes ]
crmd[6507]:  notice: notify_9:6626:stderr [ Created directory: /xxxx/.snmp_presist/mib_indexes ]
```
The SNMP_PERSISTENT_DIR of the default is /var/lib/pacemaker/snmp .
In trap_snmp_persistent_dir parameter, the user can appoint it.
This patch was discussed with the next link.
* …
> Mid: Alert: Set SNMP_PERSISTENT_DIR directory for the snmp-trap tool.

- .gitignore
- GNUmakefile
- Makefile.am
- configure.ac
To name a few pain points in the former version:
- pacemaker is not distributed with "libltdl.tar" for the past few
years and it's unclear if it ever was or if it's just the heartbeat
legacy; definitely no recipe to prepare such a file was found
- custom mechanism to use bundled libltdl is redundant (and inferior
in parameterization) compared to options automatically available
to configure script thanks to newly introduced LTDL_INIT macro
(--with-ltdl-lib DIR, --with-included-ltdl)
- "INCLTDL" was likely a typo for "LTDLINCL"
> Build: simplify and update deprecated libtool/ltdl integration

- doc/Pacemaker_Explained/en-US/Ch-Advanced-Resources.txt
Despite the documentation, this environment variable doesn't exist.
> Doc: Pacemaker Explained: remove *notify_inactive_uname variable

- tools/crm_mon.c
So far, we have been likely covered by standards requiring asctime to
produce an output ending with \n\0 bytes, because otherwise, we would
overrun the buffer, reading unspecified content, possibly segfaulting.
This was actually discovered with a brand new GCC7 warning
( [-Werror=pointer-compare]).
Another latent issue was that the code was not ready for the case
of failing asctime call (returning NULL).  This is now fixed as well.
> Fix: crm_mon: protect against non-standard or failing asctime

- pacemaker.spec.in
Commit 625d427 was too coarse and disregarded self-inflicted recursive
redefinition of an internal macro, owing to how %define is treated.
Unfortunately, rpmbuild won't currently abort the build in that case
even if it is aware of the recursive expansion [*], masking the problem.
The breakthrough emerged only thanks to materialized changes in the
resulting RPMs, specifically because __os_install_post macro definition
got suddently empty, disregarding common actions such as compressing
the man pages (beside various debug symbols stripping), which in turn
led to the discovery (good catch, Ken).
So simply revert back to using %global in this instance, which will
make it harmless one-off definition once again.  (And reformat to
spare overly long line.)
[*] …
> Build: spec: %define back to %global to prevent recursive declaration

- GNUmakefile
- pacemaker.spec.in
Notably those supporting autoscaling of commit hash abbreviation.
> Build: keep "make srpm" working with newer git versions

- tools/report.collector
- tools/report.common.in
/proc/drbd contains detailed information about the version of DRBD and the status of DRBD resources, their devices, and their connections and is often invaluable in troubleshooting issues with DRBD.
> collect info from /proc/drbd, if present

- attrd/attrd_common.c
- attrd/attrd_common.h
- attrd/commands.c
- attrd/internal.h
- attrd/legacy.c
- attrd/main.c
- crmd/attrd.c
- include/crm_internal.h
- lib/common/utils.c
- tools/crm_resource.c
- tools/crm_resource_runtime.c
Previously, crm_resource --cleanup and the crmd would clear resource failure attributes (fail-count and last-failure) explicitly. Now, they call a new attrd op, and attrd determines the attributes to clear.
The main benefit is to allow a planned change in failure attribute implementation in the future, which will require regular expressions when clearing. We can't assume that all attrd peers support regular expressions, but we can assume that the local attrd understands the new op, and will translate it to peers in a backward-compatible way.
> Add attrd operation to clear resource failure attributes

- crmd/join_dc.c
Hi All,
When a node participates after cluster constitution in Pacemaker, the following log may be sometimes output.
```
Mar  8 13:37:30 xxxxxx crmd[811]:    error: No recipient for welcome message
```
This is caused by solution to uname of the node that participated having been late.
The error log may confuse an operator.
Because the node that participated is incorporated in a cluster if a node name is finally solved, I think that the warning level is enough for the log.
Furthermore, I made modifications to include uuid of the node in log.
```
Mar  8 13:37:30 xxxxxx crmd[811]:    warning: No recipient for welcome message.(Node uuid:xxxxxxxxxxxxxx)
```
Best Regards,
> Low: crmd: Change of the log level and addition of uuid.

- crmd/join_dc.c
Hi All,
The log level was changed by the next PR.
- https://github.com/ClusterLabs/pacemaker/pull/1239
We argued about this log again.
The frequency that this log appears is unexpectedly high.
However, the node is incorporated in a cluster even if log is output.
Because we do not confuse an operator, we want to switch to info level more.
Best Regards,
> Low: crmd: Change of the log level(again).

- crmd/control.c
- crmd/te_callbacks.c
- crmd/te_callbacks.h
- include/crm_internal.h
- lib/common/utils.c
The maximum number of retry attempts for fencing to be made by crmd before giving up.Default value of 10 and accepts only positive non-zero values.
Added a new function check_positive_number() which return true if the input number is positive and false otherwise.
> new cluster option stonith-max-attempts 

- doc/Pacemaker_Explained/en-US/Ch-Options.txt
#1245 Updated Cluster Options Section with stonith-max-attempts under Pacemaker-Explained Document.
Attached the generated output.
> Stonith-Max-Attempts Doc Updation

- tools/crm_resource.c
- tools/crm_resource_runtime.c
Hi,
Based on the feedback from users deploying the PAF resource agent, it is quite easy to forget a step in the resource setup often leading to resource failure or node fencing.
As the `validate-all` function of resource agent is intended to be used by UIs, it seems useful to add command to call it from a cli tool.
I have been able to check it with a simple scenario like:
~~~console
# [...cluster setup...]
Operation validate-all for pgsqld:0 (ocf:heartbeat:pgsqlms) returned 2
>  stderr: ocf-exit-reason:Recovery template file must contain in primary_conninfo parameter "application_name=srv1"
~~~
The next step would be to be able to run this command on remote nodes as well, but I am not sure yet how to achieve this. Is it possible to export/import the cib in the crm_shadow environment? …
> Add command `validate` to crm_resource

- crmd/crmd_lrm.h
- crmd/lrm_state.c
- crmd/messages.c
- crmd/remote_lrmd_ra.c
- crmd/te_actions.c
- include/crm/crm.h
- include/crm/lrmd.h
- include/crm/msg_xml.h
- include/crm/pengine/status.h
- include/crm_internal.h
- lib/lrmd/proxy_common.c
- lib/pengine/unpack.c
- lib/pengine/utils.c
- lrmd/ipc_proxy.c
- lrmd/lrmd_private.h
- lrmd/main.c
- pengine/allocate.c
- pengine/graph.c
- pengine/pengine.h
Since introduction of the graceful shutdown of pacemaker_remoted
the shutdown is hanging if the remote-resource is unmanaged.
This happens as pacemaker_remoted is waiting for all resources
running on the remote-node to be shut down and pacemaker
on the other hand doesn't touch resources on a remote-node
when the remote-resource is unmanaged.
Fixes rhbz#1388102
> Fix: pacemaker-remote: pacemaker_remoted shutdown while unmanaged

- lrmd/main.c
Obviously with glib2 older 2.36 it is not possible to have a timer expire prematurely.
> Fix: pacemaker_remoted: Allow compilation with glib older 2.36

- crmd/Makefile.am
- crmd/callbacks.c
- crmd/control.c
- crmd/crmd_alerts.c
- crmd/crmd_alerts.h
- crmd/crmd_utils.h
- crmd/lrm.c
- crmd/notify.c
- crmd/notify.h
- crmd/te_utils.c
- include/crm/common/alerts_internal.h
- lib/common/Makefile.am
- lib/common/alerts.c
Hi All,
This is modified PR discussed by the next PR.
- https://github.com/ClusterLabs/pacemaker/pull/1251
I perform the following changes for an attribute trap function.
- Move a movable Alert-related function to a common function.
- Change of file names from notify.c to crmd_alerts.c and crmd_alerts.h.
- Changed the parameter of the function,
- Changed the description to "alert".
Some functions have not yet moved.
Best Regards,
> Low: crmd: Move Alert function to common. (again)

- crmd/crmd_utils.h
- crmd/join_client.c
- crmd/te_actions.c
- crmd/utils.c
- lib/cib/cib_attrs.c
Now we can start node with `PCMK_node_start_state` the same way. But it will be the permanent state instead of the transient. 
The behavior is:
`PCMK_node_start_state=standby` -> set standby on, 
`PCMK_node_start_state=online` -> set standby off, 
`PCMK_node_start_state=default` -> leave standby alone.
Also we can use commandline option `-s` to to start node in standby state.
E.g. `ExecStart=/path/to/pacemakerd -s` for `pacemaker.service` file.
During the testing there was no race condition. But we noticed one thing: `set_standby(...)` uses `cib_sync_call` option inside the `update_attr_delegate(...)`. We tested without this option and there was no race too.
> Сhange starting process with PCMK_node_start_state

- crmd/control.c
- crmd/throttle.c
- crmd/throttle.h
- include/crm/common/internal.h
- lib/common/procfs.c
This fixes multiple issues with crmd's throttle checks, most importantly: changes in CPU count due to hot-plugging are now detected; blocked processes are correctly parsed from /proc/stat; and I/O thresholds are set reasonably.
> Calculate throttle thresholds better

- include/crm/msg_xml.h
- include/crm/pengine/rules.h
- lib/pengine/rules.c
- pengine/constraints.c
- xml/alerts-2.8.rng
- xml/constraints-2.8.rng
- xml/nodes-2.8.rng
- xml/nvset-2.8.rng
- xml/resources-2.8.rng
- xml/rule-2.8.rng
This would allow following syntax (in crmsh terms):
location resource-require-home-zone /resource-.+/ \
rule -inf: not_defined zone or zone ne meta{zone}
> pengine: Allow use of resource meta params in location rules

- xml/resources-2.8.rng
Technically, there's no need to require particular order as
unpack_container always sticks with the first occurrence of
the element carrying particular name.
> Low: xml: relax the strict element order within the bundle body

- pacemaker.spec.in
The breakage was introduced in 2d6e6c374 (avoid bashism due to
rpmbuild-popen-/bin/sh chain) which accidentally tried to access RPM
macro level variable ("%{s}") instead of the one in the intended scope
of the nested shell ("${s}"}.  This simple swap can then be further
simplified to refer to the underlying macro level variable right away,
so carry this out as well.
> Build: spec: fix broken pre-release by tag detection

- tools/cibsecret.in
Add "--version" option for cibserect.in to fix compile error.
> low: tools: add version options for cibsecret

- fencing/commands.c
- fencing/main.c
The simple search for 'rsc_location' just triggered on delete.
'constraints' is found both in additions and deletes.
A smarter check might reduce the number of unneeded triggers but
probably isn't worth the effort.
Add some trace-logging to facilitate tracking down similar issues.
> Fix: stonith-ng: Trigger on constraints added to cib

- attrd/Makefile.am
- attrd/attrd_alerts.c
- attrd/attrd_alerts.h
- attrd/commands.c
- attrd/internal.h
- attrd/legacy.c
- attrd/main.c
- crmd/crmd_alerts.c
- extra/PCMK-MIB.txt
- extra/alerts/alert_file.sh.sample
- extra/alerts/alert_smtp.sh.sample
- extra/alerts/alert_snmp.sh.sample
- include/crm/common/alerts_internal.h
- include/crm/lrmd.h
- include/crm/lrmd_alerts_internal.h
- include/crm/msg_xml.h
- include/crm/services.h
- lib/common/alerts.c
- lib/lrmd/Makefile.am
- lib/lrmd/lrmd_alerts.c
- lib/lrmd/lrmd_client.c
- lib/services/services.c
- lib/services/services_linux.c
- lrmd/lrmd.c
-----
This PR is a revision of the next PR.
- https://github.com/ClusterLabs/pacemaker/pull/1268
-----
Hi All,
I added the alert function of the attribute.
I add two meta attributes to alert setting newly.
- kind
- attribute_name
```
(snip)
alert notify_9 /usr/share/pacemaker/alerts/alert_snmp.sh \
meta \
kind="resource,attribute" \
attribute_name="default_ping_set" \
attributes \
trap_resource_tasks="start,stop,monitor,promote,demote" \
trap_add_hires_timestamp_oid="false" \
to "192.168.xx.xxx"
(snip)
```
The kind appoints alert to handle.
For the compatibility with the former version, the default becomes "node,fencing,resource".
The alert function of the attribute that is new by appointing "attribute" becomes effective for kind.
The attribute_name appoints the attribute that alert does. …
> Mid: alert: Add the alert function of the attribute.

- cib/callbacks.c
Previously in cib legacy mode, if a cib change was requested by an
unprivileged user that had limited permissions to the cib, after it got
accepted by the master cib daemon, the broadcast of the cib change would
get denied by the ACLs check of the slave cib daemons since the user
didn't have the permission to write the additional bits from the
broadcast such as the cib properties like "epoch", "num_updates" and so
on.
Technically, the broadcast of a cib change is issued by the master cib
daemon as CRM_DAEMON_USER instead of the user that originally requested
the change. The broadcast should always pass the ACLs check when it's
processed by the slave cib daemons.
This commit fixes the issue by overwriting any existing F_CIB_USER field
in a broadcast with the privileged user …
> Fix: cib: Broadcasts of cib changes should always pass ACLs check

- cib/callbacks.c
- cib/callbacks.h
- cib/remote.c
- crmd/te_callbacks.c
- crmd/te_utils.c
- doc/Pacemaker_Explained/en-US/Ch-Options.txt
- include/crm/cluster/internal.h
- include/crm/common/ipcs.h
- include/crm/common/util.h
- lib/cib/cib_utils.c
- lib/common/ipc.c
- lib/common/utils.c
- lib/pengine/utils.c
- lrmd/tls_backend.c
Previously, cluster daemons would evict any IPC client if the client's message queue reached 500 messages. Now, the user can set this threshold via a cluster-ipc-limit option. The option only applies to clients that are other cluster daemons (connecting as uid root or hacluster, and identifying as a cluster daemon).
This helps with scalability, as certain cluster operations (such as "cleanup all") generate probes of all resources on all nodes, potentially leading to a flood of probe results from the CIB that instantly cross the 500 limit.
This request also contains a handful of unrelated commits with minor fixes.
> Support user option for IPC client eviction threshold

- attrd/legacy.c
Previously, when compiling with -Wformat (on by default with any
reasonable recent gcc), such a build setup would fail unless
--disable-fatal-warnings was specified to configure script.
Those generic void pointers are enforced by callback machinery, but
we are indeed passing strings as user data to the handlers.
> Med: attrd: make compilable again without Corosync 2

- fencing/commands.c
- fencing/main.c
- fencing/remote.c
- include/crm/fencing/internal.h
Have all the delay stuff done by pacemaker directly instead of a random delay done by pacemaker and relying on the fence-agent having an attribute for an additional static delay ( having some fancy name you have to dig out first)
And you get a single log with a single delay derived from a base-part and the already existing random part that looks the same for all fencing-agents.
Random and base part don't just simply add up so that pcmk_delay_max keeps it's original behavior as the maximum delay that can happen. Meaning the actual delay is gonna be between pcmk_delay_base and pcmk_delay_max.
> Feature: stonith-ng: add pcmk_delay_base as static base-delay

- lib/common/iso8601.c
Fixes rhbz#1462253
(cherry picked from commit 9d667c914f073fdf91b428ac345309e0fe4ded8c)
> Fix: iso8601: strftime needs fully populated struct tm

- fencing/commands.c
st_child_done does already call free_async_command ...
didn't see cases where we don't have st_child_done as done_cb.
> fix: stonith-ng: avoid double-free of pending-ops in free_device

- .travis.yml
- include/crm/common/alerts_internal.h
- lib/common/Makefile.am
- lib/common/alerts.c
- lib/common/schemas.c
- tools/regression.validity.exp
- xml/Readme.md
As a byproduct, this eliminates a dependency on the math library.
> Fix: libcrmcommon: handle schema versions properly

- autogen.sh
If rpm is not installed,
```
-e `which rpm`
```
is true, while
```
-e "`which rpm`"
```
is false.
> Properly detect if rpm is missing

- attrd/commands.c
- attrd/internal.h
- attrd/main.c
- crmd/join_client.c
fe44f400 (getting rid of unnecessary complete attribute write-outs at node join) exposed a different issue.
When a node leaves and re-joins the cluster, attrd will be up and accepting requests before the crmd comes up, so attrd can set transient attributes during this time. These will get recorded by attrd and cib correctly.
However, when the crmd completes its first join, it would erase its own transient attributes from the CIB, to handle the case where the node restarted too quickly for the cluster layer to notice
(and thus no peer loss was noticed by the other nodes). It would not wipe them from attrd, so any values set in that window would be in attrd but not the CIB. Before fe44f400, the write-out after join would put those values back in the CIB, but now, the inconsistent state …
> Clear transient attributes at attrd start-up rather than crmd first join

- pengine/native.c
Previously, pengine test "bundle-nested-colocation" failed on x86
architecture:
```
@@ -334,8 +334,8 @@
native_color: rabbitmq-bundle-docker-0 allocation score on overcloud-galera-1: -INFINITY
native_color: rabbitmq-bundle-docker-0 allocation score on overcloud-galera-2: -INFINITY
native_color: rabbitmq-bundle-docker-0 allocation score on overcloud-rabbit-0: INFINITY
-native_color: rabbitmq-bundle-docker-0 allocation score on overcloud-rabbit-1: -9999
-native_color: rabbitmq-bundle-docker-0 allocation score on overcloud-rabbit-2: -9999
+native_color: rabbitmq-bundle-docker-0 allocation score on overcloud-rabbit-1: -9998
+native_color: rabbitmq-bundle-docker-0 allocation score on overcloud-rabbit-2: -9998
native_color: rabbitmq-bundle-docker-0 allocation score on rabbitmq-bundle-0: …
```
> Fix: pengine: Make sure calculated resource scores are consistent on different architectures

- lib/lrmd/lrmd_client.c
Previously, if the operation of a remote resource failed on setting up
the key, it'd become forever in-flight operation and never return.
> Fix: liblrmd: Make sure the operation of a remote resource returns if setup of the key fails

- fencing/main.c
The metadata being used by high-level-tooling to determine which
attributes can be set for fencing-resources this is needed to
be able to replace the on-action by an alternate command.
Assuming there is no intention behind not having 'on' in the list of actions ...
> fix: stonith-ng: advertise pcmk_on_action via metadata

- doc/Pacemaker_Explained/en-US/Ch-Alerts.txt
- include/crm/msg_xml.h
- lib/common/alerts.c
- lib/pengine/rules_alerts.c
- tools/regression.validity.exp
- xml/Readme.md
- xml/alerts-2.10.rng
Structured XML is now used to filter alert events, instead of comma-separated lists in the "kind" and "attribute_name" meta-attributes, so that more errors can be caught when the schema is validated. Example of new syntax:
<alert id="my-alert" path="/path/to/my-script.sh">
<select>
<select_attributes>
<attribute name="myattr" />
</select_attributes>
<select_resources />
</select>
...
> Change XML syntax used to filter alert events

- include/crm/common/util.h
Sbd failed to build against 67795f1a0:
```
In file included from sbd-inquisitor.c:19:0:
/usr/include/pacemaker/crm/common/util.h:130:1: error: unknown type name ‘xmlNode’
xmlNode *crm_create_op_xml(xmlNode *parent, const char *prefix,
^
/usr/include/pacemaker/crm/common/util.h:130:28: error: unknown type name ‘xmlNode’
xmlNode *crm_create_op_xml(xmlNode *parent, const char *prefix,
^
```
> Build: Include libxml/tree.h in crm/common/util.h

- tools/crm_mon.c
> Fix: crm_mon: error-exit child if execl should return

- lib/common/operations.c
This is a modified version of the next PR.
- https://github.com/ClusterLabs/pacemaker/pull/1341
> Low: libcommon: Erase old exit_reason. (2)

- tools/crm_resource.c
- tools/crm_resource_runtime.c
crm_resource --force-check shows an invalid error message when a RA returns other than OCF_SUCCESS, although it's working perfectly as expected:
```
[root@centos73-1 ~]# crm_resource  --force-stop -r dummy1
Operation stop for dummy1 (ocf:heartbeat:Dummy) returned 0
>  stderr: DEBUG: dummy1 stop : 0
[root@centos73-1 ~]# crm_resource  --force-check -r dummy1
Operation monitor for dummy1 (ocf:heartbeat:Dummy) returned 7
>  stderr: DEBUG: dummy1 monitor : 7
Error performing operation: Argument list too long
[root@centos73-1 ~]# 
```
Also, it always shows RA's logs as debug level, which could be a bit noisy for some RAs.
This PR suggests to fix those as:
* do not show an error message when it's returning an OCF return value
* do not show RA's debug logs unless -V option was specified
> Fix invalid error in crm_resource --force-start/stop/check

- pacemaker.spec.in
"make rpm" of Pacemaker-1.1.18 in an environment where net-snmp-devel or libesmtp-devel is installed will create crmd outputting the following warning.
* https://github.com/ClusterLabs/pacemaker/blob/Pacemaker-1.1.18-rc3/crmd/main.c#L136-L147
So, I want to be able to disable the features of SNMP and ESMTP even in "make rpm".
"WITH='--without snmp --without esmtp' make rpm" before adding commit :
```
(snip)
configure:25512: result:   Features                 = (snip) atomic-attrd snmp libesmtp acls
```
after adding commit :
```
(snip)
configure:25512: result:   Features                 = (snip) atomic-attrd acls
```
> Build: spec: support for --without snmp and --without esmtp

- pengine/allocate.c
12d453cc enabled probing of guest nodes, but did so even if the guest node is marked as offline, unclean, or with discovery "never". This skips probing in those cases, the same as for other node types.
> Fix: pengine: don't probe offline or unclean guest nodes

- cib/remote.c
- crmd/remote_lrmd_ra.c
- include/crm/common/internal.h
- lib/common/io.c
- lib/common/remote.c
- lib/fencing/st_client.c
- lib/lrmd/lrmd_client.c
- lib/services/services_linux.c
- lrmd/lrmd_private.h
- lrmd/main.c
- lrmd/tls_backend.c
Previously, all Pacemaker Remote connection errors were treated the same: the connection would be repeatedly re-attempted until the start operation timeout, and then normal recovery would be done (by default, repeating the process 1,000,000 times on the same node, before moving to another node). This makes sense for transient errors, but not for permanent errors such as a misconfigured (missing or unreadable) authentication key.
Now, an inability to read the key is treated as a hard error, so the node is immediately banned from hosting the connection. Also, a meaningful exit reason is presented to the user in cluster status, e.g.:
Failed Actions:
* remote-rhel7-2_start_0 on rhel7-1 'invalid parameter' (2): call=8, status=Error,
exitreason='Authentication key not readable', …
> Error quickly if Pacemaker Remote authentication key is not readable

- include/crm/pengine/internal.h
- lib/pengine/utils.c
- tools/crm_resource.c
- tools/crm_resource.h
- tools/crm_resource_runtime.c
Some RAs(\*1) require the OCF_RESKEY_CRM_meta_timeout environment variable.
However, since it is not set with the crm_resource --force-* command, the RA is terminated halfway.
*1 https://github.com/ClusterLabs/resource-agents/blob/v4.0.1/heartbeat/sfex#L187
https://github.com/ClusterLabs/resource-agents/blob/v4.0.1/heartbeat/rsyslog#L162-L163
```
[root@x3650c ~]# crm_resource --force-stop -r prmEx
Operation stop for prmEx (ocf:heartbeat:sfex) returned: 'unknown error' (1)
>  stderr: INFO: sfex_daemon: stopping...
>  stderr: /usr/lib/ocf/resource.d/heartbeat/sfex: line 187: (/1000)-5: syntax error: operand expected (error token is "/1000)-5")
[root@x3650c ~]# echo $?
1
```
Since pacemaker has a value of timeout, I think that pacemaker should set it.
(I also think RA should make sure that …
> Low: tools: set meta_timeout env when crm_resource --force-* executes RA

- lib/pengine/container.c
Logs can be read using container ID from machinectl:
journalctl -M rkt-bc3c1451-2e81-45c6-aeb0-807db44e31b4
> Fix: PE: Have bundles log to stderr so that 'journalctl -M' works (rkt)

- extra/resources/ifspeed
- include/portability.h
- lib/common/strings.c
- lrmd/main.c
There are more latent problems around `time_t` conversions. Explicit casts to `long` may fail when it's a 32-bit type, and there's even a conversion to `int` in
crm_xml_add_int(vote, F_CRM_ELECTION_AGE_S, age.tv_sec);
at https://github.com/ClusterLabs/pacemaker/blob/1.1/lib/cluster/election.c#L233. These will probably require further work.
> Various portability fixes and a typo fix

- configure.ac
Pacemaker fails to cross build from source, because it uses the build
architecture pkg-config by searching for it with AC_PATH_PROG rather
than AC_PATH_TOOL or even better PKG_PROG_PKG_CONFIG. The latter two
macros do consider $ac_tool_prefix which is required for cross building.
After applying the attached patch, Pacemaker still fails to cross build
due to its use of help2man. There is no obvious solution for that
problem, but I think the attached patch is still useful, as it makes the
help2man problem visible and moves pacemaker's configure.ac to a more
correct one. Please consider applying it.
Patch from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865048
> configure: Consider $ac_tool_prefix for pkg-config

- tools/crm_resource_runtime.c
When resource related to globally-unique such as master/slave is specified by crm_resource --force-*, an instance number is given to the OCF_RESOURCE_INSTANCE environment variable of RA.
* before executing crm_resource. (when executed from lrmd, no instance number is given.) :
```
[root@rhel73-1 ~]# crm configure show
node 3232261507: rhel73-1
node 3232261509: rhel73-3
primitive prmStateful ocf:pacemaker:Stateful \
op start interval=0s timeout=10s on-fail=restart \
op promote interval=0s timeout=10s on-fail=restart trace_ra=on \
op demote interval=0s timeout=10s on-fail=restart \
op monitor interval=20s role=Slave timeout=10s on-fail=restart \
op monitor interval=10s role=Master timeout=10s on-fail=restart \
op stop interval=0s timeout=10s on-fail=fence
ms msStateful prmStateful \
meta …
```
> Low: tools: set the correct OCF_RESOURCE_INSTANCE env when crm_resource --force-* executes RA

- mcp/pacemaker.service.in
Systemd v227 introduced the "pids" cgroup controller:
https://github.com/systemd/systemd/commit/03a7b521e
From systemd v228, it's enabled for all services by default, and the
global default of TasksMax was 512:
https://github.com/systemd/systemd/commit/9ded9cd14
The limit could be be easily hit since any processes/threads spawned
from the unit count, such as the "ocf" type of resources.
In systemd v235, the default TasksMax= has been effectively changed to
4915:
https://github.com/systemd/systemd/commit/79baeeb96
But it still could be a potential issue for cluster with heavy workload.
Generally it probably doesn't make much sense to set such a limit for a
resource manager like pacemaker.
This commit recommends the same as the docker project does: …
> Doc: pacemaker.service: Recommend not to limit tasks

- crmd/crmd_metadata.c
- crmd/crmd_metadata.h
- crmd/lrm.c
- include/crm/pengine/common.h
- include/crm/pengine/internal.h
- include/crm/pengine/status.h
- lib/pengine/clone.c
- lib/pengine/container.c
- lib/pengine/native.c
- lib/pengine/status.c
- lib/pengine/unpack.c
- lib/pengine/utils.c
- lrmd/pacemaker_remote.service.in
- lrmd/test.c
- pengine/allocate.c
- pengine/constraints.c
- pengine/native.c
- tools/crm_mon.c
- tools/crm_resource.c
- tools/crm_resource.h
- tools/crm_resource_print.c
- tools/crm_resource_runtime.c
- tools/regression.sh
- tools/regression.validity.exp
Most importantly, this fixes a nasty bug introduced by 1.1.17+ffb94ac36 affecting the detection of reloadable and private resource agent parameters.
Among other changes, this also replaces find_rsc_or_clone() with a new pe_find_* flag, and overhauls the way crm_resource searches for resources.
> More cleanup before 1.1.18 release

- pacemaker.spec.in
Beside the fact that *.so symlinks delivered with that package are
indeed satisfied with and only with arch-preserving -{,cluster-}libs
packages, it's also a matter of being disciplined per what distros
reasonably require:
https://fedoraproject.org/wiki/Packaging:Guidelines#Architecture-specific_Dependencies
(https://fedoraproject.org/wiki/Packaging:Guidelines#Requiring_Base_Package)
The syntactic provision at hand was introduced in rpm 4.6.0
(8+ years ago): http://rpm.org/user_doc/arch_dependencies.html
> Build: spec: make -libs-devel package dependencies arch-qualified

- tools/crm_resource.c
- tools/crm_resource.h
- tools/crm_resource_runtime.c
The new "failures only" mode of crm_resource --cleanup had multiple issues, including not working without --resource specified, comparing a user-provided interval string against a milliseconds interval, and considering no interval specified as all intervals rather than 0 but only when clearing LRM history entries.
> Fix: tools: crm_resource --cleanup

- crmd/pengine.c
ed51cc97c introduced an issue that'd cause reentrancy of
mainloop_del_fd() on stopping crmd, which would complain like:
"crit: GLib: Source ID 22 was not found when attempting to remove it"
```
#0  0xb7f29cc9 in __kernel_vsyscall ()
#1  0xb7b538e2 in raise () from /lib/libc.so.6
#2  0xb7b54fd1 in abort () from /lib/libc.so.6
#3  0xb7e51a1e in crm_abort (file=0xb7e83c9f "logging.c", function=0xb7e85b00 <__FUNCTION__.21612> "crm_glib_handler", line=73, assert_condition=0x63c6a0 "Source ID 22 was not found when attempting to remove it", do_core=1, do_fork=<optimized out>) at utils.c:689
#4  0xb7e7257f in crm_glib_handler (log_domain=0xb7d93e8e "GLib", flags=G_LOG_LEVEL_CRITICAL, message=0x63c6a0 "Source ID 22 was not found when attempting to remove it", user_data=0x0) at logging.c:73
#5 …
```
> Fix: crmd: Avoid double-removal of glib event source on stopping

- tools/crm_master
Before ccbdb2a, crm_master would always set --node, thus ensuring crm_attribute
would treat the value as a node attribute. That commit removed that so that
crm_attribute could determine the local node name properly, but that introduced
an issue where the master value would be set as a cluster property instead of a
node attribute if --lifetime (or --node) was not set explicitly.
This fixes it by setting the default value of --lifetime explicitly.
> Fix: tools: crm_master should always work on node attribute

- crmd/lrm.c
lrm.c: In function ‘unescape_newlines’:
lrm.c:2387:9: error: ‘strncpy’ output truncated before terminating
nul copying 2 bytes from a string of the same
length [-Werror=stringop-truncation]
strncpy(pch, "\n ", 2);
^~~~~~~~~~~~~~~~~~~~~~
It was actually purposeful here, so switch to less worrying memcpy
instead (deemed better alternative to stepwise indexed assignments).
Possibly relevant:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81117#c9
> Refactor: avoid warning triggering construct with GCC8

- crmd/lrm.c
- crmd/lrm_state.c
- crmd/remote_lrmd_ra.c
- crmd/te_callbacks.c
- crmd/te_events.c
- crmd/tengine.h
- cts/CTStests.py
- include/crm/common/ipcs.h
- include/crm/lrmd.h
- lib/common/ipc.c
- lib/common/remote.c
- lib/lrmd/lrmd_client.c
- lrmd/lrmd.c
- lrmd/tls_backend.c
This addresses multiple issues, most of them timing-sensitive:
* Detect and log malformed CIB diffs better. (Unlikely to be an issue in practice, but this cleans up the code a bit.)
* Don't abort the transition when getting an LRM refresh via a v2 CIB diff if there are pending actions. This was already done for v1, and the same potential problem applies to v2: if there happen to be pending action results coming in at the same time as the LRM refresh, we could mistakenly discard them without processing.
* Match only executed events when searching for events that could make a node down. Previously, we matched any events, but one of the callers only accepted events that were executed. This would lead to wrong behavior when there were multiple possible matches, but the first one found had not …
> Improve crmd handling of various failures

- pacemaker.spec.in
Only a PreReq can be guaranteed to be installed before the dependent package.
> Build: spec: Make sure shadow package is installed before adding user and group

- doc/Pacemaker_Explained/en-US/Ch-Constraints.txt
- pengine/constraints.c
- xml/constraints-3.0.rng
Practically it has already been the case. But previously it would
complain if "symmetrical" was not explicitly configured for serialize
orders with resource sets:
```
Cannot invert serialized constraint set ...
```
This commit officially makes "symmetrical" default to "false" for
serialize orders and documents it.
Other fixes:
- A resource_set can have a "score" but no "kind".
- Potential use-of-NULL in unpack_simple_rsc_order().
> Fix: pengine: "symmetrical" defaults to "false" for serialize orders

- lib/pengine/failcounts.c
...when triggered.  Present since 9cf01f5f9 (or since 1.1.17).
> High: pengine: fix swapped warning message arguments leading to segfault

- lib/pengine/container.c
- lib/pengine/variant.h
- xml/resources-3.0.rng
Hi All,
When using a bundle in an environment constructed by combining containers with etcd and docker (overlay network) etc, the add-host option may be unnecessary in some cases.
In the following example, the network parameter "bundle" is the network created by "docker network create -d overlay bundle".
This amendment was discussed in the next PR.
- https://github.com/ClusterLabs/pacemaker/pull/1443
Best Regards,
> Mid: bundle: Added add-host option.

- cts/cts-cli
In particular, building RPM package and triggering %check lead
to cts-cli trying to work with shadow copies located under
/var/lib/pacemaker/cib -- and failing because that path did
not exist at that time.  This change was unintentionally
brought with 1d0d0eff2 commit.
Note that "mktemp" is not reliably portable (not POSIX'd),
but there were other occurrences already.
> Tests: cts-cli: fix thinko leading to system-wide shadow files

- .gitignore
- configure.ac
- cts/CIB.py
- cts/Makefile.am
- cts/cts-lrmd.in
- cts/pacemaker-cts-dummyd.in
- cts/pacemaker-cts-dummyd@.service.in
- include/crm/common/xml.h
- lib/common/xml.c
- lib/lrmd/lrmd_alerts.c
- pacemaker.spec.in
- tools/crm_diff.c
This separates out the code for the systemd dummy daemon used with CTS and cts-lrmd, to reduce code duplication between them. This includes a fix to use the PYTHON substitution variable for the shebang, so it can work when /usr/bin/python does not exist.
This PR also includes a few unrelated changes needed for 2.0.0, including a backport of a fix from the master branch.
> Replace embedded daemon code in tests

- lib/lrmd/lrmd_alerts.c
Hi All,
I forgot to delete crm_time_hr_new () discussed in the next PR.
For redundant code, I will send PR of deletion.
- https://github.com/ClusterLabs/pacemaker/pull/1442
```
(snip)
if (now == NULL) {
// ----> In order not to take different time, replace crm_time_hr_new ().
if (gettimeofday(&tv_now, NULL) == 0){
now = crm_time_timeval_hr_convert(NULL, &tv_now);
}
}
(snip)
```
Best Regards,
> Low: alerts: Delete redundant code.

- lib/cib/cib_attrs.c
Hi All,
The comparison may fail if uppercase letters are set in the host name since the next modification.
- https://github.com/ClusterLabs/pacemaker/commit/0371b8b2dee9b960d3cbdc8225c77e250ab0f483
This is because strcasecmp running in safe_str_eq is no longer executed by modification.
Pacemaker recommends lower case letters, but I think that it is necessary to compare in lowercase letters in order to have compatibility.
In case of Pacemaker remote, the node name is recognized by the id of the primitive resource, and in the VirttualDomain resource it is judged by the remote-node meta attribute.
Upper case letters and lower case letters may be mixed in each case.
Since I do not understand the specification of xpath deeply, I used the translate function.
- …
> Mid: lib: Changed to lowercase comparison.

- configure.ac
- pacemaker.spec.in
Avoiding evaluating underlying definition as "no" (will just fall
back to the designated default, instead), sticking with --without-brand
as a precedence.
Also an empty string propagated from there (--with-gnutls-priorities="")
would result in a run-time error:
$ gnutls-cli -l --priority=":+DHE-PSK:+PSK"
> Cipher suites for :+DHE-PSK:+PSK
> Syntax error at: :+DHE-PSK:+PSK
> Build: configure/spec surpriseless/overridable --with{,out}-gnutls-priorities handling

- pacemaker.spec.in
Arranged using coreutils-compatible "mv" implementation, with a fallback
to unconditional clobbering of the pre-existing move targets (as it used
to be).  Presence of the pre-2.0 log files clashing with 2.0 defaults
is unlikely, but better to be safe (consider also 2.0 release candidates
up to and including -rc3).
> Build: spec: add a simple retention of pre-existing log move targets

- cts/README.md
- xml/Readme.md
- xml/regression.sh
- xml/resources-3.0.rng
- xml/test-2/020-rsc-requires-inline.ref
- xml/test-2/021-rsc-requires-nvpair.ref
- xml/test-2/024-rsc-requires-no-selfclash.ref
- xml/test-2/024-rsc-requires-no-selfclash.ref.err
- xml/test-2/061-rsc-attrs-meta-exchange.ref
- xml/test-2/061-rsc-attrs-meta-exchange.ref.err
- xml/test-2/061-rsc-attrs-meta-exchange.xml
- xml/test-2/070-rsc-op-attrs-inst-requires-start.ref
- xml/test-2/070-rsc-op-attrs-inst-requires-start.ref.err
- xml/test-2/070-rsc-op-attrs-inst-requires-start.xml
- xml/test-2/071-rsc-op-attrs-inst-requires-nonstart.ref
- xml/test-2/071-rsc-op-attrs-inst-requires-nonstart.ref.err
- xml/test-2/071-rsc-op-attrs-inst-requires-nonstart.xml
- xml/test-2/072-rsc-op-attrs-inst-requires-no-override.ref
- xml/test-2/072-rsc-op-attrs-inst-requires-no-override.ref.err
- xml/test-2/072-rsc-op-attrs-inst-requires-no-override.xml
- xml/test-2/073-rsc-op-attrs-inst-meta-meaning.ref
- xml/test-2/073-rsc-op-attrs-inst-meta-meaning.ref.err
- xml/test-2/073-rsc-op-attrs-inst-meta-meaning.xml
- xml/upgrade-2.10.xsl
Pending:
its instance_attributes
the referential integrity would break (currently may happen)
version of the schema as a basis for 2.0 final release (details covered
in `XML: upgrade-2.10.xsl: rsc op instance_attrs [1/2]: meta-like requires`
commit
> [WIP][part 6] Prepare XSL template for 2-to-3 schema upgrade

- .gitignore
- xml/assets/upgrade-2.10-htmldiff.xsl
- xml/assets/view-source-library.xsl
- xml/assets/view-source-original.xsl
- xml/regression.sh
- xml/test-2/010-rsc_colocation-dropped-for-noop-sa.xml
- xml/test-2/020-rsc-requires-inline.xml
- xml/test-2/021-rsc-requires-nvpair.xml
- xml/test-2/022-rsc-requires-counterexamples.xml
- xml/test-2/023-rsc-requires-no-override.xml
- xml/test-2/024-rsc-requires-no-selfclash.xml
- xml/test-2/030-clu-props-plain-rename.xml
- xml/test-2/031-clu-props-drop.xml
- xml/test-2/032-clu-props-move.xml
- xml/test-2/033-clu-props-move-merge.xml
- xml/test-2/034-clu-props-move-redef.xml
- xml/test-2/040-nodes-rename-type.xml
- xml/test-2/050-rsc-attrs-instance-plain-rename.xml
- xml/test-2/051-rsc-attrs-instance-pcmk_arg_map.xml
- xml/test-2/060-rsc-attrs-meta-isolation.xml
- xml/test-2/061-rsc-attrs-meta-exchange.xml
- xml/test-2/070-rsc-op-attrs-inst-requires-start.xml
- xml/test-2/071-rsc-op-attrs-inst-requires-nonstart.xml
- xml/test-2/072-rsc-op-attrs-inst-requires-no-override.xml
- xml/test-2/073-rsc-op-attrs-inst-meta-meaning.xml
- xml/upgrade-2.10.xsl
- xml/upgrade-detail.xsl
This exercises some maintenance and allows one to perform the upgrade
on-the-fly, directly in the web browser + immediately observe the impact
in the form of a diff.
There's a possibility to spin-off this merely test maintenance helper to
full-fledged script that would present something similar to the user
based on arbitrary input CIB.  Such informative page itself can be
prerendered with `xsltproc` (which would be unnecessary overhead
in the context of its original use).
> [intermezzo] Prepare XSL template for 2-to-3 schema upgrade

- daemons/based/based_callbacks.c
Introduced with e480da50b; sticking with 55b023527 precedent.
> Build: based_callbacks.c: restore -Werror buildability, avoid truncation

- lib/common/schemas.c
There's a note left in the code so that it's picked in the future
overhaul regarding initialization and cleanup.
Makes valgrind output actually useful.
> Med: schemas.c: cleanup XSLT extension modules' data and whatnot

- lib/common/xml.c
Previously, this input to modification of CIB:
> <primitive ...>
>   <operations>
>     <op id="mySmartFuse-monitor-outputpower" name="monitor" interval="2s">
>       <instance_attributes id="mySmartFuse-outputpower-instanceparams">
>         <nvpair id="mySmartFuse-outputpower-req" name="req" value="outputpower"/>
>       </instance_attributes>
>     </op>
>   </operations>
>   <instance_attributes id="mySmartFuse-params">
>     <nvpair id="mySmartFuse-params-ip" name="ip" value="192.0.2.10"/>
>   </instance_attributes>
>   <instance_attributes id-ref="mySmartFuse-outputpower-instanceparams"/>
> </primitive>
would degenerate into this:
> <primitive ...>
>   <operations>
>     <op id="mySmartFuse-monitor-outputpower" name="monitor" interval="2s">
>       <instance_attributes …
> High: CIB: no schema violating oversimplified patching with @id-ref

- crmd/lrm_state.c
- crmd/messages.c
- include/crm/crm.h
- include/crm/msg_xml.h
- tools/crm_node.c
- tools/crmadmin.c
This is a partial backport of a fix from the 2.0 branch. Due to the need to support legacy cluster stacks, the entire fix will not be backported, so only the -n/-N options are handled like 2.0 for all stacks, and the -i option is handled like 2.0 only for the corosync 2+ stack. crm_node does not change packages.
> Fix crm_node -i/-n/-N for remote nodes

- include/crm/cib.h
- include/crm/common/xml_internal.h
- lib/cib/cib_ops.c
The change also means that `cibadmin` invocations will output
RNG/XSLT related messages sanely.
> XML: logging related enablement (in RNG/XSLT context)

- include/crm/stonith-ng.h
- lib/fencing/st_client.c
- tools/stonith_admin.c
For now just a minor issue I found where obviously memory allocated for stonith-history isn't freed.
The history-API-call being used in stonith_admin is probably a minor issue as stonith_admin never daemonizes and thus the leak can't accumulate.
In the library it is probably more ugly as you never know who is using it - might be a daemon where the leak can accumulate.
Intending to bring stonith-history to crm_mon where the history won't be used when it daemonizes for gathering events but in interactive mode the leak would accumulate over time.
> Fix: st_client, stonith_admin: cleanup memory of stonith-history

- tools/crm_mon.c
- xml/crm_mon.rng
Enable crm_mon to show fence-history grabbed from stonith
```
r192.168.123.104   (ocf::heartbeat:IPaddr2):	Started node2
petulant   (service:pacemaker-cts-dummyd@10):	Started node2
r192.168.123.105   (ocf::heartbeat:IPaddr2):	Started node2
lsb-dummy	(lsb:/usr/share/pacemaker/tests/cts/LSBDummy):  Started node2
Failed Resource Actions:
* Fencing_start_0 on node2 'unknown error' (1): call=77, status=Timed Out, exitreason='',
last-rc-change='Fri Jun 22 17:01:42 2018', queued=0ms, exec=60097ms
* Fencing_start_0 on node3 'unknown error' (1): call=68, status=Timed Out, exitreason='',
last-rc-change='Thu Jun 21 14:39:14 2018', queued=0ms, exec=60084ms
Failed Fencing Actions:
* reboot of node4 failed: delegate=node2, client=pacemaker-controld.7817, origin=node3,
last-failed='Fri Jun 22 16:59:39 …
```
> Feature: crm_mon: rhbz#1461964 - add fence history features

- configure.ac
- pacemaker.spec.in
It's not entirely clear why 7fb768bbd introduced it.
> Build: spec + configure: superfluous dependency of -libs-devel on -cts + deprecated macro swap

- daemons/pacemakerd/pacemakerd.c
If pacemaker shuts down due to being fenced by a non-power (eg fabric)
fence agent then it should also take down corosync so that full cluster
service on that node is lost, rather than just resource management.
https://bugzilla.redhat.com/show_bug.cgi?id=1448221
Signed-off-by: Christine Caulfield <ccaulfie@redhat.com>
> Shutdown corosync after a fatal error

- daemons/based/based_common.c
- daemons/based/based_io.c
- daemons/based/cibmon.c
- daemons/based/pacemaker-based.c
- daemons/execd/cts-exec-helper.c
- daemons/execd/pacemaker-execd.c
- daemons/fenced/cts-fence-helper.c
- daemons/fenced/pacemaker-fenced.c
- daemons/pacemakerd/pacemakerd.c
- daemons/pacemakerd/pacemakerd.h
- daemons/schedulerd/pacemaker-schedulerd.c
- tools/cibadmin.c
- tools/crm_mon.c
- tools/crm_resource.c
- tools/crmadmin.c
- tools/stonith_admin.c
This prevents accidental variable shadowing in the future, helps static
analyzers without cross-file (inter-unit) capabilities, and, for
instance, shall speed up static linking a tiny bit.  Normally,
everything is declared static unless there's a good reason not to...
Also drop some superfluous declarations, redundant with the content of
included headers.
External symbols' stats for a particular configuration of the build[*]:
- before: 3170
- after:  2989
[*] find -executable -type f -cnewer configure \
-exec nm -g --defined-only {} \; 2>/dev/null | wc -l
> Refactor: code hygiene: move towards "static" well-behavedness

- daemons/controld/controld_callbacks.c
- daemons/controld/controld_te_utils.c
- daemons/controld/controld_transition.h
- daemons/fenced/Makefile.am
- daemons/fenced/fenced_commands.c
- daemons/fenced/fenced_history.c
- daemons/fenced/fenced_remote.c
- daemons/fenced/pacemaker-fenced.c
- daemons/fenced/pacemaker-fenced.h
- include/crm/fencing/internal.h
- include/crm/stonith-ng.h
- tools/crm_mon.c
- tools/stonith_admin.c
This is the followup of #1521 
At the moment it is one big commit to discuss the basic approach:
```
- refactor init of remote_op_list
- add fence-history notifications
- add possibility to cleanup fence-history via API
- add possibility to cluster-sync fence-history via API
- refactor stonith-flags to enum
- make crm_mon use new fence-history notifications instead of polling
- add possibility to trigger new fence-history cleanup & broadcast to stonith_admin
```
Cleanup is triggered:
```
stonith_admin -H "*" --cleanup
```
The stonith-API-call creates a broadcast to all nodes in the cluster to purge their fence-history.
There are no replies expected.
Syncing the fence-history is triggered:
```
stonith_admin -H "*" --broadcast
```
The stonith-API-call creates a broadcast sending the local …
> Feature: fence-history: add cleanup & sync & history-notify

- lib/fencing/st_client.c
- tools/crm_mon.c
- tools/stonith_admin.c
Pending fence-actions as well as failed fence-actions should be empty on a healthy cluster
and especially pending fence-actions aren't prone to clutter the display as they disappear anyway.
so this - in case fence-history isn't shown - this adds an additional section for pending actions that pops up of there is anything pending (just as with failed actions).
in addition the - anyway to adapt - help now tries to clarify the unclear situation the the default with the '-m' option given but without value is different from the default if -m isn't given at all.
the distinction makes sense in a way that '-m' is also called --fence-history which would mean for my intuition that it should turn on the history-section when issued without additional value.
```
-m, --fence-history[=value]	Show fence …
```
> Feature: crm_mon: default to showing pending fence actions

- cts/remote.py
- cts/watcher.py
... as of Python 3.7:
https://docs.python.org/3/whatsnew/3.7.html#summary-release-highlights
One of the instance attributes turned out to be bogus.
Randomly spotted; unfortunately byte compilation when building package
for Fedora will not consider unability to pregenerate bytecode a fatal
problem.
> Maint: cts: refrain from async (await) in Python code for being reserved

- doc/Pacemaker_Explained/en-US/Ch-Rules.txt
Takes its value from site-name node attribute, not cluster property.
> Doc: Pacemaker Explained: Fix #site-name node attribute description

- lib/pengine/container.c
- lib/pengine/variant.h
- xml/crm_mon.rng
- xml/resources-3.2.rng
In the same vein as 202be7dee6db "PE: Bundles: add support for rkt bundle type"
we add support for another container type for bundles: podman.
Tested with the following container:
podman container set: test_bundle [docker.io/sdelrio/docker-minimal-nginx]
test_bundle-podman-0 (ocf::heartbeat:podman):        Started nodea
test_bundle-podman-1 (ocf::heartbeat:podman):        Started nodeb
test_bundle-podman-2 (ocf::heartbeat:podman):        Started nodec
Tested a couple of stop/start cycles successfully.
I will play with more complex scenarios as all the pieces start coming
together.
> Initial podman support

- pacemaker.spec.in
First, "so that the -libs-devel package is multilib-compliant
(no *.py[co] files)" became stale as of ea6e988e8 at latest:
- -libs-devel in the comment reference effectively turned into -cts
(originally affected files: tests/{fencing/lrmd}/regression.py)
- "multilib compliancy" no longer relevant, but for quite some
time already, "selecting the right Python for RPM-natively
run byte-compiling outside of dedicated directories" is what
makes turning such automatism off a wise decision
Another line of the problem is that otherwise beneficial automake's
automatism (heh) normally triggers Python byte-compilation on its
own for _PYTHON-suffixed variables.  That indeed should not override
procedures intrinsically aligned with wider system, so we just cut
that off when we know we have these …
> Build: spec: sanitize/generalize approach to Python byte-compilation

- cts/CIB.py
- cts/CTS.py.in
- cts/cts-exec.in
- cts/cts-fencing.in
- cts/cts-support.in
- cts/fence_dummy.in
- daemons/fenced/cts-fence-helper.c
Previously, CTS and cts-fencing individually copied fence_dummy to /usr/sbin (cts-fencing removed it after completing, CTS did not); cts-fencing also used sed on fence_dummy to create two variants; and cts-exec used its own internally defined versions of two dummy fence agents.
Now, fence_dummy can handle all of the desired variations, and cts-support handles installing and uninstalling it for all tests.
Besides making things more consistent, this will help CI run more regression tests.
> Consolidate dummy fence agents

- autogen.sh
- configure.ac
- daemons/based/based_callbacks.c
- daemons/fenced/pacemaker-fenced.c
- lib/cluster/corosync.c
- lib/common/remote.c
- tools/notifyServicelogEvent.c
This was a chained mess:
* fixed-width integer types from <stdint.h> are usually accompanied with
respective format specifiers in <inttypes.h>, which should have been
a first line of the solution
* relying on the compiler erroring out on the incorrect format specifier
in a compile test is broken (if nothing else, may fail like that for
unrelated reasons, which also happened in the case referred below),
especially since it's trivially solvable in a preprocessing test,
which avoids inteferring with -D_FORTIFY_SOURCE vs. optimization
switches -- even more so when they are split between CFLAGS and
CPPFLAGS, see https://bugs.clusterlabs.org/show_bug.cgi?id=5274
> Build: configure: fix overkill format specifier serving uint64_t check

- tools/crm_mon.c
Collection of small crm_mon output fixes.
So far:
- use more common language when connection to the cluster goes wrong
- a node in standby-mode might still have running resources - make that visible in crm_mon's output
- when writing to an html-file stdout just shows that it is attempting to connect to the cluster
> Crm mon output fixes

- .travis.yml
We will cache relaxng.rng file using the respective Travis CI facility.
Note that we really don't need to ship that file with pacemaker itself,
plus it would be one more license to care about if we borrowed that
file from BSD-covered jing-trang project:
https://github.com/relaxng/jing-trang/blob/master/eg/relaxng.rng
So we rather stay sole user of that file than redistributor...
> Test: travis: refrain from relying on (and bothering) relaxng.org host

- daemons/controld/controld_callbacks.c
- daemons/controld/controld_membership.c
- daemons/controld/controld_membership.h
- daemons/controld/controld_te_utils.c
- include/crm/cluster/internal.h
- lib/cluster/cpg.c
- lib/cluster/membership.c
Previously, the controller implicitly assumed that CPG notifications would always be received after quorum notifications when a node joined. However, that is not guaranteed, and in a test environment with corosync 2.99.3 and pcs 0.10.0, the opposite order happens frequently. The issue was likely possible with corosync 2 as well, possibly dependent on start-up timing.
There was also a related bug that was hidden when the expected order occurred, in the handling of conflicting CPG and quorum states for a node.
> Handle CPG and quorum notifications in either order

- daemons/attrd/attrd_commands.c
- daemons/attrd/pacemaker-attrd.c
- daemons/attrd/pacemaker-attrd.h
Hi All,
This correction is based on the idea from Mr. Ken.
It adds the ignore_delay parameter to reduce the number of times of scanning the attribute hash table.
In the current processing, scanning of the attribute hash table is executed twice, but this patch makes it once.
Best Regards,
> Low: attrd: Adding the ignore_delay parameter to reduce the number of scans of the attribute hash table.

- tools/crm_mon.c
This makes errors after connected successfully once non-fatal.
Further reduce number of global symbols by making all functions
static and make the definition consistent and compliant to the
coding guidelines.
> Fix: crm_mon: don't exit directly from cib_connect on error

- tools/report.collector.in
- tools/report.common.in
This request has two commits.
1. https://github.com/inouekazu/pacemaker/commit/f4c4568b007387788b4a750842c2019787954371
```
+    pattern="$pattern\\|Calculated transition"
```
It corresponds to [66364b5](https://github.com/ClusterLabs/pacemaker/commit/66364b5caa2db55d0dd437e6e1ce8237e2cb86aa#diff-9eabe1ed584de205bd89ecbf6c5ac527).
---
```
pattern="$pattern\\|cib_perform_op\\|process_lrm_event"
+    pattern="$pattern\\|Diff: +++ \\|Result of .* for .* on"
```
The messages logged via syslog does not contain a function name, so I added a <pattern> that is output within that function.
```
Aug 16 14:16:50 r75a pacemaker-based     [13647] (cib_perform_op)       info: Diff: --- 0.15.0 2
Aug 16 14:16:50 r75a pacemaker-based     [13647] (cib_perform_op)       info: Diff: +++ 0.15.1 (null)
Aug 16 …
```
> Fix: tools: Make crm_report correctly find the system log

- extra/alerts/alert_snmp.sh.sample
Some SNMP trap handlers expect all OID fields from a MIB to be available with every trap.
> Low: alerts: send all MIB OIDs with all SNMP alerts

- tools/crm_report.in
- tools/report.collector.in
Since RHEL 7.3 and later sosreport executes crm_report with --sos-mode,
the logs specified in ```PCMK_logfacility``` (/etc/sysconfig/pacemaker)
and ```syslog_facility``` (/etc/corosync/corosync.conf) are not collected.
This fixes https://bugs.clusterlabs.org/show_bug.cgi?id=5365
> Fix: crm_report: search for logs via syslog when being called by sosreport (CLBZ#5365)

- tools/crm_resource_runtime.c
The resource-agents package's ocf-shellfuncs library uses whether it has a controlling terminal to decide whether to send messages to stderr. This means that crm_resource --force-* commands run via e.g. ssh (without the -t option) would not get stderr output as expected with the -V option.
This makes crm_resource set the OCF_TRACE_FILE environment variable to /dev/stderr to force the agent to write messages to stderr (when verbose is set).
> Low: tools: ensure crm_resource --force-* commands get stderr messages

- tools/report.collector.in
lsblk ships with util-linux. If we assume that the system has 'mount' installed, I believe we can safely assume it will have 'lsblk' as well. 
I would find it useful in the crm_reports to quickly get an understanding of the storage on the node.
> Low: tools: Add lsblk to sysstats output in crm_reports

- daemons/controld/controld_schedulerd.c
- daemons/controld/controld_te_utils.c
- daemons/fenced/fenced_commands.c
- daemons/fenced/fenced_history.c
- daemons/fenced/fenced_remote.c
- daemons/fenced/pacemaker-fenced.c
- daemons/fenced/pacemaker-fenced.h
- include/crm/cluster/internal.h
- lib/cluster/membership.c
9045bac prevented manual fencing confirmations from creating node
entries for random unknown nodes, but it also disabled the ability to do
manual fencing confirmations for the nodes that are already known in the
CIB but not yet in the membership cache.
This commit fixes it by maintaining and utilizing an additional
membership cache of known nodes based on the CIB.
This follows up the discussions from https://github.com/ClusterLabs/pacemaker/pull/1503
> Fix: controld: able to manually confirm unseen nodes are down

- daemons/controld/controld_execd_state.c
- daemons/controld/controld_lrm.h
- daemons/controld/controld_remote_ra.c
- include/crm/msg_xml.h
This is crucial when watchdog-fencing is enabled as the sbd-check
done by pacemaker-remote would fail on guest-containers & bundles
(eventually tearing down pacemaker-remote inside the container)
and even on system-virtualized-guests the sbd-check doesn't make
sense as these guests would be fenced by stop/start-cycling the
VM.
As a base for discussion for the first ...
Currently skipping the whole remote_config_check for guest-nodes.
As neither a guest-node's pacemaker_remoted knows that it is
running on a guest-node nor this info is easily available when the
remote_config_check is kicked off from inside controld after the
remote-connection is established the info is passed from
schedulerd via a mockup attribute (controlling-guest).
As the decision not the kick off the check is entirely …
> Fix: pacemaker-remote: skip remote_config_check for guest-nodes

- daemons/fenced/pacemaker-fenced.c
This reverts
#1320 
and instead checks for meta-attribute deletion on cib-updates.
Content of resource-defaults may as well be relevant for the fencing devices. Thus we should look at that as well when fenced get cib-updates.
As we are adding additional checks to cib-updates it makes sense to bail out early in case of status-updates we are not interested in here.
> Fix fenced device update

- Makefile.common
The --help and --version calls are tripping up building on openbsd, and
do not currently appear to be adding anything that we can't figure out
elsewhere.
See https://bugs.clusterlabs.org/show_bug.cgi?id=5341.
> Build: Makefile.common: Remove extra output when making man pages

- doc/Clusters_from_Scratch/en-US/Ap-Configuration.txt
- doc/Clusters_from_Scratch/en-US/Ch-Active-Passive.txt
- doc/pcs-crmsh-quick-ref.md
Following the documentation, with netmask=32 the cluster IP will
eventually drop, likely after ten or fifteen minutes when you've stopped
paying attention, due to an error from findif.
There are two possible solutions.  First, you can use netmask=32
nic=eth0 (or whatever your network device is).  Second, you can use
netmask=24 by itself.  I've gone with the latter here because it's less
stuff for people to do.
See https://bugs.clusterlabs.org/show_bug.cgi?id=5325.
> Doc: Clusters from Scratch: Fix netmask in ClusterIP example.

- cts/CTSlab.py.in
It is expected that when starting a certain test without parameters it
is run once.
> Test: cts: set default number of iterations to 1

- .travis.yml
Caused with a permanent redirect to https URI at relaxng.org.
> CI: travis: disable selfchecks of XSL regression for now

- cts/CTStests.py
Previously, failure of pacemaker_remoted was simulated by sending
SIGKILL and issuing additional stop to pacemaker_remote.service. But
stop of pacemaker_remote.service would also result in stop of
sbd_remote.service if used, which'd practically leave noone eating the
poison pill.
> Test: cts: simulate failure of pacemaker_remoted by freezing it with SIGSTOP

- cts/pacemaker-cts-dummyd.in
systemd.daemon requires the systemd python library which is provided
by neither of SUSE Enterprise Linux. If systemd.daemon cannot be
imported, use the bash subprocess.call instead of the systemd.daemon.notify.
This resolves #1636
> Test: cts: use bash in the pacemaker-cts-dummyd if no systemd.daemon

- daemons/attrd/attrd_commands.c
- daemons/attrd/pacemaker-attrd.h
- include/crm_internal.h
Hi All,
This PR is a modified version of the content discussed in the next PR.
- https://github.com/ClusterLabs/pacemaker/pull/1625
Currently, this patch works quite as expected, but it is not perfect.
If election of attrd is delayed and problems arise, please set the transition-delay parameter.
Best Regards,
> Mid : attrd: Ignoring delayed updating of attributes when integrating disjointed clusters without stonith.

- .gitlab-ci.yml
We start with a matrix similar to that in .travis.yml:
* build + tests, using
- gcc
- clang
* various compilation-free immediate maintenance checks
All using Fedora Rawhide, for various reasons:
- spot the possible breakages down the line early
(incompatibility in the surrounding software, etc.)
- is reasonably trimmed down (now that glibc-langpacks-all
doesn't hog the installation)
- close familiarity on the side of developer(s), at least me :-)
As an extra, experimental measure, we put some hard time limits
on some time-criticial execution, since when they get breached
regularly, we shall reconsider whether just to bump that value
or to change the approach/restructure whole pipeline.
Conversely, when we are blocked on an RPM repo mirror, we
shall rather give up early.
Another notable …
> CI: kick off .gitlab-ci.yml for integration with GitLab CI

- daemons/attrd/attrd_alerts.c
- daemons/attrd/attrd_commands.c
- daemons/attrd/attrd_elections.c
- daemons/attrd/attrd_utils.c
- daemons/attrd/pacemaker-attrd.c
- daemons/attrd/pacemaker-attrd.h
Most significantly, avoid an unnecessary delay introduced by 73e5b6d3, start a new election as soon as the old writer is lost, and check for alert changes after a CIB replace.
> Minor enhancements to pacemaker-attrd

- cts/cts-exec.in
It'd still make sense to run the rest tests in such a case I think.
> Test: cts-exec: still run the tests for the other resource classes even without python systemd bindings

- tools/crm_resource.c
- tools/crm_resource.h
- tools/crm_resource_ban.c
- tools/crm_resource_runtime.c
- tools/regression.sh
- tools/regression.tools.exp
A node can be specified two different ways - with attribute="#uname"
and value= on an expression XML node, or with node= on a rsc_location
XML node. Both possibilities need to be considered when attempting to
clear an existing constraint.
cli_resource_clear was previously only considering the second case.
This patch rearranges the code to allow for trying both, and then adds
the code to try the first case by constructing a different blob of XML
to match.
See rhbz#1648620
> Bug: tools: Fix moving a resource with a lifetime constraint

- configure.ac
- cts/CIB.py
- cts/Makefile.am
- cts/pacemaker-cts-dummyd.in
- cts/pacemaker-cts-dummyd.service.in
- This pull request complements the pull request #1639. The overall idea
is to replace the systemd.daemon.notify python method with its bash
analog, because the systemd.daemon is provided by neither of SUSE
Enterprise Linuxes. This implementation not only replaces the
method, but also backports the pacemaker-cts-dummyd files from the master
branch.
> * Test: cts: DummySD --> pacemaker-cts-dummyd

- crmd/lrm.c
> lrm.c: In function 'unescape_newlines':
> lrm.c:2483:9: error: 'strncpy' output truncated before terminating nul
>               copying 2 bytes from a string of the same length
>               [-Werror=stringop-truncation]
>          strncpy(pch, "\n ", 2);
>          ^~~~~~~~~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors
Point is, we know better than compiler that is essentially a safe swap
of a pair of bytes.
> [1.1.20] Missing cherry-pick from master

- cts/CTStests.py
- cts/environment.py
Cluster nodes are reused as remote nodes in remote tests. If cluster
services were enabled at boot, in case the remote node got fenced, the
cluster node would join instead of the expected remote one. Meanwhile
pacemaker_remote would not be able to start. Depending on the chances,
the situations might not be able to be orchestrated gracefully any more.
> Test: cts: temporarily disable any enabled cluster serivces when running remote tests

- daemons/based/based_callbacks.c
- tools/test.iso8601.c
Sadly, pacemaker codebase seems to be possibly heavily spoiled with
this undefined behaviour when possibly passing NULL corresponding to
'%s' format specifier argument, so for the time being, fix just what
new GCC 9 started to spot[*] (due to build-time constant NULLs, which
is an immediate proof) since these occurrences boil down to mere
thinkos.  Related to that, would be wise to start rolling out
nonnull annotations to preserve more general sanity in this self
explanatory aspect.
Looking at libqb code (end destination of "crm_log" processing), there's
nothing to implicitly mask NULL with a predestined string explicitly
(like glibc make do with "(null)" in majority of the cases), so unless
merely a blackbox is used for logging (qb_vsnprintf_serialize seems to
deal with such a NULL …
> [2.0.1] restore gcc9 buildability

- tools/crm_mon.c
and unnecessary conditionals making code less readable that were
probably introduced rearranging the code.
> low: crm_mon: remove duplicity of fence-action-state in xml-output

- configure.ac
- include/crm/common/results.h
- include/crm/common/util.h
- lib/common/results.c
- lib/common/strings.c
- tools/stonith_admin.c
This format specifier is not supported by all the OS versions that
pacemaker currently builds on.  Thus it needs to be conditionalized.  In
case that specifier is not supported, use a combination of strstr and
strdup to split the provided option apart into its name and value.
> Build: configure: Conditionalize support for sscanf's %m.

- daemons/attrd/attrd_elections.c
- include/crm/cluster/election.h
- lib/cluster/election.c
Commit 435b7728 ironically made a second avenue for the problem it fixed more likely, by making it easier to hit a pre-existing timing issue in the libcrmcluster election code. This fixes that second avenue.
> Complete the fix for losing attribute write-out at node shutdown

- include/crm/services.h
- include/crm/stonith-ng.h
- lib/fencing/st_client.c
- lib/services/services.c
- lib/services/services_linux.c
- lib/services/services_private.h
- tools/Makefile.am
- tools/crm_resource.c
- tools/crm_resource.h
- tools/crm_resource_runtime.c
Here's a first draft at adding support for running the validate-all action based upon command line parameters, and not against some existing resource in the CIB.  Not all standards support validate-all at this time, but this patch set should handle any future updates along these lines without changes.  This patch currently requires a CIB connection but I think I can fix that if necessary - it's just because of where the code is positioned in crm_resource.c.
> Add support for validating resources based on command line options

- lib/common/operations.c
8435966 (2.0.0) got the sense of compare_version() wrong when attempting to remove the old behavior for recording partial live migrations, instead re-introducing it.
This causes a regression in behavior when a transition containing a live migration is aborted after the migrate_to has been initiated but before the migrate_from has been initiated. In that case, it would schedule a full start on the destination node rather than a migrate_from.
> Restore correct behavior for completing interrupted live migrations

- include/crm/stonith-ng.h
- lib/fencing/st_client.c
There's no need for this to return a gboolean, which requires then
including glib.h.  It can just be a bool.
> Fix: libfencing: Change return type on stonith_agent_exists.

- .gitlab-ci.yml
At this time, it seems better to retain signature checking enabled,
though it would be a definitive solution when the triggering out-of-sync
scenario is more a norm than an exception (unexpected).
Context:
<https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/OCFJJYQY65GBMAPDGAJKMJMYLVZ6AQYI/>
> CI: .gitlab-ci.yml: note a workaround for "troublesome Fedora branching"

- doc/Pacemaker_Development/en-US/Ch-Coding.txt
- doc/Pacemaker_Development/en-US/Ch-Evolution.txt
- doc/Pacemaker_Development/en-US/Ch-FAQ.txt
- doc/Pacemaker_Development/en-US/Ch-General.txt
- doc/Pacemaker_Development/en-US/Ch-Python.txt
- doc/Pacemaker_Development/en-US/Pacemaker_Development.xml
The previous policy of listing solely the original author's name was inconsistent with the reality of copyrights. The new policy has been added to a new "general guidelines" chapter.
> Update copyright notice policy

- lib/common/nvpair.c
Detected by static analysis; if pcmk_prepend_nvpair() were given a NULL value, pcmk__new_nvpair() would try to strdup() it. Now, name is asserted to be non-NULL, and NULL values are set directly.
> Backport handling of NULL name/value

- include/crm/services.h
- lib/Makefile.am
- lib/fencing/Makefile.am
- lib/fencing/st_client.c
- lib/services/services_linux.c
- lib/services/services_private.h
Intention is using a common service interface for calling RAs, alert-agents and fence-agents
as there is a lot of code duplicity between those implementations atm and in the past
(and actually present regarding error-output-handling of fence-agents) there have been
shortcomings on one or the other side that were fixed independently from each other.
There is a basic difference between an RA and calling a fence-agent mostly coming from
that one is about having some service running persistently and the other being about basically
a one-time-action. Alert-agents are more similar to fence-agents when it comes to this
one-time-action perspective. But if they fail they just fail and don't need anything like retries.
Hence that retry-approach is one of the larger differences in the …
> use common service interface

- daemons/execd/pacemaker_remote.service.in
- daemons/pacemakerd/pacemaker.service.in
Also unify the pacemaker_remote.service counterpart.
> Maint: pacemaker.service: cleanup/commentary on TimeoutStopSec directive

- tools/stonith_admin.c
The previous commit changed the output format.  However the output
format is relied upon in other places.
> Fix: stonith_admin: Bring fence_action_str back.

- tools/regression.sh
Previously, the cts-cli would only work with a zero-offset time zone
(suggesting that it was only run in the CI that may be expected to
have it like that).  Also drop the atypical enumeration of all digits
vs. range capture.
Backport-from-master-of: bfa3ddc527b8bfafe60b44185c1aa44abbdb5b7c
> [1.1] make fully buildable again

- include/crm/pengine/Makefile.am
It should've been done in b368355.
For instance sbd is encountering:
```
In file included from sbd-pacemaker.c:57:0:
/usr/include/pacemaker/crm/pengine/status.h:28:12: fatal error: crm/pengine/pe_types.h: No such file or directory
^~~~~~~~~~~~~~~~~~~~~~~~
```
> Build: include: install crm/pengine/pe_types.h

- .travis.yml
- configure.ac
- daemons/attrd/pacemaker-attrd.c
- daemons/based/pacemaker-based.c
- daemons/controld/controld_control.c
- daemons/controld/pacemaker-controld.c
- daemons/fenced/pacemaker-fenced.c
- daemons/pacemakerd/pacemakerd.c
- daemons/pacemakerd/pcmkd_corosync.c
- include/crm/common/Makefile.am
- include/crm/common/internal.h
- include/crm/common/ipc.h
- include/crm/common/ipc_internal.h
- lib/cluster/corosync.c
- lib/cluster/cpg.c
- lib/common/ipc.c
- lib/common/pid.c
- lib/services/services.c
- lib/services/services_linux.c
See also:
https://www.openwall.com/lists/oss-security/2019/04/17/1
People are strongly suggested to get these patches in.
> High: cumulative patchset to fix CVE-2019-3885, CVE-2018-16877, CVE-2018-16878 + additional unmasked null pointer deref

- .travis.yml
- attrd/main.c
- cib/main.c
- configure.ac
- crmd/control.c
- crmd/main.c
- fencing/main.c
- include/crm/common/Makefile.am
- include/crm/common/ipc.h
- include/crm/common/ipc_internal.h
- include/crm_internal.h
- lib/cluster/corosync.c
- lib/cluster/cpg.c
- lib/common/ipc.c
- lib/common/utils.c
- lib/services/services.c
- lib/services/services_linux.c
- mcp/corosync.c
- mcp/pacemaker.c
See also:
https://www.openwall.com/lists/oss-security/2019/04/17/1
People are strongly suggested to get these patches in.
> [1.1] High: cumulative patchset to fix CVE-2019-3885, CVE-2018-16877, CVE-2018-16878 + additional unmasked null pointer deref

- .gitignore
- include/crm/common/output.h
- include/crm/common/results.h
- include/crm/stonith-ng.h
- lib/common/Makefile.am
- lib/common/output.c
- lib/common/output_text.c
- lib/common/output_xml.c
- lib/common/results.c
- lib/fencing/Makefile.am
- lib/fencing/st_output.c
- pacemaker.spec.in
- tools/stonith_admin.c
- xml/Makefile.am
- xml/api/command-output-1.0.rng
- xml/api/stonith_admin-1.0.rng
- xml/best-match.sh
This is an initial draft of a patch set to add formatted, machine-readable output to various pacemaker command line tools.  For now, all that's present is the basics to choose the output format, inital formatting functions, and changes to stonith_admin to use it all.  Everything should be pretty well explained in individual commit messages.  It's not especially complicated stuff.
> Add formatted output

- lib/cluster/cpg.c
- lib/common/strings.c
- lib/services/services_linux.c
- lrmd/ipc_proxy.c
- lrmd/lrmd.c
- mcp/corosync.c
- pengine/constraints.c
Most importantly, correct a typo in a previous backport that could lead to use of uninitialized or invalid memory.
The backport of the "symmetrical" change could be considered a change in defaults that is questionably backward-compatible, but the behavior is identical other than silencing a spammy log message, so it's also reasonable to consider it merely a logging change.
> Backport recent fixes from master branch

- include/crm/common/iso8601_internal.h
- lib/cib/cib_utils.c
- lib/common/iso8601.c
- lib/common/xml.c
- tools/crm_mon.c
This code is defined in a couple different places, so it might as well
get moved into one single spot in libcrmcommon.  Plus, it's less stuff
in crm_mon to deal with later.
> Refactor: libcrmcommon: Add crm_now_string.

- lib/common/output_text.c
If the singular_noun or plural_noun arguments are NULL, calling strdup
will result in a segfault.  It's possible for these to be NULL -
text_end_list allows for that.  So guard against the segfault.
> Fix: libcrmcommon: Don't segfault in text_begin_list.

- daemons/controld/controld_execd.c
- daemons/controld/controld_te_callbacks.c
- daemons/controld/controld_te_events.c
- daemons/controld/controld_transition.h
- daemons/controld/controld_utils.c
- daemons/controld/controld_utils.h
Usually after a monitor has been cancelled from executor, contoller
erases the corresponding lrm_rsc_op from the cib, and DC will confirm
the cancel action by process_op_deletion() according to the cib diff.
But if a monitor has failed, the lrm_rsc_op will be recorded as
"last_failure". When cancelling it, the lrm_rsc_op won't get erased from
the cib given the logic on purpose in erase_lrm_history_by_op(). So that
the cancel action won't have a chance to get confirmed by DC with
process_op_deletion().
Previously cluster transition would get stuck waiting for the remaining
action timer to time out.
This commit fixes the issue by directly acknowledging the cancel action
in this case and enabling DC to be able to confirm it.
This also moves get_node_id() function into controld_utils.c for …
> Fix: controller: confirm cancel of failed monitors

- lib/common/xml.c
Given a resource group:
```
<group id="dummies">
<primitive id="dummy0"/>
<primitive id="dummy1"/>
<primitive id="dummy2"/>
<primitive id="dummy3"/>
<primitive id="dummy4"/>
</group>
```
, if we'd like to change it to:
```
<group id="dummies">
<primitive id="dummy3"/>
<primitive id="dummy4"/>
<primitive id="dummy2"/>
<primitive id="dummy0"/>
<primitive id="dummy1"/>
</group>
```
, the generated XML diff would be like:
```
<diff format="2">
<change operation="move" path="//primitive[@id=dummy3]" position="0"/>
<change operation="move" path="//primitive[@id=dummy4]" position="1"/>
<change operation="move" path="//primitive[@id=dummy0]" position="3"/>
<change operation="move" path="//primitive[@id=dummy1]" position="4"/>
</diff>
```
Previously after applying the XML diff, the resulting XML …
> Fix: libcrmcommon: correctly apply XML diffs with multiple move/create changes

- cts/cts-fencing.in
- daemons/fenced/fenced_commands.c
- include/crm/fencing/internal.h
- lib/fencing/st_client.c
Bailing out in case of non-existant fence-agent is such a case.
> Fix: fence-lib: avoid use-after-free on early failure return

- daemons/fenced/fenced_commands.c
If it is a retry device is already moved from activating_on to
active_on.
> Fix: fence-lib: regression introduced with fork callback

- pacemaker.spec.in
These would be delivered (co-owned in practice) with both -cli & -libs
and since the former cannot exist without the latter and since -cli
doesn't make any direct references to the particular new API schemas
anyway (judging per "Use formatted output in stonith_admin" commit),
just follow standard "include here, exclude-but-parent" there pattern.
> Build: spec: fix redundantly carried /usr/share/pacemaker/api/ files

- lib/common/xml.c
Backport of https://github.com/ClusterLabs/pacemaker/pull/1762 for 1.1 branch.
> [1.1] Fix: libcrmcommon: correctly apply XML diffs with multiple move/create changes

- crmd/crmd_utils.h
- crmd/lrm.c
- crmd/te_callbacks.c
- crmd/te_events.c
- crmd/tengine.h
- crmd/utils.c
Backports of https://github.com/ClusterLabs/pacemaker/commit/4f0399336d47162035fde6d0d23077bfd8ae4119 and https://github.com/ClusterLabs/pacemaker/pull/1772 for 1.1 branch.
> [1.1] Fix: controller: confirm cancel of failed monitors

- daemons/attrd/attrd_commands.c
- daemons/controld/controld_execd.c
- daemons/fenced/fenced_remote.c
We propose the following three log level improvements to output the necessary logs for the user.
1: Fix monitor's log to match other operation's log level
The log level of monitor is currently output as info and does not appear in syslog.
In this case, it is difficult to understand the movement of resources triggered by a monitor error.
By the way, even if you change this level, the log of the monitor that is repeatedly executed will not be output, so I think that the log will not become noisy.
2: Fix the log level when the node attribute changes to notice
Even if the attribute changes, it may trigger the move of the resource, so it is better to change it to notice level and notify the user.
Since this is also a log that is output only when the attribute changes, I think that the log will …
> Improve the log level to output the log required for the user.

- daemons/based/based_io.c
Not so helpful to observe
> Archiving unusable file /var/lib/pacemaker/cib/cib.xml as
> /var/lib/pacemaker/cib/cib.auto.XXXXXX
(not the end of the world either, especially if the chronology can
be reconstructed through timestamps)
The pessimistic case of mkstemp failing is already addressed with
a follow-up message (it's not so important to distinguish the
cause, since we know statically that trivial EINVAL won't be
that case, and anything else is expected to be a fallout of
about the same circumstance, e.g. filesystem/dir perms).
> Log: based: make "preventive rename" on CIB access fault path-specific

- daemons/execd/execd_commands.c
- daemons/execd/pacemaker-execd.h
- daemons/fenced/fenced_commands.c
- lib/fencing/st_client.c
with a bit of other fencing improvements spurred by testing. Fixes CLBZ#5352.
> Make stonith device probes fail after executor's stonith connection is lost

- cts/cts-scheduler.in
This will make it easier to do more complicated stuff, eventually including a common regression test framework.
I tried to keep the behavior and output very similar, even where that was kind of questionable, with minor exceptions: the original would sometimes print trailing whitespace which is no longer done, some of the test descriptions ended with a '.' and now don't, and one test was missing a description. A few trivially obvious bugs were probably fixed.
> Test: cts-scheduler: convert to python

- daemons/controld/controld_control.c
- daemons/controld/controld_election.c
- daemons/controld/controld_messages.c
- daemons/controld/controld_schedulerd.c
- daemons/controld/controld_te_utils.c
- daemons/controld/controld_utils.h
If the DC is able to successfully send a calculation request to the scheduler, but the scheduler never returns a result, the controller would previously not detect this, and the cluster would become blocked. Now, the DC fatally exits if the scheduler doesn't return a result within 2 minutes of a request.
> Detect unresponsive scheduler

- include/crm/pengine/internal.h
- lib/pengine/bundle.c
- lib/pengine/clone.c
- lib/pengine/native.c
- lib/pengine/pe_output.c
This commit complements the 2735a7d0cb15041eb29ffe09232efa2b07bb6091. It adds the functions-messages
to print information about resources in plain-text.
DON'T MERGE! The PR is incomplete.
This PR together with the PR #1788 bring 8 new functions by splitting/refactoring the existing ones
native_print --> (pe__resource_xml + pe__resource_text)
group_print --> (pe__group_xml + pe__group_text)
clone_print --> (pe__clone_text + pe__clone_text)
pe__bundle_print --> (pe__bundle_xml + pe__bundle_text)
I tried to keep the logic between the xml and text version similar. I
removed the pre_text and print_data paramenters from both the *_xml and *_text
functions. In case of xml it should work fine, but in case of *_text
functions it could break the reverse compatibility. I SIMPLY DON'T PRINT
THE …
> Feature: pengine: formatted output for text

- configure.ac
- daemons/pacemakerd/pacemaker.sysconfig
- lib/common/remote.c
Pacemaker 2.0.0 allowed GnuTLS cipher priorities to be specified at build time via a configure script switch. With this commit, that sets the default priorities, but the user can now configure the priorities list at runtime using an environment variable (/etc/sysconfig or equivalent).
> Feature: remote: allow run-time configurable TLS priorities

- include/crm/common/output.h
- include/crm/common/xml.h
- lib/common/Makefile.am
- lib/common/output.c
- lib/common/output_html.c
- lib/common/output_none.c
- lib/common/output_text.c
- lib/common/output_xml.c
- lib/common/xml.c
- lib/fencing/st_output.c
This splits a couple commits out of PR #1798, introducing just the new formatters.  The other two commits fix a couple of minor problems just so I don't have to do them later and the new formatters can start off without those problems.
> Add HTML and none formatters

- include/crm/pengine/internal.h
- lib/pengine/bundle.c
- lib/pengine/clone.c
- lib/pengine/native.c
- lib/pengine/pe_output.c
This PR complements the PRs #1821 and #1788. It adds other 4 functions-messages
to print information about resources in HTML by splitting/refactoring
native_print --> pe__resource_html
group_print --> pe__group_html
clone_print --> pe__clone_html
pe__print_bundle --> pe__bundle_html
Like the *_xml functions, the *_html functions don't have the pre_text
parameter. A single space used instead. (It's fair for html).
Like the PR #1821, it adds the supplementary functions:
print_bundle_replica --> pe__bundle_replica_output_html
common_print --> pe__common_output_html
print_rscs_brief --> pe__rscs_brief_output_html
short_print --> pe__short_output_html
native_print_attr --> pe__native_output_attr_html
> Feature: pengine: formatted output for html

- include/crm/common/output.h
- include/crm/common/xml.h
- lib/common/output_html.c
- lib/common/output_xml.c
- lib/common/xml.c
- lib/fencing/st_output.c
- lib/pengine/bundle.c
- lib/pengine/clone.c
- lib/pengine/native.c
- lib/pengine/pe_output.c
This PR renames a bunch of functions to a consistent naming scheme, adds a couple useful functions, and in general just tries to straighten out the mess that is the XML node creating functions in formatted output.  I kind of hate how long the function names are, but it seems necessary for explaining which function does what.
I additionally have started a cheat sheet locally for when you should use which function.  It could be added somewhere, but I couldn't find a great place for it.
> Make sense of our various XML functions in formatted output

- include/crm/common/cmdline_internal.h
- lib/common/cmdline.c
- tools/stonith_admin.c
This patch introduces a new pcmk__cmdline_preproc function which
restores getopt's single character argument behavior that was lost when
switching to glib.  getopt recognizes a string like "-xval" to be the -x
command line option with a value of val.  glib would recognize that as
the four command line options -x, -v, -a, and -l.
Passing the command line through this new function converts it into
something that glib understands.  See the documentation and comments on
this function for more details.
> Fix: libcrmcommon:  Restore getopt behavior in stonith_admin.

- extra/resources/ClusterMon.in
- extra/resources/Dummy
- extra/resources/HealthCPU
- extra/resources/HealthIOWait
- extra/resources/HealthSMART.in
- extra/resources/Stateful
- extra/resources/SysInfo.in
- extra/resources/SystemHealth
- extra/resources/attribute
- extra/resources/controld
- extra/resources/ifspeed.in
- extra/resources/o2cb.in
- extra/resources/ping
- extra/resources/pingd
- extra/resources/remote
The main incentive for this is that a pacemaker agent is often used as a template for new agents, which has resulted in various ugliness being propagated around. I decided to do a general clean-up of all the agents to use good shell programming practices, and fixed a few bugs discovered in the process.
There are a few more things I'd like to do, but this has taken enough time already.
> Clean up ocf:pacemaker resource agents

- include/crm/cib/Makefile.am
Since it's included in other external headers.
It should have been done in 70f21e6f8.
> Build: libcib: install cib_types.h

- include/crm/common/cmdline_internal.h
- lib/common/cmdline.c
- lib/common/output_html.c
- lib/common/output_text.c
- lib/common/output_xml.c
- tools/Makefile.am
- tools/crm_mon.c
- tools/crm_mon.h
- tools/crm_mon_curses.c
- tools/crm_mon_print.c
These patches add the formatted output command line options, a curses formatted, and a special XML formatted to crm_mon.  There's a lot of code to make sure both the older mode options and the newer formatted output options both work and both do the same things.  Also note that while the formatted output options are present, there's no formatted output yet.
> Initial formatted output support in crm_mon

- tools/crm_mon.h
- tools/crm_mon_print.c
- tools/crm_mon_runtime.c
Instead of using g_hash_table_foreach and passing in a pointer to the
list that needs to be updated, simply use an iter and update the list as
we go.  This fixes a bug where the list was not actually being appended
to.
> Fix: tools: Fix append_attr_list.

- lib/common/acl.c
- lib/common/xml.c
- lib/pacemaker/pcmk_sched_allocate.c
- lib/pacemaker/pcmk_sched_constraints.c
- lib/pacemaker/pcmk_sched_native.c
- lib/pacemaker/pcmk_sched_transition.c
- lib/pengine/clone.c
- lib/pengine/complex.c
- lib/pengine/group.c
- lib/pengine/rules.c
- lib/pengine/rules_alerts.c
- lib/pengine/unpack.c
- lib/pengine/utils.c
- tools/crm_mon.c
- tools/crm_mon_print.c
- tools/crm_resource_print.c
- tools/crmadmin.c
__xml_first_child() and __xml_next() are intended to be used in "for" loops
where all XML node types (elements, comments, etc.) are desired.
__xml_first_child_element() and __xml_next_element() are intended when
only element children are desired.
Previously, many element-only loops properly used __xml_next_element() but
started with __xml_first_child(). In most cases, this would (by lucky
circumstance) work without harm. However, there were cases where a comment as
the first child of an element would case problems (for example,
unpack_resources() would log a configuration error).
Now, __xml_first_child_element() is always used in such cases.
Additionally, there were some loops using __xml_first_child()/__xml_next() that
clearly were expecting only elements. These have been converted to …
> Fix: all: restrict XML children loops to XML elements where appropriate

- lib/pengine/common.c
cluster option "stop-all-resources" behaviour was changed in f4d8a29d6d
at 2010. It was reverted by ecd95f7f10 at 2012, but only left the
self-documenting text behind. It makes 'man pengine' and 'man
pacemaker-schedulerd' conflict with the actual behaviour since then.
BTW, "Pacemaker Explained" is up-to-date and in the good shape for it.
Signed-off-by: Roger Zhou <zzhou@suse.com>
> Doc: fix stop-all-resources self-documenting text

- configure.ac
- lib/pacemaker-cib.pc.in
- pacemaker.spec.in
- xml/Makefile.am
- xml/pacemaker-schemas.pc.in
This need stems from the downstream parcelling of the bits (where
it irrefutably, unlike with upstream one trying to be as suitable
and universal preimage as possible [hence this upstream change],
interacts with other software packages such as clufter [see also
6ef3f776b]), since previously, any external package only interested
in the actual schemas or transformation stylesheets would (in
systemically constructed approach not relying on any kind of
pacemaker-related hardwiring, which is recommended for obvious
reasons) query pacemaker-cib.pc for schemadir variable.  However,
for that file to be present, the avalanche of packages starting
with pacemaker devel package (and consequently corosync libraries,
libqb, ...) is needed for that, adding up to the from-ground-up
requirements …
> Build: add truly noarch indirection towards pacemaker schemas

- lib/fencing/st_client.c
Hi All,
When pcmk_monitor_action is specified in fence_mpath etc., the following log is output in the monitor cycle and it is very noisy.
```
Aug 30 13:06:47 rh80-04 pacemaker-fenced    [17361] (make_args)         info: Substituting action 'metadata' for requested operation 'monitor'
Aug 30 13:07:48 rh80-04 pacemaker-fenced    [17361] (make_args)         info: Substituting action 'metadata' for requested operation 'monitor'
Aug 30 13:08:48 rh80-04 pacemaker-fenced    [17361] (make_args)         info: Substituting action 'metadata' for requested operation 'monitor'
Aug 30 13:09:48 rh80-04 pacemaker-fenced    [17361] (make_args)         info: Substituting action 'metadata' for requested operation 'monitor'
Aug 30 13:10:48 rh80-04 pacemaker-fenced    [17361] (make_args)         info: …
```
> Low: libstonithd: Changing the log level.

- tools/crm_mon_print.c
Hi All,
Hi Ken,
Hi wenningerk,
This is a modification of crm_mon discussed in the next PR.
- https://github.com/ClusterLabs/pacemaker/pull/1872
This should reduce user confusion.
(After failure)
```
[root@rh76hv-02 ~]# crm_mon -1 -Af
Stack: corosync
Current DC: rh76hv-02 (version 2.0.2-3e18b2a5a0) - partition WITHOUT quorum
Last updated: Wed Sep  4 14:10:37 2019
Last change: Wed Sep  4 13:56:49 2019 by root via cibadmin on rh76hv-01
2 nodes configured
2 resources configured
Node rh76hv-01: UNCLEAN (offline)
Online: [ rh76hv-02 ]
Active resources:
Resource Group: grpStonith1
prmStonith1-2      (stonith:external/ssh): Started rh76hv-02
Resource Group: grpStonith2
prmStonith2-2      (stonith:external/ssh): Started rh76hv-01 (UNCLEAN)
Node Attributes:
* Node rh76hv-02:
Migration Summary:
* …
```
> Mid: crm_mon: Displays completed failed actions as processed.

- Makefile.am
- cts/Makefile.am
- cts/cts-scheduler.in
- xml/Makefile.am
This is part of a larger project to get "make distcheck" working for CI purposes. This handles the second step of make distcheck, running "make check" from the build tree of a VPATH build with a read-only source directory created by "make dist".
This does not address later steps of make distcheck, which still fails.
> Get "make check" working in VPATH builds

- .travis.yml
- GNUmakefile
- Makefile.am
- configure.ac
- cts/Makefile.am
- cts/cts-support.in
- daemons/execd/Makefile.am
- daemons/pacemakerd/Makefile.am
- daemons/pacemakerd/pacemakerd.c
- lib/common/watchdog.c
- rpm/pacemaker.spec.in
- tools/Makefile.am
- tools/ipmiservicelogd.c
- xml/Makefile.am
These are the final changes to get "make distcheck" working. They take care of the last two steps in the process: running "make install" in a VPATH build (for non-root accounts), and ensuring "make distclean" doesn't leave anything behind.
This involves adding several new configure options for normally hardcoded locations. In addition there are a few related commits cleaning up the configure script and makefiles. Two unused configure options are now officially deprecated.
> Get "make distcheck" working

- .gitignore
- .travis.yml
- GNUmakefile
- Makefile.am
- configure.ac
- lib/Makefile.am
- lib/ais/Makefile.am
- lib/common/watchdog.c
- lrmd/Makefile.am
- mcp/Makefile.am
- mcp/pacemaker.c
- pengine/Makefile.am
- rpm/pacemaker.spec.in
- tools/Makefile.am
- tools/ipmiservicelogd.c
- xml/Makefile.am
"make distcheck" requires automake 1.12 or higher (for AM_DISTCHECK_CONFIGURE_FLAGS; this is true of the master branch as well), and does not work if support for the corosync 1 plugin is enabled (which could be fixed by adding a configure option for lcrsodir, but that's not worth the effort at this point)
> Backport build changes from master to get "make distcheck" working

- cts/cli/regression.tools.exp
- cts/cts-cli.in
- tools/crm_resource_runtime.c
When applying maintenance to a group of primitives, it applies it to the
first primitive in the group, but leaves the group maintenance property and
all other primitives unchanged.
This patch makes all primitives in the group and the group itself inherit the maintenance attribute.
> fix: crm_resource: apply maintenance property to all group primitives and the group itself

- extra/resources/SysInfo.in
Fix a problem that '1.9T' converted to '1' in SysInfo_megabytes
> Fix SysInfo_megabytes func

- lib/common/cmdline.c
These were getting skipped, meaning there was no way of specifying
stdin/stdout as command line parameters.  Just pass them through and let
the rest of the command line handling code decide if it's an error or
not.
> Fix: libcrmcommon: Accept a single dash on the command line.

- doc/Pacemaker_Administration/en-US/Ch-Configuring.txt
- doc/Pacemaker_Administration/en-US/Ch-Tools.txt
- doc/Pacemaker_Administration/en-US/Ch-Troubleshooting.txt
- doc/Pacemaker_Administration/en-US/Ch-Upgrading.txt
- doc/Pacemaker_Administration/en-US/Pacemaker_Administration.xml
This adds a new chapter to the "Pacemaker Administration" document for the command-line tools.
Existing documentation for crm_mon, cibadmin, crm_shadow, and crm_simulate has been moved to the new chapter, and documentation for attrd_updater and crm_attribute have been added. Additionally the ClusterLabs wiki page "Using crm_simulate" has been merged into the crm_simulate section.
> Document command-line tools in Pacemaker Administration

- include/crm/services.h
- lib/fencing/st_client.c
- lib/services/services.c
Switching to common service interface for fencing actions as of
18c321e79 introduced a regression that concurrent fencing actions on a
fencing device would get blocked. The impact would be very obvious for
"slow" fencing mechanisms such as sbd.
> Fix: fencing: Do not block concurrent fencing actions on a device

- daemons/fenced/fenced_commands.c
A fencing device might get triggered to work by multiple fencing
commands simultaneously. Trigger the device again to make sure any
remaining concurrent commands get executed.
> Fix: fencer: Make sure concurrent fencing commands get triggered to execute

- include/crm/services.h
- lib/fencing/st_client.c
- lib/services/services.c
Backport of #1902 for 1.1 branch.
Switching to common service interface for fencing actions as of
18c321e79 introduced a regression that concurrent fencing actions on a
fencing device would get blocked. The impact would be very obvious for
"slow" fencing mechanisms such as sbd.
> [1.1] Fix: fencing: Do not block concurrent fencing actions on a device

- fencing/commands.c
Backport of #1904 for 1.1 branch.
A fencing device might get triggered to work by multiple fencing
commands simultaneously. Trigger the device again to make sure any
remaining concurrent commands get executed.
> [1.1] Fix: fencer: Make sure concurrent fencing commands get triggered to execute

- cts/Makefile.am
- cts/cts-support.in
- cts/cts.conf
When killing the corosync in the ComponentFail test, the node will not
necessarily be shot. If it's shot it will go into CTStests.py: 1430,
otherwise it will jump over the 'if shot:' statement in CTStests.py: 1429
and the removed patterns
r"pengine.*Scheduling Node .* for STONITH",
r"crmd.*:\s*Peer .* was terminated \(.*\) by .* for .*:\s*OK"
will not be matched => false positive failure.
> Test: cts: ComponentFail: killed corosync may not reboot the node

- fencing/commands.c
- fencing/regression.py.in
- lib/fencing/st_client.c
Backport of #1910 for 1.1 branch.
This is trivial but I feel it'd make life easier to keep things consistent when it's possible.
* Quote fencing actions
* Fencing actions "targeting ..." instead of "for node ..."
> [1.1] Log: fencer: improved log messages regarding fencing actions

- daemons/pacemakerd/pacemakerd.c
- include/crm/common/internal.h
- lib/common/io.c
- lib/services/services_linux.c
This is irrelevant in normal use. However, valgrind can open high-numbered
file descriptors for its own use above the soft limit of the process being run
under valgrind. If that process forks a child that tries to close all open file
descriptors (e.g. the executor running an agent), the close fails because the
file descriptors are invalid, and (ironically) valgrind warns about that.
This allows 5a73027 to work under valgrind. Additionally, we extend the
efficient close method from that commit to pacemakerd's spawning of children.
> Low: libcrmservice: don't close descriptors above current limit

- cts/CTS.py
- cts/CTStests.py
Backport the #1897. corosync doesn't respawn immediatelly when killed,
so that the fencing had more time to reboot the node.
> Test: cts: ComponentFail: killed corosync doesn't respawn immediatelly.

- include/crm/common/output.h
- tools/crm_mon_output.c
Using the function attribute means the compiler will check that callers
include a NULL at the end.
> Fix: libcrmcommon: Enforce NULL in pcmk__html_add_header args.

- doc/Pacemaker_Administration/en-US/Ch-Tools.txt
- include/crm/common/cmdline_internal.h
- include/crm/common/output.h
- lib/common/cmdline.c
- lib/common/output.c
- lib/common/output_html.c
- lib/common/output_text.c
- lib/common/output_xml.c
- tools/crm_mon.c
- tools/crm_node.c
- tools/stonith_admin.c
Also, rename them from --output-whatever to --<format>-whatever.
> Put all formatted output command line args into a single group

- include/crm/common/xml.h
- lib/pengine/bundle.c
- lib/pengine/clone.c
- lib/pengine/group.c
- lib/pengine/pe_output.c
- tools/crm_mon_output.c
- tools/crm_mon_print.c
crm_element_name will return "master" for these resources but there is
no message registered for that, so master resources will just get
ignored.  We need to map "master" to "clone" before calling the message
function.  crm_map_element_name does that, giving us a place to do
future mappings if necessary.
> Fix: libpengine: Correct display of master resources.

- configure.ac
- daemons/execd/execd_commands.c
Since the usage of ftime(3) used to be opt-in only and since
clock_gettime(3) is mandated with POSIX 2001, we can simply
look at whether CLOCK_MONOTONIC is defined to be used as an
identifier for the particular clock (kind exactly suitable
for this context).  Dropping some old cruft being a bonus.
Restores out-of-the-box buildability with recent enough glibc.
References:
https://sourceware.org/git/?p=glibc.git;a=commit;h=2b5fea833bcd0f651579afd16ed7842770ecbae1
https://src.fedoraproject.org/rpms/glibc/c/ebf75398f06dd27357d8a5321e8e5959633b8182?branch=master
(for a Fedora Rawhide follow-the-upstream update that lead to this
discovery)
> Build: restore buildability in the face of obsolete ftime(3)

- Makefile.common
- tools/Makefile.am
- tools/crm_mon.8.inc
- tools/crm_mon.c
- tools/fix-manpages
This moves the notes and time specification sections out of crm_mon's
help output and into crm_mon.8.inc so they get included in the man page.
The help output contains a reference to the man page so people know
what's up with TIMESPEC.
Previously, I was using asterisks around the section names to set them
apart in the man page.  This served to turn those names into proper man
page sections, while as the same time looking reasonably good in the
help output.  However, this asterisk trick does not work with older
versions of help2man, such as is used in the epel7 mock chroot (and
therefore presumably, on RHEL7 builders).
> Fix: tools: Correct the crm_mon man page.

- lib/pengine/complex.c
Both primitive and cluster may have maintenance attribute.
When a primitive has is-managed=true, maintenance=false
and the cluster has maintenance-mode=true, the maintenance-mode
wouldn't previously override the is-managed attribute as expected.
> Fix: scheduler: make sure cluster-wide maintenance-mode=true overrides per-resource settings

- lib/common/iso8601.c
crm_time_parse_offset() incorrectly handles time offset with plus ('+') sign, e.g. +0900 while minus ('-') is handled correctly.
> Fix: iso8601: Fix crm_time_parse_offset() to parse offset with plus sign.

- doc/Pacemaker_Administration/en-US/Ch-Troubleshooting.txt
The function outputting the transition statistics is not
process_pe_message since commit 4d5fe6bf (present in 2.0.2), but
pcmk__log_transition_summary, so that part is different in the actual
log now. The first part of the log line (up to "notice") is subject to
change anyway, so just omit it altogether for simplicity.
> doc: skip outdated part of example log

- tools/crm_mon_curses.c
The placeholder version that is built if curses is not enabled does not
have a type that matches the header file.  Correct that.
> Fix: tools: Fix definition of curses_indented_printf.

- daemons/attrd/attrd_alerts.c
- daemons/attrd/pacemaker-attrd.c
- daemons/controld/controld_attrd.c
- daemons/controld/controld_based.c
- daemons/execd/execd_alerts.c
- include/crm/Makefile.am
- include/crm/common/Makefile.am
- include/crm/common/alerts_internal.h
- include/crm/common/attrd_internal.h
- include/crm/common/results.h
- include/crm_internal.h
- lib/common/acl.c
- lib/common/agents.c
- lib/common/alerts.c
- lib/common/attrd_client.c
- lib/common/ipc.c
- lib/common/results.c
- lib/lrmd/lrmd_alerts.c
- lib/pengine/rules_alerts.c
- tools/attrd_updater.c
- tools/crm_attribute.c
- tools/crm_error.c
- tools/crm_node.c
- tools/crm_resource.c
- tools/crm_resource.h
- tools/crm_resource_runtime.c
- tools/notifyServicelogEvent.c
Since we are soon introducing a high-level public API, it's a good time to
address issues with the current model of function return codes.
Most Pacemaker API functions currently return an integer return code, such that the
absolute value of the return code is either a system error number or a custom
pcmk_err_* number. This is less than ideal because system error numbers are
constrained only to the positive int range, so there's the possibility (though
not noticed in the wild) that system errors and custom errors could collide.
The new method being introduced here still uses an integer return code,
but negative values are from a new enum pcmk_rc_e, and positive values are
system error numbers. 0 still represents success.
It is expected that the new method will be used with new public API …
> Refactor: libcrmcommon: introduce new set of return codes

- include/Makefile.am
- include/crm/common/cmdline_internal.h
- include/crm/common/output.h
- include/doxygen.h
- include/pacemaker-internal.h
- include/pacemaker.h
- include/pcmki/Makefile.am
- include/pcmki/pcmki_fence.h
- include/pcmki/pcmki_output.h
- lib/common/cmdline.c
- lib/common/output.c
- lib/common/output_html.c
- lib/common/output_log.c
- lib/common/output_none.c
- lib/common/output_text.c
- lib/common/output_xml.c
- lib/pacemaker/Makefile.am
- lib/pacemaker/pcmk_fence.c
- lib/pacemaker/pcmk_output.c
- tools/Makefile.am
- tools/crm_diff.c
- tools/crm_mon.c
- tools/crm_mon_curses.c
- tools/crm_node.c
- tools/stonith_admin.c
At the least, I sitll need to add a bunch of documentation to the headers.  Return codes will need to be synced up with that PR.  I haven't really taken much care with return values at the moment because of that.  Here's some other things to think about:
* The pcmk__preproc_cmdline patch ends up being totally standalone, but I think it's worth it.
* I got rid of the pcmk__output_fnew/pcmk__output_dnew patch, but it could come back.  Nothing ended up needing it.
* Some of the public functions in lib/pacemaker/pcmk_stonith.c are just wrappers around the private versions.  I thought it was important to have both to keep the completeness of both APIs.
* Not everything that stonith_admin does ended up getting turned into API functions.  For instance, the register and remove device blocks in …
> Move stonith_admin into a library

- include/crm/common/results.h
In principle this is an ABI change, but the affected versions (2.0.2 and
later) were impossible to build due to duplicate case values in
lib/common/results.c.
https://bugs.clusterlabs.org/show_bug.cgi?id=5419
> Avoid clashes with glibc error codes on HPPA

- fencing/commands.c
Backport of more commits from https://github.com/ClusterLabs/pacemaker/pull/1818 for 1.1 branch.
It makes sense to fix the behavior of `stonith_admin --list-targets`.
> [1.1] fencer: don't require API registration for list and status commands

- tools/stonith_admin.c
There are three understandings of time here.  stonith_admin wants
seconds on the command line and stores timeouts and tolerances in
seconds.  The tool API wants to get those values in milliseconds.  The
stonith_t commands also want seconds.
Right now, the API converts its parameters from milliseconds to seconds.
However, stonith_admin is not passing the API milliseconds.  It's
directly passing what it gets from the command line, which is seconds.
When the timeout values finally make it to the stonith_t commands,
they've effectively been divided down to zero.
This patch corrects the problem by continuing to store timeouts in
seconds in stonith_admin, but multiplying them by 1000 to make them
milliseconds before passing to the API.  An alternate fix would be to
have stonith_admin store …
> Fix: tools: Correct sec vs. msec discrepancy in stonith_admin.

- lib/common/mainloop.c
Problem of not explicating how exactly the function is supposed to
behave that would allow for a straightforward cross-check, as opposed
to examining the callers into full depth that often gets substituted
with guestimation.
> Fix: rectify thinko possibly behind spurious "process will not die" msg

- daemons/execd/pacemaker-execd.h
Currently, -fno-common yields (and only yields, slightly restructured):
> /usr/bin/ld:
>   pacemaker_execd-execd_commands.o:
>     pcmk/daemons/execd/pacemaker-execd.h:23:
>       multiple definition of `rsc_list';
>   + pacemaker_execd-pacemaker-execd.o:
>     pcmk/daemons/execd/pacemaker-execd.h:23:
>       first defined here
>
>   pacemaker_execd-execd_alerts.o:
>     pcmk/daemons/execd/pacemaker-execd.h:23:
>       multiple definition of `rsc_list';
>   + pacemaker_execd-pacemaker-execd.o:
>     pcmk/daemons/execd/pacemaker-execd.h:23:
>       first defined here
>
> collect2: error: ld returned 1 exit status
The problem is that a global (with external linkage) variable without
explicit "extern" stands for "tentative definition" (as opposed to mere
reference to existing object with …
> Build: get ready for implicit -fno-common with upcoming GCC 10

- include/crm/pengine/internal.h
- lib/pengine/pe_output.c
- tools/crm_mon_curses.c
- tools/crm_mon_print.c
Previously, I had changed print_rsc_history to call the new
resource-header message instead of resource-history.  The thinking there
was the previous message was being used in two different ways and we
needed two different messages to cover each case.
However, this change means that all the non-text formats are calling a
non-existent resource-header message and not getting anything output
here at all.  For these formats, I still want the old message to be
called.  There are a couple ways to accomplish this, but it seems like
the easiest is to just have the resource-header message go to the same
place that resource-history does.
Note that this means the handlers for those two messages must always
take the same arguments.
> Fix: libpe_status: Add resource-header messages for other formats.

- lib/pengine/pe_output.c
This patch turns this output:
Operations:
* Node: cluster01:
* stonithid: migration-threshold=1000000 fail-count=1000000:
* (11) start:
* (14) stop:
Into this:
Operations:
* Node: cluster01:
* stonithid: migration-threshold=1000000 fail-count=1000000:
* (11) start
* (14) stop
> Fix: libpe_status: Remove extra colons from operations output.

- lib/cib/cib_attrs.c
Memory allocated with g_ascii_strdown() should be deallocated with g_free() accordingly.
Found by Cppcheck.
> Fix: cib_attrs: Fix mismatching deallocation

- tools/crm_mon.c
Many error messages were being printed out with fprintf, printf, or
print_as which means they were unconditionally printed to the console
instead of through the formatted output system.  For XML and other
structured formats, this means getting plain text printed out in the
middle of the rest.
This doesn't fix all error messages.  Many errors are still using
print_as, but those are only related to refreshing the screen in a loop
which should not affect XML or HTML output.  Other error messages occur
before formatted output is active, or if there's an error in the
formatted output itself.  These have likewise not been converted.
See: rhbz#1793653
> Fix: tools: Use formatted output for more errors in crm_mon.

- daemons/attrd/attrd_utils.c
- daemons/attrd/pacemaker-attrd.c
- daemons/based/based_callbacks.c
- daemons/controld/controld_control.c
- daemons/controld/controld_execd.c
- daemons/controld/controld_execd_state.c
- daemons/controld/controld_messages.c
- daemons/controld/controld_messages.h
- daemons/execd/execd_commands.c
- daemons/execd/pacemaker-execd.c
- daemons/execd/remoted_proxy.c
- daemons/fenced/fenced_commands.c
- daemons/fenced/pacemaker-fenced.c
- daemons/pacemakerd/pacemakerd.c
- daemons/schedulerd/pacemaker-schedulerd.c
- include/crm/common/ipcs_internal.h
- lib/common/ipc.c
- maint/mocked/based.c
- tools/Makefile.am
- tools/crm_resource.c
- tools/crm_resource.h
- tools/crm_resource_controller.c
- tools/crm_resource_controller.h
- tools/crm_resource_runtime.c
This isolates the controller-related code of crm_resource into new files crm_resource_controller.h and crm_resource_controller.c, creating an IPC API interface for the controller somewhat like what we have for other daemons. This is intended as a first step toward a common model for daemon IPC APIs, to be refined and eventually moved to libcrmcommon.
It is also hoped to fix CLBZ#5420, or at least make it easier to fix.
> Abstract controller API from crm_resource

- .gitignore
- configure.ac
- include/crm/common/util.h
- lib/common/Makefile.am
- lib/common/strings.c
- lib/common/tests/Makefile.am
- lib/common/tests/strings/Makefile.am
- lib/common/tests/strings/pcmk__parse_ll_range.c
- lib/common/tests/strings/pcmk__split_range.c
- lib/pengine/rules.c
- lib/pengine/tests/rules/pe_cron_range_satisfied.c
This is in support of #1982.  If it would help, I could make a bunch of other improvements here like skipping whitespace, returning ints instead of chars, and returning errors if the bounds aren't valid ints.  This function is only used in one spot at the moment but maybe it'll prove more broadly useful once it's in a library.
> Move decodeNVpair into libcrmcommon, rename, and extend.

- tools/crm_mon.c
- tools/crm_mon_curses.c
When clean_up_connections is called at the end of crm_mon, one of the
things it does is call mon_cib_connection_destroy.  This calls out->err.
However, this happens after curses has been shut down.  The result is
the terminal doesn't work as expected after crm_mon quits.
Instead, move all the curses shutdown code into curses_finish.  This
function gets called almost as the very last thing, hopefully after any
other output could possibly take place.
I did a little bit of reorganization around how out->finish is called at
the end of crm_mon too, just to make everything happen in one place.
> Fix: tools: Properly close ncurses output in crm_mon.

- include/crm/pengine/internal.h
- lib/pengine/pe_output.c
- tools/crm_mon.8.inc
- tools/crm_mon.c
- tools/crm_mon.h
- tools/crm_mon_curses.c
- tools/crm_mon_print.c
- tools/fix-manpages
- xml/api/crm_mon-2.1.rng
- xml/crm_mon.rng
I'm not sure I am done testing this, but the final patches are likely to look very much like these.  Basically, --include and --exclude are added as command line options.  Each can be specified multiple times, and each time can have a comma-separated list of output sections.  These options build off the defaults and can be mixed with older options line --failcounts, --inactive, and --operations.  They are just different ways of manipulating the `show` bitfield.
> More command line options to control crm_mon output

- cts/cli/regression.rules.exp
- cts/cts-cli.in
- include/crm/common/results.h
- include/crm/pengine/rules_internal.h
- lib/common/results.c
- lib/pengine/rules.c
- lib/pengine/tests/rules/pe_cron_range_satisfied.c
- tools/crm_rule.c
I'm not really convinced the CRM_EX_UNSATISFIED patch is necessary, but it seemed worth it to differentiate between the expired/unexpired and currently-in-effect/not-in-effect cases.  They seem subtly different to me.
> Expand what crm_rule can check

- lib/pengine/pe_output.c
All output message functions should always pop all arguments off the
va_arg stack, even if they're not going to use them.  This is to help
prevent bugs in the future.  The ones that are unused should be marked
as such.
> Fix: libpe_status: Add unused arguments to output messages.

- tools/crm_mon.c
- tools/crm_mon.h
- tools/crm_mon_print.c
These are fixes for things found while testing #1944.  The error reporting patch is probably the least tested and also probably worth the most discussion.  I've also not been able to reproduce the pending fencing action problem.
> Fixes for crm_mon following --include/--exclude

- include/crm/common/internal.h
- include/crm/common/util.h
The argument orders of definition and declaration for decode_transition_key() and generate_transition_key()  do not match.
This fixes the order in the declarations, the order in the definitions is correct.
Found with the help of Cppcheck.
> Low: crm: Fix argument order in declarations

- tools/crm_resource.c
Hi All,
NULL set of cib connection pointer of bye () process added to master is missing.
For this reason, running cleanup will cause a segmentation fault.
```
[root@rh80-test01 tools]# crm_mon -1 -Af
* Stack: corosync
* Current DC: rh80-test01 (version 2.0.3-78db2071e) - partition WITHOUT quorum
* Last updated: Tue Mar 10 10:26:41 2020
* Last change:  Tue Mar 10 10:16:54 2020 by hacluster via crmd on rh80-test01
* 2 nodes configured
* 12 resource instances configured
Node List:
* Online: [ rh80-test01 ]
* OFFLINE: [ rh80-test02 ]
Active Resources:
* prmDummy    (ocf::heartbeat:Dummy): Started rh80-test01
* Clone Set: prmPing-clone [prmPing]:
* Started: [ rh80-test01 ]
* Resource Group: grpTest:
* prmDummy1 (ocf::heartbeat:Dummy): Started rh80-test01
* prmDummy2 …
```
> High: tools: Add clear cib connection pointer.

- include/crm/common/output.h
- include/crm/common/results.h
- include/crm/pengine/internal.h
- lib/common/output.c
- lib/common/results.c
- lib/fencing/st_output.c
- lib/pacemaker/pcmk_fence.c
- lib/pengine/bundle.c
- lib/pengine/clone.c
- lib/pengine/group.c
- lib/pengine/native.c
- lib/pengine/pe_output.c
- tools/crm_mon_curses.c
- tools/crm_mon_print.c
The point of this is to make it easier to tell whether or not something has been printed in crm_mon's text mode, getting rid of a bunch of special purpose variables I added for that purpose.  All formatted output messages should return a standard pacemaker return code now, though not all of them need to be checked.
> Convert formatted output to use new pacemaker return codes

- daemons/schedulerd/pacemaker-schedulerd.c
- include/crm/common/output.h
- lib/common/output.c
- tools/crm_mon.c
This functions frees the hash table previously constructed by
pcmk__register_formats and also frees the strings that are the keys.
This should be called at program termination.
> Fix: libcrmcommon: Add pcmk__unregister_formats.

- tools/crm_mon_print.c
The previous patch using pcmk_rc_no_output was close, but not completely
correct.  It failed to account for the situation where block A has
output, block B was requested but has no output, and block C has output.
In this case, rc will be set to pcmk_rc_no_output from the call to block
B, resulting in no blank line between A and C.
Instead, what we need to do is keep track of if any block before the
previous one had output, only setting rc to pcmk_rc_ok and never back to
pcmk_rc_no_output.
> Fix: tools: One more blank line related fix for crm_mon.

- include/crm/common/results.h
- lib/common/results.c
- tools/Makefile.am
- tools/crm_simulate.8.inc
- tools/crm_simulate.c
- tools/fix-manpages
Note that there's still one pretty big problem I can't figure out.  The last patch ("Feature: Use glib for cmdline processing in crm_simulate.") causes `cts/cts-cli` to fail.  Backing the patch out makes everything pass.  Diffing expected output against generated output produces things like this:
```--- /tmp/cts-cli.tools.e7PzKuTeCc       2020-03-27 14:40:06.532345387 -0400
+++ cts/cli/regression.tools.exp        2020-03-05 17:17:24.703884790 -0500
@@ -329,14 +329,14 @@
Performing requested modifications
- + Bringing node UTF-16BE online
+ + Bringing node node1 online
Transition Summary:
Executing cluster transition:
Revised cluster status:
-Online: [ UTF-16BE ]
+Online: [ node1 ]
```
I can't find any reason why that would be the case, so hopefully someone else can spot it.  Note that …
> Convert crm_simulate to use glib for command line handling

- include/crm/cluster/internal.h
- lib/cluster/membership.c
The reason is not clear yet, but some clusters of users ran into the
situation that corosync somehow bumped the ringid to a huge number like
"4294967300" which is exactly greater than the maximum uint32_t:
```
corosync[...]:   [TOTEM ] A new membership (X.X.X.X:4294967300) was
formed. Members
```
Node state got updated but with a wrong "last_seen" assigned to an
incomplete ringid:
```
pacemaker-controld  [...] info: Quorum retained | membership=4294967300
members=1
pacemaker-controld  [...] notice: Node node1 state is now member |
nodeid=... previous=unknown source=pcmk_quorum_notification
pacemaker-controld  [...] info: Cluster node node1 is now member (was in
unknown state)
```
And it immediately reaped itself from the membership cache because the
wrong "last_seen" of course was not …
> Fix: libcrmcluster: use uint64_t type for corosync ringid (membership  id) when updating node state

- lib/pengine/bundle.c
- lib/pengine/clone.c
- lib/pengine/group.c
- lib/pengine/pe_output.c
- tools/crm_mon_print.c
The calls to these messages were all missing the argument showing which
nodes should be output, which would have resulted in some weird bugs
(and potentially segfaults).  Doing this also requires adding the same
argument to the node message so it can be passed through.
Finally, pe__output_node passes the complete node list instead of
obeying the --node= option.  This function is marked in the header file
as a debugging function so it seems reasonable to not do any filtering.
> Fix: libpe_status: Add node list arg to output messages.

- include/crm_internal.h
- lib/fencing/st_output.c
- lib/pengine/bundle.c
- lib/pengine/clone.c
- lib/pengine/group.c
- lib/pengine/native.c
- lib/pengine/pe_output.c
- tools/crm_mon_curses.c
- tools/crm_mon_print.c
With some other tools, this can be used for compile time analysis.  It can also be used to grep for where formatted output messages are defined.
> Mark formatted output messages with a special #define

- lib/pengine/clone.c
If "crm_mon --show-detail" is given, the summary lists should not be
displayed in the non-XML formats.
> Fix: libpe_status: Skip summary output of cloned resources.

- cts/fence_dummy.in
- lib/fencing/st_client.c
- lib/fencing/st_rhcs.c
-  Add `plug` parameter besides `port` for RHCS-style fence-agents
According to:
https://github.com/ClusterLabs/fence-agents/commit/de490e059
, `port` parameter is massively deprecated in favor of `plug`:
```
<parameter name="plug" ... obsoletes="port">...
<parameter name="port" ... deprecated="1">...
```
The relatively new agent:
https://github.com/ClusterLabs/fence-agents/blob/master/agents/gce/fence_gce.py
doesn't even correctly handle `port`.
With the commit, `plug` parameter is added besides `port` with the same value.
- The `action` and `plug` parameters of RHCS-style fence-agents are shown as non-required in the metadata
The parameter `action` of RHCS-style fence-agents shouldn't usually be
specified in fencing resource configuration, although it'd be properly
remapped anyways with …
> Fixes: libstonithd: handling parameters of RHCS-style fence-agents

- include/crm/cluster/internal.h
- lib/cluster/membership.c
Backport of https://github.com/ClusterLabs/pacemaker/pull/2030 for 1.1 branch.
The culprit is clear now: https://github.com/corosync/corosync/pull/532#issuecomment-617647233 
Cluster with mixed versions of corosync with or without those commits could run into the
situation that corosync unexpectedly bumped the ringid to a huge number like
"4294967300" which is exactly greater than the maximum uint32_t:
```
corosync[...]:   [TOTEM ] A new membership (X.X.X.X:4294967300) was
formed. Members
```
Node state got updated but with a wrong "last_seen" assigned to an
incomplete ringid:
```
pacemaker-controld  [...] info: Quorum retained | membership=4294967300
members=1
pacemaker-controld  [...] notice: Node node1 state is now member |
nodeid=... previous=unknown source=pcmk_quorum_notification …
```
> [1.1] Fix: libcrmcluster: use uint64_t type for corosync ringid (membership id) when updating node state

- daemons/based/based_callbacks.c
With ```cibadmin --replace --scope=configuration```, ```<node>``` will disappear from CIB.
```
* Stack: corosync
* Current DC: r81-1 (version 2.0.3-432290022) - partition with quorum
* Last updated: Tue Apr 28 12:13:47 2020
* Last change:  Tue Apr 28 12:13:32 2020 by hacluster via crmd on r81-1
* 2 nodes configured
* 0 resource instances configured
Node List:
* Online: [ r81-1 r81-2 ]
Active Resources:
* No active resources
<cib crm_feature_set="3.3.0" validate-with="pacemaker-3.3" epoch="5" num_updates="4" admin_epoch="0" cib-last-written="Tue Apr 28 12:13:32 2020" update-origin="r81-1" update-client="crmd" update-user="hacluster" have-quorum="1" dc-uuid="1">
<configuration>
<crm_config>
<cluster_property_set id="cib-bootstrap-options">
<nvpair …
```
> Fix: cib: populate cib_nodes when 'cibadmin -R -scope=configuration'

- fencing/fence_dummy
- lib/fencing/st_client.c
- lib/fencing/st_rhcs.c
Backport of https://github.com/ClusterLabs/pacemaker/pull/2036 for 1.1 branch.
-  Add `plug` parameter besides `port` for RHCS-style fence-agents
According to:
https://github.com/ClusterLabs/fence-agents/commit/de490e059
, `port` parameter is massively deprecated in favor of `plug`:
```
<parameter name="plug" ... obsoletes="port">...
<parameter name="port" ... deprecated="1">...
```
The relatively new agent:
https://github.com/ClusterLabs/fence-agents/blob/master/agents/gce/fence_gce.py
doesn't even correctly handle `port`.
With the commit, `plug` parameter is added besides `port` with the same value.
- The `action` and `plug` parameters of RHCS-style fence-agents are shown as non-required in the metadata
The parameter `action` of RHCS-style fence-agents shouldn't usually be
specified in …
> [1.1] Fixes: libstonithd: handling parameters of RHCS-style fence-agents

- daemons/controld/controld_messages.c
Hi All,
This fix allows CRM_OP_LRM_DELETE to be properly processed after shutdown-lock-limit has expired.
The contents are in Bugzilla at:
- https://bugs.clusterlabs.org/show_bug.cgi?id=5424
Best Regards,
> High : cotrold: Notify tengine of completion of CRM_OP_LRM_DELETE.(Fix:CLBZ:#5424)

- daemons/controld/controld_execd_state.c
This fixes a regression introduced in 1.1.19 / 2.0.0
Ironically the original change was intended to make crm_node -n work reliably
on Pacemaker Remote nodes (even when the node name in the cluster differed from
the local hostname). However, the remote request might not be detected
appropriately depending on what the value of an uninitialized variable happened
to be.
The fix is to initialize the variable.
> Fix: controller: properly detect remote node info requests

- daemons/fenced/fenced_commands.c
- daemons/fenced/fenced_remote.c
- include/crm/fencing/internal.h
Hi All,
This is a revised version of the next modified PR.
The log output has been changed in more detail than PR1967.
#1967
#1951
Delete the DC node RELAY operation and remove the duplicate fencing remote-op.
Best Regards,
> Low: fenced: Remove relayed stonith operation.(Fix:CLBZ#5401)

- rpm/pacemaker.spec.in
71a283bf was incomplete; the source tarball name differs based on whether it is a tagged release or not
Also refactor and re-comment to try to make things clearer, and update github source URL.
> Build: rpm: define source name correctly in spec file

- daemons/fenced/fenced_commands.c
- daemons/fenced/pacemaker-fenced.h
- doc/Pacemaker_Explained/en-US/Ch-Fencing.txt
- include/crm/fencing/internal.h
- lib/fencing/st_client.c
- lib/fencing/st_rhcs.c
This addresses the issue brought up from: https://github.com/ClusterLabs/pacemaker/pull/2036#issuecomment-621529506
According to:
https://github.com/ClusterLabs/fence-agents/commit/de490e059
, `port` parameter is massively deprecated in favor of `plug`:
```
<parameter name="plug" ... obsoletes="port">...
<parameter name="port" ... deprecated="1">...
```
With this commit, according to the metadata, if `port` parameter is not
supported, `plug` parameter is added if supported. By default, `port`
is added.
> Fix: fencer,libstonithd: add `port` or `plug` parameter according to metadata for RHCS-style fence-agents

- lib/fencing/st_rhcs.c
Although for now by default, `port` is still added in make_args() for
backward compatibility. This will be really respected in the future
possibly since 2.1.0.
> Fix: libstonithd: respect `pcmk_host_argument=none` on `validate`

- doc/Pacemaker_Explained/en-US/Ch-Stonith.txt
- fencing/commands.c
- fencing/internal.h
- include/crm/fencing/internal.h
- lib/fencing/st_client.c
- lib/fencing/st_rhcs.c
Backports of https://github.com/ClusterLabs/pacemaker/pull/2059 and https://github.com/ClusterLabs/pacemaker/pull/2066 for 1.1 branch.
This addresses the issue brought up from: https://github.com/ClusterLabs/pacemaker/pull/2036#issuecomment-621529506
According to:
https://github.com/ClusterLabs/fence-agents/commit/de490e059
, `port` parameter is massively deprecated in favor of `plug`:
```
<parameter name="plug" ... obsoletes="port">...
<parameter name="port" ... deprecated="1">...
```
With this commit, according to the metadata, if `port` parameter is not
supported, `plug` parameter is added if supported. By default, `port`
is added.
> [1.1] Fix: fencer,libstonithd: add `port` or `plug` parameter according to metadata for RHCS-style fence-agents

- fencing/commands.c
- lib/fencing/st_client.c
Backport of https://github.com/ClusterLabs/pacemaker/pull/2070 for 1.1 branch.
> [1.1] Fix: fencer: avoid possible use-of-NULL when parsing metadata

- include/crm/pengine/internal.h
- lib/pengine/bundle.c
- lib/pengine/clone.c
- lib/pengine/group.c
- lib/pengine/utils.c
- tools/crm_mon.c
- tools/crm_mon_print.c
These patches aim to fix a couple problems in 2.0.4-rc1 with crm_mon's output. In particular, inactive resources do not get printed by default XML output, and inactive resources do not get printed anywhere (even with -r) due to the --node= option.
> Fixes for crm_mon output bugs

- rpm/pacemaker.spec.in
548b16b1 still wasn't complete; the update to the github URL confused rpmbuild,
which assumes the Source0 base name is the name of the tar archive. This sets
the correct base name.
Separately, ut turns out the Source0 URL has always been broken for tagged
releases. Github names official release downloads like Pacemaker-X.Y.Z.tar.gz,
and tag downloads like pacemaker-Pacemaker-X.Y.Z.tar.gz, neither of which will
work with rpmbuild, which expects pacemaker-X.Y.Z.tar.gz (which is correct for
"make rpm" builds, which are based on "make dist"/"make export"). If we changed
our release tags to start with a lowercase letter, we could configure the URL
appropriately, but that's not likely worth the effort (and inconsistency).
> Build: rpm: ensure rpmbuild knows correct tarball name

- daemons/fenced/fenced_remote.c
The issue can only occur when a node has a fencing topology with a single level containing a single device, unfencing is requested for the node, and the topology is removed from the configuration before the unfencing result arrives.
> Avoid potential infinite loop in fencer

- cts/cli/regression.crm_mon.exp
- lib/pengine/bundle.c
This regression was introduced by 037c8ece42dabc55f9ce19dc4b4c807ff70a7c9b.
> Fix: scheduler: Add the node name back to bundle instances.

- lib/pacemaker/pcmk_sched_constraints.c
This is only tripping up F32 s390x builds, but I don't suppose there's
any reason it couldn't come up elsewhere later.
> Fix: libpacemaker: Don't allow a potential NULL in a format string.

- include/crm/common/output.h
- include/crm/fencing/internal.h
- lib/fencing/st_client.c
- lib/fencing/st_output.c
- lib/pengine/bundle.c
- lib/pengine/clone.c
- lib/pengine/group.c
- lib/pengine/native.c
- lib/pengine/pe_output.c
- tools/crm_mon_curses.c
- tools/crm_mon_print.c
As I've been working on adding the --resource= option to crm_mon, I've noticed a lot of boilerplate code around formatted output.  This is the first set of patches to try to reduce that.  I imagine a fair bit more could be done.  I'll continue looking into it and will probably have more to add to this PR.
> Formatted output refactoring

- daemons/controld/controld_messages.c
- daemons/pacemakerd/Makefile.am
- daemons/pacemakerd/pacemakerd.c
- daemons/pacemakerd/pacemakerd.h
- daemons/pacemakerd/pcmkd_corosync.c
- include/crm/common/ipc_controld.h
- include/crm/common/util.h
- include/crm_internal.h
- lib/common/ipc_controld.c
- lib/common/strings.c
- lib/pengine/utils.c
- tools/crm_node.c
This builds on the recently introduced universal daemon IPC model to move crm_node's -l/-p functionality from pacemakerd to pacemaker-controld, which allows it to work on Pacemaker Remote nodes (which proxy controller connections but not pacemakerd connections). It also contains some ancillary improvements in pacemakerd.
> Allow crm_node -l/-p to be used from Pacemaker Remote nodes

- daemons/controld/controld_te_callbacks.c
`action_timer_callback()` prints a misleading error message. If it
times out waiting for an action result, the error message prints the
timeout value followed by `"(action timeout plus cluster-delay)"`.
However, only the `action->timeout` value is displayed. `cluster-delay`
is not added in.
Resolves: RHBZ#1856035
> Log: controld: Show action timer plus cluster-delay in action_timer cb

- daemons/controld/controld_te_utils.c
- lib/cluster/corosync.c
- lib/common/operations.c
- lib/lrmd/lrmd_client.c
- lib/pengine/utils.c
- tools/crm_mon.c
Remove superfluous breaks, as there is a "return" before them.
Signed-off-by: Liao Pingfang <liao.pingfang@zte.com.cn>
> Fix: Remove superfluous breaks

- lib/cib/cib_utils.c
- tools/cibadmin.c
`acls` and `configuration` are also valid values for the `--scope`
option.
> Doc: tools: Add valid scope values for cibadmin --help

- include/pacemaker.h
Building libpacemaker is currently disabled unless the right
preprocessor define is given.  We're never doing that, so over time the
code's going to rot a little bit.  This patch just makes sure it can
still be built successfully.
> Fix: libpacemaker:  Get libpacemaker building again.

- daemons/execd/execd_commands.c
- daemons/execd/remoted_proxy.c
- include/crm/common/ipc_internal.h
This bug has existed since Pacemaker Remote was first implemented, but was hidden until crm_node -l/-p was recently modified to go through controller IPC, because other command-line IPC API clients either fire-and-forget IPC requests or merely count replies, rather than parse the content of replies.
Previously, when the executor sent notifications of results, it broadcast the notification to all IPC clients. Normally this behavior makes sense, but for the executor in particular, it may be running as pacemaker-remoted, in which case its IPC clients include not only clients that connected to the executor IPC, but clients that connected via proxy to other IPC APIs on the cluster node hosting the remote connection.
With crm_node -l/-p, this meant that it was possible for an executor API …
> Fix: executor: only send executor notifications to executor clients

- daemons/pacemakerd/pacemakerd.c
- include/crm/common/Makefile.am
- include/crm/common/ipc_pacemakerd.h
- include/crm/common/options_internal.h
- include/crm/crm.h
- include/crm/msg_xml.h
- lib/common/Makefile.am
- lib/common/crmcommon_private.h
- lib/common/ipc_client.c
- lib/common/ipc_pacemakerd.c
- lib/common/watchdog.c
- tools/crmadmin.c
This rebases #1957 
to current master & refactors it to use the generic ipc-client-api.
And it needs https://github.com/ClusterLabs/sbd/pull/113
or otherwise will wait - when sbd is enabled - till eternity
to be pinged.
Make pacemakerd wait to be pinged by sbd before starting
sub-daemons. Pings further reply health-state and timestamp
of last successful check. On shutdown bring down all the
sub-daemons and wait to be polled for state by sbd before
finally exiting pacemakerd.
Add new api as not to make the xml-structure an external interface.
Added SBD_SYNC_RESOURCE_STARTUP defaulting to 'no' to
sbd config so that upgrading pacemaker without sbd doesn't lead
to pacemaker locked waiting to be pinged by sbd.
> Fix: sbd-integration: sync pacemakerd with sbd

- lib/pengine/utils.c
Minor memleak in pe_get_configured_timeout.
> Fix: libpe_status: Destroy hash table after use

- daemons/controld/controld_execd.c
This patch makes the message indicating a request to execute RA clearer to the user. (see https://github.com/ClusterLabs/pacemaker/pull/2115 for the process of making the change.)
```
(in syslog)
Jul 22 16:17:43 r81-1 pacemaker-controld[2520]:
notice: Requesting local execution of start operation for pgsql on r81-1
(in pacemaker.log)
Jul 22 16:17:43 r81-1 pacemaker-controld  [2520] (do_lrm_rsc_op)
notice: Requesting local execution of start operation for pgsql on r81-1 | transition_key=14:2:0:46e432eb-62f3-45d2-9cea-ffd972daae2f op_key=pgsql_start_0
```
> Log: controld: improve message indicating the RA execution request
