ClusterLabs/pacemaker

doc/Pacemaker_Explained/en-US/Ch-Multi-site-Clusters.txt, doc/Pacemaker_Explained/en-US/Ch-Utilization.txt
=> doc: minor corrections to Pacemaker Explained

tools/crm_resource.c
This minor preparation for adding a --wait option fixes some typos and a memory leak in code relevant to how --wait will be implemented.
=> Minor fixes to crm_resource

doc/Pacemaker_Explained/en-US/Ch-Multi-site-Clusters.txt
Thanks to Dejan Muhamedagic for review.
=> doc: minor clarifications of multisite clusters in Pacemaker Explained

attrd/commands.c, attrd/internal.h, attrd/main.c, tools/attrd_updater.c
Request has been amended to put all new logic in attrd and attrd_updater and not touch lib/common.
Ran CTS with 25 random tests, no errors. Tested attrd_updater queries and updates for private and public attributes.
=> Feature: attrd and attrd_updater support queries

tools/crm_resource.c
main() required a bit of refactoring because it was previously guarding some blocks of code by checking rsc_cmd, but for --wait there is not a unique rsc_cmd (it has no short option equivalent). So now there are booleans that guard those blocks, and each command can enable/disable the blocks it needs (the defaults cover most commands).
I ran CTS (quite a few tests use crm_resource one way or another) for 100 random tests; only 2 failed (ComponentFail corosync, stale IPC files on one node after SimulStop), and those appeared unrelated to any changes here. I tested crm_resource --wait and crm_resource --restart with a Dummy resource with varying operation delays and using various --timeouts.
=> Implement crm_resource --wait

include/crm/pengine/common.h, lib/pengine/clone.c, tools/crm_mon.c
Slight refactoring to make plain, XML and HTML outputs behave more consistently
=> Improvements to crm_mon output

crmd/lrm.c, tools/crm_resource.c
fixes crm_resource -C and crm_resource -C -N <remote node>
=> crm_resource -C fixes for remote nodes.

pacemaker.spec.in
https://bugzilla.redhat.com/show_bug.cgi?id=1200785
=> Low: spec: move report.common and report.collector to cli package

lib/common/mainloop.c
libqb requires mainloop to be able to add, remove, and the add back the same fd. This is required for libqb to be able to perform async connection authentication. Without this functionality, libqb will block during the authentication process which is won't work for us. Our implementation of mainloop has a race condition that makes this libqb functionality of poll (add, rm, add) not work properly.
Example.
- add fd - is_used = TRUE
- remove fd  - remove source from mainloop. is_used = FALSE
- add fd - is_used = TRUE
- destroy callback from previous remove sets is_used =FALSE even though the fd is actually still active.
This causes some really interesting crashes when file descriptors look like they get removed from mainloop when in fact mainloop is still monitoring them. It's possible that …
=> Fix: mainloop: resolves race condition mainloop poll

extra/resources/Makefile.am, lib/pengine/complex.c, lib/pengine/rules.c, lrmd/lrmd.c, lrmd/lrmd_private.h, pacemaker.spec.in, pengine/graph.c, pengine/native.c, pengine/test10/isolation-clone.xml, pengine/test10/isolation-restart-all.xml, pengine/test10/isolation-start-all.xml
this appears to work fine. thanks for the idea @kgaillot
=> High: lrmd: move isolation wrappers to hidden directory

xml/Makefile.am, xml/crm_mon.rng
This schema is accurate as of 1.1.13rc2. I did not check for backwards compatibility with output from older crm_mon; I expect it's compatible with 1.1.12 output but not earlier.
=> crm_mon XML schema

lib/common/xml.c
Maybe I'm paranoid. Better safe than sorry.
=> Fix: xml: Prevent potential use-of-NULL

crmd/lrm.c, crmd/remote_lrmd_ra.c, crmd/te_actions.c, extra/resources/remote, include/crm/msg_xml.h, include/crm/pengine/status.h, lib/pengine/complex.c, lib/pengine/unpack.c, lib/pengine/utils.c, pengine/test10/remote-fence-unclean.exp, pengine/test10/remote-unclean2.exp
I'm posting this for discussion. It is not ready to be merged yet.
=> Failure reconnect delay feature

crmd/callbacks.c, cts/CM_lha.py, cts/CTSaudits.py, cts/CTStests.py, cts/patterns.py, include/crm/pengine/internal.h, include/crm/pengine/status.h, include/crm/stonith-ng.h, lib/cluster/cluster.c, lib/pengine/native.c, lib/pengine/unpack.c, mcp/pacemaker.c, pengine/allocate.c, pengine/native.c, pengine/utils.c
This small request updates some obsolete comments and misspellings.
=> Clean up comments and misspellings

cts/environment.py
test: cts: change the stack from openais (white-tank) to corosync (plugin v0) in set_stack of environment.py
=> change stack name

fencing/internal.h, fencing/remote.c
This is the first bit of plumbing for being able to remap sequential topology reboots to all-off-then-all-on. It introduces the concept of fencing operaton "phases", where most (i.e. non-remapped) operations will have a single phase (0), but remapped reboots will go from phase 0 (reboot request) to 1 (remap to off) to 2 (remap to on).
The various action-specific properties (required status, timeout, etc.) need to be tracked separately by phase, so these revisions modify the structure members for those from scalar to array[3].
No remapping is done yet, so phase is always 0, and actual cluster behavior is unchanged.
=> Add support for fencing "phases"

doc/asciidoc.reference
Heureka, I now understand the purpose of the file :)
For posterity, reference to previous exchange with Ken:
https://github.com/jnpkrn/pacemaker/commit/6d38cfc49e810149135103e72fd448c267b747fc
=> Asciidoc.reference

doc/shared/en-US/pacemaker-intro.txt
This should be merged after pull request #733 for better logical continuity.
Some previous discussion (that disappeared due to slight rework of the first patch in row): https://github.com/jnpkrn/pacemaker/commit/30a545d62907d82a19d123e8f85235e9ff17c2c5
=> Pcmk intro

pacemaker.spec.in, version.m4
=> Build: Update version numbers to 1.1.13 in version.m4 and sample spec file

cib/io.c, crmd/crmd_lrm.h, crmd/lrm.c, crmd/lrm_state.c, cts/CM_ais.py, cts/environment.py, cts/patterns.py, lib/services/dbus.c, lib/services/services.c, lib/services/services_private.h, lib/services/systemd.c
The first three commits here just fix some pain points when running under valgrind. The second three fix some minor memory leaks in crmd and libservices.
=> Fix small memory leaks

cts/README, cts/cluster_test
=> Cluster test+readme

README.markdown, crmd/lrm_state.c, cts/CIB.py, cts/CTStests.py, cts/README, lib/common/remote.c
The most important commit here is a fix for a regression in remote node proxying. Most of the rest are fixes for CTS's testing of remote nodes.
=> Fixes related to pacemaker_remote

extra/PCMK-MIB.txt, extra/pcmk_snmp_helper.sh
Also removed example with cloned resource because there is no need to run mon on all cluster nodes.
Signed-off-by: Kristián Feldsam <feldsam@gmail.com>
=> Added snmp trap of type "NOTIFICATION-TYPE" to MIB and snmp helper script

cts/cts, extra/cluster-helper, extra/cluster-init
Brushing up `cts` script (and related files: `cluster-helper`, ...).
=> Cts script

ChangeLog, cts/CTSscenarios.py, include/crm/common/xml.h
Can rest unmerged for a long time to serve for accumulation over time...
=> fix various typos

cts/CIB.py, cts/CTStests.py, cts/environment.py, cts/remote.py
This adds --notification-agent and --notification-recipient options to CTSlab.py, and fixes a few other CTS issues.
=> Add notification options to CTS

extra/resources/controld, lib/lrmd/lrmd_client.c
Issue and solution reported on users@clusterlabs.org mailing list
by dan.oscarsson@intraphone.com, Ulrich.Windl@rz.uni-regensburg.de
and bubble@hoster-ok.com.
=> Fix: controld: replace bashism

crmd/messages.c, crmd/tengine.c, fencing/commands.c, include/crm/common/logging.h, include/crm/common/xml.h, lib/cib/cib_file.c, lib/cib/cib_remote.c, lib/common/ipc.c, lib/common/xml.c, lib/pengine/common.c, lib/services/dbus.c, tools/crm_resource_runtime.c
Most of these are insignificant or false positives, but they do tighten up some edge cases.
=> Fix various issues discovered by coverity

lib/ais/plugin.c, mcp/pacemaker.c
=> Fix typo: Shuting -> Shutting

include/crm/cib/internal.h, lib/cib/cib_attrs.c, tools/crm_attribute.c
This is WIP, not to be merged yet.
=> crm_attribute: allow showing all node attributes

crmd/lrm.c
Prevously, "!= pcmk_ok" was used as the failure condition, but asynchronous CIB
calls return a positive call id on success, so use "< 0" instead. Also, use
crm_perror() so we log the underlying reason for the failure, and log it at
warning level rather than debug, because it can potentially cause problems
later.
This avoids spurious log messages and makes real ones more meaningful.
=> Fix: crmd: properly detect CIB update failures for remote nodes

tools/crm_resource_runtime.c
Use the same logics as "--set-parameter" for "--delete-parameter".
=> Fix: crm_resource: Correctly delete existing meta attributes regardless of their position in the heirarchy

cts/CTS.py, cts/CTSaudits.py, cts/CTSscenarios.py, cts/CTStests.py, cts/environment.py
CTS: add "try except" to deal with errors that raw_input gets EOFError and add "--yes" to skip interaction
=> CTS: add "try except" to deal with errors that raw_input gets EOFError

tools/crm_mon.sysconfig
The user should make PID file in the directory which is removed when a
node started.
Otherwise the PID file which is not removed does mischief.
=> Low : Change of the mention example.

ChangeLog, GNUmakefile, crmd/control.c, doc/Pacemaker_Explained/en-US/Book_Info.xml, doc/Pacemaker_Explained/en-US/Ch-Advanced-Resources.txt, doc/Pacemaker_Explained/en-US/Ch-Stonith.txt, doc/Pacemaker_Explained/en-US/Revision_History.xml, doc/Pacemaker_Remote/en-US/Book_Info.xml, doc/Pacemaker_Remote/en-US/Ch-Intro.txt, doc/Pacemaker_Remote/en-US/Ch-Options.txt, doc/Pacemaker_Remote/en-US/Revision_History.xml, lib/cib/Makefile.am, lib/fencing/Makefile.am, lib/pengine/Makefile.am, lib/services/Makefile.am, pacemaker.spec.in, pengine/Makefile.am, version.m4
This updates documentation and version information for the 1.1.14-rc1 release. It also disables the new notification-script/notification-agent configuration options, and fixes a minor makefile issue.
=> Release 1.1.14-rc1

extra/PCMK-MIB.txt, fencing/commands.c, fencing/regression.py.in, lib/fencing/st_client.c
=> Fencing and SNMP fixes

fencing/commands.c, fencing/internal.h, fencing/main.c, include/crm/fencing/internal.h, include/crm/pengine/status.h, lib/pengine/common.c, lib/pengine/unpack.c, pengine/allocate.c, pengine/regression.sh, pengine/test10/concurrent-fencing.dot, pengine/test10/concurrent-fencing.exp, pengine/test10/concurrent-fencing.scores, pengine/test10/concurrent-fencing.summary, pengine/test10/concurrent-fencing.xml
Not ready for merging yet. I'm pushing it for discussion.
A pengine property "concurrent-fencing" can be configured to allow
performing fencing operations in parallel. It defaults to "false".
Or, would you prefer the name "concurrent-stonith"?
=> Feature: Support concurrent fencing

doc/Pacemaker_Explained/en-US/Ch-Resources.txt
=> Doc: PE: be more explicit wrt. interval+enabled op properties

README.markdown, crmd/messages.c, cts/CTStests.py, cts/README.md, cts/lxc_autogen.sh.in
Fix a bug in remote node state tracking, and update LXC remote node tests in CTS
=> Remote node fixes

lrmd/tls_backend.c
=> Refactor: remote: Simplfy calls to accept() and inet_ntop() by using "struct sockaddr_storage"

lib/services/services_linux.c
The following patches aim to add error handling for pipe problems.
=> Fix: libservices: Add error handling for pipe problems.

crmd/te_callbacks.c, include/crm_internal.h, lib/common/watchdog.c, pengine/native.c
Fix spelling in log messages, and refactor some things to make coverity happy
=> Minor updates

lrmd/pacemaker_remote.in, mcp/pacemaker.sysconfig
=> Auto-export the init script variables read from the config file

xml/Makefile.am
Follow-up of PR #910 (+ #912).  Partly inspired with PR #935.
=> Build: xml: track new file context-of.xsl as noinst_DATA

doc/Pacemaker_Explained/en-US/Ch-Resources.txt, extra/resources/ClusterMon, extra/resources/Dummy, extra/resources/HealthCPU, extra/resources/HealthSMART, extra/resources/Stateful, extra/resources/SysInfo, extra/resources/ping, extra/resources/pingd
Minor fixes to ocf:pacemaker resource agents
=> Resource agent cleanup

doc/Pacemaker_Explained/en-US/Ch-Basics.txt
=> Replace the deprecated obj_type option in the examples

doc/Pacemaker_Explained/en-US/Ch-Options.txt
=> doc: describe recovery behavior of stonith-enabled=false

extra/resources/SysInfo, extra/resources/ifspeed, extra/resources/ping
Hi All,
A change of dampen was supported by attrd.
Please revise RA in conjunction with the change.
* https://github.com/ClusterLabs/pacemaker/commit/da9af2d2958c3b501777e45c42d2b605d162a6ca
Best Regards,
Hideo Yamauch.
=> Mid: extra: Support of the dampen change by RA.

tools/crm_report.in, tools/report.collector, tools/report.common.in
This is a significant overhaul of crm_report, partly for performance improvements and general cleanup, but primarily to better support Pacemaker Remote nodes.
This addresses the most significant concerns in RHBZ#1323544.
=> Enhance crm_report

GNUmakefile, pacemaker.spec.in
This is time around against a correct upstream branch as requested:
http://oss.clusterlabs.org/pipermail/developers/2016-April/000202.html
=> Build: spec: pre-releases support

pacemaker.spec.in
See also builds:
https://copr.fedorainfracloud.org/coprs/jpokorny/pacemaker-testing/build/292191/
=> Build: spec changes for RHEL6

extra/alerts/pcmk_snmp_helper.sh
Hi All,
I send the script for the SNMP trap
I branch off the transmission in a parameter.
We want to put this script as the script which is available to users immediately.
We want to include this script in Pacemaker1.1.15 with order of traps control.
This patch reconstituted next pullrequest.
- https://github.com/ClusterLabs/pacemaker/pull/1006
- https://github.com/ClusterLabs/pacemaker/pull/1009
Best Regards,
=> Mid: extra: Change pcmk_snmp_helper.sh (2).

configure.ac, lrmd/pacemaker_remote.service.in, mcp/pacemaker.service.in
Added "--with-configdir" argument that defaults to /etc/sysconfig for Pacemaker config directory.
=> Fix Pacemaker config directory.

extra/alerts/pcmk_snmp_helper.sh
=> fix: alert-helpers: fixed if statement

crmd/lrm.c, include/crm/crm.h
- Modified so that it is understood that the operation of the probe
- Return the return code to the system log
This request is a re-request for #1053.
=> Improvement of the log

lib/cib/cib_client.c
Hi All,
After a cluster started, in the node that released the roll of the DC node, all of notices of CIB stops.
(A notice to do_cib_updated() stops.)
```
(snip)
void
do_te_control(long long action,
enum crmd_fsa_cause cause,
enum crmd_fsa_state cur_state,
enum crmd_fsa_input current_input, fsa_data_t * msg_data)
{
gboolean init_ok = TRUE;
if (action & A_TE_STOP) {
if (transition_graph) {
destroy_graph(transition_graph);
transition_graph = NULL;
}
if (fsa_cib_conn) {
fsa_cib_conn->cmds->del_notify_callback(fsa_cib_conn, T_CIB_DIFF_NOTIFY,
te_update_diff);
}
(snip)
void
do_cib_control(long long action,
enum crmd_fsa_cause cause,
enum crmd_fsa_state cur_state,
enum crmd_fsa_input current_input, fsa_data_t * msg_data)
{
(snip)
} else if (pcmk_ok != …
```
=> High: lib: Correction of the deletion of the notice registration.

lrmd/pacemaker_remote.in, mcp/pacemaker.in
This needs 
https://github.com/ClusterLabs/sbd/pull/12
=> make Lsb init scripts start/stop sbd

tools/crm_mon.c
Always prints a header in HTML and console output, and
indicates if there are no resources of the requested type to show.
=> Low: tools: make crm_mon resources section more consistent

fencing/fence_dummy
This also cleans up the code a good bit
=> Make fence_dummy python 3 compatible

lib/common/schemas.c, tools/regression.sh, tools/regression.validity.exp
WIP - missing tests and possibly other corner cases I'll hit
=> XML validation infloop followup

.gitignore, cib/remote.c, crmd/main.c, fencing/admin.c, fencing/config.y, fencing/test.c, include/crm/common/xml.h, lib/cib/cib_attrs.c, lib/cib/cib_ops.c, lib/cib/cib_remote.c, lib/cluster/corosync.c, lib/cluster/cpg.c, lib/common/remote.c, lib/common/schemas.c, lib/common/watchdog.c, lib/services/upstart.c, lrmd/remote_ctl.c, lrmd/test.c, pengine/constraints.c, pengine/native.c, tools/Makefile.am, tools/crm_mon.c, tools/crm_node.c, tools/fake_transition.c, tools/ipmiservicelogd.c
In part, a follow-up of #1120.
=> Minor fixes

lib/services/Makefile.am, lib/services/dbus.c, lib/services/pcmk-dbus.h, lib/services/systemd.c, lib/services/upstart.c
Most significantly, this handles DBus errors better. It's also intended to make future work on the systemd code easier.
=> Systemd code cleanup

Makefile.am, lrmd/Makefile.am, pengine/Makefile.am
One might want to `--disable-cts` if (s)he doesn't want to install it or simply hasn't got Python around.
=> Build enhancements

lib/common/ipc.c
It was discovered that at some not so uncommon circumstances, some
pacemaker daemons could be talked to, via libqb-facilitated IPC, by
unprivileged clients due to flawed authorization decision.  Depending
on the capabilities of affected daemons, this might equip unauthorized
user with local privilege escalation or up to cluster-wide remote
execution of possibly arbitrary commands when such user happens to
reside at standard or remote/guest cluster node, respectively.
The original vulnerability was introduced in an attempt to allow
unprivileged IPC clients to clean up the file system materialized
leftovers in case the server (otherwise responsible for the lifecycle
of these files) crashes.  While the intended part of such behavior is
now effectively voided (along with the unintended one), …
=> High: libcrmcommon: fix CVE-2016-7035 (improper IPC guarding)

tools/crm_report.in
...so advertise the replacement instead.
=> Low: crm_report: linux-foundation.org bug tracker deprecated

tools/regression.sh, tools/regression.validity.exp, xml/resources-2.7.rng
Based on Ken's heads up that also regression tests were not happy.
Could be split into this composition:
- update sed filter in tools/regression.sh + update expected results
prior to pacemaker-2.7 schema
- add resources-2.7.rng
- update expected results once more
if it's deemed worth it.
=> PR #1178 + addendum (regression tests update)

pacemaker.spec.in, pengine/regression.core.sh.in
Also add a note about -cts possibly being noarch if one file moved over.
=> Build: spec: pre-/post-release logic fix, enabling tests in %check of spec, and another small changes

attrd/legacy.c, crmd/attrd.c, cts/CTStests.py, lrmd/regression.py.in
This is mostly preparation for future failure handling changes
=> Legacy attrd improvements, plus a few minor fixes

attrd/legacy.c, crmd/attrd.c, lib/cib/cib_attrs.c, tools/crm_attribute.c, tools/crm_resource_runtime.c
=> Support remote nodes and regular expressions in legacy attrd

cib/cibio.h, cib/main.c, doc/Pacemaker_Explained/en-US/Ch-Advanced-Options.txt, lib/cib/cib_attrs.c
=> Avoid memory leak

crmd/remote_lrmd_ra.c, fencing/main.c, include/crm/services.h, lib/common/utils.c, lib/lrmd/lrmd_client.c, lib/pengine/complex.c, lib/pengine/native.c, lib/pengine/remote.c, lib/pengine/unpack.c, lib/services/services.c, lib/services/services_linux.c, lib/services/services_private.h, lrmd/lrmd.c, pengine/native.c, tools/crm_resource_print.c, tools/crm_resource_runtime.c, tools/fake_transition.c
=> Avoid memory issues in libservices

fencing/commands.c, lib/fencing/st_client.c
"action" should never be specified in fence device configuration.
Previously, this was handled by re-inserting the proper action when creating a
fence command, if the proper action were on a "safe" list (list, monitor,
status, or meta-data).
However, that was insufficient, partly because "on" should have been on the
list, but also because action="reboot" would interfere with reboots that were
remapped to off or off+on.
Now, stonithd intelligently maps any action parameter to pcmk_off_action and/or
pcmk_reboot_action as appropriate when the device configuration is registered,
and libfencing ignores any action parameter that makes it that far.
=> Fix: libfencing,fencing: properly remap "action" in configuration

ChangeLog, cib/callbacks.c, crmd/control.c, crmd/fsa_defines.h, cts/CM_lha.py, doc/Pacemaker_Explained/en-US/Ch-Advanced-Resources.txt, fencing/commands.c, fencing/main.c, include/crm/cluster/internal.h, include/crm/common/xml.h, include/crm/crm.h, include/crm/lrmd.h, include/crm/msg_xml.h, lib/ais/plugin.c, lib/cluster/heartbeat.c, lib/common/strings.c, lib/pengine/complex.c, lib/pengine/container.c, lib/pengine/unpack.c, lib/pengine/utils.c, pacemaker.spec.in, pengine/allocate.c, pengine/container.c, pengine/graph.c, pengine/native.c, pengine/test10/remote-orphaned.scores, pengine/test10/whitebox-orphaned.scores, pengine/utilization.c
plus a few unrelated minor fixes
=> Pull 1.1.17-rc2 back into master

attrd/commands.c, crmd/join_client.c, crmd/join_dc.c, crmd/membership.c, crmd/te_events.c, doc/Pacemaker_Explained/en-US/Ch-Alerts.txt, doc/Pacemaker_Remote/en-US/Ch-Alternatives.txt, doc/Pacemaker_Remote/en-US/Ch-Intro.txt, include/crm/common/xml.h, lib/common/xml.c, lib/common/xpath.c, lib/lrmd/lrmd_client.c, lib/pengine/remote.c, pengine/container.c, pengine/graph.c
This also includes Andrew Beekhof's ff426526 from the master branch, and a few minor documentation updates.
=> Scalability fix

tools/crm_resource.c, tools/crm_resource.h, tools/crm_resource_runtime.c
WIP and Yet to test.
Wanted to know if this is the correct approach.
1.Added a new option "Why" with an alias of 'Y'
2.Checking if rsc_cmd == 'Y'
2.1 Checking if rsc id is present
2.2 If so find the resource and do a cli_resource_check
Should I change the cli_resource_check for all the resources if no rsc id mentioned.? 
If so should I be doing it by iterating data_set.resources ?
=> Tools: Added option of --why/Y to crm_resource. 

pengine/clone.c, pengine/container.c, pengine/graph.c, pengine/test10/base-score.scores, pengine/utils.c, pengine/utils.h
Imported as patches from beekhof/pacemaker master branch (based on ClusterLabs/pacemaker master branch)
=> Bundle constraint support

cib/io.c, include/crm/common/internal.h, lib/cib/cib_file.c, lib/common/schemas.c, lib/common/strings.c, lib/common/xml.c, tools/crm_mon.c, tools/crm_resource_runtime.c, tools/crm_simulate.c
Replacement for PR #1299.
For the possible integration with httpd, see commit message of the 5th commit.
=> Restore and tweak the usage of crm_mon as CGI script + crm_ends_with special case optimization

crmd/cib.c, crmd/pengine.c, crmd/subsystems.c, crmd/tengine.c
Piggyback a comment reformat within.
* * *
```
4 files changed, 28 insertions(+), 92 deletions(-)
```
Oh, well...
=> Cleanup: crmd: drop superfluous includes

.gitignore, Makefile.am, lib/services/Makefile.am, xml/Makefile.am
Reproduce with:
mkdir build; cd build; ../configure; make
=> Pristine source support where top_builddir != top_srcdir, add a few missing git ignores

pengine/master.c, pengine/regression.core.sh.in, tools/regression.sh, tools/report.collector
with a couple of minor other fixes
=> Restore crm_report --sos-mode functionality

extra/resources/ifspeed
Added support of Intel Omni Path nics.
=> Fix: a proper calculation of a speed in case of hfi1 for ifspeed RA.

lib/pengine/container.c, lib/pengine/variant.h, tools/regression.validity.exp, xml/crm_mon.rng, xml/resources-2.10.rng
Known limitations:
* port names exposed by the container need to be numeric and equal to port number.
=> Add support for rkt bundle type

crmd/crmd_metadata.c, doc/Pacemaker_Explained/en-US/Ch-Advanced-Resources.txt, include/crm/common/util.h, include/crm/common/xml.h, include/crm/pengine/remote.h, include/crm/services.h, lib/cib/cib_attrs.c, lib/common/remote.c, lib/common/xml.c, lib/lrmd/lrmd_client.c, lib/pengine/container.c, lib/pengine/remote.c, lib/pengine/unpack.c, lib/services/services.c, lib/services/systemd.c, lib/services/upstart.c, lrmd/main.c, pengine/allocate.c, tools/crm_resource_runtime.c, tools/crm_ticket.c, tools/fake_transition.c
Reduce code duplication, improve error checking, and improve documentation. The most significant change is that bundles now respect PCMK_remote_port and PCMK_authkey_location if set on the host.
=> Bundle cleanup

include/crm/common/util.h, include/crm/pengine/status.h, lib/common/utils.c, lib/lrmd/lrmd_client.c, lib/pengine/container.c, lib/pengine/native.c, lib/pengine/utils.c, lib/services/services.c, tools/crm_resource.c, tools/crm_resource_runtime.c, tools/fake_transition.c, tools/regression.tools.exp
Closes CLBZ#5251, CLBZ#5287, RHBZ#1489735
=> Improve crm_resource

tools/crm_resource.c, tools/crm_resource.h, tools/crm_resource_runtime.c
Here is the log improvements for crm_resources --force-* options as suggested in https://github.com/ClusterLabs/pacemaker/pull/1358#issuecomment-337696509
=> Log improvements for crm_resource --force-start/stop/check

extra/resources/ifspeed, include/crm/pengine/internal.h, lib/pengine/failcounts.c, lib/pengine/unpack.c, pengine/allocate.c, pengine/container.c, pengine/regression.sh, pengine/test10/on-fail-ignore.dot, pengine/test10/on-fail-ignore.exp, pengine/test10/on-fail-ignore.scores, pengine/test10/on-fail-ignore.summary, pengine/test10/on-fail-ignore.xml, tools/crm_mon.c
This fixes RHBZ#1507344.
This also includes an unrelated commit to restore buildbot's ability to generate man pages without the OCF libraries installed.
=> Ignore migration-threshold if ignoring failures

attrd/commands.c, attrd/internal.h, attrd/main.c, crmd/join_client.c, crmd/join_dc.c, cts/CIB.py, include/crm/crm.h, tools/attrd_updater.c, tools/crm_resource.c
with a couple of unrelated fixes for issues introduced with recent 2.0 branch commits
=> Fix regression in 1.1.18 (CLBZ#5330)

cts/CIB.py, cts/CM_common.py, cts/CM_corosync.py, cts/CTS.py, cts/CTSaudits.py, cts/CTSscenarios.py, cts/CTStests.py, cts/CTSvars.py.in, cts/OCFIPraTest.py, cts/cib_xml.py, cts/environment.py, cts/patterns.py, cts/remote.py, cts/watcher.py
make pacemaker-cts runs on both python2 and python3, I tried on python2.7.13 and python3.6.3
=> low:cts: migrate cts to python3 while compitable with python2

tools/crm_master
Backport fix from master branch
=> Fix: tools: crm_master should always work on node attribute

attrd/commands.c, attrd/internal.h
Hi All,
This PR is a modified version of the content discussed in the next PR.
https://github.com/ClusterLabs/pacemaker/pull/1423
https://github.com/ClusterLabs/pacemaker/pull/1424
Best Regards,
=> Mid: attrd: Synchronize attributes held only on own node.

cts/pengine/versioned-resources.xml
Issue introduced with e55709886.
=> Test: pengine: fix duplicate ID-typed identifiers

.gitignore, GNUmakefile, attrd/commands.c, attrd/internal.h, crmd/corosync.c, crmd/lrm.c, crmd/lrm_state.c, crmd/te_callbacks.c, crmd/te_events.c, crmd/tengine.h, include/crm/lrmd.h, lib/common/logging.c, lib/common/schemas.c, lib/common/watchdog.c, lib/lrmd/lrmd_client.c, lib/pengine/common.c, lib/pengine/unpack.c, lib/pengine/unpack.h, lrmd/lrmd.c, mcp/pacemaker.service.in, pacemaker.spec.in, tools/crm_resource_runtime.c, tools/regression.validity.exp
This includes fixes for CLBZ#5336, CLBZ#5338, and CLBZ#5339, as well as other selected fixes.
=> Backport recent fixes from 2.0 branch

lib/common/schemas.c
Recent upgrade-2.10.xsl extensions discovered a silent precondition
about the CIB XML tree to work with, which is now not met, so it's
enforced again till the long-term solution is delivered.
=> High: schema upgrade: temporary fix to avoid crash on newly present text

extra/alerts/alert_snmp.sh.sample, include/crm/common/alerts_internal.h, lib/common/alerts.c, lib/lrmd/lrmd_alerts.c
Hi All,
This PR was previously discussed at the next PR.
- https://github.com/ClusterLabs/pacemaker/pull/1442
Best Regards,
=> Mid: alerts: Change timestamp of Alert of snmp.

doc/Pacemaker_Explained/en-US/Ch-Constraints.txt, doc/Pacemaker_Explained/en-US/Ch-Stonith.txt
There are many in the wild.  Clarification requested by Tomáš Jelínek.
=> Doc: Pacemaker Explained: care to explain a kind of reg. expressions

cts/cts-regression.in
Fixes the regression introduced by 628590c716
=> Test: cts-regression: allow specifying to run multiple tests again

lib/common/Makefile.am, xml/regression.sh, xml/test-2/020-rsc-requires-inline.ref, xml/test-2/024-rsc-requires-no-selfclash.ref, xml/upgrade-2.10.xsl
Just the "mark space" issue fix.
=> Upgrade xsl 2to3 part3

configure.ac, cts/CTStests.py, cts/cts-cli.in, daemons/execd/execd_commands.c, doc/shared/en-US/pacemaker-intro.txt, lib/lrmd/lrmd_client.c, lib/pengine/unpack.c, lib/services/Makefile.am, lib/services/services.c, lib/services/services_linux.c, lib/services/services_lsb.c, lib/services/services_lsb.h, lib/services/services_private.h, pacemaker.spec.in
=> "service:" handling bug fixes

daemons/attrd/Makefile.am, daemons/based/Makefile.am, daemons/controld/Makefile.am, daemons/execd/Makefile.am, daemons/fenced/Makefile.am, daemons/schedulerd/Makefile.am
Hi All,
This PR is a modified version of the following PR.
- https://github.com/ClusterLabs/pacemaker/pull/1482
Best Regards,
=> Low: daemons: Delete link when re-executing make install.

xml/regression.sh, xml/test-2/020-rsc-requires-inline.ref.err, xml/test-2/021-rsc-requires-nvpair.ref, xml/test-2/021-rsc-requires-nvpair.ref.err, xml/test-2/022-rsc-requires-counterexamples.ref.err, xml/test-2/023-rsc-requires-no-override.ref.err, xml/test-2/024-rsc-requires-no-selfclash.ref, xml/test-2/024-rsc-requires-no-selfclash.ref.err, xml/test-2/060-rsc-attrs-meta-isolation.ref, xml/test-2/060-rsc-attrs-meta-isolation.ref.err, xml/test-2/060-rsc-attrs-meta-isolation.xml, xml/upgrade-2.10.xsl
Sadly, I am currently stuck with a conflict between extraneous empty lines
emitted in the regression test run (without `-B`) but correct `-B` results,
and no new empty lines and broken `-B` result.  Cannot find the right
constellation.  That needs to be closed, then there are two more aspects
of the upgrade yet to be addressed.
=> [WIP][part 4] Prepare XSL template for 2-to-3 schema upgrade

cts/cts.in, cts/scheduler/order-expired-failure.stderr, cts/scheduler/order-expired-failure.summary, cts/scheduler/order-expired-failure.xml, daemons/controld/controld_execd.c, daemons/execd/remoted_tls.c, lib/pengine/status.c
=> Fix memory leak

cts/watcher.py, daemons/based/based_callbacks.c, daemons/execd/remoted_tls.c, daemons/fenced/pacemaker-fenced.c, daemons/schedulerd/sched_native.c, doc/shared/en-US/images/pcmk-internals.svg, lib/common/ipc.c, lib/lrmd/lrmd_client.c, tools/crm_resource_runtime.c
with minor unrelated changes such as log improvements
=> Fix regression in crm_resource --move --master

lib/pengine/container.c, lib/pengine/native.c, pengine/allocate.c, pengine/clone.c, pengine/graph.c, pengine/native.c, pengine/notif.c, tools/crm_mon.c, tools/crm_resource.c, tools/crm_resource_print.c, tools/crm_resource_runtime.c
Backport one more commit from 2.0 branch to complete primitive requires=quorum fix
=> Fix: all: prefer appropriate node when multiply active

configure.ac, daemons/fenced/pacemaker-fenced.c, include/crm/common/cib_secrets.h, include/crm/fencing/internal.h, include/crm/stonith-ng.h, lib/common/cib_secrets.c, lib/fencing/Makefile.am, lib/fencing/st_client.c, lib/fencing/st_lha.c, lib/fencing/st_rhcs.c, tools/stonith_admin.c
The new option should help higher-level tools validate fence device configurations before committing them to the configuration.
This also includes some refactoring in libstonithd.
=> Add stonith_admin --validate option

cts/CM_common.py, cts/CTS.py.in, cts/watcher.py, lib/cluster/membership.c, lib/common/ipc.c, lib/services/systemd.c, tools/stonith_admin.c
with a few unrelated minor fixes
=> Support systemd path, mount, and timer units

cts/CM_lha.py, cts/CTS.py, cts/patterns.py, lib/cluster/membership.c, lib/services/systemd.c
with other minor backported fixes
=> Backport systemd support from 2.0 branch

daemons/schedulerd/sched_allocate.c, daemons/schedulerd/sched_promotable.c, include/crm/pengine/status.h, lib/pengine/utils.c, tools/crm_failcount.in, tools/crm_simulate.c
crm_failcount treates INFINITY as 0 (regression in 1.1.17 via 83236161)
crm_simulate -L doesn't print promotion scores (regression in 1.1.18 via 349a37f5b) (CLBZ#5353)
=> Fix two regressions

daemons/attrd/attrd_commands.c, daemons/controld/controld_execd_state.c, daemons/controld/controld_messages.c, include/crm/common/util.h, include/crm/crm.h, include/crm/msg_xml.h, lib/cluster/cluster.c, lib/common/utils.c, pacemaker.spec.in, tools/Makefile.am, tools/crm_node.c, tools/crmadmin.c
and remove crm_node's dependence on libcrmcluster, allowing it to be moved to -cli package
=> Fix crm_node on remote nodes

lib/common/xml.c
The issue is described in the in-code comment.  Previously, this wasn't
a problem as no result tree fragments got created with upgrade-1.3.xsl.
With upgrade-2.10.xsl, they are used heavily, mostly as oracles whether
the evaluated content will be non-empty and (or in addition) to avoid
redundant evaluations.
=> High: xml.c: fix cleaning of own vs. XSLT's XML node's _private load

lib/common/schemas.c
Memory leak spotted by Ken (thanks); demagicizing numeric constants
is akin to 16eeb6882 landed in the interim (possible annoyance with
repeated strings could be mitigated with suitable macros).
=> XML: schemas.c: fix possible memleak + less magic with numeric constants

daemons/controld/controld_based.c, daemons/controld/controld_execd.c, daemons/controld/controld_te_actions.c, daemons/controld/controld_te_callbacks.c, daemons/controld/controld_transition.h, daemons/controld/controld_utils.h, daemons/execd/cts-exec-helper.c, lib/common/operations.c, lib/pengine/clone.c, lib/pengine/native.c, lib/pengine/variant.h
=> Don't record pending clone notifications in CIB

include/crm/common/alerts_internal.h, lib/common/alerts.c, lib/lrmd/lrmd_alerts.c
Thanks ... creating new pull request in master
=> Present exec_time in event environment

tools/ipmiservicelogd.c
allows ppc64le build when relevant dependencies are installed
=> Doc: tools: add --help/--version options to ipmiservicelogd

daemons/based/based_callbacks.c, daemons/based/based_messages.c, daemons/controld/controld_execd.c, include/crm/cib/internal.h, tools/cibadmin.c, tools/crm_resource_runtime.c
with a couple of minor other commits
=> cibadmin fixes

cts/cts-exec.in, daemons/controld/controld_callbacks.c, daemons/controld/controld_election.c, daemons/controld/controld_join_dc.c, daemons/controld/controld_utils.h
with unrelated minor refactor+log change
=> Restore cts-exec python 3 compatibility

crmd/callbacks.c, crmd/te_utils.c, crmd/tengine.h, fencing/Makefile.am, fencing/admin.c, fencing/commands.c, fencing/history.c, fencing/internal.h, fencing/main.c, fencing/remote.c, include/crm/fencing/internal.h, include/crm/stonith-ng.h, lib/fencing/st_client.c, tools/crm_mon.c, xml/crm_mon.rng
=> Crm mon add fence history 1.1

lib/common/schemas.c
Former should have been in commit e535c3f4d; latter is an attempt to
make static analysis happy (despite that possibility is excluded as
long as the array of schemas in evidence only goes through
add_schema_by_version).
=> XML: schemas.c: ensure proper upgrade-enter fallback & guard strdup arg

tools/crm_mon.c
If cib is read from file fence-history & interactive mode don't
make sense
Instead of switching to one-shot we could fix interactive mode on files in a way that we don't bail out on failure of notifications.
And it might be worth it to add a possibility to cib_file.c that allows us to query if the cib would come from a file and if so if it is still the live cib. So we wouldn't have to check for the environment everywhere cib is used and where it would make a difference if it comes from a file or if it is live.
=> Fix: crm_mon: rhbz#1625231 - disable fence-history in file-mode

tools/crm_mon.c
merge of #1578 was unexpectedly quick
had an amended version of the commit we discussed already in my local repo - just hadn't pushed it as I was waiting for a feedback on the idea ...
This is the diff as a separate commit.
=> Fix: crm_mon: don't exit directly from cib_connect on error

GNUmakefile, lib/common/operations.c, tools/crm_mon.c, tools/crm_node.c
This fixes a regression introduced by bdf69722 that broke reloads (no released version is affected).
Additionally there are unrelated minor commits to help static analysis.
=> Fix regression that broke reloads

.gitignore, doc/Makefile.am, doc/Pacemaker_Explained/en-US/Ch-Constraints.txt, doc/Pacemaker_Explained/en-US/Ch-Stonith.txt, extra/alerts/alert_snmp.sh.sample, fencing/main.c, lib/common/operations.c, pengine/native.c, pengine/regression.sh, pengine/test10/asymmetrical-order-restart.dot, pengine/test10/asymmetrical-order-restart.exp, pengine/test10/asymmetrical-order-restart.scores, pengine/test10/asymmetrical-order-restart.summary, pengine/test10/asymmetrical-order-restart.xml, tools/crm_mon.c, tools/crm_node.c, tools/crm_report.in, tools/report.collector, tools/report.common.in
including an important regression fix
=> Backport fixes from master

cts/cts-exec.in, cts/cts-fencing.in, daemons/fenced/fence_legacy.in, extra/logrotate/pacemaker.in, pacemaker.spec.in, tools/report.collector.in, tools/report.common.in
with a few unrelated minor changes
=> Python 3 compatibility improvements

.gitignore, configure.ac, tools/report.collector.in
Additional backport request for https://github.com/ClusterLabs/pacemaker/pull/1594
=>  Fix: tools: Make crm_report find log file from Pacemaker config

crmd/pengine.c, crmd/te_utils.c, fencing/commands.c, fencing/history.c, fencing/internal.h, fencing/main.c, fencing/remote.c, include/crm/cluster/internal.h, lib/cluster/membership.c
=> Fix: controld: able to manually confirm unseen nodes are down

daemons/attrd/Makefile.am, daemons/attrd/attrd_commands.c, daemons/attrd/attrd_elections.c, daemons/attrd/pacemaker-attrd.c, daemons/attrd/pacemaker-attrd.h, daemons/controld/controld_callbacks.c, daemons/controld/controld_control.c, daemons/controld/controld_election.c, daemons/controld/controld_fsa.c, daemons/controld/controld_fsa.h, daemons/controld/controld_membership.c, daemons/controld/pacemaker-controld.h, include/crm/cluster/election.h, lib/cluster/election.c
This includes mostly documentation, refactoring, and logging changes, but also some minor improvements.
=> Clean up elections code

GNUmakefile, doc/Pacemaker_Explained/en-US/Ch-Advanced-Resources.txt, include/crm/common/util.h, include/crm/common/xml.h, lib/cluster/election.c, lib/common/strings.c, lib/common/xml.c, lib/services/systemd.c
=> Miscellaneous bug fixes

crmd/crmd_lrm.h, crmd/lrm_state.c, crmd/remote_lrmd_ra.c, include/crm/msg_xml.h
=> Prevent sbd check on guests 1.1

cts/README.md, lib/common/logging.c, tools/crm_simulate.c, tools/crm_ticket.c
=> Add compatibility with libqb master branch

cts/CTStests.py
=> Test: cts: simulate failure of pacemaker_remoted by freezing it with SIGSTOP

tools/crm_resource.c, tools/crm_resource.h, tools/crm_resource_ban.c
This is a port of #1633 to the 1.1 branch.  There's only one small change - changing remove to delete in cli_resource_clear_all_expired.
=> Feature: tools: Add crm_resource --expired.

attrd/attrd_elections.c, attrd/commands.c, attrd/internal.h, attrd/main.c, crmd/lrm.c, fencing/commands.c, include/crm/stonith-ng.h, include/crm_internal.h, lib/fencing/st_client.c, lib/pengine/status.c, lib/pengine/unpack.c, lib/pengine/utils.c, pacemaker.spec.in
This includes the most significant bug fixes through 2.0.1-rc3
=> Backports from master branch

doc/Pacemaker_Explained/en-US/Ch-Advanced-Options.txt, doc/Pacemaker_Explained/pot/Ch-Advanced-Options.pot, extra/resources/HealthIOWait, extra/resources/Makefile.am
Hi,
Since we did have a need to check our clusters for high IOWait - I have added such plugin based on HealthCPU and decided to add it to an upstream.
Also I decided to provide updated docs on how to take advantage of this feature.
=> Feature: Added CPU Health provider based on CPU IOWait

cts/CIB.py, cts/CTS.py, cts/environment.py
This commit complements the 9c993a7cca76da81448263fdecd78aad2badd06f but for 1.1 branch. Additionally to the original commit, it modifies the CIB.py.
=> Test: CTS: don't require nodes to be specified if only listing tests

.gitignore, cts/Makefile.am, cts/cli/regression.rules.exp, cts/cts-cli.in, include/crm/common/results.h, include/crm/pengine/rules_internal.h, lib/common/results.c, lib/pengine/rules.c, pacemaker.spec.in, tools/Makefile.am, tools/crm_rule.c
And here's the first draft of this PR.  I have two main concerns/things left to do:
(1) I suppose I should add some regression tests, but I was kind of saving that until after everyone was happy with the format of the command line output.
(2) I don't like mixing the error return code of 1 with the "this rule isn't expired" return code of 1.
=> Add crm_rule

pacemaker.spec.in
Reiteration from #1706, this time against master.
=> Build: spec: move stonith_admin to -cli where it belongs

include/crm/services.h, lib/Makefile.am, lib/fencing/Makefile.am, lib/fencing/st_client.c, lib/services/services_linux.c, lib/services/services_private.h
fortunately these code-parts didn't significantly change with pacemaker-2.x.
So porting the patch from PR#1719 seems to work without issues.
=> use common service interface for fence-agents and RAs

include/crm/common/xml.h, include/crm/stonith-ng.h, lib/common/acl.c, lib/common/nvpair.c, lib/common/schemas.c, lib/common/xml.c, lib/common/xpath.c, lib/fencing/st_client.c, lib/internal/pcmki_sched_constraints.c, tools/crm_mon.c, tools/stonith_admin.c
This PR is stuff that's required before #1707 can be merged but is standalone and potentially more generally useful.
=> Prepare for #1707

lib/common/schemas.c, lib/common/utils.c, lib/common/xml.c, lib/fencing/st_rhcs.c
These were at least partially reviewed already: #1597
The only change is applying `fstatat` where possible in one case.
=> Collection of low prio maint stuff vol. 2

configure.ac, cts/cts-fencing.in, daemons/attrd/attrd_utils.c, daemons/based/pacemaker-based.c, daemons/based/pacemaker-based.h, daemons/controld/controld_fsa.c, daemons/controld/controld_fsa.h, daemons/execd/pacemaker-execd.c, doc/Pacemaker_Administration/en-US/Ch-Configuring.txt, doc/Pacemaker_Administration/en-US/Ch-Upgrading.txt, doc/Pacemaker_Explained/en-US/Ch-Options.txt, doc/Pacemaker_Explained/en-US/Ch-Rules.txt, lib/common/logging.c, lib/common/mainloop.c, tools/crm_report.in
These are a few unrelated minor commits including some documentation enhancements
=> Minor changes

configure.ac, tools/crm_report.in, tools/regression.sh
Also fix a regression test issue resulting from a prior incomplete backport
=> Backport configurable bug report URL from master branch

include/crm/services.h, lib/fencing/st_client.c, lib/services/services.c, lib/services/services_linux.c, lib/services/services_private.h
not ready to be merged yet - just for discussion
avoid use after free detected by coverity
=> avoid call-pattern leading to use-after-free

include/crm/services.h, lib/fencing/st_client.c, lib/services/services.c, lib/services/services_linux.c, lib/services/services_private.h
=> Fix: service-lib: avoid call-pattern leading to use-after-free

.gitignore, .gitlab-ci.yml, .travis.yml, xml/regression.sh, xml/xslt_cibtr-2.rng
Most notably, hopefully definitely resolve the problem with
"network provided resources", allowing for enabling some original
CI tests again.
=> Xml: regression.sh fixups

cts/cts-exec.in, daemons/execd/execd_commands.c
These address some small issues found while investigating CLBZ#5352 (which is not directly addressed here).
=> Improve executor fence device handling

daemons/execd/execd_commands.c
=> Return error instead of "not running" for failed systemd starts

cts/cts-fencing.in, lib/cluster/cpg.c, tools/Makefile.am, tools/cibsecret.in, tools/crm_diff.c, tools/crm_error.c, tools/crm_failcount.in, tools/crm_master.in, tools/crm_report.in, tools/crm_resource_print.c, tools/crm_standby.in, tools/crmadmin.c, tools/ipmiservicelogd.c, tools/notifyServicelogEvent.c, tools/report.collector.in, tools/report.common.in, tools/stonith_admin.c
also, update stonith regression tests for recent stonith_admin output changes, and continue updating copyright notices to new policy, in tools subdirectory
=> Improve CPG membership log messages

lib/fencing/st_output.c
This PR collects some unrelated fixes to the formatted output work.  We could merge it now, or we could wait and see if it collects more fixes.
=> Formatted output fixes

bumplibs.sh, lib/common/Makefile.am, lib/common/utils.c, lib/pengine/Makefile.am, tools/crm_resource.c
=> Backport fixes from master and clean up before new release

fencing/main.c
=> Fix stonithd device update 1.1

configure.ac, doc/Makefile.am
Follow-up for https://github.com/ClusterLabs/pacemaker/pull/1707#issuecomment-490132444
=> Fix "make dist" wrt. doc

fencing/commands.c, fencing/regression.py.in, include/crm/fencing/internal.h, lib/fencing/st_client.c
=> Fencing unify exec 1.1

.gitignore, doc/Pacemaker_Development/en-US/Ch-Evolution.txt, doc/Pacemaker_Development/en-US/Ch-Hacking.txt, doc/Pacemaker_Development/en-US/Pacemaker_Development.xml, doc/Pacemaker_Development/en-US/Revision_History.xml, include/crm/common/mainloop.h, lib/common/mainloop.c, lib/common/utils.c, maint/mocked/Makefile, maint/mocked/based-notifyfenced.c, maint/mocked/based.c, maint/mocked/based.h
Potential fix appears much easier than actually synthetically reproducing and
testing the fix, this part is pending.
=> High: pacemaker-fenced cannot be blocked with CIB updates forever

.gitignore, doc/Pacemaker_Development/en-US/Ch-Hacking.txt, doc/Pacemaker_Development/en-US/Pacemaker_Development.xml, doc/Pacemaker_Development/en-US/Revision_History.xml, include/crm/common/mainloop.h, lib/common/mainloop.c, lib/common/utils.c, maint/mocked/Makefile, maint/mocked/based-notifyfenced.c, maint/mocked/based.c, maint/mocked/based.h
backport of #1573
I settled on a full patchset approach, it wasn't difficult to adapt
and may be handy to investigate some observed behavioural
changes amongst the branches, for instance.
=> [1.1] High: fenced allow service regardless

cts/patterns.py, daemons/controld/controld_callbacks.c, daemons/controld/controld_control.c, daemons/controld/controld_fencing.c, daemons/controld/controld_fencing.h, daemons/fenced/fenced_history.c, daemons/fenced/fenced_remote.c, daemons/fenced/pacemaker-fenced.c, daemons/fenced/pacemaker-fenced.h, include/crm/stonith-ng.h, lib/fencing/st_client.c
#1805 Fix: fence-history: resync fence-history after fenced crash
same thing on master branch ...
=> Fence history handling after fenced crash master

include/crm/common/output.h, include/crm/common/util.h, include/crm/pengine/internal.h, lib/common/output_xml.c, lib/pengine/Makefile.am, lib/pengine/bundle.c, lib/pengine/clone.c, lib/pengine/native.c, lib/pengine/pe_output.c
Please review the new functionality. I propose changes of already existing xml formatter introduced in #1707 , add a new formatter for html and refactor crm_mon using new formatters.
=> Structurize crm mon

Makefile.common, include/crm/common/Makefile.am, include/crm/common/cmdline_internal.h, include/crm/common/output.h, lib/common/Makefile.am, lib/common/cmdline.c, lib/common/output.c, lib/common/output_text.c, lib/common/output_xml.c, tools/Makefile.am, tools/stonith_admin.8.inc, tools/stonith_admin.c, xml/Makefile.am, xml/api/status-2.0.rng, xml/api/version-2.0.rng
This patch set isn't done, but I'd like to get some comments on whether I am on the right track or not.  At the moment, there are two major things left undone:
* I need to complete testing that all arguments continue working like they used to.  For the most part, this is pretty boring stuff since it's just setting flags and I don't expect to have broken anything.  It's still worth double checking.
* The last patch (WIP) is an experiment to see what adding an option to a format handler would look like.  The big question is where to get the variable that the option value is stored in.  Having it be some sort of global static extern thing is gross.  I could make it a macro or function that takes an argument, but that's going to get annoying when we add options.  Perhaps the number of options …
=> Use glib for cmdline arg processing in stonith_admin

lib/fencing/st_client.c
=> Fix: st_client: cleanup token whenever setting api to disconnected

doc/pcs-crmsh-quick-ref.md
I updated the pcs-crmsh-quick-ref in respect to changes in pcs-0.10.
=> Doc: pcs-crmsh-quick-ref: update for pcs-0.10

CONTRIBUTING.md
The former spotted by Tomáš Jelínek of Red Hat.
=> Doc: CONTRIBUTING: update devel doc deadlink & URI schemes to https

include/crm/common/output.h, lib/common/output.c, lib/common/output_html.c, lib/common/output_none.c, lib/common/output_text.c, lib/common/output_xml.c, tools/stonith_admin.c
This is one potential way of addressing the comments that have come up in #1821
=> Add a way of accessing the xmlNode inside an XML pcmk__output_t

doc/Clusters_from_Scratch/en-US/Ch-Installation.txt, doc/Clusters_from_Scratch/en-US/Ch-Shared-Storage.txt
I added note boxes pointing out the most important changes in pcs-0.10.
=> Doc: Clusters from Scratch: note changes in pcs-0.10

doc/pcs-crmsh-quick-ref.md
Fixed Table of Contents I broke in 774fd55bd.
=> Doc: pcs-crmsh-quick-ref: fix TOC

ChangeLog, doc/Pacemaker_Explained/en-US/Ch-Advanced-Resources.txt, doc/Pacemaker_Explained/en-US/Ch-Fencing.txt, doc/Pacemaker_Explained/en-US/Ch-Resources.txt, doc/Pacemaker_Explained/en-US/Pacemaker_Explained.xml, doc/shared/en-US/pacemaker-intro.txt
Fixes clbz#5396 among other issues
=> Documentation improvements

extra/resources/controld, include/crm/common/Makefile.am, include/crm/common/curses_internal.h, include/crm/common/iso8601_internal.h, include/crm/common/util.h, lib/cib/cib_utils.c, lib/common/cmdline.c, lib/common/iso8601.c, lib/common/nvpair.c, lib/common/output.c, lib/common/output_text.c, lib/common/xml.c, lib/fencing/st_output.c, lib/pengine/bundle.c, lib/pengine/clone.c, lib/pengine/group.c, lib/pengine/native.c, lib/pengine/pe_output.c, lib/pengine/unpack.h, tools/crm_mon.c, tools/stonith_admin.c
I'm not sure this set of patches is totally ready, but I'm interested in starting to get feedback on them.  For the most part, they are all standalone patches that have come up in the course of moving crm_mon to using formatted output.  I've made several modifications along the way but I think I am done modifying these patches for now.  I'm also going to make a couple comments on them where I have questions.
=> Various changes to formatted output to prep for crm_mon work

cts/patterns.py, daemons/controld/controld_control.c, daemons/controld/controld_fencing.c, daemons/controld/controld_fencing.h, daemons/execd/execd_commands.c, daemons/execd/pacemaker-execd.c, daemons/fenced/cts-fence-helper.c, daemons/fenced/fenced_commands.c, daemons/pacemakerd/pacemakerd.c, doc/Pacemaker_Explained/en-US/Ch-Options.txt, include/crm/lrmd.h, include/crm/msg_xml.h, lib/fencing/st_client.c, lib/lrmd/lrmd_client.c, lib/pacemaker/pcmk_sched_allocate.c, lib/pacemaker/pcmk_sched_native.c, tools/crm_mon.c, tools/stonith_admin.c
Most significantly, allow the previous or new behavior for local node fence notifications to be selected via a cluster property.
=> Follow-up to recent fixes

tools/crm_mon.c
Hi All,
This fix is a revised version of the following PR.
Moved sort processing and changed reduce processing.
- https://github.com/ClusterLabs/pacemaker/pull/1816
Best Regards,
=> Refactor: crm_mon: Move of sort processing and simplification of reduce processing. 

include/crm/common/cmdline_internal.h, lib/common/cmdline.c, lib/common/strings.c, tools/crm_mon.8.inc, tools/crm_mon.c
I have not tested every single command line option, but what I've checked so far has been good.
=> Use glib for command line handling in crm_mon

fencing/admin.c
Backport of https://github.com/ClusterLabs/pacemaker/pull/1775 for 1.1 branch.
=> [1.1] Low: stonith_admin --help: specify the usage of --cleanup

.gitignore, GNUmakefile, cts/Makefile.am, cts/cli/crm_diff_new.xml, cts/cli/crm_diff_old.xml, cts/cli/regression.tools.exp, cts/cts-cli.in, daemons/controld/controld_execd.c, daemons/pacemakerd/pacemakerd.c, lib/common/results.c, lib/common/xml.c, lib/pengine/clone.c, lib/pengine/native.c, lib/pengine/pe_output.c, tools/crm_mon.c, tools/stonith_admin.c
Fix some issues found by static analysis (a memory leak being the only significant one)
=> Make static analysis happy

daemons/execd/pacemaker_remote.service.in, daemons/execd/remoted_tls.c, daemons/pacemakerd/pacemaker.sysconfig, extra/logrotate/pacemaker.in, lib/common/output.c, tools/report.common.in
with a couple of unrelated trivial follow-ups from recent work
=> Add ability to specify Pacemaker Remote bind address

Makefile.am, rpm/pacemaker.spec.in
with one other trivial build change
=> Fix SUSE RPM build

include/crm/fencing/internal.h, lib/common/output_text.c, lib/fencing/st_client.c, lib/fencing/st_output.c, lib/pengine/native.c, tools/crm_mon.c, tools/crm_mon_curses.c, tools/crm_mon_print.c, tools/stonith_admin.c
This should be the last set of patches for problems that have come up while converting crm_mon to use formatted output.  There's nothing major here.
=> Misc crm_mon related patches

include/crm/fencing/internal.h, lib/common/output_html.c, lib/common/output_text.c, lib/common/output_xml.c, lib/fencing/st_client.c, lib/pengine/bundle.c, tools/crm_mon.c, tools/crm_mon_print.c, tools/stonith_admin.c
Remember when I said a PR was going to be the last one containing miscellaneous fixes for crm_mon?  I was apparently wrong.  Here's several more.  These have been pulled out of #1884 since they are not strictly a part of enabling formatted output.
=> More crm mon fixes

lib/common/cmdline.c, lib/common/output.c, lib/common/output_html.c, lib/common/output_xml.c, lib/pengine/clone.c, lib/pengine/native.c, tools/crm_mon.c, tools/crm_mon.h, tools/crm_mon_print.c
Here's another collection of unrelated fixes that have come up in the course of converting crm_mon to formatted output.  Some of these may be appropriate for other branches.
=> More fixes for crm_mon & formatted output

include/crm/common/output.h, lib/common/output_html.c, lib/common/output_none.c, lib/common/output_text.c, lib/common/output_xml.c, lib/fencing/st_output.c, lib/pengine/bundle.c, lib/pengine/clone.c, lib/pengine/native.c, lib/pengine/pe_output.c, tools/crm_mon.h, tools/crm_mon_curses.c, tools/stonith_admin.c
This came out of https://github.com/ClusterLabs/pacemaker/pull/1884#discussion_r326390552.  For the moment it's based on master which means we're not saving much code by doing this.  Once #1884 gets merged, I can rebase this PR and it should save us a lot of work.
=> WIP: begin_list and list_item take varargs

GNUmakefile, daemons/execd/remoted_tls.c, include/crm/compatibility.h, lib/common/iso8601.c, lib/fencing/st_client.c, lib/pacemaker/pcmk_sched_allocate.c, lib/pacemaker/pcmk_sched_utilization.c, rpm/pacemaker.spec.in, tools/crm_resource.c, tools/stonith_admin.c
This is a collection of small, unrelated commits that fix issues found by static analysis, improve documentation or logging, or fix build issues.
=> Mostly static analysis fixes

cts/cts-fencing.in, daemons/fenced/fenced_commands.c, lib/fencing/st_client.c
* Quote fencing actions
* Fencing actions "targeting ..." instead of "for node ..."
=> Log: fencer: improved log messages regarding fencing actions

lib/services/services_linux.c
With large file descriptor limits, action_launch_child can close
millions of non-existent file descriptors.
Instead, try to read open file descriptors from /proc and close only
those which are open.
See rhbz#1762025
=> Fix: libcrmservice: try not to spam close() file descriptors

doc/Pacemaker_Administration/en-US/Ch-Tools.txt, tools/crm_mon.c
These are the last couple things outstanding from #1913.
=> crm_mon output-related fixes

lib/fencing/st_output.c, lib/pengine/bundle.c, lib/pengine/clone.c, lib/pengine/group.c, lib/pengine/native.c, lib/pengine/pe_output.c, tools/crm_mon_curses.c, tools/crm_mon_print.c
None of these are especially serious, but they make the types of output-related functions line up better.
=> Fix output-related types

daemons/fenced/fenced_commands.c, daemons/fenced/fenced_history.c, daemons/fenced/fenced_remote.c, daemons/fenced/pacemaker-fenced.h, include/crm/fencing/internal.h
Hi All,
This is a modified version of the content discussed in the next PR.
- https://github.com/ClusterLabs/pacemaker/pull/1959
Best Regards,
=> Low: fenced: Clearly log merged STONITH operations.

GNUmakefile, daemons/controld/controld_based.c, daemons/controld/controld_callbacks.c, daemons/controld/controld_execd.c, daemons/controld/controld_execd_state.c, daemons/controld/controld_fencing.c, daemons/controld/controld_fsa.c, daemons/controld/controld_join_dc.c, daemons/controld/controld_lrm.h, daemons/controld/controld_remote_ra.c, daemons/controld/controld_utils.c, daemons/controld/controld_utils.h, include/crm/common/internal.h, include/crm/pengine/common.h, lib/pacemaker/pcmk_sched_allocate.c, lib/pacemaker/pcmk_sched_graph.c, lib/pengine/native.c
These commits are preparation for a larger project.
Perhaps the most interesting change is when the controller needs to erase both a node's resource history and its transient node attributes, this is now done with a single CIB operation instead of two.
=> Logging and refactoring changes

include/crm/pengine/internal.h, lib/common/output_html.c, lib/pengine/pe_output.c, tools/crm_mon.c, tools/crm_mon_curses.c, tools/crm_mon_print.c
These are fixes to problems that have come up in the process of testing #1944.  These are independent of the --include/--exclude options being added.  Everything is handled here except the lack of CGI output.  I'm still working on that one.
Also note that #1944 will need to be rebased to go on top of this PR.
=> Various crm_mon output fixes

attrd/internal.h, crmd/cib.c, crmd/crmd_fsa.h, crmd/crmd_lrm.h, crmd/crmd_utils.h, crmd/fsa.c, crmd/fsa_proto.h, crmd/join_client.c, crmd/join_dc.c, crmd/lrm.c, include/crm/common/nvpair.h, include/crm/error.h, include/crm/lrmd.h, lib/common/logging.c, lib/common/mainloop.c, lib/common/nvpair.c, lib/lrmd/lrmd_client.c, lib/transition/unpack.c, tools/crm_error.c, tools/crm_resource_runtime.c, tools/fake_transition.c
These are mainly refactors to make backporting future changes easier. It also includes recent fixes to restore compilability with GCC 10, and with glibc on HP-PA architecture.
=> Backport recent changes from master

doc/Makefile.am
...and possibly beyond.
References:
https://gitlab.com/inkscape/inbox/issues/1244
=> Build: fix unability to build with Inkscape 1.0 beta version(s)

lib/common/output_xml.c
=> Fix: tools: Print errors to stderr for crm_mon's legacy xml.

doc/Pacemaker_Development/en-US/Ch-Coding.txt, lib/pengine/utils.c
More a preview now, will test on Thu.
=> Build: fix compilation -Werror compilation issue with GCC 10 with s390x

cts/cli/regression.rules.exp, cts/cli/regression.upgrade.exp, cts/cli/regression.validity.exp, include/crm/pengine/internal.h, lib/pengine/Makefile.am, lib/pengine/tags.c, tools/crm_diff.c, xml/Readme.md, xml/tags-3.3.rng
I expect to add to this set, especially where it comes to searching/getting/setting but this is a start.  Maybe there's something here to talk about.
=> Tag related patches

GNUmakefile, configure.ac, cts/cts-scheduler.in, include/crm/common/internal.h, include/crm/common/ipc.h, include/crm/lrmd.h, include/crm/pengine/remote_internal.h, include/crm/stonith-ng.h, lib/common/io.c, lib/common/xml.c, lib/pacemaker/pcmk_fence.c, lib/pengine/remote.c, tools/stonith_admin.c, xml/api/stonith_admin-2.1.rng
The main goal is to get the cppcheck and stonith_admin changes in before 2.0.4-rc1. The rest were just quick improvements.
=> Minor improvements

crmd/te_actions.c, fencing/admin.c
Backport of https://github.com/ClusterLabs/pacemaker/pull/2049 for 1.1 branch.
=> [1.1] Fixes about fencing delay

GNUmakefile
fdd8ea5ce (in Pacemaker 2.0.3) broke RPM generation for release candidates.
That commit was part of a larger project to get "make dist" working, and made "make dist" use the same archive file name as "make export". To get this to work, it made the rpm spec use SHORTTAG instead of TAG as the commit.
This was fine for untagged releases, but for tagged releases, distribution naming should use the version number alone, while the spec commit should use the entire tag.
The solution is to use separate variables for distribution naming and the spec commit.
=> Build: rpm: define spec commit correctly for release candidate tags

include/pacemaker.h, include/pcmki/pcmki_fence.h, lib/pacemaker/pcmk_fence.c, tools/stonith_admin.c
=> Fix: tools: get stonith_admin --list-targets working again

GNUmakefile, crmd/callbacks.c, crmd/lrm_state.c, extra/resources/attribute, lib/cluster/Makefile.am, lib/common/Makefile.am, lib/common/remote.c, lib/fencing/Makefile.am, lib/lrmd/Makefile.am, lib/pengine/Makefile.am, lib/pengine/unpack.c, lib/services/Makefile.am, lib/services/services_linux.c, lib/transition/Makefile.am, pengine/Makefile.am, rpm/pacemaker.spec.in, tools/attrd_updater.c, tools/crm_mon.c, version.m4
Everything but the change log update
=> Prepare 1.1.23-rc1 release

extra/resources/attribute, lib/pengine/unpack.c, rpm/pacemaker.spec.in, tools/attrd_updater.c, tools/crm_resource.c
These are little things that came up during testing of the release candidates
=> Trivial fixes

configure.ac, cts/lxc_autogen.sh.in, cts/scheduler/on_fail_demote4.xml, daemons/pacemakerd/pacemaker.sysconfig, extra/resources/attribute, include/crm/cib/util.h, include/crm/common/internal.h, include/crm/common/logging.h, include/crm/common/mainloop.h, include/crm/common/util.h, include/crm/pengine/pe_types.h, include/crm/pengine/rules.h, include/crm/stonith-ng.h, lib/cib/cib_native.c, lib/cib/cib_remote.c, lib/cib/cib_utils.c, rpm/pacemaker.spec.in
These are small fixes I've been collecting while waiting for 2.0.4 to be released. None of them are particularly significant but are useful to get done.
=> Minor unrelated fixes

doc/sphinx/Clusters_from_Scratch/intro.rst, doc/sphinx/Makefile.am, doc/sphinx/Pacemaker_Administration/agents.rst, doc/sphinx/Pacemaker_Administration/configuring.rst, doc/sphinx/Pacemaker_Administration/tools.rst, doc/sphinx/Pacemaker_Administration/upgrading.rst, doc/sphinx/Pacemaker_Explained/acls.rst, doc/sphinx/Pacemaker_Explained/advanced-options.rst, doc/sphinx/Pacemaker_Explained/advanced-resources.rst, doc/sphinx/Pacemaker_Explained/alerts.rst, doc/sphinx/Pacemaker_Explained/ap-samples.rst, doc/sphinx/Pacemaker_Explained/constraints.rst, doc/sphinx/Pacemaker_Explained/fencing.rst, doc/sphinx/Pacemaker_Explained/index.rst, doc/sphinx/Pacemaker_Explained/intro.rst, doc/sphinx/Pacemaker_Explained/multi-site-clusters.rst, doc/sphinx/Pacemaker_Explained/nodes.rst, doc/sphinx/Pacemaker_Explained/options.rst, doc/sphinx/Pacemaker_Explained/resources.rst, doc/sphinx/Pacemaker_Explained/reusing-configuration.rst, doc/sphinx/Pacemaker_Explained/rules.rst, doc/sphinx/Pacemaker_Explained/status.rst, doc/sphinx/Pacemaker_Explained/utilization.rst, doc/sphinx/Pacemaker_Remote/options.rst
Aside from some minor reformatting to already-converted books, the bulk of this is creating a template for converting "Pacemaker Explained".
=> Continue converting documentation to Sphinx

cts/cli/crm_mon.xml, cts/cli/regression.crm_mon.exp, cts/cts-cli.in, include/crm/pengine/internal.h, lib/fencing/st_output.c, lib/pengine/bundle.c, lib/pengine/clone.c, lib/pengine/group.c, lib/pengine/native.c, lib/pengine/pe_output.c, lib/pengine/tags.c, lib/pengine/utils.c, tools/crm_mon.h, tools/crm_mon_print.c
These are mostly standalone patches that prepare crm_mon for the --resource= option.  There's a couple more still in that PR that add support functions, but those are more closely tied to adding that option and I felt they were best to be left where they were.
=> Patches to get ready for crm_mon --resource

include/crm/common/output.h, lib/common/output_html.c, lib/common/output_log.c, lib/common/output_text.c, lib/common/output_xml.c, tools/crm_mon.c, tools/crm_mon_curses.c
This was empty due to several bugs, the most obvious of which was that only the finish function was ever being called, and only at program termination.
=> Fix crm_mon --daemonize output

daemons/controld/controld_execd.c
Remove clutter from `construct_op()`.
=> Refactor: controld: Functionalize versioned param resolution

cts/CTS.py.in, cts/CTSaudits.py, cts/patterns.py, daemons/fenced/fenced_commands.c, include/crm/cluster/internal.h, include/crm/common/internal.h, include/crm_internal.h, lib/common/ipc_controld.c, m4/CHECK_ENUM_VALUE.m4
(with a few trivial unrelated fixes)
=> Update CTS for recent external software changes

cts/cli/regression.tools.exp, cts/cts-cli.in, include/crm/common/internal.h, lib/common/results.c, tools/crm_mon.c, tools/crm_node.c, tools/crm_simulate.c, tools/stonith_admin.c
The test patch I am not happy with.  I'd like to add a lot more tests, especially around validation and fail/restart/refresh/cleanup.  I'm getting various errors when trying to add those regarding transport endpoints not being connected, or operations not being allowed.  The other tests found bugs in my crm_resource changes so I believe further tests would probably find more bugs.
=> Patches to get ready for moving crm_resource to glib

daemons/pacemakerd/pacemaker.sysconfig, lib/common/logging.c
=> Log: Allow logfile perms to be set in sysconfig

cts/cli/regression.tools.exp, tools/Makefile.am, tools/crm_resource.8.inc, tools/crm_resource.c, tools/crm_resource.h, tools/crm_resource_ban.c, tools/crm_resource_print.c, tools/crm_resource_runtime.c
This is an awful lot of patch, but a bunch of it just moving code around.
=> Convert crm_resource to use glib for command line handling

cts/cli/crm_mon.xml, cts/cli/regression.crm_mon.exp, cts/cts-cli.in, include/crm/pengine/internal.h, include/crm/pengine/pe_types.h, lib/pacemaker/pcmk_sched_messages.c, lib/pengine/bundle.c, lib/pengine/clone.c, lib/pengine/complex.c, lib/pengine/group.c, lib/pengine/native.c, lib/pengine/pe_output.c, lib/pengine/utils.c, tools/crm_mon.c, tools/crm_mon.h, tools/crm_mon_print.c
This builds on top of #2085 and is included in this patch too.  It's possible I am missing some spots where resources can be displayed.  They're all over the place in crm_mon output.
=> Add --resource= to crm_mon

include/crm/services.h
We can't use pcmk__* in services.h because those are internal functions
and external users won't be able to include them.  Additionally, this
should be a case-sensitive comparision so use strcmp instead.
Note that the conditional is a little more verbose than it needs to be.
This is just to get around coccinelle trying to change it to use the
internal function.
=> High: include: Don't include an internal header in services.h.

doc/sphinx/Clusters_from_Scratch/active-active.rst, doc/sphinx/Clusters_from_Scratch/active-passive.rst, doc/sphinx/Clusters_from_Scratch/apache.rst, doc/sphinx/Clusters_from_Scratch/cluster-setup.rst, doc/sphinx/Clusters_from_Scratch/fencing.rst, doc/sphinx/Clusters_from_Scratch/installation.rst, doc/sphinx/Clusters_from_Scratch/intro.rst, doc/sphinx/Clusters_from_Scratch/shared-storage.rst, doc/sphinx/Pacemaker_Administration/agents.rst, doc/sphinx/Pacemaker_Administration/cluster.rst, doc/sphinx/Pacemaker_Administration/configuring.rst, doc/sphinx/Pacemaker_Administration/installing.rst, doc/sphinx/Pacemaker_Administration/tools.rst, doc/sphinx/Pacemaker_Administration/troubleshooting.rst, doc/sphinx/Pacemaker_Administration/upgrading.rst, doc/sphinx/Pacemaker_Development/c.rst, doc/sphinx/Pacemaker_Development/faq.rst, doc/sphinx/Pacemaker_Development/general.rst, doc/sphinx/Pacemaker_Development/python.rst, doc/sphinx/Pacemaker_Explained/alerts.rst, doc/sphinx/Pacemaker_Remote/alternatives.rst, doc/sphinx/Pacemaker_Remote/baremetal-tutorial.rst, doc/sphinx/Pacemaker_Remote/example.rst, doc/sphinx/Pacemaker_Remote/intro.rst, doc/sphinx/Pacemaker_Remote/kvm-tutorial.rst, doc/sphinx/Pacemaker_Remote/options.rst
... and improve indexes in already-converted books
=> Convert Pacemaker Explained alerts chapter to rst+sphinx

doc/sphinx/Pacemaker_Explained/ap-samples.rst, doc/sphinx/Pacemaker_Explained/status.rst
There's two things I haven't figured out here:
* Whether the indexing I've added is any good at all.
* The "Node Attributes" cross reference in chapter 14.
=> Convert Pacemaker Explained chapters 14 and 16 to rst+sphinx

daemons/based/based_messages.c, daemons/controld/controld_schedulerd.c, include/crm/common/logging.h, include/crm/common/xml.h, include/crm/common/xml_internal.h, include/crm_internal.h, lib/cib/cib_file.c, lib/cib/cib_ops.c, lib/cib/cib_utils.c, lib/common/crmcommon_private.h, lib/common/digest.c, lib/common/schemas.c, lib/common/xml.c, lib/pacemaker/pcmk_sched_utils.c, lib/pengine/complex.c
This is mostly function renames but does include a little bit of refactoring
=> Continue "best practices" project for libcrmcommon internal API

daemons/controld/controld_execd.c, tools/crm_resource.c
This is some prep for adding a --digests option later
=> Regression fixes and crm_resource clean-up

cts/cli/regression.crm_mon.exp, cts/cts-cli.in
Replace the api-version with an "X" so it always matches when running
regression tests.
=> Fix: cts: Don't worry about api-version= in test comparisions.

configure.ac, daemons/execd/execd_commands.c, doc/sphinx/Pacemaker_Explained/advanced-resources.rst, doc/sphinx/Pacemaker_Explained/alerts.rst, doc/sphinx/Pacemaker_Explained/options.rst, doc/sphinx/Pacemaker_Explained/resources.rst, doc/sphinx/Pacemaker_Explained/rules.rst
These were a few little things I wanted to get done before the next release
=> Minor prep for 2.0.5 release

daemons/controld/controld_te_events.c, daemons/execd/execd_commands.c, extra/resources/Dummy, extra/resources/Stateful, include/crm/common/internal.h, include/crm/common/results.h, include/crm/services.h, lib/common/agents.c, lib/pengine/unpack.c
also added OCF_CHECK_LEVEL to Dummy agent to return custom rc.
=> Feature: Accept PCMK_OCF_DEGRADED and PCMK_OCF_DEGRADED_MASTER codes

daemons/fenced/fenced_remote.c, include/crm/common/curses_internal.h, include/crm/common/options_internal.h, include/crm_internal.h, include/portability.h, lib/common/cmdline.c, lib/common/output_xml.c, lib/gnu/md5.h, lib/gnu/stdalign.in.h, lib/pacemaker/pcmk_sched_bundle.c, lib/pengine/status.c, lib/pengine/utils.c, m4/00gnulib.m4, m4/gl-openssl.m4, m4/gnulib-common.m4, m4/gnulib-comp.m4, tools/crm_mon_print.c, tools/crm_resource.c, tools/crm_simulate.c, tools/crmadmin.c, tools/notifyServicelogEvent.c
Here's a bunch of stuff preparing for RC1.  Things that I haven't dealt with yet:
=> Preparing for RC1

ChangeLog, lib/cib/Makefile.am, lib/cluster/Makefile.am, lib/common/Makefile.am, lib/fencing/Makefile.am, lib/lrmd/Makefile.am, lib/pacemaker/Makefile.am, lib/pengine/Makefile.am, lib/services/Makefile.am, version.m4, xml/Readme.md
This is for after master gets merged into the 2.0 branch.  I'm especially curious to know if I did the soname stuff right.
=> Changelog and docs for 2.0.5-rc1

lib/pengine/status.c
=> Fix: scheduler: fix build when DEFAULT_CONCURRENT_FENCING_TRUE is set

lib/pengine/unpack.c, pengine/test10/migrate-fail-9.dot, pengine/test10/migrate-fail-9.exp, pengine/test10/migrate-fail-9.summary
Backport of https://github.com/ClusterLabs/pacemaker/pull/2146 for 1.1 branch.
=> [1.1] Fix: scheduler: don't schedule a dangling migration stop if one already occurred

lib/pacemaker.pc.in
... to future-proof against the other .pc's going away.
=> Build: pkg-config: put all variables in pacemaker.pc

include/crm/pengine/common.h, include/crm/pengine/rules_internal.h, include/pcmki/pcmki_sched_allocate.h, lib/pacemaker/pcmk_sched_constraints.c, lib/pengine/bundle.c, lib/pengine/native.c, lib/pengine/pe_digest.c, lib/pengine/rules.c, lib/pengine/utils.c, tools/crm_rule.c
This was split out from another project that got a bit large. While not very significant in itself, it lays the groundwork for that one.
=> Minor scheduler fixes and refactoring

lib/pengine/complex.c
Hi All,
The following PR that solves the problem reported in Bugzilla.
- https://bugs.clusterlabs.org/show_bug.cgi?id=5451
This PR solves Bugzilla's problem by correctly handling all fixed meta_attributes of parent resources above child resources.
Best Regards,
=> Mid: schedulerd: Fixed processing to expand meta_attributes. Fix(#CLBZ:5451)

cts/cli/regression.crm_mon.exp, tools/crm_mon_print.c
Hi All,
This PR has been modified for 2.0.
See the following PR for details.
- https://github.com/ClusterLabs/pacemaker/pull/2229
Best Regards,
=> High: tools: "Connectivity is lost" may not be displayed even if the ping communication is lost. 

doc/sphinx/Pacemaker_Explained/utilization.rst
This will need to get rebased after the resources chapter goes in due to references.
=> Doc: Pacemaker Explained: convert utilization chapter to rST+sphinx

lib/pengine/pe_output.c
If there's no resources to print, don't output just the header with
nothing under it.  This potentially comes up if there are only inactive
resources, but inactive_resources is FALSE.
=> Fix: scheduler: Don't output a resource header with no list.

cts/cli/constraints.xml, cts/cli/regression.tools.exp, cts/cts-cli.in, include/crm/pengine/internal.h, lib/pacemaker/pcmk_output.c, lib/pengine/utils.c, tools/crm_resource.c, tools/crm_resource_runtime.c, xml/api/crm_resource-2.5.rng
I'm not really sure of this at all, but hopefully it's a good direction to start in.  I have only worked on the text output.  XML is likely broken at best, segfaulty at worst.  I'll fix that should the text output changes be correct.  I could definitely use more CIB examples that I could use as test cases.
=> Fix crm_resource -a/-A output

doc/sphinx/Pacemaker_Explained/advanced-resources.rst, doc/sphinx/Pacemaker_Explained/constraints.rst, include/crm/pengine/pe_types.h, include/pcmki/pcmki_sched_allocate.h, include/pcmki/pcmki_sched_utils.h, include/pcmki/pcmki_scheduler.h, lib/pacemaker/pcmk_output.c, lib/pacemaker/pcmk_sched_bundle.c, lib/pacemaker/pcmk_sched_clone.c, lib/pacemaker/pcmk_sched_constraints.c, lib/pacemaker/pcmk_sched_graph.c, lib/pacemaker/pcmk_sched_group.c, lib/pacemaker/pcmk_sched_native.c, lib/pacemaker/pcmk_sched_promotable.c, lib/pacemaker/pcmk_sched_utilization.c, lib/pacemaker/pcmk_sched_utils.c, tools/crm_resource_runtime.c
This is preparation for a new feature.
=> Colocation constraint refactoring and documentation

.travis.yml, autogen.sh, doc/sphinx/Pacemaker_Development/faq.rst, include/crm/crm.h
Small updates related to recent pull requests
=> Follow-up changes for 2.1.0

tools/crm_mon.c, tools/crm_mon.h, tools/crm_mon_print.c
The main point of this is fixing bug 1880426 and bug 1466875.
=> Various connection management changes for crm_mon

tools/cibsecret.in
=> Fix: tools: get cibsecret stash working again

daemons/fenced/fenced_commands.c, daemons/fenced/pacemaker-fenced.c, daemons/fenced/pacemaker-fenced.h
This is a modified version of https://github.com/ClusterLabs/pacemaker/pull/2262.
=> Fix: fencing: remove any devices that are not installed

cts/cli/crm_mon.xml, cts/cli/regression.crm_mon.exp, cts/cli/regression.tools.exp, cts/cts-cli.in, tools/crm_resource.c, tools/crm_resource.h, tools/crm_resource_print.c, tools/crm_resource_runtime.c
This kind of feels like I am going around in a circle I don't need to be, but I'm not sure what I would do differently.
=> Fix crm_resource --locate for promotable clones

tools/Makefile.am, tools/crm_verify.8.inc, tools/crm_verify.c
crm_verify uses some of the same functions as crm_simulate, so this just gets crm_verify ready.  Next, I can start working on converting those shared functions.
=> crm_verify goption and formatted output conversion

cts/cli/crm_mon.xml, cts/cli/regression.crm_mon.exp
I think this is the right thing to do - I can't remember why I wouldn't have included all this information in the first place.
Note that if I need to work on the promotable bundle thing, I would put that into a new file (and put the promotable clone stuff in there too).  Those changes could also be a part of this PR.
=> Update the cts/cli/crm_mon.xml file

INSTALL.md, doc/sphinx/Clusters_from_Scratch/cluster-setup.rst, doc/sphinx/Clusters_from_Scratch/installation.rst, doc/sphinx/Makefile.am, doc/sphinx/Pacemaker_Administration/tools.rst, doc/sphinx/Pacemaker_Explained/nodes.rst, doc/sphinx/Pacemaker_Explained/options.rst, doc/sphinx/Pacemaker_Remote/intro.rst, doc/sphinx/conf.py.in, doc/sphinx/shared/pacemaker-intro.rst
... with a few minor corrections to the books themselves
=> Fix generation of books in PDF format

include/crm/common/output_internal.h, lib/common/output_text.c, lib/pacemaker/pcmk_fence.c, lib/pacemaker/pcmk_output.c, lib/pengine/pe_output.c, tools/crm_mon.c, tools/crm_mon.h, tools/crm_mon_curses.c, tools/crm_resource_ban.c, tools/crm_resource_print.c, tools/crm_resource_runtime.c
I took a survey of all the places out->info was being used and I think the only ones left are those that can safely be ignored if is_quiet is set.  But it might be worth another look.
=> out->info should respect out->is_quiet

include/crm/common/output_internal.h, include/crm_internal.h, include/pcmki/pcmki_sched_utils.h, lib/common/output_html.c, lib/common/output_log.c, lib/common/output_none.c, lib/common/output_text.c, lib/common/output_xml.c, lib/pacemaker/Makefile.am, lib/pacemaker/pcmk_output.c, lib/pacemaker/pcmk_output_utils.c, lib/pacemaker/pcmk_sched_messages.c, lib/pacemaker/pcmk_sched_utils.c, lib/pengine/status.c, tools/crm_mon_curses.c, tools/crm_resource_print.c
Here's several more easily digestable patches out of the big crm_simulate PR that are fairly stand alone.  I don't think there's anything else in that PR that could be added here, but there might be more in the future as it gets closer to going in.  Still, I think it's worth breaking these patches out and reviewing them separately.
=> More preparation for crm_simulate

tools/crm_resource_runtime.c
Without this being set, crm_resource will segfault at some point when it
dereferences data_set->priv.  Doing this also means update_dataset
doesn't need an extra output parameter.
=> Fix: tools: Set the output object when running crm_resource --restart.

lib/common/attrd_client.c, mk/common.mk, tools/Makefile.am, tools/attrd_updater.c, tools/crm_attribute.8.inc, tools/crm_attribute.c
This is part of my long background task of converting all the tools away from our own command line code, so it can then be deprecated.
=> Convert crm_attribute to use glib for command line handling

include/crm/pengine/internal.h, lib/pengine/native.c, lib/pengine/unpack.c
Hi All,
This fix resolves the following Bugzilla issues.
- https://bugs.clusterlabs.org/show_bug.cgi?id=5467
This will be a modified version of the next PR.
- https://github.com/ClusterLabs/pacemaker/pull/2352
Best Regards,
=> Mid: schedulerd: Correctly calculate priority-fencing-delay from Master resource stop failure.(Fix:#CLBZ5467)

include/crm/pengine/internal.h, lib/pengine/pe_output.c, lib/pengine/utils.c, tools/crm_mon.c, tools/crm_mon.h, tools/crm_mon_print.c
This is just the beginning of #2353, pulled out into its own PR.
=> New formatted output messages for crm_mon

configure.ac, cts/cts-exec.in, daemons/execd/execd_commands.c, extra/resources/Makefile.am, include/crm/Makefile.am, include/crm/services_internal.h, lib/services/services.c, lib/services/services_linux.c, lib/services/services_private.h, tools/crm_resource.c
- OCF_RA_PATH for comma-separated directories to search for agents
- OCF_RA_INSTALL_DIR for installation of pacemaker agents
2.1 version of https://github.com/ClusterLabs/pacemaker/pull/2355 w/improvements.
=> Feature: configure/lib: add OCF_RA_PATH and OCF_RA_INSTALL_DIR

daemons/fenced/pacemaker-fenced.c
Resubmit https://github.com/ClusterLabs/pacemaker/pull/2292 to the 2.1 branch.
=> Fix: fencing: register/remove the watchdog device

README.markdown, configure.ac, doc/crm_fencing.txt, doc/sphinx/Pacemaker_Development/faq.rst, doc/sphinx/conf.py.in, extra/cluster-init, rpm/pacemaker.spec.in
... along with a minor RPM improvement and some updated URLs in the documentation
=> Add stack clash protection by default

include/crm/msg_xml_compat.h
should have been done with 42343b75
=> Refactor: libcrmcommon: use unique header guard

.travis.yml, INSTALL.md, cts/cli/regression.tools.exp, cts/cts-cli.in
This covers some output from crm_mon and crm_resource.  We can add more as we go along.  It will fail until the fix for the crm_resource digests stuff gets merged into master.
=> Validate CTS XML output against the schema

daemons/fenced/fenced_commands.c
Hi Ken,
Hi All,
This PR will be a re-correction of the next PR.
- https://github.com/ClusterLabs/pacemaker/pull/2410
Best Regards,
=> High: fenced: Wrong device may be selected when "dynamic-list" is specified.(Fix:CLBZ#5474) 

include/crm/common/output_internal.h, tools/crm_simulate.c, xml/Makefile.am, xml/api/crm_mon-2.12.rng, xml/api/crm_simulate-2.12.rng, xml/api/node-history-2.12.rng
This unfortunately did not get included in the previous PR that added to the crm_simulate output.  Hopefully it can still be included.  I'm not quite sure what schema version numbers to use for all this since master has already moved on.  Obviously, I can change them to whatever is necessary.
=> Add failcounts to crm_simulate output

cts/cts-scheduler.in, cts/scheduler/dot/colocate-unmanaged-group.dot, cts/scheduler/exp/colocate-unmanaged-group.exp, cts/scheduler/scores/colocate-unmanaged-group.scores, cts/scheduler/scores/unmanaged-promoted.scores, cts/scheduler/summary/colocate-unmanaged-group.summary, cts/scheduler/xml/colocate-unmanaged-group.xml, include/crm/pengine/pe_types.h, include/pcmki/pcmki_sched_allocate.h, lib/pacemaker/pcmk_sched_allocate.c, lib/pacemaker/pcmk_sched_clone.c, lib/pacemaker/pcmk_sched_constraints.c, lib/pacemaker/pcmk_sched_graph.c, lib/pacemaker/pcmk_sched_group.c, lib/pacemaker/pcmk_sched_native.c, lib/pacemaker/pcmk_sched_notif.c, lib/pacemaker/pcmk_sched_utils.c
Most importantly, this fixes an invalid transition possible when a subset of group members are unmanaged and started.
=> Scheduler fixes (including CLBZ#5423)

lib/common/cmdline.c, lib/common/tests/cmdline/pcmk__cmdline_preproc_test.c, tools/crm_attribute.c, tools/crm_error.c, tools/crm_resource.c, tools/crm_rule.c, tools/crm_simulate.c, tools/crmadmin.c, tools/stonith_admin.c
However, note that this is not perfect.  See the commit message in e9d87e6 for details.
=> More cmdline processing fixes

lib/pengine/utils.c
custom_action() has always been long and difficult to follow, so hopefully separating it into smaller pieces will help
=> Functionize custom_action() sections for readability

include/crm/pengine/internal.h, lib/pacemaker/pcmk_sched_allocate.c, lib/pacemaker/pcmk_sched_constraints.c, lib/pacemaker/pcmk_sched_graph.c, lib/pacemaker/pcmk_sched_messages.c, lib/pacemaker/pcmk_sched_native.c, lib/pengine/utils.c
While investigating a particularly stubborn problem, I redid a bunch of trace logs to make it easier
=> Improve scheduler trace logging

cts/Makefile.am, cts/cli/crm_mon-unmanaged.xml, cts/cli/regression.crm_mon.exp, cts/cts-cli.in, cts/scheduler/summary/unmanaged-promoted.summary, lib/pengine/native.c
This is the same PR as #2450, just against 2.1 instead.
=>  Active resources on offline nodes

include/crm/pengine/pe_types.h, lib/pacemaker/pcmk_sched_allocate.c, lib/pacemaker/pcmk_sched_clone.c, lib/pacemaker/pcmk_sched_constraints.c, lib/pacemaker/pcmk_sched_graph.c, lib/pacemaker/pcmk_sched_native.c
While investigating a scheduler ordering issue, I did a bunch of refactoring to try to understand the code better.
=> Scheduler refactoring for readability and efficiency

daemons/controld/controld_callbacks.c
Commit 0ec714adc covers the case where a node is rejoining. But for the
case where a node is newly joining controld cpg group, hence its node
name is not known by us yet, peer_update_callback() will directly bail
out with the logic:
```
if (node->uname == NULL) {
return;
}
```
, so that non-DC nodes don't get to send out a hello message.
This commit fixes it by moving the hello messaging logic prior to that.
=> Fix: controller: ensure newly joining node learns the node names of none-DCs

.gitignore, cts/cts-scheduler.in
Example of no failures occuring:
```
[gchin@gchin pacemaker]$ ./cts/cts-scheduler --run target-0
Test home is:   /home/gchin/pacemaker/cts
Test binary is: /home/gchin/pacemaker/tools/crm_simulate
Schema home is: /home/gchin/pacemaker/xml
Test target-0:                 Single shot
/home/gchin/pacemaker/tools/crm_simulate -x /home/gchin/pacemaker/cts/scheduler/xml/target-0.xml -S
Current cluster status:
* Node List:
* Online: [ c001n01 c001n02 c001n03 c001n08 ]
* Full List of Resources:
* DcIPaddr  (ocf:heartbeat:IPaddr):  Started c001n02
* rsc_c001n08       (ocf:heartbeat:IPaddr):  Started c001n08
* rsc_c001n02       (ocf:heartbeat:IPaddr):  Started c001n02
* rsc_c001n03       (ocf:heartbeat:IPaddr):  Started c001n03
* rsc_c001n01       (ocf:heartbeat:IPaddr):  Started c001n01
Transition …
```
=> Test: cts-scheduler: Write failures to file in temporary directory

cts/cts-fencing.in, daemons/fenced/fence_watchdog.in
fixes the metadata
add tests to cts-fencing checking the metadata created by fence_dummy & fence_watchdog for valid xml
=> Fix: fence_watchdog: fix malformed xml in metadata

cts/lab/CTStests.py, cts/scheduler/summary/stonith-4.summary, daemons/controld/controld_callbacks.c, daemons/controld/controld_control.c, daemons/controld/controld_execd.c, daemons/controld/controld_execd_state.c, daemons/controld/controld_lrm.h, daemons/controld/controld_messages.c, daemons/controld/controld_remote_ra.c, daemons/controld/controld_transition.c, daemons/fenced/fenced_remote.c, daemons/pacemakerd/pcmkd_corosync.c, include/crm/lrmd_internal.h, include/pcmki/pcmki_sched_utils.h, lib/cluster/corosync.c, lib/cluster/cpg.c, lib/lrmd/lrmd_client.c, lib/pacemaker/pcmk_sched_allocate.c, lib/pacemaker/pcmk_sched_bundle.c, lib/pacemaker/pcmk_sched_native.c, lib/pacemaker/pcmk_sched_utils.c, lib/pengine/unpack.c, tools/crm_rule.c
Reword various messages for clarity and consistency, drop some redundant messages, and refactor some functions to return standard return codes so error messages can give sufficient detail.
=> Logging improvements

include/crm/common/output.h, include/pacemaker-internal.h, include/pcmki/Makefile.am, include/pcmki/pcmki_simulate.h, lib/cib/cib_client.c, lib/cib/cib_file.c, lib/cib/cib_native.c, lib/cib/cib_remote.c, lib/pacemaker/Makefile.am, lib/pacemaker/pcmk_output.c, lib/pacemaker/pcmk_simulate.c, lib/pengine/pe_output.c, tools/crm_mon.c, tools/crm_simulate.c
These are the easiest commits out of #2467 split off onto their own.
=> Prepare for a crm_simulate library function

daemons/fenced/fenced_commands.c
Hi All,
This PR is a revised version of the next PR discussion.
- https://github.com/ClusterLabs/pacemaker/pull/2508
- https://github.com/ClusterLabs/pacemaker/pull/2515
Best Regards,
=> Mid: fenced: Change query timeout calculation.

cts/cli/regression.upgrade.exp, cts/cli/regression.validity.exp, xml/README.md, xml/acls-3.8.rng
@kgaillot I followed Steps 1-8 of https://github.com/ClusterLabs/pacemaker/blob/master/xml/README.md to make this PR. Let me know if it looks right...
=> Add a 'name' attribute to acl_target and acl_group elements

daemons/based/based_callbacks.c
Hi Ken,
Hi All,
This amendment was discussed in the next PR.
- https://github.com/ClusterLabs/pacemaker/pull/2550
- https://github.com/ClusterLabs/pacemaker/pull/2561
With this fix, the result of the replace process of cib is changed to be judged by the hash value of the section of cib before and after the change.
This fix also resolves an issue where attrd is not currently notified of changes in the alert section.
Best Regards,
=> Mid: based: Makes the replace notification a comparison base for the hash value of the section.

daemons/attrd/attrd_utils.c
Hi Ken,
Hi All,
This amendment was discussed in the next PR.
- https://github.com/ClusterLabs/pacemaker/pull/2550
This fix eliminates the extra processing of attrd when the CIB is replaced.
Best Regards,
=> Mid: attrd: Change to determine the processing of attrd depending on the section replacement location of CIB.

lib/services/systemd.c
These unit files (which have an @ sign at the end) expect to be
parameterized by an instance name.  Not providing an instance name
causes the dbus lookup to fail, and we fall back to assume this is an
LSB service.  If the user doesn't provide an instance name, just add a
fake one.  It doesn't seem to matter what name is given for the lookup.
See: rhbz#2003151
=> Low: libcrmservice: Handle systemd service templates.

daemons/fenced/fenced_commands.c, daemons/fenced/fenced_history.c, daemons/fenced/fenced_remote.c, daemons/fenced/pacemaker-fenced.c, daemons/fenced/pacemaker-fenced.h, include/crm/common/internal.h, lib/common/operations.c, lib/pacemaker/pcmk_graph_producer.c, lib/pengine/common.c
This is continued preparation for returning exit reasons to fence clients, addressing minor issues found in the fencer to make it easier to pass the full result around everywhere.
=> Minor clean-up of fencer

daemons/based/based_callbacks.c, daemons/based/based_notify.c, daemons/based/based_remote.c, daemons/controld/controld_callbacks.c, daemons/controld/controld_fsa.c, daemons/execd/execd_commands.c, daemons/execd/pacemaker-execd.c, daemons/fenced/pacemaker-fenced.c, include/crm/common/internal.h, lib/cib/cib_utils.c, lib/pacemaker/pcmk_graph_producer.c, lib/pacemaker/pcmk_sched_actions.c, lib/pacemaker/pcmk_sched_allocate.c, lib/pacemaker/pcmk_sched_native.c, lib/pacemaker/pcmk_sched_ordering.c, lib/services/dbus.c, tools/crm_resource_print.c, tools/crm_resource_runtime.c, tools/ipmiservicelogd.c
This does the same thing as adding "0x" to the front of the string,
except the library will do it for you.  Also, change a "0x%p" to just
"%p", since that format specifier will add the "0x" as well.
=> Refactor: Use the "#" format specifier in printf.

lib/lrmd/lrmd_client.c
This commit fixes a regression introduced by 31c7fa8a, causing a
double-free in notify operations. lrmd_dispatch_internal() assigns the
exit_reason string directly from an XML node to a new lrmd_event_data_t
object (without duplicating), and this string gets freed twice.
Free #1: pcmk__create_history_xml() (reached via callback) calls
lrmd__set_result(), which frees event.exit_reason and sets it to NULL.
Free #2: lrmd_ipc_dispatch() frees the XML node, which contains a
pointer to the exit_reason string just freed, after
lrmd_dispatch_internal() returns.
Prior to 31c7fa8a, pcmk__create_history_xml reset event.rc and
event.op_status but **not** event.exit_reason.
In this commit we simply make a copy of event.exit_reason in
lrmd_dispatch_internal() before the callback. This way we don't have …
=> Fix: liblrmd: Avoid double-free during notify operation

lib/pengine/clone.c
Previously, pe__clone_default() unconditionally created a hash table for
stopped instances, but didn't free it in every code path.
Now, only create the table when we have something to put in it and might
actually use it, and ensure it always gets freed.
=> Fix: scheduler: avoid memory leak when displaying clones

daemons/pacemakerd/pcmkd_subdaemons.c
regression from introduction of periodic subdaemon checking
in cases they are pacemakerd children - previously it was either
periodic checking or signal-handler per process.
=> Fix: pacemakerd: have signal-handler take care of lost processes

lib/fencing/st_client.c
regression introduced with
'Allow removing all registered callbacks at once.'
=> Fix: libstonithd: avoid controld shutdown hanging

configure.ac, cts/lxc_autogen.sh.in, daemons/controld/controld_metadata.c, daemons/controld/controld_te_events.c, daemons/pacemakerd/pcmkd_subdaemons.c, lib/common/iso8601.c, lib/common/schemas.c, lib/pacemaker/pcmk_acl.c, lib/pacemaker/pcmk_sched_ordering.c
This contains one major fix, a regression in 2.1.2, plus some unrelated trivial stuff I ran across lately while working on other stuff.
=> Fix regression in down event detection in 2.1.2

include/pacemaker-internal.h, include/pacemaker.h, include/pcmki/Makefile.am, include/pcmki/pcmki_fence.h, include/pcmki/pcmki_status.h, lib/pacemaker/Makefile.am, lib/pacemaker/pcmk_fence.c, lib/pacemaker/pcmk_status.c, tools/crm_mon.c
This is everything from #2612 before it starts actually making the library functions.
=> Prepare crm_mon to be a library

lib/services/systemd.c
A previous patch for this did not handle the possibility of templates
used with a unit file suffix.  For example, chrony-dnssrv@ would work
but chrony-dnssrv@.template would not.
This patch takes care of the extra case.  Additionally, it uses the
"pacemaker" instance name for both cases.
See: rhbz#2045096
=> Low: libcrmservice: Additional metadata fix for systemd templates.

daemons/fenced/pacemaker-fenced.c, lib/common/options.c, po/POTFILES.in, po/zh_CN.po
Hi:
In this pr, I added Chinese translation about pacemaker-fenced files.
=> Add Chinese translation of pacemaker-fenced files

lib/cib/cib_attrs.c
This function doesn't return a standard pacemaker return code.  It
returns a negative value on error and the positive call ID on success.
So, be more careful handling this return value.  Note that the find_attr
function that wraps it does return a standard pacemaker return code.
=> High: libcib: Fix handling the return value of cib_internal_op.

tools/crm_resource.c
Oops, missed this one.
should have been done with c572d9f27
=> Fix: tools: set command for `crm_resource -q/--query-xml` before changing any options

lib/common/xml.c
=> fix Chinese garbled

cts/lab/CTStests.py, cts/lab/patterns.py, daemons/controld/controld_fencing.c, daemons/execd/execd_commands.c, daemons/execd/pacemaker-execd.c, daemons/fenced/fenced_commands.c, daemons/fenced/fenced_remote.c, daemons/fenced/pacemaker-fenced.c, include/crm/fencing/internal.h, lib/fencing/st_client.c, lib/fencing/st_output.c, lib/pacemaker/pcmk_fence.c, tools/crm_mon_curses.c, tools/stonith_admin.c
This improves some log messages I had to look at far too much for the exit reasons project :)
=> Fencing log improvements

daemons/controld/controld_te_actions.c
Previously given a scenario:
- rscA failed to migrate from node1 to node2 with a failed migrate_to on
node1
- rscA failed to stop on node2
- node2 got fenced and rscA recovered on node1
- node2 rejoined
, rscA would be considered being "multiple-active" and an unnecessary
full recovery would be issued.
With this commit, when node2 gets fenced, a successful event for the
pseudo stop of rscA will be synthesized in resource history, so that
rscA won't be considered being active on node2 when node2 rejoins which
will prevent unnecessary stop or recovery of rscA.
=> Refactor: controller: functionalize record of synthesized action event

lib/common/options.c
Fix: nls: format of XML-escaped string
=> Fix: nls: format of XML-escaped string

cts/Makefile.am
should have been done with 5b6280ac1
=> Test: cts: install new cts-cli data files

daemons/attrd/attrd_commands.c
When an attrd instance broadcasts its protocol version to the rest of
the cluster, check and see if it's lower than the previous version.
And then, we can use that to clear failures faster if the cluster is
using at least protocol version 2.
=> Feature: daemons: Track the minimum attrd protocol version.

daemons/controld/controld_fencing.c, daemons/fenced/cts-fence-helper.c, daemons/fenced/fenced_commands.c, daemons/fenced/fenced_remote.c, daemons/fenced/pacemaker-fenced.c, daemons/fenced/pacemaker-fenced.h, include/crm/stonith-ng.h, lib/fencing/st_client.c
This is another follow-up for issues found during the internal failure message project, focusing on fencing notifications.
=> Improve fencing notifications

daemons/fenced/pacemaker-fenced.c
=> fenced: Don't ignore CIB updates if stonith-enabled=false

include/crm/common/Makefile.am, include/crm/common/acl_internal.h, include/crm/common/internal.h
=> Separate ACL-related declarations from internal.h to new acl_internal.h

lib/fencing/st_rhcs.c
Null-check result even if rc == 0.
=> Low: Always null-check result in stonith__rhcs_get_metadata

include/crm/pengine/internal.h, lib/pacemaker/libpacemaker_private.h, lib/pacemaker/pcmk_sched_actions.c, lib/pacemaker/pcmk_sched_clone.c, lib/pacemaker/pcmk_sched_native.c, lib/pacemaker/pcmk_sched_nodes.c, lib/pacemaker/pcmk_sched_promotable.c, lib/pacemaker/pcmk_sched_resource.c, lib/pacemaker/pcmk_sched_utilization.c, lib/pengine/clone.c, lib/pengine/utils.c, lib/pengine/variant.h
This continues bringing libpacemaker up to current development guidelines, focusing on some clone-related code
=> Best practices for some clone-related functions

include/crm/pengine/internal.h, include/pcmki/pcmki_sched_allocate.h, lib/pacemaker/libpacemaker_private.h, lib/pacemaker/pcmk_sched_clone.c, lib/pacemaker/pcmk_sched_promotable.c, lib/pengine/clone.c
This continues bringing pcmk_sched_promotable.c up to current development guidelines.
=> Continue best practices for promotable clone code

configure.ac
=> Build: configure: Use AS_IF and AS_CASE everywhere.

include/crm/pengine/internal.h, include/pcmki/pcmki_sched_allocate.h, lib/pacemaker/libpacemaker_private.h, lib/pacemaker/pcmk_sched_bundle.c, lib/pacemaker/pcmk_sched_clone.c, lib/pacemaker/pcmk_sched_ordering.c, lib/pacemaker/pcmk_sched_promotable.c, lib/pengine/clone.c
This finishes bringing pcmk_sched_promotable.c up to current development guidelines
=> Best practices for libpacemaker code related to promotable clones

doc/sphinx/Clusters_from_Scratch/active-active.rst, doc/sphinx/Clusters_from_Scratch/active-passive.rst, doc/sphinx/Clusters_from_Scratch/ap-configuration.rst, doc/sphinx/Clusters_from_Scratch/apache.rst, doc/sphinx/Clusters_from_Scratch/cluster-setup.rst, doc/sphinx/Clusters_from_Scratch/fencing.rst, doc/sphinx/Clusters_from_Scratch/index.rst, doc/sphinx/Clusters_from_Scratch/installation.rst, doc/sphinx/Clusters_from_Scratch/intro.rst, doc/sphinx/Clusters_from_Scratch/shared-storage.rst, doc/sphinx/Clusters_from_Scratch/verification.rst, doc/sphinx/conf.py.in, doc/sphinx/shared/pacemaker-intro.rst
These are a number of fixes and improvements that apply to both Centos 8 Stream and AlmaLinux 9, that I want to get in before we update for AL9 in #2786.
=> Doc: Clusters from Scratch: Various fixes, prep for update to AlmaLinux 9

lib/pengine/unpack.c
This block has been commented out since 2006.
=> Refactor: scheduler: Remove an unused block of code.

configure.ac, lib/pacemaker/libpacemaker_private.h, lib/pacemaker/pcmk_sched_colocation.c, lib/pacemaker/pcmk_sched_group.c, lib/pacemaker/pcmk_sched_location.c, lib/pacemaker/pcmk_sched_native.c, lib/pacemaker/pcmk_sched_ordering.c, lib/pacemaker/pcmk_sched_remote.c, lib/pacemaker/pcmk_sched_tickets.c, lib/pengine/bundle.c, lib/pengine/unpack.c
This takes care of a few suggestions from #2773 and continues removing the "lh/rh" terminology from other types of constraints
=> Follow-up to colocation PR

lib/pengine/pe_output.c
regression introduced in 2.1.0 by 5ef28b946
Fixes T533
=> Fix: tools: correct minimum execution status shown by crm_resource -O

doc/sphinx/Clusters_from_Scratch/active-passive.rst, doc/sphinx/Pacemaker_Remote/baremetal-tutorial.rst, doc/sphinx/Pacemaker_Remote/intro.rst, doc/sphinx/Pacemaker_Remote/kvm-tutorial.rst, doc/sphinx/Pacemaker_Remote/options.rst, doc/sphinx/conf.py.in
Closes [T492](https://projects.clusterlabs.org/T492).
I've got other minor fixes and improvements on the to-do list. This covers the meat of it.
=> Doc: Pacemaker Remote: Update for AlmaLinux 9, and assorted fixes

cts/cli/regression.tools.exp, cts/cts-cli.in
Closes [T494](https://projects.clusterlabs.org/T494).
=> Test: cts-cli: Add crm_attribute --promotion regression tests

daemons/controld/controld_control.c, daemons/fenced/fenced_commands.c, daemons/fenced/pacemaker-fenced.c, daemons/pacemakerd/pacemakerd.c, lib/fencing/st_actions.c
Mostly this is logging improvements I did while investigating T70 (which unfortunately couldn't be reproduced) along with some refactors and a couple of follow-ups to a previous PR.
=> Minor fencing improvements

cts/cts-regression.in
=> Test: cts: Reimplement cts-regression in Python

cts/cts-cli.in
Commit cb7f3207 caused a minor regression wherein cts/cli/crm_mon.xml
gets modified by the tools tests.
=> Test: cts-cli: Prevent modification of crm_mon.xml

configure.ac, lib/common/mock.c, lib/common/mock_private.h, lib/common/options.c, lib/common/tests/Makefile.am, lib/common/tests/options/Makefile.am, lib/common/tests/options/pcmk__env_option_enabled_test.c, lib/common/tests/options/pcmk__env_option_test.c, lib/common/tests/options/pcmk__set_env_option_test.c, mk/tap.mk
Closes [T493](lib/common/tests/options/Makefile.am).
=> Unit tests for some env option functions

configure.ac, daemons/controld/controld_throttle.c, include/crm/common/ipc_internal.h, include/portability.h, lib/common/io.c, lib/common/ipc_client.c, lib/common/iso8601.c, lib/common/nvpair.c, lib/common/operations.c, lib/common/output_text.c, lib/common/procfs.c, lib/common/tests/procfs/pcmk__procfs_has_pids_false_test.c, lib/common/tests/procfs/pcmk__procfs_has_pids_true_test.c, lib/common/tests/procfs/pcmk__procfs_pid2path_test.c, lib/common/watchdog.c, lib/services/services.c, lib/services/services_private.h
=> Build: Name "HAVE"-style constants consistently

daemons/based/based_remote.c, daemons/execd/execd_commands.c, daemons/execd/remoted_tls.c, include/crm/common/ipc_internal.h
=> Refactor: libcrmcommon: Convert pcmk__remote_s bool and authenticated to pcmk__client_flags

configure.ac, include/crm/common/xml_internal.h, lib/common/tests/Makefile.am, lib/common/tests/xml/Makefile.am, lib/common/tests/xml/pcmk__xe_foreach_child_test.c, lib/common/xml.c, tools/crm_attribute.c, tools/crm_mon.c, tools/crm_resource_print.c
This is just a start - there's a ton of places these kinds of loops occur, so I want to get the foundation right before starting in on converting all of them.
=> Add new XML iterator functions

include/crm/pengine/complex.h, include/crm/pengine/internal.h, include/crm/pengine/rules.h, include/crm/pengine/status.h, include/pcmki/pcmki_transition.h, lib/pacemaker/pcmk_graph_consumer.c, lib/pengine/complex.c, lib/pengine/rules.c, lib/pengine/utils.c
This is not comprehensive but focuses on functions that will be needed for similar changes in daemons
=> Make some function arguments const in libpacemaker and libpe_status

cts/cli/regression.rules.exp, cts/cts-cli.in, include/crm/common/results.h, include/pacemaker-internal.h, include/pacemaker.h, include/pcmki/Makefile.am, include/pcmki/pcmki_cluster_queries.h, include/pcmki/pcmki_rule.h, lib/common/results.c, lib/pacemaker/Makefile.am, lib/pacemaker/pcmk_output.c, lib/pacemaker/pcmk_rule.c, tools/Makefile.am, tools/crm_rule.c
=> API: libpacemaker: Move crm_rule functionality to libpacemaker

include/crm/common/results.h, include/crm/common/results_internal.h, lib/common/results.c, lib/common/strings.c, tools/crm_error.c
In preparation for #2847 to use formatted output in crm_error and move to libpacemaker
=> libcrmcommon, tools: Various refactors and improvements

daemons/attrd/attrd_attributes.c, daemons/attrd/attrd_corosync.c, daemons/attrd/attrd_ipc.c, daemons/attrd/pacemaker-attrd.h, daemons/execd/execd_commands.c, daemons/execd/pacemaker-execd.c, daemons/execd/remoted_proxy.c, daemons/execd/remoted_tls.c, lib/common/ipc_server.c
This takes care of pacemaker-attrd and pacemaker-execd
=> Clarify pointer arguments in more daemons

cts/cli/regression.error_codes.exp, cts/cts-cli.in, include/crm/crm.h, include/pacemaker-internal.h, include/pacemaker.h, include/pcmki/Makefile.am, include/pcmki/pcmki_result_code.h, lib/pacemaker/Makefile.am, lib/pacemaker/pcmk_output.c, lib/pacemaker/pcmk_result_code.c, tools/Makefile.am, tools/crm_error.c, xml/Makefile.am, xml/api/crm_error-2.23.rng
Closes [T95](https://projects.clusterlabs.org/T95) and [T97](https://projects.clusterlabs.org/T97)
=> API: libpacemaker: Move crm_error functionality to libpacemaker

daemons/controld/controld_execd.c, daemons/controld/controld_execd_state.c, daemons/controld/controld_fencing.c, daemons/controld/controld_join_client.c, daemons/controld/controld_lrm.h, daemons/controld/controld_messages.c, daemons/controld/controld_messages.h, daemons/controld/controld_metadata.c, daemons/controld/controld_metadata.h, daemons/controld/controld_remote_ra.c, daemons/controld/controld_schedulerd.c, daemons/controld/controld_te_actions.c, daemons/controld/controld_te_callbacks.c, daemons/controld/controld_te_events.c, daemons/controld/controld_te_utils.c, daemons/controld/controld_throttle.c, daemons/controld/controld_transition.h
This finishes updating doxygen blocks in the daemons to use in,out properly
=> Clarify pointer arguments in controller

daemons/controld/controld_te_utils.c, include/crm/common/xml.h, include/crm/common/xml_compat.h, include/crm/common/xml_internal.h, lib/common/acl.c, lib/common/crmcommon_private.h, lib/common/digest.c, lib/common/patchset.c, lib/common/xml.c, lib/common/xpath.c
I'm scrapping #2126 and starting fresh. Normally that's not advisable, but it's easier than reconciling two years worth of merge conflicts during the rebase. Plus I generally understand the code better this time around.
=> Use GString in XML code

cts/cts-fencing.in, daemons/execd/execd_commands.c, include/crm/lrmd.h, include/crm/pengine/internal.h, include/crm/pengine/status.h, include/crm/services.h, include/crm/services_compat.h, include/crm/services_internal.h
This finishes updating doxygen blocks for [in,out] under include/crm
=> Clarify pointer arguments in headers

daemons/fenced/pacemaker-fenced.c, po/zh_CN.po
Supplement the translation of fenced file.
=> add zh_CN translations for fenced file

daemons/fenced/fenced_remote.c
Hi Ken,
Hi All,
Even if I set pcmk_host_list and topology of fence_scsi like below, I should be able to configure cluster, but unfencing timeout occurs and cluster cannot be configured.
```
(snip)
<primitive class="stonith" id="fence1-scsi" type="fence_scsi">
<instance_attributes id="fence1-scsi-instance_attributes">
<nvpair id="fence1-scsi-instance_attributes-devices" name="devices" value="/dev/sdb"/>
<nvpair id="fence1-scsi-instance_attributes-pcmk_host_list" name="pcmk_host_list" value="rh85-01sc rh85-02sc rh85-03sc"/>
<nvpair id="fence1-scsi-instance_attributes-pcmk_off_timeout" name="pcmk_off_timeout" value="46"/>
<nvpair id="fence1-scsi-instance_attributes-pcmk_on_timeout" name="pcmk_on_timeout" value="46"/>
<nvpair id="fence1-scsi-instance_attributes-pcmk_reboot_action" …
```
=> Mid: fenced: Add automatic_list devices to unfencing timeout when topology is presents.

.gitignore, GNUmakefile, configure.ac, cts/scheduler/xml/migration-ping-pong.xml, cts/scheduler/xml/probe-2.xml, daemons/execd/cts-exec-helper.c, daemons/execd/remoted_pidone.c, devel/Makefile.am, lib/common/iso8601.c, lib/common/tests/Makefile.am, lib/common/tests/procfs/pcmk__procfs_has_pids_false_test.c, lib/common/tests/procfs/pcmk__procfs_has_pids_true_test.c, lib/common/tests/procfs/pcmk__procfs_pid2path_test.c, lib/pacemaker/pcmk_sched_ordering.c, xml/README.md
mostly stuff from running static analysis
=> Cleanup ahead of 2.1.5-rc1 release

daemons/attrd/Makefile.am, daemons/attrd/attrd_corosync.c, daemons/attrd/attrd_ipc.c, daemons/attrd/attrd_messages.c, daemons/attrd/attrd_sync.c, daemons/attrd/attrd_utils.c, daemons/attrd/pacemaker-attrd.c, daemons/attrd/pacemaker-attrd.h, include/crm/common/attrd_internal.h, include/crm/common/options_internal.h, include/crm/crm.h, include/crm_internal.h, lib/common/ipc_attrd.c, lib/common/tests/xml/Makefile.am, lib/common/tests/xml/pcmk__xe_match_test.c, lib/common/xml.c, tools/attrd_updater.c
=> Add support for attrd local sync points

cts/cli/constraints.xml, cts/cli/regression.tools.exp, cts/cts-cli.in, lib/pacemaker/pcmk_output.c, tools/crm_resource.c
I did this to help investigate issues with the scheduler colocation code, but the rest of that project is not ready, so I figured I'd get this out in time for rc2. Normally I wouldn't put features in rc2, but this change has very limited scope and is well regression-tested, and if the rest of the project makes a later release candidate, this will be useful for testing it.
=> Improve crm_resource --constraints

xml/api/crm_mon-2.28.rng, xml/api/crm_resource-2.28.rng, xml/api/crm_simulate-2.28.rng, xml/api/nodes-2.28.rng
Introduced by 3e330720, due to a mistake in a rebase.
=> Low: schemas: Fix schema regression just introduced

doc/sphinx/Pacemaker_Explained/advanced-resources.rst, doc/sphinx/Pacemaker_Explained/resources.rst
=> Low: Document resource, bundle, clone, and group descriptions

lib/common/ipc_client.c
When a controller is elected DC, it initiates a scheduler IPC connection (`new_schedulerd_ipc_connection()`). If the connection is interrupted by a signal (generally `SIGTERM` for cluster shutdown), it logs "Error connecting to the scheduler: Resource temporarily unavailable" and "Cannot shut down gracefully without the scheduler" and terminates quickly.
If the connection error code is `EAGAIN`, we should try again before giving up, so that we have a chance of shutting down gracefully in this situation.
This commit adds a retry to `pcmk_connect_ipc()`, to proactively avoid similar timing issues that other callers may face. If this turns out to be problematic (for example, if each connection attempt takes a while in some situation and this doubles the time it takes to give up), then we can …
=> Fix: libcrmcommon: Retry pcmk_connect_ipc() if EAGAIN

lib/pengine/common.c, po/zh_CN.po
=> add zh_CN translation

tools/Makefile.am, tools/crm_shadow.8.inc, tools/crm_shadow.c
Also moved `edit` into commands. It isn't really a query. The only thing it has in common with the queries is that it grabs the shadow from the environment.
Closes T98
=> Refactor: tools: Use GOption in crm_shadow.c

maint/Makefile.am, mk/release.mk, rpm/Makefile.am
This will save a little editing in the release process
=> Improve changelog make targets

daemons/based/pacemaker-based.c, daemons/based/pacemaker-based.h, daemons/controld/pacemaker-controld.c, daemons/execd/Makefile.am, daemons/execd/pacemaker-execd.c, daemons/execd/pacemaker-remoted.8.inc, include/crm/crm.h
Closes T104, T105, T106. I would've hit the fencer but there was no task for it and I thought it was done :) Will get that soon.
The (current) first two commits are from approved PR #2942. They're here so that I can update the `CRM_FEATURE_SET` to a higher value in the `pcmk__output_t` commits.
=> Use GOption and formatted output in controller, CIB manager, executor

cts/cts-cli.in, daemons/attrd/attrd_attributes.c, lib/pacemaker/pcmk_sched_migration.c, lib/pengine/pe_notif.c
I wish these had turned up somewhere else earlier, but no.  Also note that the third patch ends up changing cts-cli output, even though I thought it was really just going to make static analysis happy and nothing else.
=> Problems found by covscan

daemons/attrd/attrd_ipc.c
Supporting cluster-wide sync points means attrd_expect_confirmations needs to be called, and then attrd_send_message needs "true" as a third argument.  This indicates attrd wants confirmations back from all its peers when they have applied the update.
We're already doing this at the end of attrd_client_update for single-update IPC messages, and handling it for multi-update messages is a simple matter of breaking that code out into a function and making sure it's called.
Note that this leaves two other spots where sync points still need to be dealt with:
* An update message that uses a regex.  See https://projects.clusterlabs.org/T600 for details.
* A multi-update IPC message in a cluster where that is not supported. See https://projects.clusterlabs.org/T601 for details.
=> Low: daemons: Support cluster-wide sync points for multi IPC messages.

po/zh_CN.po, tools/crm_resource.c
translation   tools/crm_resource.c file error message
=> add zh_cn translation for error

cts/cli/regression.tools.exp, include/pcmki/pcmki_acl.h, lib/common/acl.c, lib/pacemaker/pcmk_acl.c, tools/Makefile.am, tools/cibadmin.8.inc, tools/cibadmin.c
=> Refactor: tools: Use GOption in cibadmin

daemons/based/based_remote.c, daemons/controld/controld_execd.c, daemons/controld/controld_join_dc.c, lib/common/output.c
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>
=> Build: fix build with clang compiler

daemons/controld/controld_execd.c
Currently, `daemons/controld/controld_execd.c:force_reprobe()` reprobes all remote nodes that were ever probed on the reprobed cluster node (that is, all remote nodes that are in the cluster node's lrm state table). This was originally intended for cleanup all (see 077cde20), but it also happens when reprobing a single cluster node.
To fix this, we start by determining whether the operation is targeting all nodes (indicated by XML_LRM_ATTR_TARGET == NULL). Then we pass the result as a boolean to handle_reprobe_op() and on to force_reprobe(). In force_reprobe(), if we find a remote connection resource in the history, we reprobe the corresponding remote node only if we're targeting all nodes.
Closes T219
=> Fix: controller: Don't reprobe remotes when target is only a cluster node

daemons/attrd/attrd_corosync.c, daemons/attrd/pacemaker-attrd.c, daemons/based/based_callbacks.c, daemons/based/pacemaker-based.c, daemons/based/pacemaker-based.h, daemons/controld/controld_control.c, daemons/controld/pacemaker-controld.c, daemons/execd/pacemaker-execd.c, daemons/fenced/pacemaker-fenced.c, daemons/pacemakerd/pacemakerd.c, daemons/schedulerd/pacemaker-schedulerd.c, include/crm/cluster.h, include/crm/crm.h, lib/cluster/cluster.c, tools/attrd_updater.c, tools/crm_attribute.c, tools/crm_error.c, tools/crm_resource.c, tools/crm_rule.c, tools/crm_simulate.c, tools/crm_verify.c, tools/crmadmin.c, tools/stonith_admin.c
=> Use GOption and formatted output in pacemaker-fenced.c

configure.ac, include/crm/common/internal.h, include/crm/pengine/pe_types.h, lib/common/cmdline.c, lib/common/nvpair.c, lib/common/options.c, lib/common/strings.c, lib/pacemaker/pcmk_sched_location.c, lib/pengine/failcounts.c, lib/pengine/pe_output.c, lib/pengine/unpack.c, lib/pengine/utils.c, tools/crmadmin.c
A few minor fixes I've been saving up
=> Miscellaneous small fixes

doc/sphinx/Pacemaker_Development/c.rst, include/crm/pengine/internal.h, lib/pacemaker/libpacemaker_private.h, lib/pacemaker/pcmk_sched_actions.c, lib/pacemaker/pcmk_sched_allocate.c, lib/pacemaker/pcmk_sched_bundle.c, lib/pacemaker/pcmk_sched_recurring.c, lib/pacemaker/pcmk_sched_resource.c, lib/pengine/bundle.c, lib/pengine/failcounts.c, lib/pengine/pe_actions.c, lib/pengine/pe_digest.c, lib/pengine/pe_output.c, lib/pengine/pe_status_private.h, lib/pengine/remote.c, lib/pengine/unpack.c, lib/pengine/utils.c
This is not comprehensive but makes the next batch of changes easier
=> Drop some unnecessary function arguments in libpe_status

include/crm/pengine/common.h, include/crm/pengine/internal.h, include/crm/pengine/pe_types.h, include/crm/pengine/status.h, lib/common/strings.c, lib/pacemaker/pcmk_sched_colocation.c, lib/pacemaker/pcmk_sched_ordering.c, lib/pacemaker/pcmk_sched_tickets.c, lib/pengine/bundle.c, lib/pengine/clone.c, lib/pengine/complex.c, lib/pengine/group.c, lib/pengine/native.c, lib/pengine/pe_output.c, lib/pengine/unpack.c, lib/pengine/utils.c
Functions with doxygen blocks were previously done. This handles some more that will make it easier to clarify arguments in libpacemaker.
=> Clarify more pointer arguments in libpe_status

tools/attrd_updater.c, tools/crm_resource.h, tools/crm_resource_print.c, tools/crm_resource_runtime.c
This wraps up the project to clarify pointer arguments in functions that have doxygen blocks. This one handles tools.
=> Finish clarifying pointer arguments

lib/pengine/common.c, po/zh_CN.po
Add chinese translation https://github.com/ClusterLabs/pacemaker/pull/2980
=> Doc: scheduler: update Chinese translation

include/pcmki/pcmki_sched_utils.h, lib/pacemaker/libpacemaker_private.h, lib/pacemaker/pcmk_sched_bundle.c, lib/pacemaker/pcmk_sched_clone.c, lib/pacemaker/pcmk_sched_instances.c, lib/pacemaker/pcmk_sched_probes.c, lib/pacemaker/pcmk_sched_promotable.c
This continues (but does not finish) work on pcmk_sched_instances.c
=> Continue bringing libpacemaker up to current guidelines

lib/pengine/unpack.c
This is a bit of refactoring I did to make investigating an unrelated regression easier.
=> Improve unpacking of migrate_to success

.gitignore, configure.ac, cts/Makefile.am, cts/cts-attrd.in, cts/cts-exec.in, cts/cts-fencing.in, cts/cts-regression.in, daemons/attrd/attrd_cib.c, daemons/attrd/attrd_corosync.c, daemons/attrd/attrd_sync.c, daemons/attrd/pacemaker-attrd.c, daemons/attrd/pacemaker-attrd.h, daemons/fenced/pacemaker-fenced.c, include/crm/common/logging_internal.h, lib/common/logging.c, python/pacemaker/_cts/Makefile.am, python/pacemaker/_cts/corosync.py, python/pacemaker/_cts/test.py
While I work on the actual tests, the rest of this stuff can be reviewed.  There was surprisingly little work to be done to attrd itself.  Most of this is actually just more refactoring in CTS as I wrote cts-attrd and found more things that could be combined.
=> Add cts-attrd

cts/cli/regression.tools.exp, cts/cts-cli.in, cts/scheduler/summary/bundle-order-partial-start-2.summary, tools/crm_resource.c, tools/crm_resource_print.c
Here is an example of --get-parameter being used with --element:
```
[root@pcmk-1 ~]# crm_resource -r myping --get-parameter description --element
test_description
```
=> Feature: crm_resource: Add the --element option for --get-parameter

cts/cli/regression.crm_mon.exp, cts/scheduler/xml/rec-rsc-9.xml, include/crm/pengine/internal.h, lib/pengine/pe_output.c, lib/pengine/unpack.c, lib/pengine/utils.c, tools/crm_mon.c
This is prep work for investigating a regression. The unpacking code is rather difficult to follow, and this hopefully helps a little. Much more could be done, but this is already a big sidetrack.
=> Improve resource action history unpacking code

daemons/controld/Makefile.am, daemons/controld/controld_callbacks.c, daemons/controld/controld_callbacks.h, daemons/controld/controld_cib.c, daemons/controld/controld_cib.h, daemons/controld/controld_control.c, daemons/controld/controld_election.c, daemons/controld/controld_fencing.c, daemons/controld/controld_fsa.h, daemons/controld/controld_globals.h, daemons/controld/controld_join_client.c, daemons/controld/controld_join_dc.c, daemons/controld/controld_membership.c, daemons/controld/controld_messages.h, daemons/controld/controld_remote_ra.c, daemons/controld/controld_schedulerd.c, daemons/controld/controld_te_actions.c, daemons/controld/controld_utils.c, daemons/controld/controld_utils.h, daemons/controld/pacemaker-controld.h
This was helpful while investigating an unrelated regression
=> Clean up controller CIB functions a bit

cts/cts-cli.in, cts/cts-regression.in
Regression in 2.1.5 introduced by d3a20880d.
=> Test: cts-regression: reflect any test failures again with the return code

cts/cli/regression.acls.exp, cts/cli/regression.feature_set.exp, cts/cli/regression.rules.exp, cts/cli/regression.tools.exp, cts/cli/regression.upgrade.exp, cts/cli/regression.validity.exp, cts/cts-cli.in, lib/cib/cib_client.c, tools/crm_shadow.c
These are a few minor changes that came up while I was working on adding `pcmk__output_t` support to `crm_shadow`. I probably won't have that change finished in time for review this afternoon, so I'm going ahead and pushing these.
=> A few more crm_shadow cleanups

tools/crm_resource.c
As of 652c2344, --element is also supported with -p and -d.
=> Doc: tools: Fix --element description in crm_resource

cts/scheduler/xml/promoted-role.xml, daemons/based/based_callbacks.c, daemons/based/based_messages.c, daemons/based/pacemaker-based.c, daemons/based/pacemaker-based.h, daemons/controld/controld_control.c, daemons/controld/controld_te_callbacks.c, daemons/fenced/pacemaker-fenced.c, daemons/pacemakerd/pcmkd_subdaemons.c, doc/sphinx/Pacemaker_Development/components.rst, include/crm/cib/cib_types.h, include/crm/cib/internal.h, include/crm/common/xml.h, include/crm/common/xml_compat.h, lib/cib/cib_client.c, lib/cib/cib_file.c, lib/cib/cib_native.c, lib/cib/cib_ops.c, lib/cib/cib_remote.c, lib/cib/cib_utils.c, lib/cluster/cluster.c, lib/common/xml.c
These are some minor changes that I made while investigating T375 and playing with the possibility of local CIB locking. Getting rid of some clutter made me feel better while I beat my head against a wall.
I'm not tied to the static ones, since they move a bunch of code around for no real benefit. I prefer single-file functions to be static, and I feel like forward declarations look like clutter unless two functions recursively call each other or something.
=> Various minor improvements

include/crm/pengine/internal.h, lib/common/scores.c, lib/pacemaker/pcmk_sched_actions.c, lib/pacemaker/pcmk_sched_colocation.c, lib/pacemaker/pcmk_sched_instances.c, lib/pacemaker/pcmk_sched_location.c, lib/pacemaker/pcmk_sched_ordering.c, lib/pacemaker/pcmk_sched_promotable.c, lib/pengine/clone.c, lib/pengine/complex.c, lib/pengine/failcounts.c, lib/pengine/pe_health.c, lib/pengine/pe_notif.c, lib/pengine/pe_status_private.h, lib/pengine/utils.c
This is a collection of unrelated minor issues I stumbled across while working on other projects
=> Minor scheduler improvements

lib/pacemaker/libpacemaker_private.h, lib/pacemaker/pcmk_sched_clone.c, lib/pacemaker/pcmk_sched_colocation.c, lib/pacemaker/pcmk_sched_group.c, lib/pacemaker/pcmk_sched_instances.c, lib/pacemaker/pcmk_sched_primitive.c, lib/pacemaker/pcmk_sched_promotable.c, lib/pacemaker/pcmk_sched_resource.c
With the recent colocation code changes, a couple areas of code can be cleaned up better
=> Minor scheduler clean-up

daemons/controld/controld_execd_state.c
The issue was reported by an user with pacemaker-2.0.5. Pacemaker-controld encountered segfault during shutdown:
Core was generated by `/usr/lib/pacemaker/pacemaker-controld'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f78f1df09d3 in xmlCheckUTF8__internal_alias (utf=utf@entry=0x616d726f666e6920 <error: Cannot access memory at address 0x616d726f666e6920>) at xmlstring.c:796
796         for (ix = 0; (c = utf[ix]);) {      /* string is 0-terminated */ #0  0x00007f78f1df09d3 in xmlCheckUTF8__internal_alias (utf=utf@entry=0x616d726f666e6920 <error: Cannot access memory at address 0x616d726f666e6920>) at xmlstring.c:796
#1  0x00007f78f1d99e49 in xmlNewPropInternal (node=node@entry=0x55c58a0a4b20, ns=ns@entry=0x0, name=name@entry=0x7f78f34e3a27 "lrmd_ipc_session", …
=> Fix: controller: avoid use-after-free when disconnecting proxy IPCs during shutdown

daemons/pacemakerd/pacemakerd.c
Previously, `pacemakerd -S` would request a shutdown and then sit in a loop for 30 minutes, waiting for the IPC connection to drop.  Only then would it return to the command line.  This gave the user a way of knowing the shutdown completed.
There are potentially various ways of solving this problem.  However, a shutdown works by adding an event to the main loop which makes it difficult to know exactly when it happens.  So, just go with the easiest fix and re-implement the loop checking the IPC connection status.
Regression in 2.1.1 introduced by 64d4f9b5f
=> Low: daemons: pacemakerd -S should wait for shutdown before returning

cts/lab/CTSlab.py.in, cts/lab/CTStests.py, python/pacemaker/_cts/CTS.py, python/pacemaker/_cts/environment.py
Just a quick little improvement that came up while I was working on something else.
=> Support the python membership protocol in cts

include/crm/common/xml_internal.h, lib/common/Makefile.am, lib/common/crmcommon_private.h, lib/common/patchset.c, lib/common/xml.c, lib/common/xml_attr.c, lib/common/xml_display.c, lib/pengine/complex.c, lib/pengine/pe_actions.c, lib/pengine/unpack.c
- improve efficiency by swapping crm_element_value() with pcmk__xml_attr_value() where possible
- seaparate functions that operate on xmlAttr ino xml_attr.c
closes T583
=> low: xml: XML attribute improvements

python/pacemaker/_cts/audits.py, python/pacemaker/_cts/logging.py, python/pacemaker/_cts/process.py, python/pacemaker/_cts/remote.py, python/pacemaker/_cts/test.py, python/pacemaker/_cts/watcher.py
I don't know that I actually like the results, and I'd like to know what other people think.  Inline comments below.
=> RFC: Reformat python code with black

devel/Makefile.am, doc/sphinx/Pacemaker_Development/helpers.rst, include/crm/common/unittest_internal.h, lib/common/tests/agents/crm_parse_agent_spec_test.c, lib/common/tests/cmdline/Makefile.am, lib/common/tests/cmdline/pcmk__cmdline_preproc_test.c, lib/common/tests/cmdline/pcmk__new_common_args_test.c, lib/common/tests/scores/pcmk__add_scores_test.c, lib/common/tests/strings/Makefile.am, lib/common/tests/strings/pcmk__guint_from_hash_test.c, lib/common/tests/strings/pcmk__scan_ll_test.c, lib/common/tests/utils/Makefile.am, lib/common/tests/utils/pcmk__fail_attr_name_test.c, lib/common/tests/utils/pcmk__failcount_name_test.c, lib/common/tests/utils/pcmk__lastfailure_name_test.c
Here's a couple really lame unit tests, a new pcmk__assert_ macro, and some additional test-related makefile crud.
=> Unit test related stuff

cts/cli/regression.tools.exp, include/crm/pengine/internal.h, include/pcmki/pcmki_scheduler.h, lib/pacemaker/libpacemaker_private.h, lib/pacemaker/pcmk_sched_bundle.c, lib/pacemaker/pcmk_sched_clone.c, lib/pacemaker/pcmk_sched_colocation.c, lib/pacemaker/pcmk_sched_group.c, lib/pacemaker/pcmk_sched_instances.c, lib/pacemaker/pcmk_sched_primitive.c, lib/pacemaker/pcmk_sched_resource.c, lib/pengine/bundle.c
If I don't get any farther on [T672](https://projects.clusterlabs.org/T672) tonight, at least we have these.
I propose we drop support for colocations. Just let resources run wherever they want relative to other resources, who cares anymore.
=> Minor libpacemaker and libpe_status improvements

cts/scheduler/scores/asymmetric.scores, doc/sphinx/Pacemaker_Explained/constraints.rst, include/crm/pengine/internal.h, lib/pacemaker/libpacemaker_private.h, lib/pacemaker/pcmk_sched_bundle.c, lib/pacemaker/pcmk_sched_clone.c, lib/pacemaker/pcmk_sched_colocation.c, lib/pacemaker/pcmk_sched_fencing.c, lib/pacemaker/pcmk_sched_instances.c, lib/pacemaker/pcmk_sched_location.c, lib/pacemaker/pcmk_sched_nodes.c, lib/pacemaker/pcmk_sched_promotable.c, lib/pacemaker/pcmk_scheduler.c, lib/pengine/utils.c
A few that I did along the way of #3137
=> Minor libpacemaker improvements

daemons/attrd/pacemaker-attrd.c, daemons/based/pacemaker-based.c, daemons/controld/controld_schedulerd.c, daemons/controld/pacemaker-controld.c, daemons/fenced/pacemaker-fenced.c, daemons/pacemakerd/pacemakerd.c, include/crm/common/ipc_internal.h, lib/cib/cib_native.c, lib/common/crmcommon_private.h, lib/common/ipc_attrd.c, lib/common/ipc_client.c, lib/common/mainloop.c, lib/fencing/st_client.c, lib/lrmd/lrmd_client.c, lib/pacemaker/pcmk_cluster_queries.c, tools/attrd_updater.c, tools/crm_node.c, tools/crm_resource.c
This started as "I'll just improve this one log message"
=> Improve IPC connection handing

cts/lab/CM_corosync.py, cts/lab/Makefile.am, python/pacemaker/_cts/Makefile.am, python/pacemaker/_cts/audits.py, python/pacemaker/_cts/cib.py, python/pacemaker/_cts/clustermanager.py, python/pacemaker/_cts/scenarios.py, python/pacemaker/_cts/tests/componentfail.py, python/pacemaker/_cts/tests/fliptest.py, python/pacemaker/_cts/tests/maintenancemode.py, python/pacemaker/_cts/tests/nearquorumpointtest.py, python/pacemaker/_cts/tests/partialstart.py, python/pacemaker/_cts/tests/resourcerecover.py, python/pacemaker/_cts/tests/restarttest.py, python/pacemaker/_cts/tests/simulstartlite.py, python/pacemaker/_cts/tests/simulstoplite.py, python/pacemaker/_cts/tests/standbytest.py, python/pacemaker/_cts/tests/starttest.py, python/pacemaker/_cts/tests/stonithdtest.py, python/pacemaker/_cts/tests/stoptest.py
This ended up being larger than I expected, but we're almost done.  Lots of dead code in here.
=> Move ClusterManager into the _cts module

lib/pengine/pe_output.c
=> Fix: tools: Fix a bug in clone resource description display

cts/cts-attrd.in
From a quick revert & test, it looks like this would have caught the regression.
=> Add a test case for the recent attrd_updater regression

daemons/attrd/attrd_messages.c
This only affects sync points on IPC messages containing multiple update messages, and only when those messages are received by an attrd that does not support multiple update messages.  Hopefully, this is a pretty small number of installations.
In these cases, right now we act like sync points are supported but they are not.  For local sync points, what happens is we iterate over each individual update message.  Each update message will have a sync point attribute, and the server will send the ACK for each as it processes the message.  However, the client is only going to wait for the first ACK before continuing.  For all the other ACKs, there will not be a client listening.
Cluster-wide sync points likely work the same way, though I have not tested it to be sure.  I don't see how they …
=> Disable sync points in certain circumstances.

include/crm/common/resources.h, include/crm/pengine/common.h, lib/pacemaker/pcmk_sched_fencing.c, lib/pengine/pe_actions.c
This is part of a project to consolidate libpe_rules/libpe_status into libcrmcommon, updating code to current guidelines as we go
=> Move rsc_start_requirement to libcrmcommon

configure.ac, doc/sphinx/Makefile.am, include/Makefile.am, lib/common/mock.c, lib/common/mock_private.h, lib/common/tests/output/pcmk__output_new_test.c, maint/Makefile.am, mk/release.mk, mk/tap.mk, rpm/Makefile.am
... along with a major cleanup of configure.ac
=> T694: Fix unit test on 32-bit systems with 64-bit file sizes

agents/ocf/HealthCPU.in
Modify the validation function to ensure that it meets the set input parameter rules
=> fix the validation function of input

agents/ocf/ping.in, daemons/attrd/attrd_cib.c, daemons/attrd/attrd_corosync.c, daemons/attrd/attrd_elections.c, daemons/attrd/attrd_ipc.c, daemons/attrd/attrd_utils.c, daemons/attrd/pacemaker-attrd.h, daemons/based/based_callbacks.c, daemons/controld/controld_cib.c, daemons/controld/controld_corosync.c, daemons/controld/controld_execd.c, daemons/controld/controld_fencing.c, daemons/controld/controld_schedulerd.c, daemons/fenced/fenced_remote.c, daemons/fenced/pacemaker-fenced.h, doc/sphinx/Pacemaker_Explained/reusing-configuration.rst, lib/common/ipc_client.c, lib/lrmd/lrmd_client.c
... along with a few unrelated minor changes that I've been saving up
=> Complete fix for T138

daemons/controld/controld_control.c, daemons/controld/controld_fencing.c, daemons/controld/controld_fencing.h
=> Refactor: fencer: sleep 1s between reconnects

tools/crm_resource_runtime.c
=> Refactor: crm_resource: report error when trying to restart unmanaged resources

daemons/based/based_callbacks.c, daemons/controld/controld_te_callbacks.c, daemons/fenced/pacemaker-fenced.c, include/crm/common/logging_internal.h, include/crm/msg_xml.h, lib/cib/cib_file.c, lib/cib/cib_ops.c, lib/cib/cib_utils.c, lib/common/logging.c, lib/common/patchset.c, lib/common/patchset_display.c, tools/crm_diff.c, tools/crm_mon.c, tools/crm_shadow.c
Commits from #3200 that apply easily to main without compatibility issues
=> Minor XML cleanups

doc/sphinx/Pacemaker_Development/c.rst, lib/pacemaker/pcmk_graph_producer.c, lib/pacemaker/pcmk_sched_actions.c, lib/pacemaker/pcmk_sched_ordering.c, rpm/pacemaker.spec.in
... with a couple of other small changes
=> Fix clang build

tools/crm_resource.c, tools/crm_resource.h, tools/crm_resource_ban.c, tools/crm_resource_runtime.c
=> Refactor: crm_resource: move/ban fall back to old Promoted equivalent

cts/cli/regression.tools.exp, daemons/based/based_callbacks.c, include/crm/crm.h
=> Low: based: Make CIB transactions backward compatible

daemons/based/based_io.c, daemons/controld/controld_cib.c, daemons/controld/controld_throttle.c, daemons/execd/pacemaker-execd.c, daemons/execd/remoted_pidone.c, daemons/execd/remoted_tls.c, daemons/pacemakerd/pacemakerd.c, daemons/pacemakerd/pacemakerd.h, daemons/pacemakerd/pcmkd_corosync.c, daemons/pacemakerd/pcmkd_messages.c, daemons/pacemakerd/pcmkd_subdaemons.c, include/crm/common/options_internal.h, lib/common/ipc_common.c, lib/common/logging.c, lib/common/mainloop.c, lib/common/options.c, lib/common/remote.c, lib/common/tests/options/pcmk__set_env_option_test.c, lib/common/watchdog.c, lib/common/xml.c, lib/lrmd/lrmd_client.c, lib/pengine/bundle.c, tools/crm_resource_runtime.c
=> Environment variable improvements

python/pacemaker/_cts/CTS.py, python/pacemaker/_cts/audits.py, python/pacemaker/_cts/cib.py, python/pacemaker/_cts/cibxml.py, python/pacemaker/_cts/clustermanager.py, python/pacemaker/_cts/cmcorosync.py, python/pacemaker/_cts/environment.py, python/pacemaker/_cts/remote.py, python/pacemaker/_cts/scenarios.py, python/pacemaker/_cts/test.py, python/pacemaker/_cts/tests/__init__.py, python/pacemaker/_cts/tests/componentfail.py, python/pacemaker/_cts/tests/ctstest.py, python/pacemaker/_cts/tests/maintenancemode.py, python/pacemaker/_cts/tests/nearquorumpointtest.py, python/pacemaker/_cts/tests/partialstart.py, python/pacemaker/_cts/tests/reattach.py, python/pacemaker/_cts/tests/remotedriver.py, python/pacemaker/_cts/tests/remoterscfailure.py, python/pacemaker/_cts/tests/remotestonithd.py, python/pacemaker/_cts/tests/resourcerecover.py, python/pacemaker/_cts/tests/resynccib.py, python/pacemaker/_cts/tests/simulstartlite.py, python/pacemaker/_cts/tests/simulstoplite.py, python/pacemaker/_cts/tests/splitbraintest.py, python/pacemaker/_cts/tests/standbytest.py, python/pacemaker/_cts/tests/starttest.py, python/pacemaker/_cts/tests/stonithdtest.py, python/pacemaker/_cts/tests/stoptest.py, python/pacemaker/_cts/watcher.py
=> Avoid false positives in CTS lab's Reattach test

tools/crm_resource_runtime.c
=> Refactor: crm_resource: make --wait wait for pending actions in CIB

cts/cli/crm_verify_invalid_bz.xml, cts/cli/crm_verify_invalid_no_stonith.xml, cts/cli/regression.tools.exp, cts/cts-cli.in, include/crm/common/logging_internal.h, include/crm/common/xml_internal.h, lib/common/logging.c, lib/common/schemas.c, tools/crm_verify.c
=> Add crm_verify detailed messages to formatted output

include/crm/common/xml_internal.h, lib/common/schemas.c
Along the way, clean up and simplify a bunch of things.  This is in preparation for #3218.
=> Convert known_schemas to a GList

doc/sphinx/Clusters_from_Scratch/apache.rst
Reported by Holger Schroeder in
https://lists.clusterlabs.org/pipermail/users/2023-November/031349.html.
=> Doc: Clusters from Scratch: Fix location constraint typo

include/crm/pengine/internal.h, lib/pacemaker/pcmk_sched_constraints.c, lib/pacemaker/pcmk_sched_location.c, lib/pacemaker/pcmk_sched_primitive.c, lib/pengine/unpack.c, lib/pengine/utils.c
=> Update scheduler recheck time for node-pending-timeout

.gitignore, configure.ac, daemons/based/based_messages.c, daemons/based/based_operation.c, daemons/based/pacemaker-based.h, daemons/execd/Makefile.am, daemons/execd/execd_commands.c, daemons/execd/pacemaker-execd.h, daemons/execd/remoted_schemas.c, daemons/execd/remoted_tls.c, doc/sphinx/Pacemaker_Explained/local-options.rst, etc/sysconfig/pacemaker.in, include/crm/cib/cib_types.h, include/crm/cib/internal.h, include/crm/common/internal.h, include/crm/common/options_internal.h, include/crm/common/xml_internal.h, include/crm/lrmd.h, include/crm_internal.h, lib/cib/cib_client.c, lib/cib/cib_ops.c, lib/common/schemas.c, lib/common/tests/schemas/Makefile.am, lib/common/tests/schemas/pcmk__build_schema_xml_node_test.c, lib/common/tests/schemas/pcmk__schema_files_later_than_test.c, lib/common/tests/utils/compare_version_test.c, lib/common/xml.c
I have tested to verify that schemas do get transferred and added to the known schemas list, but I have not yet verified that these schemas are used to actually do the validation.  That's the next step, but in the meantime we can at least talk about what I've done up to this point.
=> Transfer schemas to remote node

daemons/attrd/attrd_attributes.c, daemons/attrd/attrd_cib.c, daemons/attrd/attrd_corosync.c, daemons/attrd/attrd_messages.c, daemons/attrd/pacemaker-attrd.h, daemons/controld/controld_attrd.c, include/crm/cluster/internal.h, include/crm/common/ipc_attrd_internal.h, include/crm_internal.h, lib/cluster/membership.c, lib/common/ipc_attrd.c, lib/common/ipc_client.c, lib/common/ipc_pacemakerd.c
This is prep work for having pacemaker-attrd handle purging transient node attributes from the CIB
=> Improve pacemaker-attrd cache management and logging

daemons/attrd/attrd_cib.c, daemons/attrd/attrd_corosync.c, daemons/attrd/attrd_elections.c, daemons/attrd/attrd_messages.c, daemons/attrd/pacemaker-attrd.h
=> Minor cleanup of pacemaker-attrd

lib/cib/cib_file.c
=> Refactor: cib_file: improve error message when schema file is missing

daemons/attrd/attrd_attributes.c, daemons/attrd/attrd_cib.c, daemons/attrd/attrd_corosync.c, daemons/attrd/pacemaker-attrd.h
... along with some refactoring as prep work for T137
=> Fix issues with transient utilization attributes

daemons/attrd/attrd_attributes.c, daemons/attrd/attrd_cib.c, daemons/attrd/attrd_corosync.c, daemons/attrd/pacemaker-attrd.h
This is prep work for future attrd changes that I'm probably not going to get around to for a little while.  But in the mean time, it doesn't hurt anything else to get this in.
=> Move settings in attribute_s into their own flags field

daemons/attrd/attrd_attributes.c, daemons/attrd/attrd_cib.c, daemons/attrd/attrd_corosync.c, daemons/attrd/attrd_messages.c, daemons/attrd/attrd_utils.c, daemons/attrd/pacemaker-attrd.h, include/crm/cluster.h, include/crm/common/xml_names_internal.h, include/crm_internal.h
These changes came out of the work on T137 but are not directly related
=> Minor tweaks to attribute manager

daemons/attrd/attrd_cib.c, daemons/based/based_callbacks.c, daemons/based/based_messages.c, daemons/based/based_notify.c, daemons/based/based_remote.c, daemons/based/based_transaction.c, daemons/controld/controld_cib.c, daemons/controld/controld_transition.c, daemons/execd/execd_alerts.c, daemons/execd/execd_commands.c, daemons/execd/pacemaker-execd.c, daemons/execd/remoted_tls.c, daemons/fenced/fenced_cib.c, daemons/fenced/pacemaker-fenced.c, include/crm/Makefile.am, include/crm/cib.h, include/crm/cib/internal.h, include/crm/cib_compat.h, include/crm/common/options_internal.h, include/crm/common/xml_names_internal.h, include/crm/lrmd.h, include/crm/lrmd_compat.h, lib/cib/cib_client.c, lib/cib/cib_file.c, lib/cib/cib_native.c, lib/cib/cib_remote.c, lib/cib/cib_utils.c, lib/fencing/st_client.c, lib/lrmd/lrmd_client.c, tools/crm_mon.c
Follow-up to #3349. Ready for review, leaving as draft to avoid CI build until after rebase.
=> PCMK__XE_CIB_COMMAND to PCMK__XA_LRMD_RUN_TIME XML constants

include/crm/common/unittest_internal.h, lib/common/Makefile.am, lib/common/output_xml.c, lib/common/unittest.c, lib/pacemaker/tests/pcmk_resource/pcmk_resource_delete_test.c
Spoiler alert: they don't validate without an additional patch.
=> Add validation to public API tests

lib/common/ipc_client.c
Previously if qb_ipcc_connect_async() succeeded but the following poll()
failed, the file descriptor would leak.
In that case, given that disconnect function is not registered yet,
qb_ipcc_disconnect() won't clean up the socket. In any case, call
qb_ipcc_connect_continue() here so that it may fail and do the cleanup
for us.
Issue introduced in 2.1.3 by 4b60aa100.
=> Fix: libcrmcommon: avoid file descriptor leak in IPC client with async connection

include/crm/cib.h, include/crm/lrmd.h
That should fix sbd using T_CIB_DIFF_NOTIFY
=> Fix: cib.h: conditionally include cib_compat.h

cts/cli/regression.daemons.exp, daemons/fenced/pacemaker-fenced.c
Mistake in 2.1.5 by da9727953.
=> Doc: fencer: fix pcmk_delay_max description

lib/services/services_linux.c
Previously when executing a synchronous action, if there were existing asynchronous actions on-going, any SIGCHLD for those child processes would be redirected and ignored, so the processes would become zombies.
This commit fixes it by resending any ignored SIGCHLD after the synchronous action has completed and the previous SIGCHLD handler has been restored, so that the asynchronous children will be handled.
Issue exposed in 2.1.5 by bc852fe36. It introduced the asynchronous way of retrieving metadata in controller meanwhile retaining the synchronous way.
See discussion at:
https://github.com/ClusterLabs/pacemaker/pull/2873#discussion_r1472734082
=> Fix: libcrmservice: avoid async zombie children by resending ignored SIGCHLD

po/zh_CN.po
Hi @kgaillot @gao-yan:
I made some changes as suggested earlier.  #3300
=> Optimize some Chinese translations

tools/crm_resource.c
Before adding a new option to it in an upcoming PR. Or maybe in this one, if I wake back up early enough today.
The main goal here is to make option parsing less convoluted, with fewer side effects.
=> Some crm_resource refactors

daemons/attrd/attrd_corosync.c, daemons/controld/controld_membership.c, daemons/controld/controld_te_callbacks.c, daemons/fenced/fenced_cib.c, daemons/fenced/fenced_history.c, daemons/fenced/fenced_remote.c, include/crm/common/xml_internal.h, lib/cib/cib_attrs.c, lib/cib/cib_ops.c, lib/cib/cib_utils.c, lib/common/messages.c, lib/common/nvpair.c, lib/common/patchset_display.c, lib/common/tests/schemas/pcmk__build_schema_xml_node_test.c, lib/common/xml.c, lib/common/xpath.c, lib/fencing/st_client.c, lib/pacemaker/pcmk_graph_consumer.c, lib/pengine/pe_output.c, lib/pengine/utils.c, tools/crm_mon.c, tools/crm_resource_runtime.c
This passes ctslab and regression tests with one minor change (see patches, obviously) but I'm still a little nervous that this is going to break something subtle somewhere.  The XML diff/patch stuff I'm especially unsure of.
=> Use pcmk__xe_first_child where possible

doc/sphinx/Pacemaker_Development/c.rst
Feedback is very welcome on both structure and content. My technical writing is decent but it's not my strongest point.
=> Doc: Pacemaker Development: Add to function naming conventions

include/crm/common/xml.h, include/crm/common/xml_compat.h, include/crm/common/xml_internal.h, lib/cib/cib_ops.c, lib/common/crmcommon_private.h, lib/common/xml.c, lib/common/xml_io.c, lib/common/xpath.c
New functions and deprecations along the way. Stopping at "update" seems like a good place to break it up.
=> Start separating XML tree traversal from work

cts/cli/regression.acls.exp, cts/cli/regression.validity.exp, include/crm/cib/cib_types.h, include/crm/common/xml_internal.h, include/crm/common/xml_names_internal.h, lib/cib/cib_ops.c, lib/common/crmcommon_private.h, lib/common/patchset.c, lib/common/xml.c
Here's another piece of #3403 that's probably fine now, while I continue making changes to the rest.
=> Refactor: Drop update_cib_object()

include/crm/common/nvpair_internal.h, lib/pengine/rules.c
This is prep work for moving the remaining libpe_rules code to libcrmcommon
=> Clean up nvpair block processing

include/crm/common/Makefile.am, include/crm/common/internal.h, include/crm/common/logging_internal.h, include/crm/common/scheduler_internal.h, include/crm/common/schemas.h, include/crm/common/schemas_internal.h, include/crm/common/xml.h, include/crm/common/xml_internal.h, include/crm_internal.h, lib/common/schemas.c, lib/common/tests/health/pcmk__parse_health_strategy_test.c, lib/common/tests/health/pcmk__validate_health_strategy_test.c, lib/common/tests/schemas/crm_schema_init_test.c, lib/pacemaker/pcmk_output.c, tools/crm_mon.c
This fixes some minor issues in the schema code, in preparation for further changes
=> Prepare schema code for further deprecations

agents/ocf/o2cb.in
=> Feature: agents: Update the o2cb agent for OCF 1.1.

lib/lrmd/lrmd_client.c
If PCMK_authkey_location is given in /etc/sysconfig/pacemaker, but the key doesn't exist or is unreadable, we will fall back to trying to read the key from default locations.
If /etc/pacemaker/authkey doesn't exist, we will fall back to trying to use /etc/corosync/authkey.
Both of these are undocumented behaviors that end up loading a key from a location the administrator does not expect.  Mark them as deprecated so we can remove them in 3.0.0.
Ref T304
=> Low: lrmd: Warn on insecure and undocumented key handling behaviors.

cts/cli/regression.upgrade.exp, cts/cli/regression.validity.exp, daemons/controld/controld_join_dc.c, include/crm/common/schemas_internal.h, lib/cib/cib_utils.c, lib/common/crmcommon_private.h, lib/common/schemas.c, lib/common/tests/schemas/Makefile.am, lib/common/tests/schemas/crm_schema_init_test.c, lib/common/tests/schemas/pcmk__cmp_schemas_by_name_test.c, lib/common/tests/schemas/pcmk__get_schema_test.c, lib/pacemaker/pcmk_acl.c
... and simplify update_validation()
=> Fix a few minor schema processing bugs

cts/cli/regression.upgrade.exp, cts/cli/regression.validity.exp, cts/cts-cli.in, daemons/based/based_io.c, daemons/based/based_messages.c, include/crm/common/Makefile.am, include/crm/common/schemas.h, include/crm/common/schemas_compat.h, include/crm/common/schemas_internal.h, lib/cib/cib_ops.c, lib/common/schemas.c, tools/cibadmin.c
And replace it with a much-cleaned-up and easier-to-follow internal function
=> Deprecate update_validation()

tools/crm_mon.c
Previously when crm_mon was running in console mode, if the attached pseudo-terminal got lost, crm_mon would persist in the background and raise the CPU usage to 100%.
The situation triggers if `use_pty` is enabled for `sudo`, in which case it creates a separate pseudo-terminal device for its child process.
A producer:
- Enable `use_pty` by adding `Defaults use_pty` to /etc/sudoers
- Open a console and execute:
```
> sudo su -
```
- Open another console, find the PID of crm_mon's bash parent and kill it:
```
```
The pty device created by `sudo` from the first console is basically deleted, but crm_mon continues running in the background and raises the CPU usage.
This commit fixes it by watching more conditions from stdin and exiting upon (G_IO_ERR | G_IO_HUP).
The similar was reported and …
=> Fix: tools: make crm_mon exit upon loss of the attached pseudo-terminal

configure.ac, daemons/attrd/attrd_corosync.c, daemons/attrd/pacemaker-attrd.c, daemons/attrd/pacemaker-attrd.h, daemons/based/pacemaker-based.c, daemons/based/pacemaker-based.h, daemons/controld/controld_control.c, daemons/controld/controld_corosync.c, daemons/controld/controld_election.c, daemons/controld/controld_membership.c, daemons/controld/controld_messages.c, daemons/fenced/pacemaker-fenced.c, daemons/pacemakerd/pcmkd_corosync.c, daemons/pacemakerd/pcmkd_subdaemons.c, include/crm/cluster.h, include/crm/cluster/compat.h, include/crm/cluster/internal.h, include/crm/common/options.h, lib/cluster/Makefile.am, lib/cluster/cluster.c, lib/cluster/corosync.c, lib/cluster/cpg.c, lib/cluster/crmcluster_private.h, lib/cluster/membership.c, lib/cluster/tests/Makefile.am, lib/cluster/tests/cluster/Makefile.am, lib/cluster/tests/cluster/pcmk_cluster_set_destroy_fn_test.c, lib/cluster/tests/cpg/Makefile.am, lib/cluster/tests/cpg/pcmk_cpg_set_confchg_fn_test.c, lib/cluster/tests/cpg/pcmk_cpg_set_deliver_fn_test.c
=> crmcluster deprecations: crm_peer_cache through crm_join_phase_str()

tools/crm_resource.c, tools/crm_resource.h, tools/crm_resource_runtime.c
This is all the straightforward stuff out of #3411.  I'd love to figure out a way to simplify this file a lot more, but it resists change.
=> Rearrange some code in crm_resource_runtime.c

daemons/attrd/attrd_attributes.c, daemons/controld/controld_schedulerd.c, include/crm/cluster/compat.h, include/crm/common/xml.h, include/crm/common/xml_compat.h, include/crm/common/xml_internal.h, include/crm/msg_xml_compat.h, lib/cib/cib_attrs.c, lib/cluster/corosync.c, lib/cluster/membership.c, lib/common/actions.c, lib/common/crmcommon_private.h, lib/common/ipc_client.c, lib/common/ipc_controld.c, lib/common/nvpair.c, lib/common/tests/xml/Makefile.am, lib/common/tests/xml/pcmk__xe_set_id_test.c, lib/common/tests/xml/pcmk__xml_is_name_char_test.c, lib/common/tests/xml/pcmk__xml_is_name_start_char_test.c, lib/common/tests/xml/pcmk__xml_sanitize_id_test.c, lib/common/xml.c, lib/pengine/bundle.c, lib/pengine/remote.c, tools/crm_node.c, tools/crm_resource_ban.c
=> Deprecate crm_xml_set_id() and crm_xml_sanitize_id()

daemons/attrd/attrd_cib.c, daemons/controld/controld_alerts.c, daemons/controld/controld_callbacks.c, daemons/controld/controld_corosync.c, daemons/controld/controld_join_dc.c, daemons/controld/controld_messages.c, daemons/fenced/fenced_commands.c, daemons/fenced/pacemaker-fenced.c, include/crm/cluster/internal.h, lib/cluster/corosync.c, lib/cluster/cpg.c, lib/cluster/membership.c
This is all I'll be able to get in before EOD, so here ya go.
=> Refactor: libcrmcluster: pcmk__node_status_t:id -> cluster_layer_id

cts/cli/crm_verify_invalid_fencing_topology.xml, cts/cli/regression.tools.exp, cts/cts-cli.in, daemons/fenced/fenced_commands.c, daemons/fenced/fenced_remote.c, daemons/fenced/pacemaker-fenced.h, include/crm/fencing/internal.h, include/crm_internal.h, lib/pengine/pe_status_private.h, lib/pengine/status.c, lib/pengine/unpack.c
=> crm_verify: Improve checking of fencing level IDs

ChangeLog
... and drop a duplicate entry from an earlier release
=> Doc: ChangeLog: update for 2.1.8-rc4 release

doc/sphinx/Pacemaker_Explained/local-options.rst, doc/sphinx/Pacemaker_Explained/status.rst
Most importantly, we previously did not explicitly document the CIB's status section as internal to Pacemaker and subject to change from release to release.
=> Overhaul status chapter of Pacemaker Explained

configure.ac, daemons/attrd/attrd_elections.c, daemons/controld/controld_callbacks.c, daemons/controld/controld_control.c, daemons/controld/controld_election.c, daemons/controld/controld_execd.c, daemons/controld/controld_join_client.c, daemons/controld/controld_join_dc.c, daemons/controld/controld_membership.c, daemons/controld/controld_messages.c, daemons/controld/controld_te_actions.c, daemons/controld/controld_throttle.c, daemons/pacemakerd/pcmkd_messages.c, daemons/schedulerd/schedulerd_messages.c, include/crm/cluster/election_internal.h, include/crm/common/ipc.h, include/crm/common/messages_internal.h, include/crm/common/options_internal.h, include/crm/common/xml_names_internal.h, lib/cluster/election.c, lib/common/ipc_client.c, lib/common/ipc_controld.c, lib/common/ipc_pacemakerd.c, lib/common/ipc_schedulerd.c, lib/common/messages.c, lib/common/tests/Makefile.am, lib/common/tests/messages/Makefile.am, lib/common/tests/messages/pcmk__new_message_as_test.c, tools/crm_node.c
... and make the message code more sane
=> Drop deprecated message APIs

daemons/attrd/attrd_elections.c, daemons/attrd/pacemaker-attrd.c, daemons/attrd/pacemaker-attrd.h, daemons/controld/controld_control.c, daemons/controld/controld_election.c, daemons/controld/controld_globals.h, daemons/controld/pacemaker-controld.h, include/crm/cluster/election_internal.h, include/crm/cluster/internal.h, lib/cluster/cluster.c, lib/cluster/cpg.c, lib/cluster/crmcluster_private.h, lib/cluster/election.c
Since most cluster APIs have been made internal and server name APIs were added, we can now simplify election management
=> Merge election object into cluster object

doc/Makefile.am, doc/sphinx/Pacemaker_Administration/agents.rst, tools/crm_rule.8.inc
There are always little things to fix after a release ...
=> Improve documentation uploads

cts/cts-cli.in, python/pacemaker/_cts/test.py
@kgaillot also had a report of the number of test failures being wrong under certain circumstances, but I haven't tracked that down yet.  In the meantime, here's a bunch of other fixes.
=> Various fixes to cts-cli

cts/scheduler/exp/nvpair-id-ref.exp, cts/scheduler/xml/nvpair-id-ref.xml, cts/schemas/test-3/ref/id-ref.ref-1, cts/schemas/test-3/ref/id-ref.ref-99, cts/schemas/test-3/ref/no-validate-with.ref-0, cts/schemas/test-3/ref/no-validate-with.ref-1, cts/schemas/test-3/ref/no-validate-with.ref-99, cts/schemas/test-3/ref/nvpair-no-value.ref-0, cts/schemas/test-3/ref/nvpair-no-value.ref-1, cts/schemas/test-3/ref/nvpair-no-value.ref-99, cts/schemas/test-3/ref/sort-nvsets.ref-0, cts/schemas/test-3/ref/sort-nvsets.ref-1, cts/schemas/test-3/ref/sort-nvsets.ref-99, cts/schemas/test-3/xml/no-validate-with.xml, cts/schemas/test-3/xml/nvpair-no-value.xml, cts/schemas/test-3/xml/sort-nvsets.xml, lib/pengine/rules.c, xml/nvset-4.0.rng, xml/upgrade-3.10-1.xsl
The biggest piece here is sorting. The sorting that we add here doesn't change Pacemaker's behavior on output vs. input. However, it will enable more changes that are coming in future PRs.
=> XSLT: Sort nvsets and ensure nvpairs are well-formed

configure.ac, cts/cli/regression.agents.exp, cts/cts-cli.in, cts/cts-exec.in, cts/support/cts-support.in, daemons/execd/Makefile.am, daemons/execd/execd_commands.c, doc/sphinx/Pacemaker_Explained/resources.rst, etc/Makefile.am, include/crm/common/agents.h, lib/common/agents.c, lib/common/tests/agents/pcmk_get_ra_caps_test.c, lib/services/Makefile.am, lib/services/services.c, lib/services/services_linux.c, python/pacemaker/_cts/cib.py, python/pacemaker/buildoptions.py.in, tools/crm_resource_runtime.c
This will be backported to the 2.1 branch (except the last commit, which is unrelated)
=> Allow disabling lsb resource support at build time

cts/cts-exec.in, cts/cts-lab.in, python/pacemaker/buildoptions.py.in
Here's a couple minor python fixes related to recent changes, plus I might as well make cts-lab.in pass pyflake while I'm in the area.
=> Minor python fixes

python/pacemaker/_cts/environment.py
Separate them with spaces, just like you would do for --nodes.
=> Test: cts-lab: Allow running multiple tests with the --choose argument.

cts/schemas/test-3/ref/bundle-promoted-max-legacy.ref-0, cts/schemas/test-3/ref/bundle-promoted-max-legacy.ref-1, cts/schemas/test-3/ref/bundle-promoted-max-legacy.ref-2, cts/schemas/test-3/ref/bundle-promoted-max-legacy.ref-3, cts/schemas/test-3/ref/bundle-promoted-max-legacy.ref-99, cts/schemas/test-3/ref/promotable-legacy.ref-0, cts/schemas/test-3/ref/promotable-legacy.ref-1, cts/schemas/test-3/ref/promotable-legacy.ref-2, cts/schemas/test-3/ref/promotable-legacy.ref-3, cts/schemas/test-3/ref/promotable-legacy.ref-4, cts/schemas/test-3/ref/promotable-legacy.ref-99, cts/schemas/test-3/xml/bundle-promoted-max-legacy.xml, cts/schemas/test-3/xml/promotable-legacy.xml, doc/sphinx/Pacemaker_Explained/collective.rst, include/crm/common/xml_internal.h, lib/pengine/complex.c, xml/resources-4.0.rng, xml/upgrade-3.10-2.xsl
Fixes part of T273. We can't drop the meta-attributes mentioned there because resource agents still use them.
=> XSLT: Disallow master resources and masters XML attribute

configure.ac, daemons/based/based_remote.c, daemons/controld/controld_schedulerd.c, doc/sphinx/Pacemaker_Administration/configuring.rst, lib/cib/cib_client.c
Also clean up the remote CIB authentication code
=> Fix memory issues found by coverity

doc/sphinx/Pacemaker_Explained/constraints.rst, lib/common/iso8601.c, lib/common/tests/iso8601/Makefile.am, lib/common/tests/iso8601/crm_time_add_days_test.c, lib/common/tests/iso8601/crm_time_parse_duration_test.c
... plus an unrelated documentation change. Everything will be backported to 2.1.
=> Fix time handling issues found by fuzz testing

xml/Makefile.am, xml/README.md
=> Feature: build: add make target to update schemas

lib/pengine/pe_actions.c
Hi All,
Fixed a memory leak when searching for unfencing devices.
Best Regards,
=> Mid: scheduler: Fixed memory leak when searching for unfencing devices.

cts/schemas/test-3/ref/ping-node.ref-0, cts/schemas/test-3/ref/ping-node.ref-1, cts/schemas/test-3/ref/ping-node.ref-2, cts/schemas/test-3/ref/ping-node.ref-3, cts/schemas/test-3/ref/ping-node.ref-4, cts/schemas/test-3/ref/ping-node.ref-99, cts/schemas/test-3/xml/ping-node.xml, lib/pengine/pe_output.c, lib/pengine/unpack.c, xml/nodes-4.0.rng, xml/upgrade-3.10-2.xsl
=> XSLT: Disallow ping nodes

cts/cli/regression.rules.exp, include/crm/common/xml_names_internal.h, lib/common/rules.c, lib/pacemaker/pcmk_rule.c
=> Feature: various: Drop support for phase of the moon in rule date_spec

cts/cts-exec.in, python/pacemaker/_cts/corosync.py
If needed, I can track down when the second two patches became necessary.  However it takes a fair bit of bisecting to check things against main which is why I didn't do this originally.  I don't think any of these are required on 2.1.
=> Regression test fixes

daemons/controld/controld_messages.c
Right after starting the cluster the DC is offline for short time, and if you call `crmadmin --dc_lookup` during this time, it would hang. This change lets the `crmadmin` wait for 5 seconds before breaking.
=> Fix: controld: leave xml-src attribute empty when no DC selected #2902

lib/common/remote.c, lib/lrmd/lrmd_client.c
Here's a couple more standalone patches from my async IPC read series.  I've given these a couple runs through cts-lab, but no interactive testing yet.
=> More async prep

configure.ac, daemons/based/Makefile.am, lib/common/Makefile.am, lib/fencing/Makefile.am, lib/pacemaker-fencing.pc.in, lib/pacemaker-service.pc.in, lib/pacemaker.pc.in, lib/services/services_linux.c, tools/Makefile.am, tools/crm_mon.c, tools/crm_mon.h, tools/crm_mon_curses.c
=> Build: configure: AC_CHECK_LIB -> AC_SEARCH_LIBS

daemons/execd/remoted_tls.c
This is the last of the patches from #3633 before we start running into problems.  I see no ctslab errors when testing these patches out, but I do see log messages indicating that we are hitting EAGAIN and will retry.  I also don't think that these patches contribute to the problems I was seeing in that other PR.
=> Read remote connections async in execd

python/pacemaker/_cts/audits.py, tools/crm_resource.c, tools/crm_resource.h, tools/crm_resource_ban.c, tools/crm_resource_print.c, tools/crm_resource_runtime.c
I'm not quite finished with T885, but did these along the way to give myself less to sort through.
=> Some crm_resource simplifications

cts/schemas/test-3/ref.err/acl-drop.ref.err-1, cts/schemas/test-3/ref.err/acl-drop.ref.err-4, cts/schemas/test-3/ref/acl-drop.ref-0, cts/schemas/test-3/ref/acl-drop.ref-1, cts/schemas/test-3/ref/acl-drop.ref-2, cts/schemas/test-3/ref/acl-drop.ref-3, cts/schemas/test-3/ref/acl-drop.ref-4, cts/schemas/test-3/ref/acl-drop.ref-99, cts/schemas/test-3/xml/acl-drop.xml, xml/upgrade-3.10-2.xsl, xml/upgrade-3.10-99.xsl
=> [3.0] XSLT: Preserve ACL reference behavior for replaced constraints

lib/pengine/bundle.c
Regression introduced in 3.0.0-rc1
=> Fix: scheduler: avoid memory leak in bundles

cts/schemas/test-3/ref/acl-drop.ref-2, cts/schemas/test-3/ref/acl-drop.ref-3, cts/schemas/test-3/ref/acl-drop.ref-4, cts/schemas/test-3/ref/acl-drop.ref-99, xml/upgrade-3.10-2.xsl
=> Low: xml: Fix ACL xpath typo from 986cc5c4

daemons/controld/controld_execd.c, daemons/controld/controld_fsa.c, daemons/controld/controld_fsa.h, daemons/controld/controld_matrix.c, daemons/controld/controld_messages.c, daemons/controld/controld_remote_ra.c, daemons/controld/controld_utils.c, daemons/fenced/fenced_commands.c, daemons/fenced/fenced_remote.c, daemons/fenced/pacemaker-fenced.c, include/crm/common/actions_internal.h, lib/fencing/st_actions.c, lib/pacemaker/pcmk_sched_instances.c, lib/pacemaker/pcmk_sched_ordering.c
Wrapping up final notes/patches I had lying around
=> Miscellaneous minor refactors

INSTALL.md, configure.ac, rpm/pacemaker.spec.in
=> Build: raise minimum GnuTLS dependency to 3.4.6

lib/common/scheduler.c
Hi All,
This PR is a modified version of the following PR:
- https://github.com/ClusterLabs/pacemaker/pull/3784
Best Regards,
=> Mid: schedulerd: Resetting error and warning flags.

daemons/controld/controld_fsa.c, daemons/controld/controld_messages.c, lib/cluster/cpg.c, lib/common/ipc_server.c, lib/common/remote.c, lib/services/services_linux.c
I'm trying to make sure I understand everything before I start fixing the `pcmk__read_available_remote_data()` logic. Here are a few minor fixes that I came across while tracing.
=> Pedantic corrections related to printf and sockets

include/crm/common/internal.h, lib/common/nvpair.c, lib/common/tests/nvpair/Makefile.am, lib/common/tests/nvpair/pcmk__scan_nvpair_test.c, tools/crm_resource.c, tools/stonith_admin.c
I want to use this for a couple of other changes I'm working on, and it's self-contained, so I'll go ahead and file a PR for it.
=> Improvements to pcmk__scan_nvpair()

include/crm/common/resources_internal.h, include/crm/pengine/internal.h, lib/pacemaker/pcmk_sched_actions.c, lib/pacemaker/pcmk_sched_ordering.c, lib/pacemaker/pcmk_sched_promotable.c, lib/pengine/bundle.c, lib/pengine/clone.c, lib/pengine/complex.c, lib/pengine/group.c, lib/pengine/native.c, lib/pengine/pe_actions.c, lib/pengine/pe_output.c, lib/pengine/status.c, lib/pengine/utils.c, tools/crm_resource.c, tools/crm_resource_runtime.c
These should all be trivial. I'm not bothering with best practices within the functions right now. Just the interfaces.
=> Update interfaces of pcmk__rsc_methods_t functions

include/crm/common/ipc.h, lib/common/ipc_client.c
@nrwahl2 This is going to need some close examination.  I've run it through ctslab and that looks good, so the next step is having CI look for mistakes and then getting some review on it.  I'm not yet done with the multipart message code so there's always the possibility that something here will need to be changed later but this is mostly just rearranging code, so I don't think so.
=> Prepare IPC code to handle multipart messages

include/crm/common/ipc.h, lib/common/ipc_client.c
cts-lab still running, but I don't expect any surprises there.
=> Backport IPC prep to 2.1

cts/cli/regression.daemons.exp, cts/cli/regression.tools.exp, include/crm/common/options_internal.h, include/crm/common/scheduler.h, lib/common/options.c, lib/pengine/unpack.c, lib/pengine/utils.c
Hopefully, the commit messages are enough to remind us what this is all about.  I have tested a version of this against Pacemaker-2.1.5 (where the bug was first reported), but I have not tested these exact patches nor on Pacemaker-3.0.  Test setup is pretty involved.
=> Change fencing behavior for Pacemaker Remote nodes in certain circumstances

daemons/controld/controld_callbacks.c, daemons/controld/controld_cib.c, daemons/controld/controld_control.c, daemons/controld/controld_election.c, daemons/controld/controld_execd.c, daemons/controld/controld_fencing.c, daemons/controld/controld_fsa.c, daemons/controld/controld_membership.c, daemons/controld/controld_remote_ra.c, daemons/controld/controld_utils.h
For a little while, I was considering having the fencer do something similar to what the controller is doing here, and then I decided against it. But first, I did a little bit of cleanup to get a better understanding of what the controller was doing.
We should probably do some cts-lab before thinking about merging this.
=> Refactor: controller: Best practices for populate_cib_nodes()

cts/cli/regression.acls.exp, daemons/based/based_callbacks.c, include/crm/common/acl_internal.h, include/crm/common/xml.h, include/crm/common/xml_compat.h, include/crm/common/xml_internal.h, lib/cib/cib_utils.c, lib/common/acl.c, lib/common/crmcommon_private.h, lib/common/patchset.c, lib/common/tests/patchset/pcmk__cib_element_in_patchset_test.c, lib/common/tests/xml/pcmk__xml_new_doc_test.c, lib/common/tests/xml_comment/pcmk__xc_create_test.c, lib/common/tests/xml_element/pcmk__xe_sort_attrs_test.c, lib/common/xml.c, lib/common/xml_comment.c, lib/common/xml_element.c, tools/crm_diff.c, tools/crm_shadow.c
@clumens Next batch.
This has 25 commits, but the last five are fairly trivial and are the payoff/motivation for the preceding few commits.
=> XML refactors/deprecations: xml_accept_changes() to xml_calculate_significant_changes()

cts/cli/regression.agents.exp, daemons/execd/remoted_pidone.c, daemons/execd/remoted_schemas.c, daemons/fenced/fenced_commands.c, daemons/fenced/fenced_remote.c, lib/cib/cib_remote.c, lib/cluster/election.c, lib/common/cmdline.c, lib/common/io.c, lib/common/ipc_client.c, lib/common/iso8601.c, lib/common/schemas.c, lib/fencing/st_client.c, lib/lrmd/lrmd_client.c, lib/pacemaker/pcmk_sched_bundle.c, lib/pacemaker/pcmk_sched_ordering.c, lib/pacemaker/pcmk_simulate.c, lib/pacemaker/pcmk_verify.c, lib/pengine/bundle.c, lib/pengine/pe_digest.c, lib/services/services_linux.c, tools/crm_resource_runtime.c
@nrwahl2 Unfortunately, this is another high priority PR.  Once this and the fencing PR are merged, I'm going to pull main back into the 3.0 branch and then I'll proceed with the rest of the release steps on that branch.
This is very similar to the 2.1 version, except (1) it does not include the release steps and (2) there are some minor differences in the coverity and clang patches.
=> Static analysis fixes for main

ChangeLog
@nrwahl2 Can you proofread this real quick and give me an approval or not?  If it's all good, our release checklist says to commit it with "Rebase and merge" instead of creating a merge commit.  Thanks.
=> Doc: ChangeLog: update for 2.1.10-rc1 release

doc/sphinx/Pacemaker_Explained/collective.rst, rpm/pacemaker.spec.in, rpm/rpmlintrc
@nrwahl2 If I'm reading git history correctly, these commits are only on the 3.0 branch and not on main.  I think this is causing a problem for me when it comes to pulling main back into the 3.0 branch (there are other problems too, but this is an easy one to fix).
=> Add missing commits

ChangeLog.md, lib/cib/Makefile.am, lib/cluster/Makefile.am, lib/common/Makefile.am, lib/fencing/Makefile.am, lib/lrmd/Makefile.am, lib/pacemaker/Makefile.am, lib/pengine/Makefile.am, lib/services/Makefile.am, m4/version.m4, po/zh_CN.po
@nrwahl2 Here's yet another one of these.  Luckily these are pretty straightforward.
=> Prepare for the 3.0.1 release

daemons/pacemakerd/pacemakerd.c, daemons/pacemakerd/pacemakerd.h, daemons/pacemakerd/pcmkd_subdaemons.c
This should also fix T950, though I haven't been able to reproduce a situation that would cause that message to be printed.  I could probably spend a whole lot more time cleaning up this file, but this will have to do for now.
=> Code cleanups in daemons/pacemakerd/pcmkd_subdaemons.c

daemons/controld/controld_schedulerd.c
And rename cib_retry_timer to controld_cib_retry_timer so that it doesn't look like public CIB API.
This fixes a regression introduced by 676b547 and/or f91848e.
Issues have been observed occasionally during cts-lab runs. For example:
Jul 30 16:20:21 BadNews: 2025-07-30T16:19:46-0400 rhel9-ctslab-3 pacemaker-controld[54218]:  error: crm_glib_handler: Forked child [73686] to record non-fatal assertion at logging.c:83 : Source ID 2307737477 was not found when attempting to remove it
Jul 30 16:20:21 BadNews: 2025-07-30T16:19:47-0400 rhel9-ctslab-3 pacemaker-controld[54218]:  crit: GLib: Source ID 2307737477 was not found when attempting to remove it
Jul 30 16:20:23 BadNews: 2025-07-30T16:19:58-0400 rhel9-ctslab-3 pacemakerd[54211]:  error: pacemaker-controld[54218] terminated with signal 6 …
=> Fix: controller: Avoid crash due to GSource double-free
